= PropertyDescription -- класс

Класс `PropertyDescription` содержит описание свойства элемента управления в расширении программы {kvr}.

*Пространство имён*: `{dv}.Platform.Tools.LayoutEditor.ObjectModel.Descriptions`

*Сборка*: `{dv}.LayoutEditor.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
public class PropertyDescription : ICloneable

----

== Конструкторы

|===
|Имя |Описание 

|`PropertyDescription(String)` |Инициализирует новый экземпляр класса `PropertyDescription`.
|===

== Свойства

|===
|Имя |Описание 

|`BindingResolverType` |Зарезервировано.
|`Category` |Задаёт или возвращает категорию свойства.
|`ChangeLocalizaionKeys` |Задаёт или возвращает функцию обновления ключей локализации при копировании свойства с сериализованным значением.
|`CheckAvailablity` |Задаёт или возвращает функцию проверки доступности свойства для настройки в текущем контексте (к примеру, в текущем типе разметки).
|`CollectLocalizationKeys` |Задаёт или возвращает функцию получения нужных ключей локализации при копировании свойства с сериализованным значением.
|`DefaultValue` |Задаёт или возвращает значение по умолчанию.
|`DeviceDependent` |Задаёт или возвращает флаг, указывающий, зависит ли значение свойства от типа клиентского устройства.
|`DisplayName` |Задаёт или возвращает строковый ресурс, предоставляющий локализованное название элемента управления.
|`Editor` |Задаёт или возвращает тип компонента редактирования (редактора) значения свойства. Редактор является компонентом UserControl с реализованным интерфейсом `Xceed.Wpf.Toolkit.PropertyGrid.Editors. ITypeEditor` (сборка `Xceed.Wpf.Toolkit.Fixed.dll`).
|`ExcludeFromIL` |Задаёт или возвращает флаг, указывающий, будет ли данное свойство исключено из пакета свойств элемента управления, передаваемых в клиентскую часть {wc}а. Свойство с установленным флагом `ExcludeFromIL` остается настраиваемым в программе {kvr}.
|`GenerateDefaultValue` |Задаёт или возвращает метод, генерирующий для свойства значение по умолчанию.
|`GenerateValueOnPaste` |Задаёт или возвращает метод, генерирующий значение свойства при копировании элемента управления, содержащего данное свойство.
|`GetBindingLoader` |Задаёт или возвращает функцию, реализующую механизм получения и сохранения значения свойства.
|`Hidden` |Задаёт или возвращает флаг, определяющий, является ли свойство скрытым. Скрытое свойство не отображается при настройке элемента управления.
|`IsTemporarilyReadOnly` |Задаёт или возвращает функцию, проверяющую является ли элемент управления доступным только на чтение.
|`ItemsSource` |Задаёт или возвращает тип компонента, который предоставляет список готовых значений свойства, из которого значение свойства выбирается.
|`Localized` |Задаёт или возвращает флаг, указывающий, является ли свойство локализуемым. Свойство должно быть строкового типа. Для редактирования значения локализуемого свойства в Editor должен быть указан тип редактора `LocalizedPropertyEditor`.
|`Name` |Задаёт или возвращает уникальное название свойства.
|`Priority` |Задаёт или возвращает порядок отображения свойства в текущей категории свойств. Чем выше порядок, тем выше будет отображено свойство.
|`PropertyResolverType` |Задаёт или возвращает название компонента, предоставляющего дополнительную возможность настройки свойства: `DeviceDependent` (зависящего от типа устройства), `Localized` (зависящего от локализации). Рекомендуется использовать вместо `PropertyResolverType` флаги `Localized` и `DeviceDependent` класса `PropertyDescription`.
|`ReadOnly` |Задаёт или возвращает флаг, указывающий, является ли значение элемента управления доступным только на чтение.
|`RefreshProperties` |Задаёт или возвращает флаг, указывающий, требуется ли обновлять отображаемое значение свойства при изменении значения. В `true` следует устанавливать, если для изменения свойства используется отдельное окно редактирования.
|`Type` |Задаёт или возвращает тип значения свойства.
|`Validate` |Задаёт или возвращает функцию валидации значения свойства.
|===

== Примеры

Следующий код демонстрирует пример свойства `Slider`, добавляемого в категорию _Данные_. Для свойства назначается специализированный редактор значения -- `SliderEditor`.

[source,csharp]
----
private PropertyDescription GetSliderPropertyDescription()
{
 return new PropertyDescription <.>
 {
  Type = typeof(string), <.>
  Name = Constants.SampleImage.Slider, <.>
  Category = PropertyCategoryConstants.DataCategory, <.>
  DisplayName = Resources.ControlTypes_SliderProperty, <.>
  DefaultValue = String.Empty, <.>
  ExcludeFromIL = true, <.>
  Editor = typeof(SliderEditor), <.>
  
  CollectLocalizationKeys = args => <.>
  {
   var value = (string)args.ControlInfo.GetProperty(args.PropertyDescription.Name); <.>
   var items = SliderModeHelper.StringToItems(value); <.>
   var keys = args.LocalizationKeys; <.>
   foreach (var item in items) <.>
   {
    if (!string.IsNullOrEmpty(item.DescriptionLocalizationKey))
     keys.Add(item.DescriptionLocalizationKey);
   }
  },
  ChangeLocalizaionKeys = args => <.>
  {
   var value = (string)args.ControlInfo.GetProperty(args.PropertyDescription.Name);
   
   var items = SliderModeHelper.StringToItems(value);
   var mapping = args.LocalizationMapping;
   foreach (var item in items)
   {
    if (!string.IsNullOrEmpty(item.DescriptionLocalizationKey))
    {
     string newKey;
     if (mapping.TryGetValue(item.DescriptionLocalizationKey, out newKey)) <.>
      item.DescriptionLocalizationKey = newKey;
     }
    }
    return SliderModeHelper.ItemsToString(items); <.>
  }
 };
}
----
<.> Создаем экземпляр класса описания свойства .
<.> Определяем строковый тип данного свойства ЭУ. Реальное значение сериализуемое.
<.> Указывается уникальное название.
<.> Категория для размещения свойства Данные.
<.> Отображаемое название свойства.
<.> Пустое значение по умолчанию.
<.> Свойство не должно передаваться на клиентскую сторону {wc}а.
<.> Указываем специфический редактор значения свойства.
<.> Определяем метод, который будет вызываться при копировании свойства. Метод получает ключи локализации DescriptionLocalizationKey из объекта свойства args.PropertyDescription.Name и заполняет ими коллекцию args.LocalizationKeys.
<.> Получаем значение требуемого свойства.
<.> Десериализуем значение свойства в нужный класс.
<.> Получаем из параметров (передается в args) элемента управления текущей разметки.
<.> Заполняем keys ключами из описания свойства.
<.> Определяем метод, который будет вызываться при копировании элемента управления и, соответственно, его свойств.
<.> Создаем связь.
<.> Сериализуем значение свойства.
