= {dv} 5 {wc} 16

{dv} 5. {wc} является _дополнительным модулем_ системы {dv} 5.5. {wc} предоставляет возможность работать с карточками системы {dv} и осуществлять основные операции с электронными документами в веб-браузере на персональном компьютере и на мобильном устройстве.

== Функции модуля

{wc} **не является автономным**, он обеспечивает выполнение следующих функциональных задач:

.Работа с документами:
* создание и просмотр документов;
* просмотр приложенных к документам файлов офисных и графических форматов в веб-браузере.
* согласование документов с использованием расширенных маршрутов согласования приложения _{dv} 5. Конструктор согласований_.

.Работа с заданиями:
* создание, просмотр и отправка на исполнение заданий;
* исполнение или делегирование поступивших на исполнение заданий;
* просмотр приложенных к заданиям файлов офисных и графических форматов в веб-браузере;
* создание подчинённых заданий и групп заданий.

.Поиск карточек:
* в выбранной папке;
* по всей базе данных с помощью полнотекстового поиска.

== {kvr}

xref:layouts:Preparationfor_work.adoc[{kvr}] – программа для настройки разметок модуля {wc}.

Программа {kvr} предназначена для применения в организациях, в которых используется система {dv} и модуль {dv} 5. {wc}.

.Возможности программы {kvr}:

* настройка разметок карточек, дерева папок, дашборда, а также других элементов {wc}а, с помощью встроенного редактора;
* настройка условий использования разметки в зависимости от типа устройства, роли сотрудника, состояния карточки, а также других условий. Список возможных условий выбора разметки определяется её назначением;
* настройка Решений – комплект настроек, содержащий разметки, данные локализации и условия выбора разметок;
* экспорт/импорт Решений и др.
* создание расширенных маршрутов согласования;
* использование сценариев (язык JavaScript) для обработки событий разметки;
* локализация разметок.
* Разработка новых компонентов:
** элементы управления для настройки разметок;
** серверные расширения для получения дополнительной серверной бизнес-логики.

== Администрирование
Раздел администрирование содержит инструкцию по установке Модуля, описание функций _администратора {dv}_, инструкцию по настройке дерева папок и дашборда, а также описание других задач по администрированию:

. xref:admin:installKit.adoc[Установка и настройка] (содержит инструкцию по установке и первоначальной настройке Модуля, инструкцию по обновлению и настройке кластера Модуля).
. xref:admin:administratorFunctions.adoc[Функции администратора] (содержит описание программы {pu}, перечислены действия, выполняемые администратором {dv}).

== Расширение возможностей

=== Расширение функциональных возможностей

Функциональные возможности серверной части Модуля могут быть увеличены с помощью серверных расширений. С помощью данного типа расширений в сервер Модуля могут быть добавлены новые методы WebAPI (в т. ч. реализующие серверную бизнес-логику карточек); дополнительные данные, необходимые для формирования пользовательского интерфейса Модуля (в т. ч. новых элементов управления); методы, обеспечивающие возможность создания новых типов карточек из меню создания карточек; и др.

Функциональные возможности клиентской части Модуля могут быть увеличены с помощью клиентских расширений и клиентских скриптов. В клиентских расширениях могут быть реализованы новые общие функции, доступные всем клиентским компонентам Модуля, а также клиентские компоненты элементов управления. Клиентские скрипты добавляют в Модуль функции-обработчики для событий элементов разметок, настраиваемых в программе _{kvr}_.

=== Расширение возможностей Конструктора web-разметок

{kvr} также предоставляет возможность расширять свою функциональность с помощью дополнительных компонентов. С помощью расширений Конструктора web-разметок могут быть добавлены новые типы элементов управления и связанные с ними сущности.

TIP: Инструкция по разработке разметок приведена в Руководстве пользователя программы xref:layouts:Preparationfor_work.adoc[{kvr}].
