= {dv} 5 {wc}

Модуль {dv} 5. {wc} предназначен для применения в организациях, в которых используется СЭД {dv}.

{dv} 5. {wc} является _дополнительным модулем_ системы {dv} 5.5. {wc} предоставляет возможность работать с карточками системы {dv} и осуществлять основные операции с электронными документами в веб-браузере на персональном компьютере и на мобильном устройстве.

== Функции {wc}а

{wc} **не является автономным**, он обеспечивает выполнение следующих функциональных задач:

.Работа с документами:
* Создание и просмотр документов.
* Просмотр в веб-браузере файлов офисных и графических форматов, приложенных к документам.
* Согласование документов с использованием расширенных маршрутов согласования приложения _{dv} 5. Конструктор согласований_.

.Работа с заданиями:
* Создание, просмотр и отправка на исполнение заданий.
* Исполнение или делегирование поступивших на исполнение заданий.
* Просмотр приложенных к заданиям файлов офисных и графических форматов в веб-браузере.
* Создание подчинённых заданий и групп заданий.

.Поиск карточек:
* В выбранной папке.
* По всей базе данных с помощью полнотекстового поиска.

[#layouts]
== {kvr}

xref:layouts:infoInstall.adoc[{kvr}] -- программа для настройки разметок модуля {wc}.

Программа {kvr} предназначена для применения в организациях, в которых используется система {dv} и модуль {dv} 5. {wc}.

.Возможности программы {kvr}:

* Настройка разметок карточек, дерева папок, дашборда, а также других элементов {wc}а, с помощью встроенного редактора.
* Настройка условий использования разметки в зависимости от типа устройства, роли сотрудника, состояния карточки, а также других условий. Список возможных условий выбора разметки определяется её назначением.
* Настройка Решений -- комплект настроек, содержащий разметки, данные локализации и условия выбора разметок.
* Экспорт/импорт Решений и др.
* Создание расширенных маршрутов согласования.
* Использование сценариев (язык JavaScript) для обработки событий разметки.
* Локализация разметок.
* Разработка новых элементов управления для настройки разметок.
* Разработка серверных расширений для получения дополнительной серверной бизнес-логики.

== Администрирование

Раздел администрирование содержит инструкцию по установке {wc}а, описание функций _администратора {dv}_, инструкцию по настройке дерева папок и дашборда, а также описание других задач по администрированию:

. xref:admin:installKit.adoc[Установка и настройка] содержит инструкцию по установке и первоначальной настройке {wc}а, инструкцию по обновлению и настройке кластера {wc}а.
. xref:admin:adminFunctions.adoc[Функции администратора] содержит описание программы {pu}, перечислены действия, выполняемые администратором {dv}.

== Расширение возможностей

=== Расширение функциональных возможностей

Функциональные возможности серверной части {wc}а могут быть увеличены с помощью серверных расширений. С помощью данного типа расширений в сервер {wc}а могут быть добавлены новые методы WebAPI (в т. ч. реализующие серверную бизнес-логику карточек); дополнительные данные, необходимые для формирования пользовательского интерфейса Модуля (в т. ч. новых элементов управления); методы, обеспечивающие возможность создания новых типов карточек из меню создания карточек; и др.

Функциональные возможности клиентской части {wc}а могут быть увеличены с помощью клиентских расширений и клиентских скриптов. В клиентских расширениях могут быть реализованы новые общие функции, доступные всем клиентским компонентам Модуля, а также клиентские компоненты элементов управления. Клиентские скрипты добавляют в Модуль функции-обработчики для событий элементов разметок, настраиваемых в программе {kvr}.

=== Расширение возможностей программы {kvr}

{kvr} также предоставляет возможность расширять свою функциональность с помощью дополнительных компонентов. С помощью расширений программы {kvr} могут быть добавлены новые типы элементов управления и связанные с ними сущности.

TIP: Инструкция по разработке разметок приведена в Руководстве пользователя программы xref:layouts:guideGeneral.adoc[{kvr}].
