= Соглашения по оформлению

Для представления различных терминов и названий используются следующие средства форматирования:

[width="99%",cols="34%,66%",options="header",]
|===
|Шрифт |Описание
|*Жирный* |Используется при написании названий элементов экранного интерфейса.
|_Курсив_ |Используется для обозначения новых терминов, названий типов и видов карточек.
|http://{dv}.com[Синий] |Используется для выделения перекрестных ссылок внутри документа и ссылок на доступные внешние документы, для указания адресов интернет-страниц.
|`Моноширинный` |Используется для выделения текстов макрокоманд и программных кодов, имен файлов и путей к ним. Также используется для указания необходимой опции, выделения значений, задаваемых пользователем с клавиатуры.
|===

Некоторые абзацы в тексте содержат информацию, на которую следует обратить особое внимание. Эти абзацы выделены в специальные блоки.

[IMPORTANT]
====
Служит для привлечения внимания пользователя к информации, которая необходима для корректного восприятия изложенного далее текста, и к указаниям, которые настоятельно рекомендуется выполнять.
====

[NOTE]
====
Используется для отображения информации дополнительного характера.
====
