= Необходимые ресурсы и программное обеспечение

[#dvGeneral]
== Общие требования к системе {dv}

* Данная версия {wc}а предназначена для работы с системой {dv} версии 5.5. Работа с {dv} версии 5.4 не поддерживается.
* Для корректной установки {wc}а БД {dv} должна быть обновлена до последней версии (см. руководство _администратора модуля Платформа_).
* Рекомендуется перевести БД системы {dv} на работу с расширенными метаданными. {wc} может работать с БД с динамическими метаданными, но динамические метаданные будут недоступны в модуле.
* Если в {wc}е планируется работать с функциями модуля _{dv} 5. {arch}_, указанный модуль обязательно должен быть установлен на сервере {dv} перед установкой {wc}аfootnote:[Поддерживаемая версия модуля _{dv} 5. {arch}_ указана в пункте xref:requirementsDocsVision.adoc#archive[Необходимое программное обеспечение].].

[#modules]
.Модули системы Docsvisionfootnote:[Установить. Настраивать не нужно. *Минимальная версия* позволяет запустить Web-клиент,  однако некоторые функции Web-клиента могут оказаться недоступны. *Рекомендуемая версия* позволяет получить полный доступ и ожидаемую работу всех функций Web-клиента.]:
. Серверная часть модуля _Docsvision 5. Платформа_.
+
*Минимальная версия:* 5.5.2 c обновлением 5.5.4572 и выше.
+
*Рекомендуемая версия:* 5.5.4 с обновлением 5.5.6634.0 и выше.
+
. Серверная часть модуля _Docsvision 5. Базовые объекты_.
+
*Минимальная версия:*  5.5.3 c обновлением 5.5.5367 и выше.
+
*Рекомендуемая версия:* 5.5.4 с обновлением 5.5.7454.0 и выше.
+
. Серверная часть приложения _Docsvision 5. Управление документами_.
+
*Минимальная версия:* 5.5.3 c обновлением 5.5.5316 и выше.
+
*Рекомендуемая версия:* 5.5.4 с обновлением 5.5.5316.0 и выше.
+
. Серверная часть модуля _Docsvision 5. Управление процессами_.
+
*Минимальная версия:* 5.5.2 c обновлением 5.5.4224.0 и выше.
+
*Рекомендуемая версия:* 5.5.4 с обновлением 5.5.4582.0 и выше.
+
. Серверная часть приложения _Docsvision 5. Конструктор согласований_.
+
*Минимальная версия:* 5.5.2 c обновлением 5.5.4221 и выше.
+
*Рекомендуемая версия:* 5.5.4 с обновлением 5.5.4221.0 и выше.
+
[#archive]
. Серверная часть модуля _{dv} 5. {arch}_ версии 5.5.1footnote:[Необязательный компонент. Обязателен, если требуется поддержка работы с функциями модуля _{dv} 5. {arch}_].

[#checkVersions]
== Проверка версий требуемых модулей

При установке серверного расширения и {wc}а происходит проверка требуемых модулей и их версий. Результаты проверки определяются цветом:

** *_Зеленый_*. Проверка прошла успешно. Модуль обнаружен, его версия соответствует минимальным требованиям. Установка {wc}а может быть продолжена.
** *_Красный_*. Проверка не пройдена. Модуль обнаружен, но его версия не соответствует минимальным требованиям. Установка {wc}а заблокирована.
** *_Желтый_*. Модуль обнаружен, его версия не соответствует требованиям. Рекомендуется обновить версию модуля. Установка {wc}а может быть продолжена.
** *_Серый_*. Модуль не обнаружен. Установите модуль, затем возобновите установку {wc}а. Установка {wc}а заблокирована.