= Программное обеспечение для формирования усиленной подписи

{wc} поддерживает два типа подписи: простая и усиленная. Формирование простой подписи доступно без дополнительных настроек, но должно быть предусмотрено сценарием подписания.

include::user:partial$excerpts.adoc[tags=signature]
Необходимые компоненты перечисленные далее.

[#requirements]
== Общие требования

В справочнике _Системные настройки_, в разделе menu:{bo}[Подписи и шифрование] должен быть выбран криптопровайдер и алгоритм подписи, соответствующие используемому сертификату ЭП. В частности, для работы с сертификатами КриптоПро должен быть выбран провайдер КриптоПро (_Crypto-Pro GOST R 34.10-2012 Cryptographic Service Provider_).

[NOTE]
====
Дополнительная информация по настройке подписания и шифрования приведена в _Руководстве администратора модуля {bo}_.
====

[#non-qualifcated]
== Использование неквалифицированных сертификатов

.Требования к клиентским рабочим местам:
. Операционная система: Windows или Mac OS.
. Веб-браузер: Google Chrome, Яндекс.Браузер или Microsoft Edge на Chromium (поддерживаемые версии см. в пункте xref:requirements-software.adoc[Необходимое программное обеспечение]).
. КриптоПро ЭЦП Browser plug-in версии {sign-plugin} (https://www.cryptopro.ru/products/cades/plugin[ссылка для загрузки]).
. Неквалифицированный сертификат пользователя. Сертификат должен быть установлен в хранилище _Личное_ на уровне _Текущий пользователь_.
. https://www.cryptopro.ru/products/mydss2#law[Приложение КриптоПро myDSS 2.0] для xref:user:docs-sign.adoc#sign-mobile[работы с подписью на мобильных устройствах.

[#qualificated]
== Использование квалифицированных сертификатов

.Требования к серверу:
. КриптоПро CSP версии {e-sign-v}.
. https://www.cryptopro.ru/downloads[КриптоПро CADESCOM версия {cades}].
. {root-cert} Сертификат должен быть установлен в хранилище _Доверенные корневые центры сертификации_ на уровне _Локальный компьютер_.

.Требования к клиентским рабочим местам:
. Операционная система: Windows или Mac OS (версии см. в требованиях https://www.cryptopro.ru/products/csp/compare[КриптоПро CSP].
. Веб-браузер: Google Chrome, Яндекс.Браузер или Microsoft Edge на Chromium (поддерживаемые версии см. в пункте xref:requirements-software.adoc#browser[Необходимое программное обеспечение]).

.Компоненты криптопровайдера КриптоПро:
. КриптоПро CSP версии {e-sign-v}.
. xref:user:prepare-add-components.adoc#cryptoPro[КриптоПро ЭЦП Browser plug-in] версии {sign-plugin}.
. CryptoPro Extension for CAdES Browser Plug-in версии 1.2.4 или выше (https://chrome.google.com/webstore/detail/cryptopro-extension-for-c/iifchhfnnmpdbibifmljnfjhpififfog[ссылка для загрузки]).

.Сертификаты ЭП:
. {root-cert} Должен быть установлен в хранилище _Доверенные корневые центры сертификации_ на уровне _Локальный компьютер_.
. Квалифицированный сертификат пользователя. Должен быть установлен в хранилище _Личное_ на уровне _Текущий пользователь_.
+
// tag::macOS[]
NOTE: Здесь указано название хранилищ в ОС Windows. Шаги, необходимые для настройки КриптоПро в ОС Mac OS можно найти в https://support.cryptopro.ru/index.php?/Knowledgebase/Article/View/232/0/rbot-s-kriptopro-csp-v-macos[документации КриптоПро].
// end::macOS[]
+
****
// tag::expiredCryptoPro[]
Если лицензия на компоненты КриптоПро CSP истекла, добавление новых подписей блокируется. Если подпись была добавлена ранее и срок действия сертификата ЭП не истёк, возможность проверки такой подписи не будет заблокирована. Проверка старых подписей выполняется успешно в любом случае.
// end::expiredCryptoPro[]

По вопросам получения компонентов криптопровайдера КриптоПро следует обращаться в компанию ООО КРИПТО-ПРО.
****
