= Необходимое техническое обеспечение

== Требования {wc}а

Ниже приведены минимальные аппаратные требования сервера {dv} для 50 одновременно работающих пользователейfootnote:[Подразумеваются пользователи с активной сессией. Время активности может быть настроено администратором.].

* Процессор: 2,5 ГГц и выше, 4 ядра.
* Оперативная память: от 6 ГБ.
* Система хранения данных: от 12 ГБ свободного места на диске. Рекомендуется использовать высокоскоростной HDD, массив или твердотельный накопитель.

Если количество одновременно работающих пользователей превышает 50, требования увеличиваются по следующим правилам:

* Дополнительное ядро процессора на каждые 50 дополнительных активных пользователей.
* Дополнительные 100 МБ оперативной памяти на каждого дополнительного активного пользователя.
* Дополнительные 200 МБ в системе хранения данных на каждого дополнительного активного пользователя.

Требования приведены исходя из "нормальной" нагрузки от работы пользователей. При повышении нагрузки (повышении активности пользователей, усложнении бизнес-сценариев, использовании расширений и дополнений {wc}а и т. п.) требования должны быть пересмотрены в сторону увеличения.

При использовании на компьютере дополнительного ПО, к приведенным требованиям необходимо прибавить требования установленных программных продуктов.

== Требования к клиентским рабочим местам

Следующие требования предъявляются к рабочему месту пользователя при работе на персональном компьютере.

* Процессор: 2 ГГц и выше, Intel Core i3 или аналоги (двухъядерные).
* Оперативная память: от 2 ГБ. Для запуска веб-браузера и открытия одной страницы {wc} должно быть свободно 512 МБ оперативной памяти.
* Для осуществления сканирования необходим WIA или TWAIN-сканер.
