= Требования к системе {dv}

* Данная версия {wc}а предназначена для работы с системой {dv} версии 5.5. Работа с {dv} версии 5.4 не поддерживается.
* Для корректной установки {wc}а БД {dv} должна быть обновлена до последней версии (см. руководство администратора модуля "Платформа").
* {wc} может работать с {dv} с БД с расширенными или динамическими метаданными, но динамические метаданные будут недоступны в Модуле. Рекомендуется перевести БД системы {dv} на работу с расширенными метаданными.
* Если в {wc}е планируется работать с функциями модуля "{dv} 5. {arch}", указанный модуль должен быть установлен на сервере {dv}:footnote:[Поддерживаемая версия модуля "{dv} 5. {arch}" указана в пункте "Необходимое программное обеспечение"].
+
[NOTE]
====
[.note__title]#Прим.:# В данном случае также обязательна установка модуля "{dv} 5. {arch}" на сервере {wc} (см. xref:requirementsSystem.adoc[Необходимое программное обеспечение]).
====

При установке серверного расширения и {wc}а происходит проверка требуемых модулей и их версий. Результаты проверки определяются цветом:

** Зеленый — проверка прошла успешно. Модуль обнаружен, его [.keyword]*версия соответствует* минимальным требованиям. Установка {wc}а [.keyword]*может быть продолжена*.
** Красный — проверка не пройдена. Модуль обнаружен, но его [.keyword]*версия не соответствует* минимальным требованиям. Установка {wc}а [.keyword]*заблокирована*.
** Желтый — модуль обнаружен, его [.keyword]*версия не соответствует* требованиям. Рекомендуется обновить версию модуля. Установка {wc}а [.keyword]*может быть продолжена*.
** Серый — модуль не обнаружен. Установите модуль, затем возобновите установку {wc}а. Установка {wc}а [.keyword]*заблокирована*.
