= Требования установки программы {kvr}

Для работы с программой {kvr} лицензия на систему {dv} должна содержать дополнительную опцию: _{dv} 5. Конструктор карточек_.

== Аппаратные требования

Остальные требования совпадают с требованиями сервера {wc} в пункте xref:requirementsHardware.adoc[].

== Программные требования

.Операционная система:
* Microsoft Windows Server {serv-1}.
* Microsoft Windows Server {serv-2}.
* Microsoft Windows Server {serv-3}.
* Microsoft Windows Server {serv-4}.

.Обязательное программное обеспечение:
. IIS (предоставляемая с ОС версия) с включенными компонентамиfootnote:[Устанавливаются с помощью menu:Диспетчера серверов[Роли и компоненты].]: ASP.NET, HTTP Redirect, Application Initialization.
. {asp}.
. Microsoft .NET Framework {net-v1}.

.Модули {dv}footnote:[Установить. Настраивать не нужно.]
. Серверная часть модуля _{dv} 5. Платформа_ версии {pl-v} и выше.
. Серверная часть модуля _{dv} 5. Базовые объекты_ версии {bo-v} и выше.
. Серверная часть модуля _{dv} 5. Управление процессами_ версии {wf-v} и выше.
. Серверная часть приложения _{dv} 5. Управление документами_ версии {dm-v} и выше.
. Серверная часть модуля _{dv} 5. Конструктор согласований_ версии {ad-v} и выше.
