= Требования установки программы {kvr}

Для работы с программой {kvr} лицензия на систему {dv} должна содержать дополнительную опцию: _{dv} 5. Конструктор карточек_.

== Аппаратные требования

Остальные требования совпадают с требованиями сервера {wc} в пункте xref:requirementsHardware.adoc[].

== Программные требования

.Операционная система:
** Microsoft Windows Server 2019 (Standard),
** Microsoft Windows Server 2016 (Standard),
** Microsoft Windows Server 2012 R2 (Standard),
** Microsoft Windows Server 2012 (Standard).

.Обязательное программное обеспечение:
. IIS (предоставляемая с ОС версия) с включенными компонентамиfootnote:[Устанавливаются с помощью menu:Диспетчера серверов[Роли и компоненты].]: ASP.NET, HTTP Redirect, Application Initialization.
. ASP.NET 4.0.
. Microsoft .NET Framework 4.6.1.

.Модули {dv}footnote:[Установить. Настраивать не нужно.]
. Серверная часть модуля _{dv} 5. Платформа_ версии 5.5.1 и выше.
. Серверная часть модуля _{dv} 5. Базовые объекты_ версии 5.5.1 и выше.
. Серверная часть модуля _{dv} 5. Управление процессами_ версии 5.5.1 и выше.
. Серверная часть приложения _{dv} 5. Управление документами_ версии 5.5.1 и выше.
. Серверная часть модуля _{dv} 5. Конструктор согласований_ версии 5.5.1 и выше.
