= Требования установки программы {kvr}

Для работы с программой {kvr} лицензия на систему {dv} должна содержать дополнительную опцию: _{dv} 5. Конструктор карточек_.

== Аппаратные требования

Остальные требования совпадают с требованиями сервера {wc} в пункте xref:requiredHardware.adoc[Необходимое техническое обеспечение].

== Программные требования

* *Операционная система*
** Microsoft Windows Server 2019 (Standard),
** Microsoft Windows Server 2016 (Standard),
** Microsoft Windows Server 2012 R2 (Standard),
** Microsoft Windows Server 2012 (Standard).
* *Обязательное программное обеспечение*
. IIS (предоставляемая с ОС версия) с включенными компонентамиfootnote:[Устанавливаются с помощью Диспетчера серверов → Роли и компоненты.]: ASP.NET, HTTP Redirect, Application Initialization.
. ASP.NET 4.0.
. Microsoft .NET Framework 4.6.1.
* *Модули {dv}*footnote:[Установить. Настраивать не нужно.]
. Серверная часть модуля {dv} 5. Платформа версии 5.5.1 и выше.
. Серверная часть модуля "{dv} 5. Базовые объекты" версии 5.5.1 и выше.
. Серверная часть модуля "{dv} 5. Управление процессами" версии 5.5.1 и выше.
. Серверная часть приложения {dv} 5. Управление документами версии 5.5.1 и выше.
. Серверная часть модуля "{dv} 5. Конструктор согласования" версии 5.5.1 и выше.
