= Уровень подготовки пользователя

== Пользователи модуля {wc}

.Пользователи должны:
* Обладать навыками работы с веб-браузерами (список браузеров, с которыми совместим модуль приведены в требованиях).
* Свободно осуществлять базовые операции в операционной системе клиентского устройства.
* Обладать знаниями предметной области.
* (желательно) обладать навыками работы с модулем {dv} 5. Windows-клиент, а также с другими модулями/приложениями, которые установлены в системе {dv}.
* Пройти обучение по работе с модулем {wc}.

== Пользователи программы {kvr}

Основной обязанностью пользователя программы {kvr} является создание и настройка разметок.

.Пользователи программы должны:
- Иметь опыт работы с персональным компьютером на базе операционной системы Windows на уровне квалифицированного пользователя.
- Свободно осуществлять базовые операции в ОС Windows,
- Предпочтительно иметь опыт написания скриптов на языке JavaScript и создания CSS стилей.

== Администраторы модуля {wc}

.Администратор модуля должен:
- Обладать навыками администрирования операционных систем:
* Microsoft Windows Server 2019 (Standard).
* Microsoft Windows Server 2016 (Standard).
* Microsoft Windows Server 2012 R2 (Standard).
* Microsoft Windows Server 2012 (Standard).
- Иметь опыт настройки IIS версий 7.5, 8.0, 8.5 или 10, а также обладать достаточным знанием IIS для включения требуемых компонентов.
- Должен уметь установить и настроить необходимое ПО, указанное в разделе Необходимые ресурсы ПО для использования электронной подписи.
- Быть способным распространить на клиентские рабочие места адрес и порт, которые используются модулем {wc}.
- Обладать навыками администрирования модуля {dv} 5. Windows-клиент и других модулей/приложений, установленных в системе {dv} (желательно).

== Разработчики расширений для {wc}

.Для успешной разработки Решений на {wc}е необходимо:
* Обладать опытом разработки на языках TypeScript и C#;
* Обладать навыками разработки веб-приложений с использованием библиотеки https://reactjs.org/[React];
* Иметь опыт разработки Решений на платформе {dv} (желательно).
