= Контейнер / Настраиваемая область

Элемент управления `_Контейнер / Настраиваемая область_` является контейнером, содержимое которого может быть настроено пользователем.

Режим настройки включается кнопкой xref:ctrl/mainMenu/configurableMainMenuContainer.adoc[Настроить].

== Свойства

include::partial$properties.adoc[tags=general]

=== Поведение

include::partial$properties.adoc[tags=visibility]

include::partial$properties.adoc[tags=addCss]

include::partial$properties.adoc[tags=stdCss]

=== События

==== После завершения конфигурации

Вызывается после выхода из режима настройки.

==== После начала конфигурации

Вызывается при входе в режим настройки.

==== После сохранения конфигурации

Вызывается при сохранении изменений.

==== Перед завершением конфигурации

Вызывается перед выходом из режима настройки.

==== Перед началом конфигурации

Вызывается перед входом в режим настройки.

==== Перед сохранением конфигурации

Вызывается перед сохранением изменений.

include::partial$properties.adoc[tags=mouseOver]

include::partial$properties.adoc[tags=mouseAway]

include::partial$properties.adoc[tags=onClick]
