= Контейнер / Настраиваемая область

Элемент управления `_Контейнер / Настраиваемая область_` является контейнером, содержимое которого может быть настроено пользователем.

Режим настройки включается кнопкой xref:configurableMainMenuContainerButton.adoc[Настроить].

== Свойства

Общие::
Название ЭУ:::
Название типа элемента управления.
Название:::
Уникальное название элемента управления.
Поведение::
Видимость:::
Настройка видимости. Элемент управления отображается в карточке, когда флаг установлен и не отображается вместе с содержимым, когда флаг снят.
+
`*Адаптивный*`
Дополнительные css классы:::
Названия дополнительных классов CSS для изменения стиля элемента управления. Перечисляются через пробел.
Стандартный css класс:::
Название CSS класса, в котором определен стандартный стиль элемента управления.
События::
После завершения конфигурации:::
Вызывается после выхода из режима настройки.
После начала конфигурации:::
Вызывается при входе в режим настройки.
После сохранения конфигурации:::
Вызывается при сохранении изменений.
Перед завершением конфигурации:::
Вызывается перед выходом из режима настройки.
Перед началом конфигурации:::
Вызывается перед входом в режим настройки.
Перед сохранением конфигурации:::
Вызывается перед сохранением изменений.
При наведении курсора:::
Вызывается при входе курсора мыши в область элемента управления.
При отведении курсора:::
Вызывается, когда курсор мыши покидает область элемента управления.
При щелчке:::
Вызывается при щелчке мыши по любой области элемента управления.
