= Ссылка / HTML страница

Элемент управления `_Ссылка / HTML страница_` добавляет в дерево папок ссылку для открытия HTML страницы с известным адресом. Страница ссылки открывается в области просмотра карточки/папки {wc}а.

== Свойства

=== Общие

==== Название ЭУ

Название типа элемента управления.

==== Название

Уникальное название элемента управления.

=== Внешний вид

==== CSS класс иконки

Название CSS класса с иконкой ссылки.

==== Заголовок страницы

Текст, отображаемый справа от открытия/скрытия дерева папок, при открытии ссылки.

`*Локализуемый*`

==== Компактный режим

Включает или выключает минимизацию пространства, необходимого для отображения данной ссылки.

==== Текст

Текст, отображаемый в строке ссылки в дереве папок.

`*Локализуемый*`

==== Цвет страницы

Определяет цвет оформления страницы для отображения содержимого папки. Варианты: *_Папка_* -- темно-синий цвет, *_Задача_* -- зеленый цвет, *_Документ_* -- синий цвет.

=== Данные

==== Адрес

Адрес HTML-страницы в формате `\http://www.company.org`.

NOTE: Целевая страница должна разрешать встраивание в другие страницы/фреймы.

=== Поведение

==== Видимость

Настройка видимости. Элемент управления отображается в карточке, когда флаг установлен. Элемент управления и любое его содержимое не отображаются, когда флаг снят.

`*Адаптивный*`

==== Дополнительные css классы

Названия дополнительных классов CSS для изменения стиля элемента управления. Перечисляются через пробел.

==== Настраиваемый

Включает или выключает режим, при котором пользователь может скрыть ЭУ. ЭУ должен находиться внутри контейнера xref:ctrl/mainMenu/configurableMainMenuContainer.adoc[Настраиваемая область].

==== Стандартный css класс

Название CSS класса, в котором определен стандартный стиль элемента управления.

=== События

==== Перед выбором

Вызывается перед изменением свойства `*isSelected*`.

==== После выбора

Вызывается после изменения свойства `*isSelected*`.

==== После изменения настройки видимости пункта

Вызывается после изменения пользователем признака видимости элемента в дереве папок.

==== При наведении курсора

Вызывается при входе курсора мыши в область элемента управления.

==== При отведении курсора

Вызывается, когда курсор мыши покидает область элемента управления.

==== При щелчке

Вызывается при щелчке мыши по любой области элемента управления.
