= Папки / Групповые папки

Элемент управления `_Папка / Групповые папки_` предназначен для добавления папок рабочей группы пользователя в дерево папок.

ЭУ отображается в дереве папок, если папки рабочей группы настроены для текущего пользователя.

== Свойства

include::partial$properties.adoc[tags=general]

=== Внешний вид

==== CSS класс иконки

Название CSS класса с иконкой папки.

==== Компактный режим

Включает или выключает минимизацию пространства, необходимого для отображения данной папки.

==== Папки в компактном режиме

Включает или выключает минимизацию пространства, необходимого для отображения папок группы.

==== Показывать иконки

Включает или выключает отображение иконок у папок группы.

==== Показывать иконки у дочерних папок

Включает или выключает отображение иконок у вложенных папок группы.

==== Показывать корневой элемент

Флаг установлен -- отображаются корневые папки группы и их дочерние папки, флаг снят -- отображаются только дочерние папки.

==== Текст

Текст, отображаемый в строке папки.

==== Управление папками

Включает/отключает меню папки, позволяющее создавать подпапки, настраивать и удалять данную папку.

==== Уровень предзагрузки дочерних папок

Определяет уровень вложенности папок данного каталога, до которого подпапки будут загружены без дополнительных запросов. Данные подпапок с более высоким уровнем вложенности загружаются через отдельные клиент-серверные запросы. Должно быть указано целое число.

=== Поведение

include::partial$properties.adoc[tags=visibility]

include::partial$properties.adoc[tags=addCss]

==== Настраиваемый

Включает или выключает режим, при котором пользователь может скрыть ЭУ. ЭУ должен находиться внутри контейнера xref:ctrl/mainMenu/configurableMainMenuContainer.adoc[Настраиваемая область].

include::partial$properties.adoc[tags=stdCss]

==== Уровень автоматического раскрытия дочерних элементов

Указывает уровень вложенности папок, до которого вложенные в ЭУ папки будут раскрыты по умолчанию. При значении 0 автоматическое раскрытие папок не выполняется.

=== События

==== Перед выбором

Вызывается перед изменением свойства `*isSelected*`.

==== Перед сворачиванием/разворачиванием элемента

Вызывается перед сворачиванием/разворачиванием элемента управления.

==== После сворачивания/разворачивания элемента

Вызывается после сворачивания/разворачивания элемента управления.

==== После выбора

Вызывается после изменения свойства `*isSelected*`.

==== После изменения настройки видимости пункта

Вызывается после изменения пользователем признака видимости элемента в дереве папок.

include::partial$properties.adoc[tags=mouseOver]

include::partial$properties.adoc[tags=mouseAway]

include::partial$properties.adoc[tags=onClick]
