= Ссылка / Локация

Элемент управления `_Ссылка / Локация_` добавляет в дерево папок ссылку для открытия xref:locations-about-settings.adoc[локации].

== Свойства

include::partial$properties.adoc[tags=general]

=== Внешний вид

==== CSS класс иконки

Название CSS класса с иконкой ссылки.

==== Заголовок страницы

Текст, отображаемый справа от открытия/скрытия дерева папок, при открытии ссылки.

`*Локализуемый*`

==== Компактный режим

Включает или выключает минимизацию пространства, необходимого для отображения данной ссылки.

==== Максимальная высота

Устанавливает ограничение по высоте для элемента управления. Значение в пикселях.

==== Текст

Текст, отображаемый в строке ссылки в дереве папок.

`*Локализуемый*`

==== Цвет страницы

Определяет цвет оформления страницы для отображения содержимого папки. Варианты: *_Папка_* -- темно-синий цвет, *_Задача_* -- зеленый цвет, *_Документ_* -- синий цвет.

=== Данные

==== Локация

Локация, которая должна открываться при переходе по ссылке.

NOTE: Поддерживается локации только из группы локаций "WebFrame".

==== Источник локации

Выбор источника локации. Для выбора доступны варианты *_Локация_* и *_Связанная карточка/строка_*.

==== Параметры загрузки разметки

Не используется. *Оставить пустым.*

=== Поведение

include::partial$properties.adoc[tags=visibility]

include::partial$properties.adoc[tags=addCss]

include::partial$properties.adoc[tags=setupable]

=== Режим

Режим отображения элемента управления. Для выбора доступны варианты: *_любой_*, *_просмотр_*, *_редактирование_*, *_создание_*.

include::partial$properties.adoc[tags=stdCss]

=== События

include::partial$properties.adoc[tags=beforeSelect]

include::partial$properties.adoc[tags=afterSelect]

include::partial$properties.adoc[tags=afterVisibilityChanged]

include::partial$properties.adoc[tags=mouseOver]

include::partial$properties.adoc[tags=mouseAway]

include::partial$properties.adoc[tags=onClick]
