= Ссылка / Страница {wc}а

Элемент управления `_Ссылка / Страница {wc}а_` добавляет в дерево папок ссылку для открытия страницы {wc}а.

== Свойства

include::partial$properties.adoc[tags=general]

=== Внешний вид

==== CSS класс иконки

Название CSS класса с иконкой ссылки.

==== Компактный режим

Включает или выключает минимизацию пространства, необходимого для отображения данной ссылки.

==== Текст

Текст, отображаемый в строке ссылки в дереве папок.

`*Локализуемый*`

=== Данные

==== Адрес

Адрес страницы {wc}а в формате `#/Folder/RecentCards`.

=== Поведение

==== HTML Accesskey

См. https://www.w3schools.com/TAGS/att_accesskey.asp.

==== HTML Download

См. https://www.w3schools.com/TAGS/att_a_download.asp.

==== HTML Hreaflang

См. https://www.w3schools.com/TAGS/att_a_hreflang.asp.

==== HTML Target

См. https://www.w3schools.com/TAGS/att_a_target.asp.

==== HTML Type

См. https://www.w3schools.com/TAGS/att_a_type.asp.

include::partial$properties.adoc[tags=visibility]

include::partial$properties.adoc[tags=addCss]

==== Настраиваемый

Включает или выключает режим, при котором пользователь может скрыть ЭУ. ЭУ должен находиться внутри контейнера xref:ctrl/mainMenu/configurableMainMenuContainer.adoc[Настраиваемая область].

include::partial$properties.adoc[tags=stdCss]

==== Уровень автоматического раскрытия дочерних элементов

Указывает уровень вложенности папок, до которого вложенные в ЭУ папки будут раскрыты по умолчанию. При значении 0 автоматическое раскрытие папок не выполняется.

=== События

==== Перед выбором

Вызывается перед изменением свойства `*isSelected*`.

==== После выбора

Вызывается после изменения свойства `*isSelected*`.

==== После изменения настройки видимости пункта

Вызывается после изменения пользователем признака видимости элемента в дереве папок.

include::partial$properties.adoc[tags=mouseOver]

include::partial$properties.adoc[tags=mouseAway]

include::partial$properties.adoc[tags=onClick]
