= Контейнер / Главное меню

Элемент управления `_Контейнер / Главное меню_` является контейнером, в котором должны размещаться элементы панели _Дерево папок_.

== Свойства

Общие::
Название ЭУ:::
Название типа элемента управления.
Название:::
Уникальное название элемента управления.
Поведение::
Видимость:::
Настройка видимости. Элемент управления отображается в карточке, когда флаг установлен. Эелемент управления и любое его содержимое не отображаются, когда флаг снят.
+
`*Адаптивный*`
Дополнительные css классы:::
Названия дополнительных классов CSS для изменения стиля элемента управления. Перечисляются через пробел.
Минимальная ширина:::
Минимально возможная ширина элемента управления в пикселях.
+
`*Адаптивный*`
Стандартный css класс:::
Название CSS класса, в котором определен стандартный стиль элемента управления.
События::
При изменении состояния закрепления:::
Вызывается при закреплении/откреплении панели с помощью элемента управления xref:mainMenuPinButton.adoc[Кнопка / Закрепить меню].
При наведении курсора:::
Вызывается при входе курсора мыши в область элемента управления.
При отведении курсора:::
Вызывается, когда курсор мыши покидает область элемента управления.
При щелчке:::
Вызывается при щелчке мыши по любой области элемента управления.
