= Контейнер / Компактная группа

Элемент управления `_Контейнер / Компактная группа_` является контейнером для создания группы папок.

== Свойства

Общие::
Название ЭУ:::
Название типа элемента управления.
Название:::
Уникальное название элемента управления.
Внешний вид::
CSS класс иконки:::
Название CSS класса с иконкой кнопки.
Компактный режим:::
Включает/выключает минимизацию пространства, необходимого для отображения ЭУ.
Показывать корневой элемент:::
Включает/выключает отображения папок первого уровня, вложенных в Группу элементов.
Текст:::
Текст, отображаемый в заголовке элемента управления.
Поведение::
Видимость:::
Настройка видимости. Элемент управления отображается в карточке, когда флаг установлен и не отображается вместе с содержимым, когда флаг снят.
+
`*Адаптивный*`
Дополнительные css классы:::
Названия дополнительных классов CSS для изменения стиля элемента управления. Перечисляются через пробел.
Настраиваемый:::
Включает/выключает режим, при котором пользователь может скрыть ЭУ. ЭУ должен находиться внутри контейнера xref:configurableMainMenuContainer.adoc[Настраиваемая область].
Стандартный css класс:::
Название CSS класса, в котором определен стандартный стиль элемента управления.
Уровень автоматического раскрытия дочерних элементов:::
Указывает уровень вложенности папок, до которого вложенные в ЭУ папки будут раскрыты по умолчанию. При значении 0 автоматическое раскрытие папок не выполняется.
События::
Перед выбором:::
Вызывается перед изменением свойства `*isSelected*`.
Перед сворачиванием/разворачиванием элемента:::
Вызывается перед сворачиванием/разворачиванием элемента управления.
После выбора:::
Вызывается после изменения свойства `*isSelected*`.
После изменения настройки видимости пункта:::
Вызывается после изменения пользователем признака видимости элемента в дереве папок.
После сворачивания/разворачивания элемента:::
Вызывается после сворачивания/разворачивания элемента управления.
При наведении курсора:::
Вызывается при входе курсора мыши в область элемента управления.
При отведении курсора:::
Вызывается, когда курсор мыши покидает область элемента управления.
При щелчке:::
Вызывается при щелчке мыши по любой области элемента управления.
