= Контейнер / Компактная группа

Элемент управления `_Контейнер / Компактная группа_` является контейнером для создания группы папок.

== Свойства

include::partial$properties.adoc[tags=general]

=== Внешний вид

==== CSS класс иконки

Название CSS класса с иконкой кнопки.

==== Компактный режим

Включает или выключает минимизацию пространства, необходимого для отображения ЭУ.

==== Показывать корневой элемент

Включает или выключает отображения папок первого уровня, вложенных в Группу элементов.

==== Текст

Текст, отображаемый в заголовке элемента управления.

=== Поведение

include::partial$properties.adoc[tags=visibility]

include::partial$properties.adoc[tags=addCss]

==== Настраиваемый

Включает или выключает режим, при котором пользователь может скрыть ЭУ. ЭУ должен находиться внутри контейнера xref:ctrl/mainMenu/configurableMainMenuContainer.adoc[Настраиваемая область].

include::partial$properties.adoc[tags=stdCss]

==== Уровень автоматического раскрытия дочерних элементов

Указывает уровень вложенности папок, до которого вложенные в ЭУ папки будут раскрыты по умолчанию. При значении 0 автоматическое раскрытие папок не выполняется.

=== События

==== Перед выбором

Вызывается перед изменением свойства `*isSelected*`.

==== Перед сворачиванием/разворачиванием элемента

Вызывается перед сворачиванием/разворачиванием элемента управления.

==== После выбора

Вызывается после изменения свойства `*isSelected*`.

==== После изменения настройки видимости пункта

Вызывается после изменения пользователем признака видимости элемента в дереве папок.

==== После сворачивания/разворачивания элемента

Вызывается после сворачивания/разворачивания элемента управления.

include::partial$properties.adoc[tags=mouseOver]

include::partial$properties.adoc[tags=mouseAway]

include::partial$properties.adoc[tags=onClick]
