= Контейнер / Панель элемента меню

Элемент управления `_Контейнер / Панель элемента меню_` является контейнером для размещения элементов xref:ctrl/mainMenu/mainMenuPinButton.adoc[Кнопка / Закрепить меню], xref:ctrl/mainMenu/configurableMainMenuContainerButton.adoc[Кнопка / Настроить], xref:ctrl/mainMenu/refreshFoldersTreeButton.adoc[Кнопка / Обновить].

== Свойства

include::partial$properties.adoc[tags=general]

=== Внешний вид

==== Локация

Данный ЭУ не создаёт собственной строки в дереве папок, а встраивается в существующую строку (располагается в правой части строки). Настройка Локация определяет, в какую строку должен быть встроен данный ЭУ:

* *_Ниже_*. Панель элемента меню будет встроена в элемент, расположенный ниже него в структуре разметки.
* *_Выше_*. Панель элемента меню будет встроена в элемент, расположенный выше него в структуре разметки.

=== Поведение

include::partial$properties.adoc[tags=visibility]

include::partial$properties.adoc[tags=addCss]

include::partial$properties.adoc[tags=minWidth]

include::partial$properties.adoc[tags=stdCss]

=== События

include::partial$properties.adoc[tags=mouseOver]

include::partial$properties.adoc[tags=mouseAway]

include::partial$properties.adoc[tags=onClick]
