= Папка / Результаты поиска

Элемент управления `_Папка / Результаты поиска_` предназначен для добавления папки с результатами последнего поискового запроса в дерево папок.

== Свойства

include::partial$properties.adoc[tags=general]

=== Внешний вид

==== CSS класс иконки

Название CSS класса с иконкой папки.

==== Компактный режим

Включает или выключает минимизацию пространства, необходимого для отображения данной папки.

==== Текст

Текст, отображаемый в строке папки. Если значение -- пустая строка, в строке ЭУ отображается название "Поиск".

=== Поведение

include::partial$properties.adoc[tags=visibility]

include::partial$properties.adoc[tags=addCss]

==== Настраиваемый

Включает или выключает режим, при котором пользователь может скрыть ЭУ. ЭУ должен находиться внутри контейнера xref:ctrl/mainMenu/configurableMainMenuContainer.adoc[Настраиваемая область].

include::partial$properties.adoc[tags=stdCss]

=== События

==== После выбора

Вызывается после изменения свойства `*isSelected*`.

==== Перед выбором

Вызывается перед изменением свойства `*isSelected*`.

==== После изменения настройки видимости пункта

Вызывается после изменения пользователем признака видимости элемента в дереве папок.

include::partial$properties.adoc[tags=mouseOver]

include::partial$properties.adoc[tags=mouseAway]

include::partial$properties.adoc[tags=onClick]
