= Папки / Пользовательские папки

Элемент управления `_Папка / Пользовательские папки_` предназначен для добавления группы настраиваемых папок в дерево папок. В данной группе отображаются папки, подключенные пользователем.

== Свойства

include::partial$properties.adoc[tags=general]

=== Внешний вид

==== CSS класс иконки

Название CSS класса с иконкой папки.

==== Анимация

Включает или выключает использование анимации при раскрытии папки.

==== Компактный режим

Включает или выключает минимизацию пространства, необходимого для отображения данной папки.

==== Папки в компактном режиме

Включает или выключает минимизацию пространства, необходимого для отображения папок группы.

==== Показывать иконки

Включает или выключает отображение иконок у пользовательских папок.

==== Показывать корневой элемент

Включает или выключает отображения данной папки. Если флаг снят, будут отображаться только вложенные папки.

==== Текст

Текст, отображаемый в строке папки. Если значение -- пустая строка, в строке ЭУ отображается название папки.

==== Управление папками

Включает/отключает меню папки, позволяющее создавать подпапки, настраивать и удалять данную папку.

==== Уровень предзагрузки дочерних папок

Определяет уровень вложенности папок данного каталога, до которого подпапки будут загружены без дополнительных запросов. Данные подпапок с более высоким уровнем вложенности загружаются через отдельные клиент-серверные запросы. Должно быть указано целое число.

=== Поведение

include::partial$properties.adoc[tags=visibility]

include::partial$properties.adoc[tags=addCss]

==== Минимальная ширина

Минимально возможная ширина элемента управления в пикселях.

`*Адаптивный*`

==== Настраиваемый

Включает или выключает режим, при котором пользователь может скрыть ЭУ. ЭУ должен находиться внутри контейнера xref:ctrl/mainMenu/configurableMainMenuContainer.adoc[Настраиваемая область].

==== Порядок

Определяет xref:layoutsBlockControlsOrder.adoc[порядок отображения] элемента управления в родительском `_Блоке_`. ЭУ с более низким порядком имеет более высокий приоритет в порядке отображения в разметке.

`*Адаптивный*`

include::partial$properties.adoc[tags=stdCss]

==== Уровень автоматического раскрытия дочерних элементов

Указывает уровень вложенности папок, до которого вложенные в ЭУ папки будут раскрыты по умолчанию. При значении 0 автоматическое раскрытие папок не выполняется.

==== Ширина в процентах

Ширина элемента управления в процентах (указывается целое число) от ширины родительского элемента управления.

`*Адаптивный*`

=== События

==== Перед выбором

Вызывается перед изменением свойства `*isSelected*`.

==== Перед сворачиванием/разворачиванием элемента

Вызывается перед сворачиванием/разворачиванием элемента управления.

==== После выбора

Вызывается после изменения свойства `*isSelected*`.

==== После изменения настройки видимости пункта

Вызывается после изменения пользователем признака видимости элемента в дереве папок.

==== После сворачивания/разворачивания элемента

Вызывается после сворачивания/разворачивания элемента управления.

include::partial$properties.adoc[tags=mouseOver]

include::partial$properties.adoc[tags=mouseAway]

include::partial$properties.adoc[tags=onClick]
