@startuml
skinparam rectangleBorderThickness 1

|#orange|Регистратор|
#lightgray:**Ввод документа в систему**;
:Регистрация документа;
if (Требуется работа по документу?) then (ДА)
:Обработка входящей корреспонденции;
|#green|Исполнитель задания|
:**Исполнение заданий по документу**;
|#orange|Регистратор|
#lightgray:**Перевод документа в архив**;
end
@enduml
