= Условия обновления

* Данная версия {wc}а предназначена для обновления с версии *5.5.15*.
* Установка новой версии должна выполняться в нерабочее время.
* Если была установлена новая версия модуля _Платформа_ и после её установки была пропущена обязательная операция обновления БД {dv}, обновите БД {dv} перед установкой {wc}а. Cм. инструкцию по обновлению в документации к новой версии модуля "Платформа".
* Перед установкой обновления ознакомьтесь с требованиями к xref:ROOT:requirementsDocsVision.adoc[системе DocsVision] и xref:ROOT:requirementsSoftware.adoc[программному обеспечению].
* В версии *5.5.16* добавлена поддержка работы с модулем _{dv} 5. {arch}_. Если планируется работать с функциями данного модуля, перед обновлением {wc}а установите серверную часть модуля _{dv} 5. {arch}_ на компьютер с сервером {dv} и компьютер с сервером {wc}а.
* При обновлении версия {wc}а должна равняться версии серверного расширения.
* {wc} версии **5.5.16** не поддерживает работу с модулем Docsvision 5. Платформа версии 5.5.1.