= Содержимое

Элемент управления `_Содержимое_` является контейнером, в котором отображается содержимое области представления {wc}а: карточка, представление папки.

== Свойства

include::partial$properties.adoc[tags=general]

=== Поведение

include::partial$properties.adoc[tags=addCss]

include::partial$properties.adoc[tags=stdCss]

[#bg]
==== Использовать фон по выбору пользователя

В свойстве указывается путь к локальному файлу. Если по указанному пути есть картинка, она будет использоваться как пользовательский фон для главной страницы.

Картинка будет также использована как фон для папок, если задано свойство `*Стандартный фон*` для элемента *root* в локациях _Папка_, _Последние карточки_, _Результаты поиска_, _Главная страница_. Если свойство не задано, для главной страницы и папок будет использоваться фон по умолчанию.

При выборе фона становится доступным свойство `*Отображение фона*` -- выпадающий список с вариантами растянуть или замостить.

=== События

include::partial$properties.adoc[tags=mouseOver]

include::partial$properties.adoc[tags=mouseAway]

include::partial$properties.adoc[tags=onClick]
