= Контейнер Body

Элемент управления `_Контейнер Body_` является контейнером для элементов управления, которые должны отображаться в основной области окна {wc}а.

== Свойства

Общие::
Название ЭУ:::
Название типа элемента управления.
Название:::
Уникальное название элемента управления.
Поведение::
Дополнительные css классы:::
Названия дополнительных классов CSS для изменения стиля элемента управления. Перечисляются через пробел.
Минимальная ширина:::
Минимально возможная ширина элемента управления в пикселях.
+
`*Адаптивный*`
Порядок:::
Определяет xref:layoutsBlockControlsOrder.adoc[порядок отображения] элемента управления в родительском `_Блоке_`. ЭУ с более низким порядком имеет более высокий приоритет в порядке отображения в разметке.
+
`*Адаптивный*`
Стандартный css класс:::
Название CSS класса, в котором определен стандартный стиль элемента управления.
Ширина в процентах:::
Ширина элемента управления в процентах (указывается целое число) от ширины родительского элемента управления.
+
`*Адаптивный*`
События::
При наведении курсора:::
Вызывается при входе курсора мыши в область элемента управления.
При отведении курсора:::
Вызывается, когда курсор мыши покидает область элемента управления.
При щелчке:::
Вызывается при щелчке мыши по любой области элемента управления.
