= Данные папки

include::partial$inDevelopment.adoc[]

Элемент управления может использоваться для отображения папки, выбранной в Главном Меню, либо папки, заданной в свойствах элемента управления. Также может являться контейнером для стандартных и специальных элементов управления для работы с данными папки.

== Свойства

include::partial$properties.adoc[tags=general]

=== Данные

==== Режим

Определяет режим отображения данных папки:

. *_Источник данных._* При выборе данного режима элемент управления будет получать данные из указанного источника. Режим *_Источник данных_* позволяет выбрать источник данных, расширенный источник данных и поле данных.
. *_Из адреса страницы_* (значение по умолчанию). При выборе данного режима элемент управления будет отображать папку, указанную в адресе страницы.
. *_Известная папка_*. При выборе данного режима элемент управления будет отображать папку с идентификатором указанным в поле `Идентификатор папки`.
. *_Системная папка._* При выборе данного режима элемент управления будет отображать выбранную из списка системную папку.

=== Поведение

include::partial$properties.adoc[tags=visibility]

include::partial$properties.adoc[tags=addCss]

include::partial$properties.adoc[tags=stdCss]

=== События

include::partial$properties.adoc[tags=mouseOver]

include::partial$properties.adoc[tags=mouseAway]

include::partial$properties.adoc[tags=onClick]
