= Данные папки

include::partial$inDevelopment.adoc[]

Элемент управления может использоваться для отображения папки, выбранной в Главном Меню, либо папки, заданной в свойствах элемента управления. Также может являться контейнером для стандартных и специальных элементов управления для работы с данными папки.

[#properties]
== Свойства

include::partial$properties.adoc[tags=general]

[#data]
=== Данные

[#mode]
==== Режим

.Определяет режим отображения данных папки:
. *_Источник данных_*. При выборе данного режима элемент управления будет получать данные из указанного источника. Режим *_Источник данных_* позволяет выбрать свойства `*Источник данных*`, `*Расширенный источник данных*` и `*Поле данных*`.
. *_Из адреса страницы_* (значение по умолчанию). При выборе данного режима элемент управления будет отображать папку, указанную в адресе страницы.
. *_Известная папка_*. При выборе данного режима элемент управления будет отображать папку с идентификатором указанным в поле `Идентификатор папки`.
. *_Системная папка_*. При выборе данного режима элемент управления будет отображать выбранную из списка системную папку.

[#dataSource]
:option: Источник данных
include::partial$properties.adoc[tags=dataSource]
include::partial$excerpts.adoc[tags=mode-source]

[#extendedDataSource]
include::partial$properties.adoc[tags=extendedDataSource]
include::partial$excerpts.adoc[tags=mode-source]

[#dataField]
include::partial$properties.adoc[tags=dataField]
include::partial$excerpts.adoc[tags=mode-source]

[#folder-id]
==== Идентификатор папки

:option: Известная папка
Позволяет указать идентификатор папки.
include::partial$excerpts.adoc[tags=mode-source]

[#system-folder]
==== Системная папка

:option: Системная папка
Позволяет выбрать отображаемую в элементе управления системную папку.
include::partial$excerpts.adoc[tags=mode-source]

.Доступные системные папки:
. Последние карточки.
. Результаты поиска.
. Избранное.

[#select-view]
==== Выбор представления

В данном свойстве отображается список всех представлений, доступных для выбора. Свойство позволяет указать разрешенные для выбора представления. Чтобы выбрать представление, установите флаг напротив его названия.

В окне настроек грида будет отображаться список выбранных в данном свойстве представлений. Если в свойстве не указано ни одно представление, будут отображаться все доступные пользователю представления.

[NOTE]
====
include::partial$excerpts.adoc[tags=mode-source]
====

[#behavior]
=== Поведение

[#visibility]
include::partial$properties.adoc[tags=visibility]

[#addCss]
include::partial$properties.adoc[tags=addCss]

[#stdCss]
include::partial$properties.adoc[tags=stdCss]

[#events]
=== События

[#mouseOver]
include::partial$properties.adoc[tags=mouseOver]

[#mouseAway]
include::partial$properties.adoc[tags=mouseAway]

[#onClick]
include::partial$properties.adoc[tags=onClick]
