= Данные папки

include::partial$inDevelopment.adoc[]

Элемент управления может использоваться для отображения папки, выбранной в Главном Меню, либо папки, заданной в свойствах элемента управления. Также может являться контейнером для стандартных и специальных элементов управления для работы с данными папки.

== Свойства

=== Общие

==== Название ЭУ

Название типа элемента управления.

==== Название

Уникальное название элемента управления.

=== Данные

==== Режим

Определяет режим отображения данных папки:

. *_Источник данных._* При выборе данного режима элемент управления будет получать данные из указанного источника. Режим *_Источник данных_* позволяет выбрать источник данных, расширенный источник данных и поле данных.
. *_Из адреса страницы_* (значение по умолчанию). При выборе данного режима элемент управления будет отображать папку, указанную в адресе страницы.
. *_Известная папка_*. При выборе данного режима элемент управления будет отображать папку с идентификатором указанным в поле `Идентификатор папки`.
. *_Системная папка._* При выборе данного режима элемент управления будет отображать выбранную из списка системную папку.

=== Поведение

==== Видимость

Настройка видимости. Элемент управления отображается в карточке, когда флаг установлен. Элемент управления и любое его содержимое не отображаются, когда флаг снят.

`*Адаптивный*`

==== Дополнительные css классы

Названия дополнительных классов CSS для изменения стиля элемента управления. Перечисляются через пробел.

==== Стандартный css класс

Название CSS класса, в котором определен стандартный стиль элемента управления.

=== События

==== При наведении курсора

Вызывается при входе курсора мыши в область элемента управления.

==== При отведении курсора

Вызывается, когда курсор мыши покидает область элемента управления.

==== При щелчке

Вызывается при щелчке мыши по любой области элемента управления.
