= Тулбар папки

Панель управления нового грида. Свойства панели управления регулируют операции, доступные для представления папки.

== Свойства

include::partial$properties.adoc[tags=general]

=== Внешний вид

Свойства категории "Внешний вид" могут быть активированы или отключены отдельно для каждого типа устройств: Десктоп, Планшет, Телефон. Например, чтобы отключить свойство, для телефона, нужно снять флаг в строке "Телефон".

[#display]
==== Изменить отображение

Позволяет или запрещает пользователям переключаться между режимами: Грид или Лента.

[#settings]
==== Настройки

Регулирует доступность окна пользовательских настроек с панели инструментов.

[#refresh]
==== Обновить

Позволяет отключить кнопку обновления данных в представлении.

[#read]
==== Прочитать все

Позволяет отключить кнопку обновления данных в представлении.

[#size]
==== Размер папки

Включает или отключает отображение количества карточек в папке.

[#reset]
==== Сбросить настройки

Когда свойство активно, пользователю будет доступна кнопка "Сбросить пользовательские настройки". Когда свойство неактивно, сбросить настройки на стандартные нельзя.

[#export]
==== Экспорт

Разрешает или запрещает возможность экспортировать представление в Excel.

=== Поведение

include::partial$properties.adoc[tags=visibility]

include::partial$properties.adoc[tags=addCss]

include::partial$properties.adoc[tags=stdCss]

=== События

include::partial$properties.adoc[tags=mouseOver]

include::partial$properties.adoc[tags=mouseAway]

include::partial$properties.adoc[tags=onClick]
