= Групповые операции / Переместить ярлык

Элемент управления `_Групповые операции / Переместить ярлык_` вызывает операцию перемещения ярлыков группы выбранных карточек из текущей папки в выбранную. Перед выполнением операции будет представлена возможность выбора папки, в которую перемещаются ярлыки.

TIP: Данный ЭУ может быть добавлен только в разметку локации menu:WebFrame[Компоненты папки > Групповые операции с карточками].

== Свойства

Общие::
Название ЭУ:::
Название типа элемента управления.
Название:::
Уникальное название элемента управления.
Внешний вид::
Текст кнопки:::
Текст, отображаемый на кнопке перемещения.
+
`*Локализуемый*`
Поведение::
Видимость:::
Настройка видимости. Элемент управления отображается в карточке, когда флаг установлен. Элемент управления и любое его содержимое не отображаются, когда флаг снят.
+
`*Адаптивный*`
Дополнительные css классы:::
Названия дополнительных классов CSS для изменения стиля элемента управления. Перечисляются через пробел.
Стандартный css класс:::
Название CSS класса, в котором определен стандартный стиль элемента управления.
События::
При наведении курсора:::
Вызывается при входе курсора мыши в область элемента управления.
При отведении курсора:::
Вызывается, когда курсор мыши покидает область элемента управления.
При щелчке:::
Вызывается при щелчке мыши по любой области элемента управления.
