= Контейнер локации

Элемент управления `_Контейнер локации_` предназначен для отображения данных карточки или другого элемента с разметкой в другой карточке.

== Свойства

include::partial$properties.adoc[tags=general]

=== Внешний вид

==== Максимальная высота

Устанавливает ограничение по высоте для элемента управления. Значение в пикселях.

=== Данные

==== Источник локации

* *_Локация_*. В элементе будет отображаться разметка из локации, выбранной в свойстве `*Локация*`.
* *_Связанная карточка/строка_*. В элементе будет отображаться связанная карточка или данные строки связанной карточки. Ссылка на карточку содержится в поле, указанном в источнике данных. При отображении будет использована разметка с режимом из свойства `*Режим*`.

NOTE: Свойство `*Локация*` доступно, если в `*Источник локации*` выбрано *_Локация_*. Свойства `*Расширенный источник данных*`, `*Источник данных*` и `*Поле данных*` доступны, если в `*Источник локации*` выбрано *_Связанная карточка/строка_*.

include::partial$properties.adoc[tags=extendedDataSource]

include::partial$properties.adoc[tags=dataSource]

==== Поле данных

Поле текущей или связанной карточки с идентификатором карточки или строки карточки, отображаемой в элементе управления.

==== Локация

Локация, разметка которой будет отображаться в элементе управления.

==== Параметры загрузки разметки

Дополнительные параметры, передаваемые при открытии разметки.

=== Поведение

==== Асинхронная загрузка

Определяет способ загрузки разметки локации.

* Разметка локации будет загружена после загрузки родительской разметки, когда флаг установлен.
* Разметка локации будет загружена вместе с родительской разметкой, когда флаг снят (потребуется больше времени для запуска родительской разметки).

include::partial$properties.adoc[tags=visibility]

include::partial$properties.adoc[tags=addCss]

==== Пользовательская функция загрузки разметки

Название функции, переопределяющей механизм загрузки разметки локации. Указывается при необходимости.

Данная функция может быть использована, если нужно передавать в разметку собственные параметры, значение которых вычисляется во время исполнения.

Функция принимает единственный параметр с типом *_LocationContainerControl_*. Описание типа см. в https://{dv}.com/docs/webclient/5.5.14/JsDocApi/classes/\_system_locationcontainercontrol_d_.locationcontainercontrol.html[JSDocsApi].

=== Режим

Режим, в котором будет открываться разметка. Может принимать значение из списка: *_Любой_*, *_Описание_*, *_Справка_*, *_Просмотр_*, *_Редактирование_*, *_Создание_*, *_Внутри другой разметки_*.
+
Свойство `*Режим*` используется при выборе подходящей разметки из списка разметок внедряемой карточки. Например, если установлен режим *_Редактирование_*, то при внедрении будет использована разметка, в условии выбора которой указан режим *_Редактирование*_.

Использование специального режима *_Внутри другой разметки_* (он также доступен в условиях выбора разметки) позволяет отделить разметки, разработанные специально для отображения карточки внутри другой карточки, от разметок, используемых при обычной работе с карточкой (с режимами *_Просмотр_*, *_Редактирование_*, *_Создание_*). При этом у внедряемой карточки должно быть условие выбора разметки с режимом *_Внутри другой разметки_*.

include::partial$properties.adoc[tags=stdCss]

==== Часть родительской разметки

Определяет режим интеграции разметки локации в родительскую разметку.

* Разметка локации будет загружена как часть родительской локации, когда флаг установлен (элементы управления разметки будут добавлены в родительскую разметку),
* Разметка локации не будет интегрирована в родительскую разметку, когда флаг снят.

=== События

include::partial$properties.adoc[tags=mouseOver]

include::partial$properties.adoc[tags=mouseAway]

include::partial$properties.adoc[tags=onClick]
