
== Добавление сотрудников в группу и удаление из группы

В справочнике сотрудников реализована возможность группировать сотрудников. Добавить сотрудника в группу можно xref:AddUserToGroup.html[из вкладки] [.keyword .wintitle]*Сотрудники* в правой области , когда в левой области открыта вкладка [.keyword .wintitle]*Группы* (позволяет добавить в одну группу несколько сотрудников) или xref:AdduserToGroupFromCard.html[из карточки] сотрудника (позволяет добавить одного сотрудника в несколько групп).

* *xref:../topics/AddUserToGroup.html[Добавление сотрудников в группу из вкладки «Сотрудники»]* +
* *xref:../topics/AdduserToGroupFromCard.html[Добавление сотрудника в группы из карточки сотрудника]* +
* *xref:../topics/DeleteUserFromGroup.html[Удаление сотрудников из группы на вкладке «Сотрудники»]* +
* *xref:../topics/DeleteUserFromGroup2.html[Удаление сотрудника из групп в карточке сотрудника]* +
* *xref:../topics/CopyMissingGroups.html[Скопировать группы сотрудников]* +

*На уровень выше:* xref:../topics/ManageGroups.html[Работа с группами]
