
== Использование новых стилей {wc} 15 в собственных разметках

В {wc} 15 для разметок карточек модуля «Управление документами» были разработаны новые стили, которые по умолчанию используются только в стандартных карточках разметок. Для использования новых стилей в собственных разметках необходимо назначить специальные обработчики и стили на элементы разметок.

. Назначьте на событие «Перед открытием карточки» (On card opening) корневого элемента разметки (*documentRoot*) обработчик:
* addNewStyleForControls -- добавляет для разметки и её модальных окон класс «new-style-layout». Новые стили могут быть применены только при наличии у разметки данного класса.
. Назначьте на событие «После открытия карточки» (On card opened) корневого элемента разметки (*documentRoot*) обработчики:
* {blank}
+
addStyleToCard -- включает в себя три обработчика:

** getControlsForExpanding -- осуществляет поиск Блоков с классом «block-with-border», для которых включает поддержку возможности сворачивания/разворачивания по щелчку на общей кнопке сворачивания/разворачивания всех блоков.
** addGrayBackgroundToCard -- добавляет в карточку фон серого цвета.
** addShadowBorder -- осуществляет поиск раскрытых Блоков с классом «block-with-border», для которых добавляет серую рамку.
+
Вместо одного обработчика addStyleToCard можно указать обработчики getControlsForExpanding, addGrayBackgroundToCard и addShadowBorder. Если отдельные функции не требуются, обработчики можно не указывать.
* outgoingDocument_CardManagementIsVisible -- загружает почту и телефон контрагентов, указанных в списке Адресаты, при загрузке карточки, а также скрывает пустой блок с примечанием. Используется только в разметке Исходящего документа.
. Назначьте на события «При сворачивании» (On collapsed) и «При разворачивании» (On expanded) элементов Блок, Список файлов, Ссылки и др. сворачиваемых элементов, обработчик:
* switchBorderWithShadow -- в развернутом состоянии добавляет к элементу рамку с тенью, и скрывает её при сворачивании элемента.
+
Обработчик switchBorderWithShadow следует добавлять только к элементам, для которых нужна тень. Например, это блок с информацией о карточке, список файлов или блок, в котором отображается ход исполнения.
+
Постоянную рамку (для несворачиваемых блоков) можно добавить с помощью стиля «block-with-shadow»: указать в параметре «Дополнительные CSS классы» требуемого элемента.
+
Для устаревших элементов управления TaskCardFilePanel, TaskCardReportPanel и т. п., у которых отсутствуют события «При сворачивании» / «При разворачивании», рамка с тенью может быть добавлена только с помощью стиля «block-with-shadow».
. Укажите в настройке «Дополнительные CSS классы» стили:
* Для корневого элемента documentRoot:
** system-layout-independent-scroll -- включает отдельную прокрутку для элемента [.dfn .term]_Предпросмотр файла_ и области с данными карточки;
** expansion-panel-header -- включает новый дизайн для заголовков Блоков;
** center-screen -- включает динамическое изменение боковых отступов от края страницы до элементов с данными карточки: чем уже окно браузера, тем меньше отступы;
** control-label-opacity-half -- включает использование серого цвета для меток элементов управления;
* Для Блоков:
** block-with-toggle-button -- добавляет в Блок кнопку сворачивания/разворачивания всех Блоков со стилем «block-with-border». Для избежания ошибок: стиль следует использовать только в одном Блоке разметки; у данного блока не должно быть обработчиков события «При щелчке»;
** top-saving-buttons-block -- включает выравнивание содержимого по высоте, убирает лишнее пространство у кнопок. Следует устанавливать только в Блоке, в котором размещается название карточки и Кнопки сохранения, если дизайн пользовательской разметки повторяет дизайн стандартной разметки документов;
** block-with-shadow -- добавляет тень и рамку к Блоку. Если для блока включен обработчик switchBorderWithShadow, добавлять стиль block-with-shadow не нужно;
* Для Блоков, Списка файлов, Ссылок и др. сворачиваемых элементов, для которых назначен обработчик switchBorderWithShadow:
** block-with-border -- добавляет функцию сворачивания/разворачивания элемента, вызываемую кнопкой сворачивания/разворачивания всех Блоков.
+
Прочие доступные стандартные стили:

* document-name-small -- устанавливает размер шрифта 1.4rem. В разметках {wc} 15 используется в элементе с названием карточки;
* document-name -- устанавливает размер шрифта 1.6875rem. Стандартные размер для элемента с названием карточки в {wc} 14;
* card-kind-large -- при ширине экрана более 420px устанавливает размер шрифта 1.125rem. В разметках {wc} 15 используется в элементе Вид карточки;
* document-view-state-wide -- переводит строчные буквы в прописные и добавляет межбуквенный интервал. В разметках {wc} 15 в элементе Состояние;
* taskstable-with-hidden-filters -- скрывает фильтры в элементе Таблица исполнения;
* colored-button -- для элемента Кнопка включает использование стандартной цветовой гаммы открытой карточки;
* block-border-top / block-border-right / block-border-bottom / block-border-left -- добавляет серую линию в 1px по верхней / правой / нижней / левой границе элемента;
* block-with-disclosure-body-center -- для Блоков включает выравнивание содержимого по центру;
* block-with-disclosure-resize -- для Блока включает особый режим выравнивания дочерних блоков, если у Блока два дочерних блока шириной 50% от родительского и установленной минимальной шириной: если ширины родительского блока достаточно для отображения обоих блоков в строку -- они будут отображаться в строку, иначе -- в столбец;
* block-with-one-height -- для Блока включает особый режим выравнивания дочерних Блоков по высоте: всем дочерним Блокам будет установлены высота самого высокого Блока;
* block-with-state-buttons -- для Блока устанавливает особый режим выстраивания элементов Кнопка: при ширине окна меньше 421px кнопки будут размещаться вертикально с выравниванием по ширине родительского Блока.
