
== Изменение режима работы с Решением

Режим работы с Решением определяет возможность изменения разметок, условий выбора и других настроек Решения. В Конструкторе web-pазметок поддерживается два режима:

* «Заказчик» – возможность изменения Решения заблокирована;
* «Поставщик» – возможность изменения Решения разрешена.

Для изменения режима работы с Решением:

. Откройте xref:dl_solution_controlpanel.html[Панель управления Решениями].
. Выберите Решение, режим которого нужно изменить.
. Нажмите кнопку «Переключить режим». Режим изменится на противоположный.
+
*Обратите внимание:*

* Запрещено изменять настройки стандартных Решений Web-клиента: «Базовые решения» и «Управления документами».
+
Если требуется модифицировать стандартные разметки:

[loweralpha]
.. Создайте собственное Решение.
.. Скопируйте в него стандартные разметки.
.. Модифицируйте копии разметок требуемым образом.
.. Создайте правила для выбора данных разметок.
* После установки Решения в рабочую базу данных не рекомендуется изменять его режим работы на «Поставщик», т. к. это может привести к ошибкам при обновлении Решения.

Кнопка «Переключить режим» по умолчанию недоступна. Чтобы разблокировать данную возможность:

. Откройте конфигурационный файл [.ph .filepath]`<Каталог установки Web-клиента>\5.5\WebLayoutsDesigner.exe.config`.
. Измените значение настройки [.ph .filepath]`Docsvision/WebClient/SettingGroups/SettingGroup[Name="WebLayoutsDesigner"]/Setting[Name="DesignerMode"]` на значение:
* «Vendor» – чтобы разрешить изменять режим Решения;
* «Customer» – чтобы запретить изменять режим Решения.
. Запустите Конструктор web-разметок и откройте xref:dl_solution_controlpanel.html[Панель управления Решениями].
. Выберите Решение в списке и нажмите кнопку [.ph .uicontrol]*Переключить режим*. Значение режима будет изменено.

*Parent topic:* xref:../topics/dl_solution.html[Управление Решениями]
