
== Выбор текущего решения

В списке xref:designerlayouts_solutions.html[Текущее решение] выберите Решение, разметки которого планируется настраивать, или вариант «Мои настройки», если нет собственного разработанного Решения.

Если планируется распространять настройки разметок, рекомендуется xref:sc_createsolution.html[создать Решение] перед настройкой разметок и условий выбора, и выбрать его в списке.

Возможность изменения настроек стандартных Решений («Базовые объекты» и «Управление документами») и Решений сторонних производителей по умолчанию заблокирована (данные Решения в списке не отображаются). Инструкция по разблокированию приведена в пункте xref:ChangeSolutionMode.html[Изменение режима работы с Решением].

[NOTE]
====
[.note__title]#Note:# Вместо изменения стандартных Разметок можно скопировать данные разметки в собственное Решение или в «Мои настройки». Копии Разметок могут быть изменены без ограничений.
====

После выбора Решения:

* новые разметки будут создаваться в выбранном Решении;
* новые условия выбора будут создаваться в выбранном Решении; возможность изменения условий выбора из других Решений будет заблокирована;
* xref:localization_opencontrolpanel.html[панель управления ресурсами локализации] будет предоставлять доступ к ресурсам выбранного Решения.

*Parent topic:* xref:../topics/Operations.html[Выполнение операций]
