
== Настройка логотипа для штампа электронной подписи

По умолчанию в штампе ЭП, отображаемом в печатной версии подписанного файла, размещается логотип «Щит». Администратор может изменить изображение.

. Откройте конфигурационный файл [.ph]#[.ph .filepath]`[Каталог установки {wc}а]\5.5\Site\web.config`#.
. Перейдите к секции [.ph .menucascade]#[.ph .uicontrol]*configuration* > [.ph .uicontrol]*{dv}* > [.ph .uicontrol]*WebClient* > [.ph .uicontrol]*SettingGroups* > [.ph .uicontrol]*SettingGroup[Name="DefaultESImageGenerator"]*#. По умолчанию данной секции нет – её нужно создать самостоятельно.
. Измените значение параметра `LogoImagePath`, указав путь к PNG файлу нового логотипа (абсолютный или относительный – относительно [.ph .filepath]`[Каталог установки {wc}а]\5.5\Site\`).
+
[source,pre,codeblock]
----
<SettingGroup Name="DefaultESImageGenerator">
   <Setting Name="LogoImagePath" Value="Content/logo.png" />
</SettingGroup>
----
+
Файл логотипа должен быть доступен процессу сервера {wc}а. Размер стандартного изображения: 127x131 пискелей. Изображение будет сжато в соответствии с фактическим размером штампа.
. Сохраните изменения конфигурационного файла.

[NOTE]
====
[.note__title]#Note:# Предусмотрена возможность реализации собственной функции формирования штампа. Пример реализации см. в репозитории ДоксВижн на GitHub.
====

*Parent topic:* xref:CardsConf.adoc[Работа с карточками]
