
== Название папки

Данный элемент управления находится в разработке и может быть изменён в будущем. Элемент управления отображает название папки, в контейнере которой он расположен. Внешний вид может определяться свойством Дополнительными CSS классами.

== Свойства

Общие::
Название ЭУ:::
Название типа элемента управления.
Название:::
Уникальное название элемента управления.
Поведение::
Видимость:::
Настройка видимости. Элемент управления отображается в карточке, когда флаг установлен и не отображается вместе с содержимым, когда флаг снят.
+
`*Адаптивный*`
Дополнительные css классы:::
Названия дополнительных классов CSS для изменения стиля элемента управления. Перечисляются через пробел.
Стандартный css класс:::
Название CSS класса, в котором определен стандартный стиль элемента управления.
События::
При наведении курсора:::
Вызывается при входе курсора мыши в область элемента управления.
При отведении курсора:::
Вызывается, когда курсор мыши покидает область элемента управления.
При щелчке:::
Вызывается при щелчке мыши по любой области элемента управления.
