
== Параметры завершения задания

Элемент управления [.ph .uicontrol]*Параметры завершения задания* предназначен для отображения дополнительных параметров завершения задания, настроенных в Справочнике видов карточек и в индивидуальных настройках задания.

Элемент управления может быть добавлен только в разметку локации [.ph .filepath]`WebFrame / Разметки для элементов управления / Диалоги операций карточек / Завершить`.

== Свойства

Общие::
Название ЭУ:::
Название типа элемента управления.
Название:::
Уникальное название элемента управления.
Поведение::
Видимость:::
Настройка видимости. Элемент управления отображается в карточке, когда флаг установлен и не отображается вместе с содержимым, когда флаг снят.
+
`*Адаптивный*`
Дополнительные css классы:::
Названия дополнительных классов CSS для изменения стиля элемента управления. Перечисляются через пробел.
Переходить по TAB:::
Флаг определяет последовательность перехода по ЭУ карточки при нажатии кнопки kbd:[TAB]. Если флаг установлен, переход по kbd:[TAB] разрешён.
Стандартный css класс:::
Название CSS класса, в котором определен стандартный стиль элемента управления.
События::
При наведении курсора:::
Вызывается при входе курсора мыши в область элемента управления.
При отведении курсора:::
Вызывается, когда курсор мыши покидает область элемента управления.
При щелчке:::
Вызывается при щелчке мыши по любой области элемента управления.
