
== Папка / Результаты поиска

Элемент управления [.ph .uicontrol]*Папка / Результаты поиска* предназначен для добавления папки с результатами последнего поискового запроса в дерево папок.

=== Свойства

Общие::
Название ЭУ:::
Название типа элемента управления.
Название:::
Уникальное название элемента управления.
Внешний вид::
CSS класс иконки:::
Название CSS класса с иконкой папки.
Компактный режим:::
Включает/выключает минимизацию пространства, необходимого для отображения данной папки.
Текст:::
Текст, отображаемый в строке папки. Если значение -- пустая строка, в строке ЭУ отображается название «Поиск».
Поведение::
Видимость:::
Настройка видимости: флаг установлен -- элемент управления отображается в карточке; флаг не установлен -- элемент управления (а также его содержимое) не отображается в карточке.
+
[.dfn .term]_Адаптивный_.
Дополнительные css классы:::
Названия дополнительных классов CSS для изменения стиля элемента управления. Перечисляются через пробел.
Настраиваемый:::
Включает/выключает режим, при котором возможно скрытие данного ЭУ пользователем. ЭУ должен находиться внутри контейнера xref:Control_configurablemainmenucontainer.adoc[Настраиваемая область].
Стандартный css класс:::
Название CSS класса, в котором определен стандартный стиль элемента управления.
События::
После выбора:::
Вызывается после изменения свойства «isSelected».
Перед выбором:::
Вызывается перед изменением свойства «isSelected».
После изменения настройки видимости пункта:::
Вызывается после изменения пользователем признака видимости элемента в дереве папок.
При наведении курсора:::
Вызывается при входе курсора мыши в область элемента управления.
При отведении курсора:::
Вызывается, когда курсор мыши покидает область элемента управления.
При щелчке:::
Вызывается при щелчке мыши по любой области элемента управления.
