
== Контейнер / Главное меню

Элемент управления [.ph .uicontrol]*Контейнер / Главное меню* является контейнером, в котором должны размещаться элементы панели [.dfn .term]_Дерево папок_.

=== Свойства

Общие::
  Название ЭУ;;
    Название типа элемента управления.
  Название;;
    Уникальное название элемента управления.
Поведение::
  Видимость;;
    Настройка видимости: флаг установлен – элемент управления отображается в карточке; флаг не установлен – элемент управления (а также его содержимое) не отображается в карточке.
    +
    [.dfn .term]_Адаптивный_.
  Дополнительные css классы;;
    Названия дополнительных классов CSS для изменения стиля элемента управления. Перечисляются через пробел.
  Минимальная ширина;;
    Минимально возможная ширина элемента управления в пикселях.
    +
    [.dfn .term]_Адаптивный_.
  Стандартный css класс;;
    Название CSS класса, в котором определен стандартный стиль элемента управления.
События::
  При изменении состояния закрепления;;
    Вызывается при закреплении/откреплении панели с помощью элемента управления xref:Control_mainmenupinbutton.html[Кнопка / Закрепить меню].
  При наведении курсора;;
    Вызывается при входе курсора мыши в область элемента управления.
  При отведении курсора;;
    Вызывается, когда курсор мыши покидает область элемента управления.
  При щелчке;;
    Вызывается при щелчке мыши по любой области элемента управления.

*Parent topic:* xref:../topics/MainMenuControls.html[Главное меню]
