
== Контейнер / Главная страница

[NOTE]
====
[.note__title]#Important:# Данный элемент управления отмечен к удалению. Используйте xref:Control_block.html[Блоки] для формирования разметки «Главной страницы».
====

Элемент управления [.ph .uicontrol]*Контейнер / Главная страница* является контейнером, в котором должны размещаться виджеты [.dfn .term]_дашборда_.

=== Свойства

Общие::
  Название ЭУ;;
    Название типа элемента управления.
  Название;;
    Уникальное название элемента управления.
Поведение::
  Видимость;;
    Настройка видимости: флаг установлен – элемент управления отображается в карточке; флаг не установлен – элемент управления (а также его содержимое) не отображается в карточке.
    +
    [.dfn .term]_Адаптивный_.
  Дополнительные css классы;;
    Названия дополнительных классов CSS для изменения стиля элемента управления. Перечисляются через пробел.
  Стандартный css класс;;
    Название CSS класса, в котором определен стандартный стиль элемента управления.
События::
  При наведении курсора;;
    Вызывается при входе курсора мыши в область элемента управления.
  При отведении курсора;;
    Вызывается, когда курсор мыши покидает область элемента управления.
  При щелчке;;
    Вызывается при щелчке мыши по любой области элемента управления.

*Parent topic:* xref:../topics/MainPageControls.html[Главная страница]
