
== Ссылка / Страница {wc}а

Элемент управления [.ph .uicontrol]*Ссылка / Страница {wc}а* добавляет в дерево папок ссылку для открытия страницы {wc}а.

=== Свойства

Общие::
Название ЭУ:::
Название типа элемента управления.
Название:::
Уникальное название элемента управления.
Внешний вид::
CSS класс иконки:::
Название CSS класса с иконкой ссылки.
Компактный режим:::
Включает/выключает минимизацию пространства, необходимого для отображения данной ссылки.
Текст:::
Текст, отображаемый в строке ссылки в дереве папок.
+
`*Локализуемый*`.
Данные::
Адрес:::
Адрес страницы {wc}а в формате «#/Folder/RecentCards».
Поведение::
HTML Accesskey:::
См. https://www.w3schools.com/TAGS/att_accesskey.asp.
HTML Download:::
См. https://www.w3schools.com/TAGS/att_a_download.asp.
HTML Hreaflang:::
См. https://www.w3schools.com/TAGS/att_a_hreflang.asp.
HTML Target:::
См. https://www.w3schools.com/TAGS/att_a_target.asp.
HTML Type:::
См. https://www.w3schools.com/TAGS/att_a_type.asp.
Видимость:::
Настройка видимости: флаг установлен -- элемент управления отображается в карточке; флаг не установлен -- элемент управления (а также его содержимое) не отображается в карточке.
+
`*Адаптивный*`.
Дополнительные css классы:::
Названия дополнительных классов CSS для изменения стиля элемента управления. Перечисляются через пробел.
Настраиваемый:::
Включает/выключает режим, при котором возможно скрытие данного ЭУ пользователем. ЭУ должен находиться внутри контейнера xref:Control_configurablemainmenucontainer.adoc[Настраиваемая область].
Стандартный css класс:::
Название CSS класса, в котором определен стандартный стиль элемента управления.
+
Уровень автоматического раскрытия дочерних элементов:::
Указывает уровень вложенности папок, до которого вложенные в ЭУ папки будут раскрыты по умолчанию. При значении 0 автоматическое раскрытие папок не выполняется.
События::
Перед выбором:::
Вызывается перед изменением свойства «isSelected».
После выбора:::
Вызывается после изменения свойства «isSelected».
После изменения настройки видимости пункта:::
Вызывается после изменения пользователем признака видимости элемента в дереве папок.
При наведении курсора:::
Вызывается при входе курсора мыши в область элемента управления.
При отведении курсора:::
Вызывается, когда курсор мыши покидает область элемента управления.
При щелчке:::
Вызывается при щелчке мыши по любой области элемента управления.
