
== Смена языка

Элемент управления [.ph .uicontrol]*Смена языка* добавляет в раскрывающийся список для смены языка пользовательского интерфейса {wc}а. Предназначен для добавления в разметку локации «WebFrame / Диалог профиля пользователя».

=== Свойства

Общие::
Название ЭУ:::
Название типа элемента управления.
Название:::
Уникальное название элемента управления.
Внешний вид::
Подсказка:::
Содержимое всплывающей подсказки.
+
[#Control_userculture__d7e65 .dfn .term]#Локализуемый#.
Поведение::
Видимость:::
Настройка видимости: флаг установлен -- элемент управления отображается в карточке; флаг не установлен -- элемент управления (а также его содержимое) не отображается в карточке.
+
`*Адаптивный*`.
Дополнительные css классы:::
Названия дополнительных классов CSS для изменения стиля элемента управления. Перечисляются через пробел.
Переходить по TAB:::
Определяет пользовательскую последовательность очередности обхода карточки по кнопке [.ph .uicontrol]*TAB*. Флаг установлен -- переход по кнопке [.ph .uicontrol]*TAB* разрешен.
Стандартный css класс:::
Название CSS класса, в котором определен стандартный стиль элемента управления.
События::
При наведении курсора:::
Вызывается при входе курсора мыши в область элемента управления.
При отведении курсора:::
Вызывается, когда курсор мыши покидает область элемента управления.
При щелчке:::
Вызывается при щелчке мыши по любой области элемента управления.
