
== Контейнер / Панель элемента меню

Элемент управления [.ph .uicontrol]*Контейнер / Панель элемента меню* является контейнером для размещения элементов xref:Control_mainmenupinbutton.adoc[Кнопка / Закрепить меню], xref:Control_configurablemainmenucontainerbutton.adoc[Кнопка / Настроить], xref:Control_refreshfolderstreebutton.adoc[Кнопка / Обновить].

=== Свойства

Общие::
  Название ЭУ;;
    Название типа элемента управления.
  Название;;
    Уникальное название элемента управления.
Внешний вид::
  Локация;;
    Данный ЭУ не создает собственной строки в дереве папок, а встраивается в существующую строку (располагается в правой части строки). Настройка Локация определяет, в какую строку должен быть встроен данный ЭУ:
    +
    * Ниже – Панель элемента меню будет встроена в элемент, расположенный ниже него в структуре разметки;
    * Выше – Панель элемента меню будет встроена в элемент, расположенный выше него в структуре разметки.
Поведение::
  Видимость;;
    Настройка видимости: флаг установлен – элемент управления отображается в карточке; флаг не установлен – элемент управления (а также его содержимое) не отображается в карточке.
    +
    [.dfn .term]_Адаптивный_.
  Дополнительные css классы;;
    Названия дополнительных классов CSS для изменения стиля элемента управления. Перечисляются через пробел.
  Минимальная ширина;;
    Минимально возможная ширина элемента управления в пикселях.
    +
    [.dfn .term]_Адаптивный_.
  Стандартный css класс;;
    Название CSS класса, в котором определен стандартный стиль элемента управления.
События::
  При наведении курсора;;
    Вызывается при входе курсора мыши в область элемента управления.
  При отведении курсора;;
    Вызывается, когда курсор мыши покидает область элемента управления.
  При щелчке;;
    Вызывается при щелчке мыши по любой области элемента управления.

*Parent topic:* xref:MainMenuControls.adoc[Главное меню]
