
== Таблица параметров запроса

Элемент управления [.ph .uicontrol]*Таблица параметров запроса* предназначен для настройки параметров параметрического поискового запроса в локации «WebFrame / Диалог поисковых параметров».

=== Свойства

Общие::
Название ЭУ:::
Название типа элемента управления.
Название:::
Уникальное название элемента управления.
Поведение::
Видимость:::
Настройка видимости: флаг установлен -- элемент управления отображается в карточке; флаг не установлен -- элемент управления (а также его содержимое) не отображается в карточке.
+
`*Адаптивный*`.
Дополнительные css классы:::
Названия дополнительных классов CSS для изменения стиля элемента управления. Перечисляются через пробел.
Минимальная ширина:::
Минимально возможная ширина элемента управления в пикселях.
+
`*Адаптивный*`.
Стандартный css класс:::
Название CSS класса, в котором определен стандартный стиль элемента управления.
Ширина в процентах:::
Ширина элемента управления в процентах (указывается целое число) от ширины родительского элемента управления.
+
`*Адаптивный*`.
События::
При наведении курсора:::
Вызывается при входе курсора мыши в область элемента управления.
При отведении курсора:::
Вызывается, когда курсор мыши покидает область элемента управления.
При щелчке:::
Вызывается при щелчке мыши по любой области элемента управления.
