
== Метка

Элемент управления *Метка* предназначен для отображения любой статической (не редактируемой и не связанной с данными карточки) строки.

== Свойства

=== Общие

==== Название ЭУ

Название типа элемента управления.

==== Название

Уникальное название элемента управления.

=== Внешний вид


==== Текст

Отображаемый в ЭУ.

`*Локализуемый*`

=== Поведение


==== Видимость

Настройка видимости. Элемент управления отображается в карточке, когда флаг установлен. Элемент управления и любое его содержимое не отображаются, когда флаг снят.

`*Адаптивный*`

==== Дополнительные css классы

Названия дополнительных классов CSS для изменения стиля элемента управления. Перечисляются через пробел.

==== Операция редактирования для видимости

Определяет операцию, которая должна быть доступна, чтобы ЭУ отображался для пользователя. Работа свойства зависит от значения свойства `*Видимость*`:

* Когда флаг `*Видимость*` установлен и выбрана _операция редактирования для видимости_, видимость элемента определяется исходя из доступности пользователю выбранной операции редактирования.
* Когда флаг `*Видимость*` установлен, и _операция редактирования для видимости_ НЕ выбрана, ЭУ отображается всегда.
* Когда флаг `*Видимость*` НЕ установлен, ЭУ всегда скрыт.

==== Стандартный css класс

Название CSS класса, в котором определен стандартный стиль элемента управления.

=== События

==== При наведении курсора

Вызывается при входе курсора мыши в область элемента управления.

==== При отведении курсора

Вызывается, когда курсор мыши покидает область элемента управления.

==== При щелчке

Вызывается при щелчке мыши по любой области элемента управления.
