
== Ссылка / Локация

Элемент управления [.ph .uicontrol]*Ссылка / Локация* добавляет в дерево папок ссылку для открытия xref:locationsAboutSettings.adoc[локации].

=== Свойства

Общие::
Название ЭУ:::
Название типа элемента управления.
Название:::
Уникальное название элемента управления.
Внешний вид::
CSS класс иконки:::
Название CSS класса с иконкой ссылки.
Заголовок страницы:::
Текст, отображаемый справа от открытия/скрытия дерева папок, при открытии ссылки.
+
`*Локализуемый*`.
Компактный режим:::
Включает/выключает минимизацию пространства, необходимого для отображения данной ссылки.
Максимальная высота:::
Устанавливает ограничение по высоте для элемента управления. Значение в пикселях.
Текст:::
Текст, отображаемый в строке ссылки в дереве папок.
+
`*Локализуемый*`.
Цвет страницы:::
Определяет цвет оформления страницы для отображения содержимого папки. Варианты: «Папка» (темно-синий цвет), «Задача» (зеленый цвет), «Документ» (синий цвет).
Данные::
Локация:::
Локация, которая должна открываться при переходе по ссылке.
+
*Поддерживается локации только из группы локаций «WebFrame»*.
Источник локации:::
Выбор источника локации. Для выбора доступны варианты [.keyword]*Локация* и [.keyword]*Связанная карточка/строка*.
Параметры загрузки разметки:::
Не используется. *Оставить пустым.*
Поведение::
Видимость:::
Настройка видимости: флаг установлен -- элемент управления отображается в карточке; флаг не установлен -- элемент управления (а также его содержимое) не отображается в карточке.
+
`*Адаптивный*`.
Дополнительные css классы:::
Названия дополнительных классов CSS для изменения стиля элемента управления. Перечисляются через пробел.
Настраиваемый:::
Включает/выключает режим, при котором возможно скрытие данного ЭУ пользователем. ЭУ должен находиться внутри контейнера xref:Control_configurablemainmenucontainer.adoc[Настраиваемая область].
Режим:::
Режим отображения элемента управления. Для выбора доступны варианты: [.keyword]*любой*, [.keyword]*просмотр*, [.keyword]*редактирование*, [.keyword]*создание*.
Стандартный css класс:::
Название CSS класса, в котором определен стандартный стиль элемента управления.
События::
Перед выбором:::
Вызывается перед изменением свойства «isSelected».
После выбора:::
Вызывается после изменения свойства «isSelected».
После изменения настройки видимости пункта:::
Вызывается после изменения пользователем признака видимости элемента в дереве папок.
При наведении курсора:::
Вызывается при входе курсора мыши в область элемента управления.
При отведении курсора:::
Вызывается, когда курсор мыши покидает область элемента управления.
При щелчке:::
Вызывается при щелчке мыши по любой области элемента управления.
