
== Проставление отметки о завершении договора/дополнительного соглашения

Если для договора не настроено продление, заключенный договор будет считаться завершенным, когда закончится срок его действия, указанный в карточке. При необходимости может быть выполнено ручное завершение договора с проставлением соответствующей отметки.

Для завершения договора выполните следующие действия:

[[task_bnc_r52_wl__steps_ykh_v33_xl]]
. [.ph .cmd]#Откройте карточку договора (дополнительного соглашения) в состоянии «Заключен».#
. [.ph .cmd]#Если договор необходимо завершить на определенную дату, отличную от текущей, установите её в поле [.ph .uicontrol]*Дата завершения*.#
+
Если дата не указана, при сохранении карточки будет установлена текущая дата.
. [.ph .cmd]#Нажмите кнопку [.ph .uicontrol]*Завершить* на xref:CardOperations.html[панели операций].#
+
Договор переводится в состояние «Завершен».

*На уровень выше:* xref:../topics/WorkWithContractsAndSupplementaryAgreemens.html[Работа по договору и дополнительному соглашению]
