
== Папки / Пользовательские папки

Элемент управления [.ph .uicontrol]*Папка / Пользовательские папки* предназначен для добавления группы настраиваемых папок в дерево папок. В данной группе отображаются папки, подключенные пользователем.

=== Свойства

Общие::
  Название ЭУ;;
    Название типа элемента управления.
  Название;;
    Уникальное название элемента управления.
Внешний вид::
  CSS класс иконки;;
    Название CSS класса с иконкой папки.
  Анимация;;
    Включает/выключает использование анимации при раскрытии папки.
  Компактный режим;;
    Включает/выключает минимизацию пространства, необходимого для отображения данной папки.
  Папки в компактном режиме;;
    Включает/выключает минимизацию пространства, необходимого для отображения папок группы.
  Показывать иконки;;
    Включает/выключает отображение иконок у пользовательских папок.
  Показывать корневой элемент;;
    Включает/выключает отображения данной папки. Если флаг снят, будут отображаться только вложенные папки.
  Текст;;
    Текст, отображаемый в строке папки. Если значение – пустая строка, в строке ЭУ отображается название папки.
  Управление папками;;
    Включает/отключает меню папки, позволяющее создавать подпапки, настраивать и удалять данную папку.
  Уровень предзагрузки дочерних папок;;
    Определяет уровень вложенности папок данного каталога, до которого подпапки будут загружены без дополнительных запросов. Данные подпапок с более высоким уровнем вложенности загружаются через отдельные клиент-серверные запросы. Должно быть указано целое число.
Поведение::
  Видимость;;
    Настройка видимости: флаг установлен – элемент управления отображается в карточке; флаг не установлен – элемент управления (а также его содержимое) не отображается в карточке.
    +
    [.dfn .term]_Адаптивный_.
  Дополнительные css классы;;
    Названия дополнительных классов CSS для изменения стиля элемента управления. Перечисляются через пробел.
  Минимальная ширина;;
    Минимально возможная ширина элемента управления в пикселях.
    +
    [.dfn .term]_Адаптивный_.
  Настраиваемый;;
    Включает/выключает режим, при котором возможно скрытие данного ЭУ пользователем. ЭУ должен находиться внутри контейнера xref:Control_configurablemainmenucontainer.html[Настраиваемая область].
  Порядок;;
    Определяет xref:dl_layout_changecontrolorder.html[порядок отображения] элемента управления в родительском [.dfn .term]_Блоке_. [.dfn .term]_ЭУ_ с более низким `порядком` имеет более высокий приоритет в порядке отображения в разметке.
    +
    [.dfn .term]_Адаптивный_.
  Стандартный css класс;;
    Название CSS класса, в котором определен стандартный стиль элемента управления.
  Уровень автоматического раскрытия дочерних элементов;;
    Указывает уровень вложенности папок, до которого вложенные в ЭУ папки будут раскрыты по умолчанию. При значении 0 автоматическое раскрытие папок не выполняется.
  Ширина в процентах;;
    Ширина элемента управления в процентах (указывается целое число) от ширины родительского элемента управления.
    +
    [.dfn .term]_Адаптивный_.
События::
  Перед выбором;;
    Вызывается перед изменением свойства «isSelected».
  Перед сворачиванием/разворачиванием элемента;;
    Вызывается перед сворачиванием/разворачиванием элемента управления.
  После выбора;;
    Вызывается после изменения свойства «isSelected».
  После изменения настройки видимости пункта;;
    Вызывается после изменения пользователем признака видимости элемента в дереве папок.
  После сворачивания/разворачивания элемента;;
    Вызывается после сворачивания/разворачивания элемента управления.
  При наведении курсора;;
    Вызывается при входе курсора мыши в область элемента управления.
  При отведении курсора;;
    Вызывается, когда курсор мыши покидает область элемента управления.
  При щелчке;;
    Вызывается при щелчке мыши по любой области элемента управления.

*Parent topic:* xref:../topics/MainMenuControls.html[Главное меню]
