
== Групповые операции / Делегирование

Элемент управления [.ph .uicontrol]*Групповые операции / Делегирование* вызывает операцию делегирования для группы выбранных карточек Задание.

ЭУ может быть добавлен в разметку локации «Групповые операции с карточками» и в корневой элемент для ЭУ групповых операций (BatchOperationsNode).

=== Свойства

Общие::
  Название ЭУ;;
    Название типа элемента управления.
  Название;;
    Уникальное название элемента управления.
Внешний вид::
  Текст кнопки;;
    Текст, отображаемый на кнопке делегирования.
    +
    [.dfn .term]_Локализуемый_
Поведение::
  Видимость;;
    Настройка видимости: флаг установлен – элемент управления отображается в карточке; флаг не установлен – элемент управления (а также его содержимое) не отображается в карточке.
    +
    [.dfn .term]_Адаптивный_.
  Дополнительные css классы;;
    Названия дополнительных классов CSS для изменения стиля элемента управления. Перечисляются через пробел.
  Операция редактирования для видимости;;
    Определяет операцию, которая должна быть доступна пользователю для показа данного элемента управления. Действие настройки зависит от значения настройки [.dfn .term]_Видимость_:
    +
    * флаг [.dfn .term]_Видимость_ установлен, [.dfn .term]_операция редактирования для видимости_ выбрана – видимость элемента определяется доступностью пользователю выбранной операции редактирования;
    * флаг [.dfn .term]_Видимость_ установлен, [.dfn .term]_операция редактирования для видимости_ НЕ выбрана – ЭУ всегда отображается;
    * флаг [.dfn .term]_Видимость_ НЕ установлен – ЭУ всегда скрыт.
  Стандартный css класс;;
    Название CSS класса, в котором определен стандартный стиль элемента управления.
События::
  При наведении курсора;;
    Вызывается при входе курсора мыши в область элемента управления.
  При отведении курсора;;
    Вызывается, когда курсор мыши покидает область элемента управления.
  При щелчке;;
    Вызывается при щелчке мыши по любой области элемента управления.

