
== Метка

Элемент управления [.ph .uicontrol]*Метка* предназначен для отображения любой статической (не редактируемой и не связанной с данными карточки) строки.

=== Свойства

Общие::
Название ЭУ:::
Название типа элемента управления.
Название:::
Уникальное название элемента управления.
Внешний вид::
Текст:::
Отображаемый в [.dfn .term]_ЭУ_.
+
`*Локализуемый*`.
Поведение::
Видимость:::
Настройка видимости: флаг установлен -- элемент управления отображается в карточке; флаг не установлен -- элемент управления (а также его содержимое) не отображается в карточке.
+
`*Адаптивный*`.
Дополнительные css классы:::
Названия дополнительных классов CSS для изменения стиля элемента управления. Перечисляются через пробел.
Операция редактирования для видимости:::
Определяет операцию, которая должна быть доступна пользователю для показа данного элемента управления. Действие настройки зависит от значения настройки [.dfn .term]_Видимость_:
+
* флаг `*Видимость*` установлен, [.dfn .term]_операция редактирования для видимости_ выбрана -- видимость элемента определяется доступностью пользователю выбранной операции редактирования;
* флаг `*Видимость*` установлен, [.dfn .term]_операция редактирования для видимости_ НЕ выбрана -- ЭУ всегда отображается;
* флаг `*Видимость*` НЕ установлен -- ЭУ всегда скрыт.
Стандартный css класс:::
Название CSS класса, в котором определен стандартный стиль элемента управления.
События::
При наведении курсора:::
Вызывается при входе курсора мыши в область элемента управления.
При отведении курсора:::
Вызывается, когда курсор мыши покидает область элемента управления.
При щелчке:::
Вызывается при щелчке мыши по любой области элемента управления.
