
== Контейнер локации

Элемент управления *Контейнер локации* предназначен для отображения данных карточки или другого элемента с разметкой в другой карточке.

== Свойства

=== Общие

==== Название ЭУ

Название типа элемента управления.

==== Название

Уникальное название элемента управления.

=== Внешний вид

Максимальная высота:::
Устанавливает ограничение по высоте для элемента управления. Значение в пикселях.

=== Данные

Источник локации:::
* Локация -- в элементе будет отображаться разметка из локации, выбранной в настройке "Локация".
* Связанная карточка/строка -- в элементе будет отображаться связанная карточка или данные строки связанной карточки, ссылка на которую содержится в поле, указанном в источнике данных. При отображении будет использована разметка с режимом из настройки "Режим
==== Расширенный источник данных

Выбор типа источника данных элемента управления: текущая карточка или один из типов, настроенных в корневом элементе разметки.

==== Источник данных

Секция карточки, содержащая данные элемента управления.
Поле данных:::
Поле текущей или связанной карточки с идентификатором карточки или строки карточки, отображаемой в элементе управления.
Локация:::
Локация, разметка которой будет отображаться в элементе управления.
Параметры загрузки разметки:::
Дополнительные параметры, передаваемые при открытии разметки.
+
Свойство "Локация" доступно, если в "Источник локации" выбрано "Локация". Свойства "Расширенный источник данных", "Источник данных" и "Поле данных" доступны, если в "Источник локации" выбрано "Связанная карточка/строка".

=== Поведение

Асинхронная загрузка:::
Определяет способ загрузки разметки локации: флаг установлен -- разметка локации будет загружена после загрузки родительской разметки, флаг снят -- разметка локации будет загружена вместе с родительской разметкой (потребуется больше времени для запуска родительской разметки).

==== Видимость

Настройка видимости. Элемент управления отображается в карточке, когда флаг установлен. Элемент управления и любое его содержимое не отображаются, когда флаг снят.

`*Адаптивный*`

==== Дополнительные css классы

Названия дополнительных классов CSS для изменения стиля элемента управления. Перечисляются через пробел.
Пользовательская функция загрузки разметки:::
Название функции, переопределяющей механизм загрузки разметки локации. Указывается при необходимости.
+
Данная функция может быть использована, если нужно передавать в разметку собственные параметры, значение которых вычисляется во время исполнения.
+
Функция принимает единственный параметр с типом [.keyword .apiname]#LocationContainerControl#. Описание типа см. в https://{dv}.com/docs/webclient/5.5.14/JsDocApi/classes/_system_locationcontainercontrol_d_.locationcontainercontrol.adoc[JSDocsApi].

=== Режим


Режим, в котором будет открываться разметка. Может принимать значение из списка: Любой, Описание, Справка, Просмотр, Редактирование, Создание, Внутри другой разметки.
+
Настройка "Режим" используется при выборе подходящей разметки из списка разметок внедряемой карточки. Например, если установлен режим "Редактирование", то при внедрении будет использована разметка, в условии выбора которой указан режим "Редактирование".
+
Использование специального режима "Внутри другой разметки" (он также доступен в условиях выбора разметки) позволяет отделить разметки, разработанные специально для отображения карточки внутри другой карточки, от разметок, используемых при обычной работе с карточкой (с режимами "Просмотр", "Редактирование", "Создание"). При этом у внедряемой карточки должно быть условие выбора разметки с режимом "Внутри другой разметки".

==== Стандартный css класс

Название CSS класса, в котором определен стандартный стиль элемента управления.
Часть родительской разметки:::
Определяет режим интеграции разметки локации в родительскую разметку: флаг установлен -- разметка локации будет загружена как часть родительской локации (элементы управления разметки буду добавлены в родительскую разметку), флаг снят -- разметка локации не будет интегрирована в родительскую разметку.

=== События


==== При наведении курсора

Вызывается при входе курсора мыши в область элемента управления.

==== При отведении курсора

Вызывается, когда курсор мыши покидает область элемента управления.

==== При щелчке

Вызывается при щелчке мыши по любой области элемента управления.
