
== Контейнер / Настраиваемая область

Элемент управления [.ph .uicontrol]*Контейнер / Настраиваемая область* является контейнером, содержимое которого может быть настроено пользователем.

Режим настройки включается кнопкой xref:Control_configurablemainmenucontainerbutton.adoc[Настроить].

=== Свойства

Общие::
Название ЭУ:::
Название типа элемента управления.
Название:::
Уникальное название элемента управления.
Поведение::
Видимость:::
Настройка видимости: флаг установлен -- элемент управления отображается в карточке; флаг не установлен -- элемент управления (а также его содержимое) не отображается в карточке.
+
`*Адаптивный*`.
Дополнительные css классы:::
Названия дополнительных классов CSS для изменения стиля элемента управления. Перечисляются через пробел.
Стандартный css класс:::
Название CSS класса, в котором определен стандартный стиль элемента управления.
События::
После завершения конфигурации:::
Вызывается после выхода из режима настройки.
После начала конфигурации:::
Вызывается при входе в режим настройки.
После сохранения конфигурации:::
Вызывается при сохранении изменений.
Перед завершением конфигурации:::
Вызывается перед выходом из режима настройки.
Перед началом конфигурации:::
Вызывается перед входом в режим настройки.
Перед сохранением конфигурации:::
Вызывается перед сохранением изменений.
При наведении курсора:::
Вызывается при входе курсора мыши в область элемента управления.
При отведении курсора:::
Вызывается, когда курсор мыши покидает область элемента управления.
При щелчке:::
Вызывается при щелчке мыши по любой области элемента управления.
