
== Ссылка / HTML страница

Элемент управления [.ph .uicontrol]*Ссылка / HTML страница* добавляет в дерево папок ссылку для открытия HTML страницы с известным адресом. Страница ссылки открывается в области просмотра карточки/папки {wc}а.

=== Свойства

Общие::
Название ЭУ:::
Название типа элемента управления.
Название:::
Уникальное название элемента управления.
Внешний вид::
CSS класс иконки:::
Название CSS класса с иконкой ссылки.
Заголовок страницы:::
Текст, отображаемый справа от открытия/скрытия дерева папок, при открытии ссылки.
+
[.dfn .term]_Локализуемый_.
Компактный режим:::
Включает/выключает минимизацию пространства, необходимого для отображения данной ссылки.
Текст:::
Текст, отображаемый в строке ссылки в дереве папок.
+
[.dfn .term]_Локализуемый_.
Цвет страницы:::
Определяет цвет оформления страницы для отображения содержимого папки. Варианты: «Папка» (темно-синий цвет), «Задача» (зеленый цвет), «Документ» (синий цвет).
Данные::
Адрес:::
Адрес HTML-страницы в формате «http://www.company.org».
+
*Целевая страница должна разрешать встраивание в другие страницы/фреймы.*
Поведение::
Видимость:::
Настройка видимости: флаг установлен -- элемент управления отображается в карточке; флаг не установлен -- элемент управления (а также его содержимое) не отображается в карточке.
+
[.dfn .term]_Адаптивный_.
Дополнительные css классы:::
Названия дополнительных классов CSS для изменения стиля элемента управления. Перечисляются через пробел.
Настраиваемый:::
Включает/выключает режим, при котором возможно скрытие данного ЭУ пользователем. ЭУ должен находиться внутри контейнера xref:Control_configurablemainmenucontainer.adoc[Настраиваемая область].
Стандартный css класс:::
Название CSS класса, в котором определен стандартный стиль элемента управления.
События::
Перед выбором:::
Вызывается перед изменением свойства «isSelected».
После выбора:::
Вызывается после изменения свойства «isSelected».
После изменения настройки видимости пункта:::
Вызывается после изменения пользователем признака видимости элемента в дереве папок.
При наведении курсора:::
Вызывается при входе курсора мыши в область элемента управления.
При отведении курсора:::
Вызывается, когда курсор мыши покидает область элемента управления.
При щелчке:::
Вызывается при щелчке мыши по любой области элемента управления.
