
== Элементы фильтра папки

Элемент управления [.ph .uicontrol]*Элементы фильтра папки* предназначен для добавления списка настроек фильтра папки в разметку локации «WebFrame / Панель поиска по столбцам представления».

=== Свойства

Общие::
  Название ЭУ;;
    Название типа элемента управления.
  Название;;
    Уникальное название элемента управления.
Поведение::
  Видимость;;
    Настройка видимости: флаг установлен – элемент управления отображается в карточке; флаг не установлен – элемент управления (а также его содержимое) не отображается в карточке.
    +
    [.dfn .term]_Адаптивный_.
  Дополнительные css классы;;
    Названия дополнительных классов CSS для изменения стиля элемента управления. Перечисляются через пробел.
  Минимальная ширина;;
    Минимально возможная ширина элемента управления в пикселях.
    +
    [.dfn .term]_Адаптивный_.
  Операция редактирования для видимости;;
    Определяет операцию, которая должна быть доступна пользователю для показа данного элемента управления. Действие настройки зависит от значения настройки [.dfn .term]_Видимость_:
    +
    * флаг [.dfn .term]_Видимость_ установлен, [.dfn .term]_операция редактирования для видимости_ выбрана – видимость элемента определяется доступностью пользователю выбранной операции редактирования;
    * флаг [.dfn .term]_Видимость_ установлен, [.dfn .term]_операция редактирования для видимости_ НЕ выбрана – ЭУ всегда отображается;
    * флаг [.dfn .term]_Видимость_ НЕ установлен – ЭУ всегда скрыт.
  Порядок;;
    Определяет xref:dl_layout_changecontrolorder.adoc[порядок отображения] элемента управления в родительском [.dfn .term]_Блоке_. [.dfn .term]_ЭУ_ с более низким `порядком` имеет более высокий приоритет в порядке отображения в разметке.
    +
    [.dfn .term]_Адаптивный_.
  Стандартный css класс;;
    Название CSS класса, в котором определен стандартный стиль элемента управления.
  Ширина в процентах;;
    Ширина элемента управления в процентах (указывается целое число) от ширины родительского элемента управления.
    +
    [.dfn .term]_Адаптивный_.
События::
  При наведении курсора;;
    Вызывается при входе курсора мыши в область элемента управления.
  При отведении курсора;;
    Вызывается, когда курсор мыши покидает область элемента управления.
  При щелчке;;
    Вызывается при щелчке мыши по любой области элемента управления.

