
== Папки / Групповые папки

Элемент управления [.ph .uicontrol]*Папка / Групповые папки* предназначен для добавления папок рабочей группы пользователя в дерево папок.

ЭУ отображается в дереве папок, если папки рабочей группы настроены для текущего пользователя.

=== Свойства

Общие::
Название ЭУ:::
Название типа элемента управления.
Название:::
Уникальное название элемента управления.
Внешний вид::
CSS класс иконки:::
Название CSS класса с иконкой папки.
Компактный режим:::
Включает/выключает минимизацию пространства, необходимого для отображения данной папки.
Папки в компактном режиме:::
Включает/выключает минимизацию пространства, необходимого для отображения папок группы.
Показывать иконки:::
Включает/выключает отображение иконок у папок группы.
Показывать иконки у дочерних папок:::
Включает/выключает отображение иконок у вложенных папок группы.
Показывать корневой элемент:::
Флаг установлен -- отображаются корневые папки группы и их дочерние папки, флаг снят -- отображаются только дочерние папки.
Текст:::
Текст, отображаемый в строке папки.
Управление папками:::
Включает/отключает меню папки, позволяющее создавать подпапки, настраивать и удалять данную папку.
Уровень предзагрузки дочерних папок:::
Определяет уровень вложенности папок данного каталога, до которого подпапки будут загружены без дополнительных запросов. Данные подпапок с более высоким уровнем вложенности загружаются через отдельные клиент-серверные запросы. Должно быть указано целое число.
Поведение::
Видимость:::
Настройка видимости: флаг установлен -- элемент управления отображается в карточке; флаг не установлен -- элемент управления (а также его содержимое) не отображается в карточке.
+
[.dfn .term]_Адаптивный_.
Дополнительные css классы:::
Названия дополнительных классов CSS для изменения стиля элемента управления. Перечисляются через пробел.
Настраиваемый:::
Включает/выключает режим, при котором возможно скрытие данного ЭУ пользователем. ЭУ должен находиться внутри контейнера xref:Control_configurablemainmenucontainer.adoc[Настраиваемая область].
Стандартный css класс:::
Название CSS класса, в котором определен стандартный стиль элемента управления.
Уровень автоматического раскрытия дочерних элементов:::
Указывает уровень вложенности папок, до которого вложенные в ЭУ папки будут раскрыты по умолчанию. При значении 0 автоматическое раскрытие папок не выполняется.
События::
Перед выбором:::
Вызывается перед изменением свойства «isSelected».
Перед сворачиванием/разворачиванием элемента:::
Вызывается перед сворачиванием/разворачиванием элемента управления.
После сворачивания/разворачивания элемента:::
Вызывается после сворачивания/разворачивания элемента управления.
После выбора:::
Вызывается после изменения свойства «isSelected».
После изменения настройки видимости пункта:::
Вызывается после изменения пользователем признака видимости элемента в дереве папок.
При наведении курсора:::
Вызывается при входе курсора мыши в область элемента управления.
При отведении курсора:::
Вызывается, когда курсор мыши покидает область элемента управления.
При щелчке:::
Вызывается при щелчке мыши по любой области элемента управления.
