
== Контейнер заголовка

Элемент управления [.ph .uicontrol]*Контейнер заголовка* является контейнером для элементов управления, которые должны отображаться в верху окна {wc}а.

=== Свойства

Общие::
Название ЭУ:::
Название типа элемента управления.
Название:::
Уникальное название элемента управления.
Поведение::
Дополнительные css классы:::
Названия дополнительных классов CSS для изменения стиля элемента управления. Перечисляются через пробел.
Минимальная ширина:::
Минимально возможная ширина элемента управления в пикселях.
+
[.dfn .term]_Адаптивный_.
Порядок:::
Определяет xref:dl_layout_changecontrolorder.adoc[порядок отображения] элемента управления в родительском [.dfn .term]_Блоке_. [.dfn .term]_ЭУ_ с более низким `порядком` имеет более высокий приоритет в порядке отображения в разметке.
+
[.dfn .term]_Адаптивный_.
Стандартный css класс:::
Название CSS класса, в котором определен стандартный стиль элемента управления.
Ширина в процентах:::
Ширина элемента управления в процентах (указывается целое число) от ширины родительского элемента управления.
+
[.dfn .term]_Адаптивный_.
События::
При наведении курсора:::
Вызывается при входе курсора мыши в область элемента управления.
При отведении курсора:::
Вызывается, когда курсор мыши покидает область элемента управления.
При щелчке:::
Вызывается при щелчке мыши по любой области элемента управления.
