
== Кнопка сброса фильтра папки

Элемент управления [.ph .uicontrol]*Кнопка сброса фильтра папки* предназначен для добавления кнопки сброса настроек фильтра папки в разметку локации «WebFrame / Панель поиска по столбцам представления».

== Свойства

Общие::
Название ЭУ:::
Название типа элемента управления.
Название:::
Уникальное название элемента управления.
Поведение::
Видимость:::
Настройка видимости. Элемент управления отображается в карточке, когда флаг установлен и не отображается вместе с содержимым, когда флаг снят.
+
`*Адаптивный*`
Дополнительные css классы:::
Названия дополнительных классов CSS для изменения стиля элемента управления. Перечисляются через пробел.
Операция редактирования для видимости:::
Определяет операцию, которая должна быть доступна пользователю для показа данного элемента управления. Действие настройки зависит от значения настройки [.dfn .term]_Видимость_:
+
* флаг `*Видимость*` установлен, [.dfn .term]_операция редактирования для видимости_ выбрана -- видимость элемента определяется доступностью пользователю выбранной операции редактирования;
* флаг `*Видимость*` установлен, [.dfn .term]_операция редактирования для видимости_ НЕ выбрана -- ЭУ всегда отображается;
* флаг `*Видимость*` НЕ установлен -- ЭУ всегда скрыт.
Стандартный css класс:::
Название CSS класса, в котором определен стандартный стиль элемента управления.
События::
При наведении курсора:::
Вызывается при входе курсора мыши в область элемента управления.
При отведении курсора:::
Вызывается, когда курсор мыши покидает область элемента управления.
При щелчке:::
Вызывается при щелчке мыши по любой области элемента управления.
