
== Параметры завершения задания

Элемент управления [.ph .uicontrol]*Параметры завершения задания* предназначен для отображения дополнительных параметров завершения задания, настроенных в Справочнике видов карточек и в индивидуальных настройках задания.

Элемент управления может быть добавлен только в разметку локации [.ph .filepath]`WebFrame / Разметки для элементов управления / Диалоги операций карточек / Завершить`.

=== Свойства

Общие::
Название ЭУ:::
Название типа элемента управления.
Название:::
Уникальное название элемента управления.
Поведение::
Видимость:::
Настройка видимости: флаг установлен -- элемент управления отображается в карточке; флаг не установлен -- элемент управления (а также его содержимое) не отображается в карточке.
+
`*Адаптивный*`.
Дополнительные css классы:::
Названия дополнительных классов CSS для изменения стиля элемента управления. Перечисляются через пробел.
Переходить по TAB:::
Определяет пользовательскую последовательность очередности обхода карточки по кнопке [.ph .uicontrol]*TAB*. Флаг установлен -- переход по кнопке [.ph .uicontrol]*TAB* разрешен.
Стандартный css класс:::
Название CSS класса, в котором определен стандартный стиль элемента управления.
События::
При наведении курсора:::
Вызывается при входе курсора мыши в область элемента управления.
При отведении курсора:::
Вызывается, когда курсор мыши покидает область элемента управления.
При щелчке:::
Вызывается при щелчке мыши по любой области элемента управления.
