
== Url

Элемент управления [.ph .uicontrol]*Url* предназначен для отображения гиперссылки на страницу или почтовый адрес.

В настройках ЭУ может быть указан фиксированный адрес или поле карточки, из которого может быть получен адрес. Если указано поле карточки с адресом, то фиксированный адрес игнорируется.

=== Свойства

Общие::
  Название ЭУ;;
    Название типа элемента управления.
  Название;;
    Уникальное название элемента управления.
Внешний вид::
  Текст;;
    Текст, замещающий адрес ссылки при отображении.
Данные::
  Расширенный источник данных;;
    Выбор типа источника данных элемента управления: текущая карточка или один из типов, настроенных в корневом элементе разметки.
  Источник данных;;
    Секция карточки, содержащая данные элемента управления.
  Поле данных;;
    Поле карточки, содержащее адрес ссылки. Возможный тип поля: Text, Unitext, Unistring или String.
  Адрес;;
    Фиксированный адрес ссылки. Если указано `Поле                                         данных`, настройка `Адрес` игнорируется.
  Протокол;;
    Протокол адреса: «http://», «https://», «mailto:». Настройка добавляет указанный префикс к адресу ссылки.
Поведение::
  Видимость;;
    Настройка видимости: флаг установлен – элемент управления отображается в карточке; флаг не установлен – элемент управления (а также его содержимое) не отображается в карточке.
    +
    [.dfn .term]_Адаптивный_.
  Дополнительные css классы;;
    Названия дополнительных классов CSS для изменения стиля элемента управления. Перечисляются через пробел.
  Операция редактирования для видимости;;
    Определяет операцию, которая должна быть доступна пользователю для показа данного элемента управления. Действие настройки зависит от значения настройки [.dfn .term]_Видимость_:
    +
    * флаг [.dfn .term]_Видимость_ установлен, [.dfn .term]_операция редактирования для видимости_ выбрана – видимость элемента определяется доступностью пользователю выбранной операции редактирования;
    * флаг [.dfn .term]_Видимость_ установлен, [.dfn .term]_операция редактирования для видимости_ НЕ выбрана – ЭУ всегда отображается;
    * флаг [.dfn .term]_Видимость_ НЕ установлен – ЭУ всегда скрыт.
  Переходить по TAB;;
    Определяет пользовательскую последовательность очередности обхода карточки по кнопке [.ph .uicontrol]*TAB*. Флаг установлен – переход по кнопке [.ph .uicontrol]*TAB* разрешен.
  Режим открытия;;
    Определяет способ открытия ссылки:
    +
    * «Текущая вкладка» – ссылка будет открыта в текущей вкладке;
    * «Новая вкладка» – ссылка будет открыта в новой вкладке;
    * «Новое окно браузера» – ссылка будет открыта в новом окне веб-браузера.
  Стандартный css класс;;
    Название CSS класса, в котором определен стандартный стиль элемента управления.
События::
  При наведении курсора;;
    Вызывается при входе курсора мыши в область элемента управления.
  При отведении курсора;;
    Вызывается, когда курсор мыши покидает область элемента управления.
  При щелчке;;
    Вызывается при щелчке мыши по любой области элемента управления.

