
== Групповые операции / Удалить ярлык

Элемент управления [.ph .uicontrol]*Групповые операции / Удалить ярлык* вызывает операцию удаления ярлыков группы выбранных карточек из текущей папки.

ЭУ может быть добавлен только в разметку локации [.ph .filepath]`WebFrame → Компоненты папки → Групповые операции с карточками`.

[[Control_batchOperationDeleteCards__section_hvc_r5h_spb]]
== Свойства

Общие::
Название ЭУ:::
Название типа элемента управления.
Название:::
Уникальное название элемента управления.
Внешний вид::
Текст кнопки:::
Текст, отображаемый на кнопке перемещения.
+
`*Локализуемый*`
Поведение::
Видимость:::
Настройка видимости. Элемент управления отображается в карточке, когда флаг установлен и не отображается вместе с содержимым, когда флаг снят.
+
`*Адаптивный*`
Дополнительные css классы:::
Названия дополнительных классов CSS для изменения стиля элемента управления. Перечисляются через пробел.
Стандартный css класс:::
Название CSS класса, в котором определен стандартный стиль элемента управления.
События::
При наведении курсора:::
Вызывается при входе курсора мыши в область элемента управления.
При отведении курсора:::
Вызывается, когда курсор мыши покидает область элемента управления.
При щелчке:::
Вызывается при щелчке мыши по любой области элемента управления.
