
== Данные папки

Данный элемент управления находится в разработке и может быть изменён в будущем. Элемент управления может использоваться для отображения папки, выбранной в Главном Меню, либо папки, заданной в свойствах элемента управления. Также может являться контейнером для стандартных и специальных элементов управления для работы с данными папки.

=== Свойства

Общие::
  Название ЭУ;;
    Название типа элемента управления.
  Название;;
    Уникальное название элемента управления.
Данные::
  Режим;;
    Определяет режим отображения данных папки:
    +
    . Источник данных. При выборе данного режима элемент управления будет получать данные из указанного источника. Режим «Источник данных» позволяет выбрать источник данных, расширенный источник данных и поле данных.
    . Из адреса страницы (значение по умолчанию). При выборе данного режима элемент управления будет отображать папку, указанную в адресе страницы.
    . Известная папка. При выборе данного режима элемент управления будет отображать папку с идентификатором указанным в поле [.kbd .ph .userinput]`Идентификатор папки`.
    . Системная папка. При выборе данного режима элемент управления будет отображать выбранную из списка системную папку.
  Дополнительные css классы;;
    Названия дополнительных классов CSS для изменения стиля элемента управления. Перечисляются через пробел.
  Стандартный css класс;;
    Название CSS класса, в котором определен стандартный стиль элемента управления.
События::
  При наведении курсора;;
    Вызывается при входе курсора мыши в область элемента управления.
  При отведении курсора;;
    Вызывается, когда курсор мыши покидает область элемента управления.
  При щелчке;;
    Вызывается при щелчке мыши по любой области элемента управления.

