
== Настройка обновления {wc}а без импорта решений

При обновлении {wc}а происходит проверка параметра `<LoadLayouts></LoadLayouts>` конфигурационного файла панели управления {wc}а ([.ph .filepath]`WebClientAdminConsole.config`), расположенного по адресу [.ph .filepath]`%LocalAppData%Docsvision\WebClientAdminConsole.config`.

Если файл отсутствует или значение `<LoadLayouts>true</LoadLayouts>`, {wc} будет обновлён в стандартном режиме с импортом решений в базу данных.

Если значение `<LoadLayouts>false</LoadLayouts>`, при обновлении {wc}а решения не будут автоматически загружены в базу данных, и администратор должен будет сделать это самостоятельно позднее.

Для включения режима обновления без импорта решений:

. [.ph .cmd]#На сервере с установленной системой {dv} с модулем [.dfn .term]_{wc}_ перейдите по адресу [.ph .filepath]`%LocalAppData%Docsvision`.#
. [.ph .cmd]#Создайте в папке документ формата [.dfn .term]_.config_ при помощи любого текстового редактора.#
. [.ph .cmd]#Добавьте в файл следующие строки, при необходимости заменив `true` на `false`:#
+
[source,,l,language-xml]
----
<?xml version="1.0" encoding="utf-8"?>
<WebAdminConsoleSettings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <LoadLayouts>false</LoadLayouts>
</WebAdminConsoleSettings>
----
. [.ph .cmd]#Закройте файл с сохранением изменений.#

[[CreateUpdateConfig__result_kd4_pyb_v4b]]
Обновление {wc}а будет происходить без автоматической загрузки решений в базу данных.

*На уровень выше:* xref:Administrator_functions.adoc[Функции администратора]
