
== Установка варианта расположения кнопок «ОК/Отмена» по умолчанию

Порядок расположения кнопок ОК/Сохранить и Отмена, отображаемых в диалоговых окнах и разметках {wc}а, является настраиваемым. Пользователь может настроить схему расположения в меню «Профиль». Администратор может установить порядок расположения по умолчанию (будет действовать до выбора нового значения пользователем).

. Откройте конфигурационный файл `{webconfig}`.
. Перейдите к секции [.ph .menucascade]#[.ph .uicontrol]*configuration* > [.ph .uicontrol]*{dv}* > [.ph .uicontrol]*WebClient* > [.ph .uicontrol]*SettingGroups* > [.ph .uicontrol]*SettingGroup[Name="WebClient"]*#.
. Измените значение параметра `DefaultButtonPosition`:
* «Auto» (значение по умолчанию) – порядок отображения кнопок определяется типом ОС пользователя:
** в ОС MacOS – «Отмена / ОК»;
** в ОС Windows, Android и пр. – «ОК / Отмена».
* «OkCancel» – «ОК / Отмена».
* «CancelOk» – «Отмена / ОК»;
+
Пример включения режима «Отмена / ОК»:
+
[source,,l]
----
<Setting Name="DefaultButtonPosition" Value="CancelOk"/>
----
. Сохраните изменения конфигурационного файла.

*Parent topic:* xref:CommonConf.adoc[Общие настройки]
