
== Изменение способа удаления карточек и папок

По умолчанию карточки и папки из Web-клиента удаляются в корзину. Администратор может включить режим удаления без возможности восстановления.

[NOTE]
====
[.note__title]#Note:# Восстановить удаленные карточки и папки можно только в Windows-клиенте.
====

. Откройте конфигурационный файл [.ph]#[.ph .filepath]`[Каталог установки Web-клиента]\5.5\Site\web.config`#.
. Перейдите к секции [.ph .menucascade]#[.ph .uicontrol]*configuration* > [.ph .uicontrol]*Docsvision* > [.ph .uicontrol]*WebClient* > [.ph .uicontrol]*SettingGroups* > [.ph .uicontrol]*SettingGroup[Name="WebClient"]*#.
. Измените значение параметра `DeletePermanently`: true – отключает использование корзины; false (по умолчанию) – удалённые карточки и папки помещаются в корзину.
+
[source,pre,codeblock]
----
<Setting Name="DeletePermanently" Value="false"/>
----
+
Если указанного параметра нет в конфигурационном файле, создайте его самостоятельно.
. Сохраните изменения конфигурационного файла.

*Parent topic:* xref:../topics/CommonConf.html[Общие настройки]
