
== Панель команд

Панель команд программы включает следующие команды:

Файл::
  Управление Решениями;;
    Открывает xref:dl_solution_controlpanel.html[Панель управления Решениями]
  Локализация;;
    Открывает xref:sc_localization.html[Панель управления ресурсами локализации]
  Локации;;
    Открывает xref:Locations_form.html[Панель управления локациями]
  Выход;;
Разметка::
  Создать;;
    Открывает окно создания новой разметки.
  Копировать из родительского вида;;
    Копирует в текущий вид карточек все разметки из родительского вида. Функция недоступна для корневого вида – вида, являющегося родительским для всех других видов.
  Копировать, Вставить;;
    xref:sc_copylayout.html[Копирует выбранную разметку] для добавления в другой или текущий вид карточек.
  Переименовать;;
    Открывает окно изменения отображаемого названия разметки.
  Настроить;;
    Открывает окно xref:dl_ui_layouteditor.html[Редактора разметок] для изменения выбранной разметки.
  Удалить;;
    Удаляет выбранную разметку.
Условия выбора::
  Добавить условие;;
    Открывает Редактор условий для создания нового условия выбора разметки.
  +
  Дублировать;;
    xref:sc_conditiondublicate.html[Создает копию выделенного условия выбора].
  +
  Редактировать;;
    Открывает Редактор условий для изменения выделенного условия выбора.
  +
  Вверх, Вниз;;
    xref:scenarios_movecondition.html[Повышает или понижает приоритет выделенного условия выбора.]
  +
  Удалить;;
    xref:sc_conditions.html[Удаляет выделенное условие выбора].

*На уровень выше:* xref:../topics/designerlayouts_interface.html[Интерфейс пользователя]
