
== Копирование элемента управления

Настроенный элемент управления может быть скопирован со всеми настройками в текущую разметку или в другую разметку. Элементы управления, содержащие дочерние элементы, копируются с ними.

Чтобы скопировать элемент управления:

. [.ph .cmd]#Выберите в текущей разметке копируемый элемент управления.#
. [.ph .cmd]#Нажмите кнопку [.ph .uicontrol]*Копировать* или вызовите одноименную команду из контекстного меню копируемого элемента.#
. [.ph .cmd]#Если нужно, откройте другую разметку.#
. [.ph .cmd]#В области [.keyword .wintitle]*Структура карточки* выберите [.ph .uicontrol]*Блок*, в который должен быть вставлен элемент управления, или [.dfn .term]_Корневой блок_.#
. [.ph .cmd]#Нажмите кнопку [.ph .uicontrol]*Вставить* или вызовите из контекстного меню копируемого элемента команду [.ph .uicontrol]*Вставить*.#
+
Элемент управления будет добавлен в выбранный [.ph .uicontrol]*Блок* последним. Скопированному элементу управления будет присвоено новое название.

