
== Изменение порядка элементов управления в блоке

Чтобы изменить порядок отображения элементов управления в блоке:

. [.ph .cmd]#В области [.keyword .wintitle]*Структура карточки* выберите элемент управления, порядок следования которого изменяется.#
. [.ph .cmd]#Нажмите кнопку [.ph .uicontrol]*Вверх* / [.ph .uicontrol]*Вниз* на ленте [.dfn .term]_Редактора разметок_, или вызовите аналогичную команду из контекстного меню перемещаемого элемента управления. Элемент управления будет перемещен вверх или вниз в своём блоке.#
+
Если перемещение элемента управления в одном из направлений невозможно, то соответствующая кнопка блокируется.

С помощью свойства `Порядок` элемента управления «Блок» можно переопределить порядок следования элементов разметки, установленный при настройке структуры разметки. В этом случае фактическая последовательность отображения элементов управления на компьютере пользователя {wc}а может отличаться от отображаемой в Редакторе разметок в области [.ph .uicontrol]*Компоновка*.

*Parent topic:* xref:dl_customizelayouts.adoc[Настройка разметок]
