
== Отключение кэширования разметок фильтра данных в представлении

{wc} по умолчанию кэширует (серверный кэш) разметки фильтров, используемых для фильтрации данных в представлении. Кэш обновляется при перезапуске сервера {wc}, а также автоматически при изменении настроек представления.

Администратору нужно отключить кэширование разметок фильтров, если в {wc}е планируется использовать две или более разметки представлений. Если кэширование не отключено, пользователи могут получать разметки фильтра, не соответствующие условиям выбора разметок, указанным в программе _{kvr}_.

Для отключения кэширования:

. Откройте конфигурационный файл [.ph]#[.ph .filepath]`{wcd}\5.5\Site\web.config`#.
. Перейдите к секции [.ph .menucascade]#[.ph .uicontrol]*configuration* > [.ph .uicontrol]*{dv}* > [.ph .uicontrol]*WebClient* > [.ph .uicontrol]*SettingGroups* > [.ph .uicontrol]*SettingGroup[Name="WebClient"]*#.
. Установите значение параметра `MinCheckDirectoryTimestampsInterval` в «false»:
+
[source,pre,codeblock]
----
<SettingGroup Name="WebClient">
    <Setting Name="GridFilterCache" Value="false" /> 
</SettingGroup>
----
+
Если указанного параметра нет в конфигурационном файле, создайте его самостоятельно.
. Сохраните изменения конфигурационного файла.

*Parent topic:* xref:CacheConf.adoc[Настройки кэширования]
