= Настройка разметки основного окна {wc}а

include::partial$webFrame1.adoc[]

Пользователь программы {kvr} может настроить разметку основного окна {wc}а, определяющую расположение основного меню, панели меню, области представления и пр.

.Чтобы настроить разметки основного окна {wc}а:
. В программе {kvr} xref:locationsSelect.adoc[перейдите в локацию] menu:WebFrame[Корень WebFrame].
. xref:layoutsGeneralOperations.adoc#layoutsCopy[Создайте копию] стандартных разметок в *собственном решении*:
* _WebFrame_ -- разметка для полной версии {wc}а;
* _WebFrame_Smartphone_ -- разметка для мобильной версии {wc}а.
. Измените разметки созданной копии разметок в соответствии с собственными требованиями.
+
В разметку могут быть добавлены любые из доступных элементов Библиотеки элементов управления. Также может быть изменено размещение элементов, присутствующих по умолчанию в стандартной разметке (см. описание элементов в разделе xref:ctrlWebFrame.adoc[WebFrame]).
+
include::partial$webFrame2.adoc[]
+
. Добавьте условие выбора, по которому будут выбираться созданные разметки.
