= Настройка разметки карточек

. xref:locationsSelect.adoc[Выберите локацию] карточки, для которой настраиваются разметки.
+
.Чтобы выбрать локацию:
.. Выберите группу локаций с требуемой локацией карточки:
+
ArchiveManagement Карточки::
Группа локаций библиотеки модуля _Управление архивом_.
BackOffice Карточки:: Группа локаций библиотеки карточек _Базовые объекты_, включает локации карточек приложения _{ud}_ и др. приложений, основанных на карточках данной библиотеки карточек.
TakeOffice Карточки:: Группа локаций библиотеки карточек _Делопроизводство 4.5_.
ApprovalDesigner Карточки:: Группа локаций библиотеки карточек _{ad}_.
Workflow Карточки:: Группа локаций библиотеки карточек _Управление процессами_.
+
.. Выберите локацию, разметки которой настраиваются.
+
Название локации соответствует названию типа/вида карточек. Например: _Документ / ДокументУД / Исходящий_.
. xref:solutionChangeCurrent.adoc[Выберите Решение], в которое включаются разметки и условия выбора, в списке `*Текущее решение*`.
+
Новые разметки автоматически включаются в Решение, выбранное в списке `*Текущее решение*`. Если распространять разметки в виде готового Решения не предполагается, можно выбрать Решение _Мои настройки_.
+
[#step3]
. xref:layoutsGeneralOperations.adoc#layoutsCreate[Создайте разметки карточек].
+
В {wc}е есть два типа разметок: для просмотра и для редактирования карточек. Разметка редактирования также используется для создания карточек.
+
В зависимости от требований, могут быть созданы разметки для просмотра, создания и редактирования карточек, или, если возможность создания и изменения карточки не требуется, только для просмотра карточек.
+
Для каждой роли пользователя и/или состояния карточки могут быть разработаны собственные разметки. Также собственные разметки могут быть разработаны для каждого типа клиентского устройства: персональный компьютер, планшет, смартфон.
. xref:layoutsAboutSetings.adoc[Настройте разметки].
+
На данном этапе в новые разметки добавляются элементы управления для ввода/просмотра данных карточки. Список элементов управления определяется индивидуально и зависит от типа/вида карточки и бизнес-требований. Параллельно могут быть разработаны xref:layoutsEventHandler.adoc[скрипты карточек], реализующие/переопределяющие бизнес-логику работы с ней.
+
[IMPORTANT]
====
Некоторые ЭУ жестко связаны с данными карточки, другие должны содержать настройки _Источник данных_, _Поле данных_.

В разметку редактирования необходимо добавить ЭУ xref:ctrl/layoutElements/savingButtons.adoc[Кнопки сохранения], иначе возможность сохранения изменений будет недоступна.
====
+
. xref:conditionsAbout.adoc[Добавьте условия выбора разметок].
+
Условия выбора определяют, какая разметка должна быть использована для открытия/создания карточки.
+
На данном этапе нужно добавить условия, которые будут выбирать созданные на <<step3,шаге 3>> разметки, в зависимости от режима работы с карточкой, роли пользователя, типа устройства и других доступных критериев.
+
Для полноценной работы с карточками (создание/просмотр/редактирование) необходимо добавить условия с режимами _Просмотр_, _Редактирование_, _Создание_, выбирающие соответствующие разметки.
+
Новые условия автоматически включаются в Решение, выбранное текущим.
. xref:conditionsMakeActive.adoc[Назначьте действующий набор условий].
+
Решение, в которое были добавлены условия, должно быть назначено действующим, иначе соответствующие разметки выбираться не будут.
