= Встраивание одной карточки в другую

{wc} предоставляет возможность отображать в карточке данные связанной карточки или карточки, получаемой с помощью xref:layoutsExtendedDataSource.adoc[расширенного источника данных]. При этом может использоваться стандартная разметка отображаемой карточки или специальная разметка для отображения одной карточки в другой.

.Чтобы настроить разметку в разметке:
. Если требуется, создайте и настройте для вида встраиваемой карточки отдельную разметку, которая будет использоваться при её отображении в другой карточке. Для данной разметки добавьте условие выбора _Внутри другой разметки_.
+
TIP: При необходимости для встраивания можно использовать существующую разметку с любым условием выбора.
+
. Настройте разметку карточки, в которую встраивается другая карточки.
+
Встраиваемая карточка может являться связанной карточкой или быть карточкой, доступной через xref:layoutsExtendedDataSource.adoc[расширенные источники данных].
+
. Создайте разметку, в которой будет отображать другая карточка.
. Если требуется, подключите xref:layoutsExtendedDataSource.adoc[расширенные источники данных].
. Добавьте в разметку элемент управления xref:Control_locationContainer.adoc[Контейнер локации] -- используется для отображения другой карточки.
. Настройте элемент `_Контейнер локаций_`:
* _Источник локации_ -- выберите значение *_Связанная карточка/строка_*.
* Выберите источник данных в параметрах: `*Расширенный источник данных*`, `*Источник данных*` и `*Поле данных*`.
* _Локация_ -- выберите локацию с разметкой встраиваемой карточки (добавлена в п. 1).
* _Режим_ -- выберите режим разметки, которая будет выбираться при открытии встраиваемой карточки.
+
NOTE: Если для встраиваемой карточки была разработана разметка с условием выбора _Внутри другой разметки_, в настройке _Режим_ выберите *_Внутри другой разметки_*.
+
* _Максимальная высота_ -- укажите максимальный размер в пикселях для блока, в котором будет отображаться встраиваемая карточка.
* Если требуется, настройте другие параметры.
. Добавьте другие элементы в разметку.
. Сохраните разметку.
