= Настройка разметки справочников

{kvr} предоставляет возможность настраивать разметки для справочников и строк справочников.

[NOTE]
====
Для доступа к строкам справочников {wc} предоставляет специальные методы, которые перечислены в пункте xref:programmer:SpecialURLs.adoc[Список специальных адресов {wc}а]. Используя данные методы можно работать со строками справочников, когда это недоступно стандартными средствами.
====

.Чтобы создать разметку:
. xref:solutionChangeCurrent.adoc[Выберите настраиваемое Решение], в которое будет включена разметка.
. xref:locationsSelect.adoc[Выберите локацию] узла справочника, для строк которого настраиваются разметки.
+
.Чтобы выбрать локацию:
.. Выберите группу локаций с требуемой локацией справочников:
ArchiveManagement Справочники:: Содержит локации справочников модуля _Управление Архивом_.
BackOffice Справочники:: Содержит локации справочников модуля _Базовые объекты_.
TakeOffice Справочники:: Содержит локации справочников модуля _Делопроизводство 4.5_.
Platform Справочники:: Содержит локации справочников модуля _Платформа_.
WebClient Справочники:: Содержит локации справочников модуля _WebClient_.
Workflow Справочники:: Содержит локации справочников модуля _Управление процессами_.
+
.. Выберите локацию, разметки которой вы хотите настроить.
+
Название локации соответствует названию справочника\узла\строки. Например: menu:Справочник контрагентов[Подразделения].
. xref:layoutsСreate.adoc[Создайте разметки].
+
Для справочника достаточно создать разметку для просмотра.
+
Для строк справочников можно создать разметки для создания, просмотра и редактирования.
. xref:layoutsAboutSetings.adoc[Настройте разметки].
+
Для разметок строк добавьте элементы, позволяющие отображать\изменять значения полей данной строки, а также xref:ctrl/layoutElements/savingButtons.adoc[кнопки сохранения].
+
Для разметки самого справочника можно добавить элементы для работы с деревом или списком значений: отображение, открытие.
. xref:conditionsAbout.adoc[Добавьте условия выбора разметок].
+
В зависимости от типа справочника/строки будут доступны различные критерии для создания условий выбора:

* для всех элементов доступна возможность создания условий на основе режима открытия элемента, роли пользователя и типа пользовательского устройства;
* для Справочника сотрудников и Справочника контрагентов доступен дополнительный критерий: _Тип строки_ -- позволяет выбирать разметку в зависимости от типа редактируемой строки;
* для строк `Подразделения` и `Сотрудники` Справочника сотрудников и Справочника контрагентов, а также строк `Узлы справочника` и `Строка справочника` Конструктора справочников доступен дополнительный критерий: _Вид карточки_. Критерий: _Вид карточки_ позволяет выбирать разметку в зависимости от _Вида карточки_, который выбран для узла данной строки в справочнике в системе {dv}.
