= Использование стилей {wc} в собственных разметках

В {wc} для разметок карточек модуля _Управление документами_ были разработаны новые стили, которые по умолчанию используются только в стандартных карточках разметок. Для использования новых стилей в собственных разметках необходимо назначить специальные обработчики и стили на элементы разметок.

. Назначьте обработчик на событие `*Перед открытием карточки*` корневого элемента разметки `_documentRoot_`:
+
addNewStyleForControls:: добавляет для разметки и её модальных окон класс *_new-style-layout_*. Новые стили могут быть применены только при наличии у разметки данного класса.
+
. Назначьте обработчики на событие `*После открытия карточки*` корневого элемента разметки _documentRoot_:
+
addStyleToCard:: Включает в себя три обработчика:

getControlsForExpanding::: Осуществляет поиск Блоков с классом *_block-with-border_*, для которых включает поддержку возможности сворачивания/разворачивания по щелчку на общей кнопке сворачивания/разворачивания всех блоков.
addGrayBackgroundToCard::: Добавляет в карточку фон серого цвета.
addShadowBorder::: Осуществляет поиск раскрытых Блоков с классом *_block-with-border_*, для которых добавляет серую рамку.
+
Вместо одного обработчика *_addStyleToCard_* можно указать обработчики *_getControlsForExpanding_*, *_addGrayBackgroundToCard_* и *_addShadowBorder_*. Если отдельные функции не требуются, обработчики можно не указывать.
+
outgoingDocument_CardManagementIsVisible:: Загружает почту и телефон контрагентов, указанных в списке Адресаты, при загрузке карточки, а также скрывает пустой блок с примечанием.
+
Используется только в разметке _Исходящего_ документа.
+
. Назначьте обработчик на события `*_При сворачивании_*` и `*_При разворачивании_*` элементов `_Блок_`, `_Список файлов_`, _Ссылки_ и др. сворачиваемых элементов:
* *_switchBorderWithShadow_* -- в развернутом состоянии добавляет к элементу рамку с тенью, и скрывает её при сворачивании элемента.
+
Обработчик *_switchBorderWithShadow_* следует добавлять только к элементам, для которых нужна тень. Например, это блок с информацией о карточке, список файлов или блок, в котором отображается ход исполнения.
+
Постоянную рамку для несворачиваемых блоков можно добавить с помощью стиля *block-with-shadow*: указать в параметре `*Дополнительные CSS классы*` требуемого элемента.
+
TIP: Для устаревших элементов управления `_TaskCardFilePanel_`, `_TaskCardReportPanel_` и т. п., у которых отсутствуют события `*При сворачивании*` / `*При разворачивании*`, рамка с тенью может быть добавлена только с помощью стиля *block-with-shadow*.
+
. Укажите стили в настройке _Дополнительные CSS классы_:
* Для корневого элемента `_documentRoot_`:
+
system-layout-independent-scroll:: Включает отдельную прокрутку для элемента `_Предпросмотр файла_` и области с данными карточки.
expansion-panel-header:: Включает новый дизайн для заголовков Блоков.
center-screen:: Включает динамическое изменение боковых отступов от края страницы до элементов с данными карточки: чем уже окно браузера, тем меньше отступы.
control-label-opacity-half:: Включает использование серого цвета для меток элементов управления.
+
* Для Блоков:
+
block-with-toggle-button:: Добавляет в Блок кнопку сворачивания/разворачивания всех Блоков со стилем *block-with-border*. Для избежания ошибок: стиль следует использовать только в одном Блоке разметки; у данного блока не должно быть обработчиков события _При щелчке_.
top-saving-buttons-block:: Включает выравнивание содержимого по высоте, убирает лишнее пространство у кнопок.
+
CAUTION: Следует устанавливать только в Блоке, в котором размещается название карточки и кнопки сохранения, если дизайн пользовательской разметки повторяет дизайн стандартной разметки документов.
+
block-with-shadow:: Добавляет тень и рамку к Блоку.
+
[TIP]
====
Если для блока включен обработчик *_switchBorderWithShadow_*, добавлять стиль *block-with-shadow* не нужно.

Для Блоков, Списка файлов, Ссылок и др. сворачиваемых элементов, для которых назначен обработчик *_switchBorderWithShadow_* *block-with-border* добавляет функцию сворачивания/разворачивания элемента, вызываемую кнопкой сворачивания/разворачивания всех Блоков.
====
+
* Прочие доступные стандартные стили:
+
document-name-small:: Устанавливает размер шрифта 1.4rem. В разметках {wc} используется в элементе с названием карточки;
document-name:: Устанавливает размер шрифта 1.6875rem. Стандартные размер для элемента с названием карточки в {wc} 14.
card-kind-large:: При ширине экрана более 420px устанавливает размер шрифта 1.125rem. В разметках {wc} используется в элементе Вид карточки.
document-view-state-wide:: Переводит строчные буквы в прописные и добавляет межбуквенный интервал. В разметках {wc} в элементе Состояние.
taskstable-with-hidden-filters:: Скрывает фильтры в элементе Таблица исполнения.
colored-button:: Для элемента Кнопка включает использование стандартной цветовой гаммы открытой карточки.
block-border-top, block-border-right, block-border-bottom, block-border-left:: Добавляет серую линию в 1px по одной из границ элемента соответственно: верхней, правой, нижней, левой.
block-with-disclosure-body-center:: Для Блоков включает выравнивание содержимого по центру.
block-with-disclosure-resize:: Для Блока включает особый режим выравнивания дочерних блоков, если у Блока два дочерних блока шириной 50% от родительского и установленной минимальной шириной. Если ширины родительского блока достаточно для отображения обоих блоков в строку -- они будут отображаться в строку, иначе -- в столбец.
block-with-one-height:: Для Блока включает особый режим выравнивания дочерних Блоков по высоте. Всем дочерним Блокам будет установлена высота самого высокого Блока.
block-with-state-buttons:: Для Блока устанавливает особый режим выстраивания элементов Кнопка. При ширине окна меньше 421px кнопки будут размещаться вертикально с выравниванием по ширине родительского Блока.
