= Настройка разметки главной страницы

Главная страница -- страница, которая открывается при запуске {wc}а и при переходе по ссылке `#/Dashboard`.

Настройка разметки главной страницы в программе {kvr} включает несколько последовательно выполняемых действий:

. xref:locationsSelect.adoc[Выберите локацию] главной страницы: menu:WebFrame[Главная страница].
. xref:solutionChangeCurrent.adoc[Выберите Решение], в которое включаются разметки и условия выбора, в списке `*Текущее решение*`.
+
[#step3]
. xref:layoutsСreate.adoc[Создайте разметку главной страницы].
+
Для главной страницы требуется разметка с типом _Просмотр_, режим _Редактирование_ не используется. Может быть разработана одна разметка для всех типов пользовательских устройств или отдельные разметки для каждого устройства.
+
Рекомендуемый вариант: разработать разметку для устройства с маленьким экраном и разметку для других устройств.
. xref:layoutsAboutSetings.adoc[Настройте разметки].
+
Типовая разметка основного меню может включать следующие элементы:
+
* xref:ctrl/dashboard/folderGroupDashboardWidget.adoc[Виджет / Группа папок].
** xref:ctrl/dashboard/folderDashboardWidget.adoc[Виджет / Известная папка].
** Другие папки и группы папок:
* xref:ctrl/dashboard/recentCardsDashboardWidget.adoc[Виджет / Последние карточки] -- содержит список последних карточек.
. xref:conditionsAbout.adoc[Добавьте условия выбора разметок].
+
Должно быть добавлено условие, использующее разметку, созданную на <<step3,шаге 3>>, для открытия главной страницы.
. xref:conditionsMakeActive.adoc[Назначьте действующий набор условий].
+
Решение, в которое были добавлены условия, должно быть назначено действующим, иначе соответствующие разметки выбираться не будут.
