= Настройка разметки основного меню

Основное меню -- сворачиваемая панель с деревом папок, размещенная в левой части окна {wc}а.

Настройка разметки основного меню в программе {kvr} включает несколько последовательно выполняемых действий:

. xref:locationsSelect.adoc[Выберите локацию] основного меню: menu:WebFrame[Основное меню].
. xref:solutionChangeCurrent.adoc[Выберите Решение], в которое включаются разметки и условия выбора, в списке `*Текущее решение*`.
[#step3]
. xref:layoutsGeneralOperations.adoc#layoutsCreate[Создайте разметки основного меню].
+
Для основного меню требуется разметка с типом _Просмотр_, режим _Редактирование_ не используется. Может быть разработана одна разметка для всех типов пользовательских устройств или отдельные разметки для каждого устройства.
. xref:layoutsAboutSetings.adoc[Настройка разметок].
+
Типовая разметка основного меню может включать следующие элементы:
+
* xref:ctrl/mainMenu/mainMenu.adoc[Контейнер / Главное меню].
** xref:ctrl/mainMenu/rightMainMenuItemPanel.adoc[Контейнер / Панель элемента меню] -- содержит ЭУ, необходимые для настройки и обновления дерева папок пользователем.
*** xref:ctrl/mainMenu/configurableMainMenuContainerButton.adoc[Кнопка / Настроить].
*** xref:ctrl/mainMenu/refreshFoldersTreeButton.adoc[Кнопка / Обновить].
*** xref:ctrl/mainMenu/mainMenuPinButton.adoc[Кнопка / Закрепить меню].
** xref:ctrl/mainMenu/linkMainMenuItem.adoc[Ссылка / Страница {wc}а] -- настроен на открытие страницы `#/Dashboard`.
** xref:ctrl/mainMenu/configurableMainMenuContainer.adoc[Контейнер / Настраиваемая область] -- содержит папки, которые могут быть скрыты пользователем.
*** xref:ctrl/mainMenu/groupMainMenuItem.adoc[Контейнер / Группа элементов].
**** xref:ctrl/mainMenu/folderMainMenuItem.adoc[Папка / Известная папка].
**** Другие папки и группы папок:
*** xref:ctrl/mainMenu/userFoldersMainMenuItem.adoc[Папки / Пользовательские папки].
* xref:ctrl/mainMenu/connectUserFoldersToConfigurableContainerScript.adoc[Скрипт / Настройка пользовательских папок] -- является контейнером для подключаемых пользователем папок.
+
****
При настройке разметки следует обратить внимание, что некоторые ЭУ предназначены для работы в связке с другими ЭУ, и в их настройках предусмотрено указывать названия связанных ЭУ. Например, при настройке ЭУ *Скрипт / Настройка пользовательских папок* должны быть указаны названия элементов управления xref:ctrl/mainMenu/configurableMainMenuContainer.adoc[Контейнер / Настраиваемая область] и xref:ctrl/mainMenu/userFoldersMainMenuItem.adoc[Папки / Пользовательские папки].
****
+
. xref:conditionsAbout.adoc[Добавьте условия выбора разметок].
+
Должно быть добавлено условие, использующее разметку, созданную на <<step3,шаге 3>>, для открытия основного меню.
+
. xref:conditionsMakeActive.adoc[Назначьте действующий набор условий].
+
Решение, в которое были добавлены условия, должно быть назначено действующим, иначе соответствующие разметки выбираться не будут.
