= Руководство по настройке Решений в программе {kvr}

Настройка Решения в программе {kvr} -- процесс, включающий несколько последовательно выполняемых действий:

. xref:solutions-new.adoc[Создайте новое Решение].
+
На данном этапе формируется проект Решения, в который далее будут включены разметки, условия выбора, локации и др.
. xref:locationsAboutSettings.adoc[Создайте новые локации].
+
Локации -- страницы {wc}а или части страницы, к которым могут применяться разметки. Стандартные локации: карточки, дашборд, основное меню и др. При необходимости могут быть добавлены собственные локации, которые могут быть встроены в разметки других локаций или открываться как отдельные страницы по ссылке.
. xref:layoutsGeneralOperations.adoc#layoutsCreate[Создайте разметки].
+
Данный этап может включать создание разметок для карточек, дерева папок, дашборда и других локаций.
+
Для каждой локации может быть разработано несколько разметок. Например, можно создать отдельные разметки для каждого типа устройств, роли пользователя, состояния карточки и т.д. Количество разметок, которые потребуется разработать, определяется собственными требованиями. Как минимум может потребоваться разработать разметки для собственных видов/типов карточек: для создания, изменения и просмотра карточки.
+
IMPORTANT: На данном шаге важно, чтобы при добавлении разметки текущим было выбрано решение, созданное в п. 1.
+
. xref:layoutsEditor.adoc[Настройте разметки].
+
Настройка разметки -- фактическая её реализация. Данный этап включает:
+
* формирование разметки с помощью предоставляемых и собственных элементов управления,
* настройка элементов управления разметки (связывание их с данными, настройка общих параметров),
* локализация и др.
+
Этап настройки разметок также может включать разработку клиентских скриптов (для реализации дополнительной бизнес-логики), стилей (для изменения графического интерфейса) и др.
. xref:conditionsAbout.adoc[Настройте условия выбора разметок].
+
Условия выбора разметок -- правила, по которым {wc} выбирает разметку, необходимую для отображения данных в определённой локации, из всех доступных разметок.
+
Условия выбора разметок могут содержать различные критерии. Список критериев зависит от локации, для которой настраивается условие.
+
IMPORTANT: На данном шаге важно, чтобы при добавлении условия текущим было выбрано решение, созданное в п. 1.
+
. xref:solutions-export.adoc[Экспортируйте Решение].
+
Настройки Решения (разметки, условия выбора и др.) выгружаются в файл XML, который может быть xref:solutions-import.adoc[загружен] в другие БД.
+
****
При настройке разметок Решений ориентируйтесь на правила, по которым {wc} выбирает разметки. Правила приведены в ПРИЛОЖЕНИИ xref:selectLayout.adoc[Правила выбора разметки для открытия карточки].
****
+
[NOTE]
====
С целью оптимизации {wc} кэширует разметки на сервере. Ознакомьтесь с особенностями xref:admin:layouts-cache-settings.adoc[настройки и использования] кэша.
====
