
== Изменение режима скрытия правой боковой панели

Правая боковая панель, на которой отображаются параметры отправки документа на согласование, на ознакомление и пр., по умолчанию скрывается при нажатии на данной панели кнопок выполнения: ОК, Отмена и пр. Администратор может включить режим, при котором панель также будет скрываться при щелчке по любой области страницы {wc}а вне боковой панели.

Для изменения режима скрытия панели:

. Откройте конфигурационный файл [.ph]#[.ph .filepath]`{wcd}\5.5\Site\web.config`#.
. Перейдите к секции [.ph .menucascade]#[.ph .uicontrol]*configuration* > [.ph .uicontrol]*{dv}* > [.ph .uicontrol]*WebClient* > [.ph .uicontrol]*SettingGroups* > [.ph .uicontrol]*SettingGroup[Name="WebClient"]*#.
. Измените значение параметра `HideSidebarOnPageClick`:
* «false» (значение по умолчанию) – панель должна скрываться только при нажатии кнопки ОК/Отмена и пр.
* «true» – панель также должна скрываться при щелчке вне боковой панели.
+
Пример включения режима, при котором панель будет скрываться при нажатии кнопки ОК/Отмена и пр., а также при щелчке вне боковой панели:
+
[source,pre,codeblock]
----
<Setting Name="HideSidebarOnPageClick" Value="true"/>
----
. Сохраните изменения конфигурационного файла.

*Parent topic:* xref:CommonConf.adoc[Общие настройки]
