
== Встраивание локации в разметку

Локация может быть добавлена в разметку другой локации или предоставляться по ссылке.

Внедрение локации в существующую разметку осуществляется с помощью ЭУ xref:Control_locationContainer.adoc[Контейнер локации].

. Добавьте в разметку элемент управления «Контейнер локации».
. Настройте добавленный ЭУ:
[loweralpha]
.. В настройке `Локация` выберите добавляемую локацию.
.. Установите флаг `Часть родительской разметки`, чтобы элементы управления разметки локации были доступны, как часть родительской локации.

Чтобы локация была доступна по ссылке:

. Добавьте в разметку элемент управления xref:Control_layoutpagemainmenuitem.adoc[Ссылка / Локация].
. В настройке `Локация` добавленного ЭУ выберите локацию, на которую добавляется ссылка.

Также можно настроить отображение в карточке связанной карточки. Инструкция по встраиванию разметки в разметку xref:LayoutInLayout.adoc[Встраивание одной карточки в другую].

*Parent topic:* xref:Locations.adoc[Настройка локаций]
