= Панель команд

Панель команд программы включает следующие команды:

Файл::
Управление Решениями:::
Открывает xref:dl_solution_controlpanel.adoc[Панель управления Решениями].

Локализация:::
Открывает xref:sc_localization.adoc[Панель управления ресурсами локализации].

Локации:::
Открывает xref:Locations_form.adoc[Панель управления локациями].

Выход:::
Закрывает {kvr}

Разметка::
Создать:::
Открывает окно создания новой разметки.

Копировать из родительского вида:::
Копирует в текущий вид карточек все разметки из родительского вида. Функция недоступна для корневого вида, являющегося родительским для всех других видов.

Копировать, Вставить:::
xref:layoutsCopy.adoc[Копирует выбранную разметку] для добавления в другой или текущий вид карточек.

Переименовать:::
Открывает окно изменения отображаемого названия разметки.

Настроить:::
Открывает окно xref:dl_ui_layouteditor.adoc[Редактора разметок] для изменения выбранной разметки.

Удалить:::
Удаляет выбранную разметку.

Условия выбора::

Добавить условие:::
Открывает Редактор условий для создания нового условия выбора разметки.

Дублировать:::
xref:sc_conditiondublicate.adoc[Создает копию выделенного условия выбора].

Редактировать:::
Открывает Редактор условий для изменения выделенного условия выбора.

Вверх, Вниз:::
xref:scenarios_movecondition.adoc[Повышает или понижает приоритет выделенного условия выбора].

Удалить:::
xref:sc_conditions.adoc[Удаляет выделенное условие выбора].
