= Панель команд

Панель команд программы включает следующие команды:

Файл::
Управление Решениями:::
Открывает xref:solutionsControlPanel.adoc[Панель управления Решениями].

Локализация:::
Открывает xref:localizationsAboutSettings.adoc[Панель управления ресурсами локализации].

Локации:::
Открывает xref:locationsContolPanel.adoc[Панель управления локациями].

Выход:::
Закрывает {kvr}

Разметка::
Создать:::
Открывает окно создания новой разметки.

Копировать из родительского вида:::
Копирует в текущий вид карточек все разметки из родительского вида. Функция недоступна для корневого вида, являющегося родительским для всех других видов.

Копировать, Вставить:::
xref:layoutsGeneralOperations.adoc#layoutsCopy[Копирует выбранную разметку] для добавления в другой или текущий вид карточек.

Переименовать:::
Открывает окно изменения отображаемого названия разметки.

Настроить:::
Открывает окно xref:layoutsEditor.adoc[Редактора разметок] для изменения выбранной разметки.

Удалить:::
Удаляет выбранную разметку.

Условия выбора::

Добавить условие:::
Открывает Редактор условий для создания нового условия выбора разметки.

Дублировать:::
xref:conditionsCopy.adoc[Создает копию выделенного условия выбора].

Редактировать:::
Открывает Редактор условий для изменения выделенного условия выбора.

Вверх, Вниз:::
xref:conditionsChangeOrder.adoc[Повышает или понижает приоритет выделенного условия выбора].

Удалить:::
xref:conditionsAbout.adoc[Удаляет выделенное условие выбора].
