= Элементы редактора разметок

_{kvr}_ предоставляется с набором стандартных элементов управления, которые могут быть использованы для разработки разметок карточек и общих разметок. Данные стандартные элементы управления составляют _Библиотеку_ стандартных элементов управления.

Все элементы управления _Библиотеки_ стандартных элементов управления делятся на несколько групп, в зависимости от функционального назначения:

* Главная страница.
* Главное меню.
* Групповые операции.
* Компоненты папки.
* Параметры поискового запроса.
* Профиль пользователя.
* Системные.
* Согласование.
* Специальные.
* Справочники.
* Стандартные.
* Таблицы.
* Фильтр папки.
* Элементы разметки.

Данные группы можно, условно разделить, на:

. Элементы разметки (далее -- *ЭР*) -- элементы управления для формирования блочной структуры разметки. Данные элементы управления следует рассматривать как контейнеры, в которые могут встраиваться другие элементы управления.
. Элементы управления (далее -- *ЭУ*) -- основные элементы управления, которые, как правило, можно связать с данными или использовать для вызова определенной функции (например, изменить состояние карточки).

Элементы управления обладают набором определенных настраиваемых свойств (базовых и собственных) и событий, на которые можно подписаться для их обработки в скрипте карточки.

В зависимости от локации и типа разметки, пользователю может быть доступен ограниченный набор элементов управления, а также их настроек.

TIP: Полное описание стандартных элементов управления приведено в разделе xref:StandardControlsLibrary.adoc[Описание стандартных элементов управления].
