
== Встраивание одной карточки в другую

Web-клиент предоставляет возможность отображать в карточке данные связанной карточки или карточки, получаемой с помощью xref:AddExtendedDataSource.html[расширенного источника данных]. При этом может использоваться стандартная разметка отображаемой карточки или специальная разметка для отображения одной карточки в другой.

Для настройки разметки в разметке:

. Если требуется, создайте и настройте для вида «встраиваемой» карточки отдельную разметку, которая будет использоваться при её отображении в другой карточке. Для данной разметки добавьте условие выбора «Внутри другой разметки».
+
Новая разметка создается при необходимости – для встраивания можно использовать существующую разметку с любым условием выбора.
. Настройте разметку карточки, в которую «встраивается» другая карточки.
+
«Встраиваемая» карточка может являться связанной карточкой или быть карточкой, доступной через xref:AddExtendedDataSource.html[расширенные источники данных].
[loweralpha]
.. Создайте разметку, в которой будет отображать другая карточка.
.. Если требуется, подключите xref:AddExtendedDataSource.html[расширенные источники данных].
.. Добавьте в разметку элемент управления xref:Control_locationContainer.html[Контейнер локации] – используется для отображения другой карточки.
.. Настройте элемент «Контейнер локаций»:
* «Источник локации» – выберите значение «Связанная карточка/строка»;
* Выберите источник данных в параметрах: «Расширенный источник данных», «Источник данных» и «Поле данных».
* «Локация» – выберите локацию с разметкой «встраиваемой» карточки (добавлена в п. 1).
* «Режим» – выберите режим разметки, которая будет выбираться при открытии «встраиваемой» карточки.
+
Если для «встраиваемой» карточки была разработана разметка с условием выбора «Внутри другой разметки», в настройке «Режим» выберите «Внутри другой разметки».
* «Максимальная высота» – укажите максимальный размер в пикселях для блока, в котором будет отображаться «встраиваемая» карточка.
* Если требуется, настройте другие параметры.
.. Добавьте другие элементы в разметку.
.. Сохраните разметку.

*Parent topic:* xref:../topics/PracticeConfigSolution.html[Этапы настройки Решения в Конструкторе web-разметок]
