= Настройка локаций

Пользовательский интерфейс содержит несколько стандартных локаций, определяющих определённые части пользовательского интерфейса {wc}а. К таким стандартным локациям относятся: _Главное меню_, _Стартовая страница_, _Панель фильтра папки_, _Окна карточек_ и др.

Пользователь программы {kvr} может добавить в {wc} новую локацию с собственным набором разметок. Данная локация может быть встроена в разметку другой локации или быть доступна как отдельная страница.

Управление локациями осуществляется с помощью _Панели управления локациями_.

== Свойства элемента локации "root"

include::partial$properties.adoc[tags=general]

=== Данные

==== Расширенные источники данных

Выбор типа источников данных локации: выбор типов, доступных для элементов управления  разметки.

=== Поведение

==== Стандартные css классы локации

Название CSS классов, определяющих стандартный стиль локации управления.

==== Дополнительные css классы локации

Названия дополнительных классов CSS для изменения стиля локации. Перечисляются через пробел.

==== Фон

Свойство позволяет задать фон и доступно только в следующих локациях: _Папка_, _Последние карточки_, _Результаты поиска_, _Главная страница_.

.Доступны следующие варианты назначения фона:
* Без фона -- используется стандартный серый фон (значение по умолчанию).
* Стандартный фон -- используется фон, назначенный в ЭУ xref:page$ctrl/webFrame/webFrameContent.adoc[].
* Специальный фон -- появляется дополнительное свойство, в котором можно указать путь к файлу по аналогии с xref:page$ctrl/webFrame/webFrameContent.adoc#bg[фоном дя ЭУ "Содержимое"].
+
** Если выбран специальный фон, обязательно требуется указать путь до файла с картинкой фона в свойстве `*Картинка фона*`. В противном случае будет невозможно сохранить изменения разметки.
** При выборе специального фона и картинки фона также можно изменить свойство `*Отображение фона*` -- выпадающий список с вариантами *_Растянуть_* или *_Замостить_*.

=== События

==== Перед изменением разметки

Вызывается перед изменением разметки.

==== Перед изменением состояния

Вызывается перед изменением состояния.

==== Перед открытием карточки

Вызывается перед открытием карточки.

==== Перед сохранением карточки

Вызывается перед сохранением карточки.

==== Перед удалением карточки

Вызывается перед удалением карточки.

==== Подготовка к сохранению карточки

Вызывается подготовке к сохранению карточки.

==== После загрузки всех ЭУ

Вызывается после загрузки всех ЭУ.

==== После открытия карточки

Вызывается после открытия карточки.

==== После сохранения карточки

Вызывается после сохранения карточки.

==== После удаления карточки

Вызывается после удаления карточки.

include::partial$properties.adoc[tags=mouseOver]

include::partial$properties.adoc[tags=mouseAway]

include::partial$properties.adoc[tags=onClick]
