
== Создание локализованного ресурса

Новый локализованный ресурс создается автоматически при присвоении нового значения настраиваемому свойству элемента управления в xref:dl_ui_layouteditor.html[Редакторе разметки].

[NOTE]
====
[.note__title]#Note:# Если локализованный ресурс с аналогичным значением (для языка локализации по умолчанию) есть в списке ресурсов локализации текущего [.dfn .term]_Решения_, то новый ресурс не создается, а используется существующий.
====

Также локализованный ресурс может быть добавлен вручную. Для этого:

. [.ph .cmd]#xref:localization_opencontrolpanel.html[Откройте Панель управления ресурсами локализации].#
. [.ph .cmd]#Нажмите кнопку [.ph .uicontrol]*Добавить*.#
+
В [.dfn .term]_Таблицу локализаций_ будет добавлена новая строка. Пустые значения для обязательного языка локализации (английского) и для языка локализации по умолчанию будут выделены красным цветом.
. [.ph .cmd]#Перейдите в режим редактирования одинарным щелчком мыши по выбранной в [.dfn .term]_Таблице локализации_ ячейке, и введите значение локализованного ресурса для соответствующего языка локализации.#
+
Обязательно должны быть заполнены значения в ячейках, выделенных красным цветом.
. [.ph .cmd]#Нажмите [.ph .uicontrol]*ОК* для сохранения изменений.#
+
Если [.dfn .term]_Панель управления ресурсами локализации_ была открыта при настройке свойства элемента управления в [.dfn .term]_Редакторе разметки_, то перед сохранением выберите локализованный ресурс, значение которого должно быть присвоено настраиваемому свойству.

Добавленный локализованный ресурс будет доступен для выбора при настройке свойств элементов управления Решения, в которое был добавлен ресурс.

*Parent topic:* xref:../topics/sc_localization.html[Управление локализованными ресурсами]
