= Создать локализованный ресурс

Новый локализованный ресурс создаётся автоматически, как только для настраиваемому свойству элемента управления присваивается новое значение в xref:layouts-editor.adoc[Редакторе разметок].

[NOTE]
====
В случае возникновения конфликта значений локализованных ресурсов будет использоваться уже существующий ресурс. Новый ресурс для языка локализации по умолчанию не создаётся, если ресурс с аналогичным значением в списке ресурсов локализации текущего _Решения_ уже имеется.
====

Локализованный ресурс может быть добавлен вручную.

.Чтобы добавить локализованный ресурс вручную:
. xref:localizations-control-panel.adoc[Откройте Панель управления ресурсами локализации].
. Нажмите кнопку *Добавить*.
+
В _Таблицу локализаций_ будет добавлена новая строка. Пустые значения для обязательного языка локализации (английского) и для языка локализации по умолчанию будут выделены красным цветом.
. Перейдите в режим редактирования нажатием по выбранной ячейке в _Таблице локализации_, и введите значение локализованного ресурса для соответствующего языка локализации.
+
IMPORTANT: Обязательно должны быть заполнены значения в ячейках, выделенных красным цветом.
+
. Нажмите *ОК* для сохранения изменений.
+
****
Если _Панель управления ресурсами локализации_ была открыта при настройке свойства элемента управления в _Редакторе разметки_, перед сохранением выберите локализованный ресурс, значение которого должно быть присвоено настраиваемому свойству.
****

Добавленный локализованный ресурс будет доступен для выбора при настройке свойств элементов управления Решения, в которое был добавлен ресурс.
