= Выбрать локацию

Выберите локацию в xref:interface-locations-tree.adoc[дереве локаций], чтобы изменить разметки.

.Чтобы настроить разметки карточек:
. Выберите xref:interface-locations-tree.adoc[группу локаций], соответствующей библиотеки карточек. Каждая локация в списке соответствует определённому виду карточек.
. Выберите требуемую локацию.
+
NOTE: Локация обычно содержит разметки для полной и мобильной версии {wc}а. В локации также могут быть расположены разметки других решений или пользовательские разметки.
+
После выбора локации, в рабочей области программы {kvr} будут открыты разметки и условия выбора разметок выбранной локации.

.Локации группы _WebFrame_:
====
.Группа локаций _WebFrame_ содержит следующие локации:
Главная страница:: Разметки дашборда.
Диалог профиля пользователя:: разметки диалогового окно _Профиль_, открываемый из меню пользователя.
Компоненты папки::
Грид::: Разметки области представления. Используются в xref:user:grid.adoc[Новом гриде].
Групповые операции с карточками::: Разметки панели групповых операций.
Диалог поисковых параметров::: Разметки диалогового окна атрибутивного поиска.
Панель поиска по столбцам представления::: Разметки панели настройки фильтра папки.
Папка::: Разметки области представления.
Последние карточки::: Разметки страницы _Последние карточки_. Используются при включении экспериментальной функции _Новый грид_.
Результаты поиска::: Разметки страницы _Результаты поиска_. _Используются при включении экспериментальной функции _Новый грид__.
Корень WebFrame:: Содержит разметки основного окна {wc}а (заголовок, в котором отображается текущая страница. основное меню с деревом папок. и область, в которой отображается содержимое выбранной папки или карточки).
+
Локация _Корень WebFrame_ содержит две разметки: для полной и мобильной версии {wc}а. Создание и удаление разметок в данной локации запрещено. В разметках допускается только изменение элемента управления `_barcodeSearchButton_`

Основное меню:: Разметки дерева папок;
Разметки для элементов управления::
Диалоги операций карточек::: Разметки боковой панели, отображаемой при выполнении операции с карточкой:
Делегировать:::: При делегировании задания;
Завершить:::: При завершении задания;
На доработку:::: При возврате задания на доработку;
Отклонить:::: При отклонении задания;
Перенос сроков исполнения:::: При переносе сроков исполнения задания;
Поиск карточек для ссылок::: Разметки окна добавления ссылок карточки;
Создание дочернего задания согласования::: Разметки панели создания дочернего согласования.
====