
== Выполнение операций

Перед началом работы с Конструктором web-разметок обратите внимание на следующие ограничения:

* запрещено изменять настройки стандартных Решений: «Базовые решения» и «Управление документами».
* не рекомендуется создавать/удалять/изменять разметки в группе локаций «WebFrame» за исключением следующих разрешенных изменений:
** создание/изменение/удаление разметок в локациях «Главная страница», «Основное меню» и «Диалог профиля пользователя»;
** изменение настроек элементов управления, для которых предоставлена данная возможность, в существующих разметках в локации «Корень WebFrame».

* *xref:../topics/SelectLocation.html[Выбор локации]* +
* *xref:../topics/ChangeCurrentSolution.html[Выбор текущего решения]* +
* *xref:../topics/sc_layouts.html[Общие операции с разметками]* +
* *xref:../topics/dl_customizelayouts.html[Настройка разметок]* +
* *xref:../topics/dl_customizecontrols.html[Настройка элементов управления]* +
* *xref:../topics/sc_conditions.html[Настройка условий выбора разметок]* +
* *xref:../topics/dl_solution.html[Управление Решениями]* +
* *xref:../topics/sc_localization.html[Управление локализованными ресурсами]* +
* *xref:../topics/Locations.html[Настройка локаций]* +
* *xref:../topics/PracticeConfigSolution.html[Этапы настройки Решения в Конструкторе web-разметок]* +
