
== Выполнение операций

Перед началом работы с Конструктором web-разметок обратите внимание на следующие ограничения:

* запрещено изменять настройки стандартных Решений: «Базовые решения» и «Управление документами».
* не рекомендуется создавать/удалять/изменять разметки в группе локаций «WebFrame» за исключением следующих разрешенных изменений:
** создание/изменение/удаление разметок в локациях «Главная страница», «Основное меню» и «Диалог профиля пользователя»;
** изменение настроек элементов управления, для которых предоставлена данная возможность, в существующих разметках в локации «Корень WebFrame».

* *xref:SelectLocation.adoc[Выбор локации]* +
* *xref:ChangeCurrentSolution.adoc[Выбор текущего решения]* +
* *xref:sc_layouts.adoc[Общие операции с разметками]* +
* *xref:dl_customizelayouts.adoc[Настройка разметок]* +
* *xref:dl_customizecontrols.adoc[Настройка элементов управления]* +
* *xref:sc_conditions.adoc[Настройка условий выбора разметок]* +
* *xref:dl_solution.adoc[Управление Решениями]* +
* *xref:sc_localization.adoc[Управление локализованными ресурсами]* +
* *xref:Locations.adoc[Настройка локаций]* +
* *xref:PracticeConfigSolution.adoc[Этапы настройки Решения в Конструкторе web-разметок]* +
