
== Настройка разметки главной страницы

[NOTE]
====
[.note__title]#Note:# Главная страница -- страница, которая открывается при запуске {wc}а и при переходе по ссылке «#/Dashboard».
====

Настройка разметки главной страницы в программе {kvr} включает несколько последовательно выполняемых действий:

. xref:locationsSelect.adoc[Выбор локации] главной страницы: [.ph .filepath]`WebFrame → Главная страница`.
. xref:solutionChangeCurrent.adoc[Выбор Решения], в которое включаются разметки и условия выбора, в списке `*Текущее решение*`.
. xref:layoutsСreate.adoc[Создание разметки главной страницы].
+
Для главной страницы требуется разметка с типом «Просмотр» (режим «Редактирование» не используется). Может быть разработана одна разметка для всех типов пользовательских устройств или отдельные разметки для каждого устройства.
+
Рекомендуемый вариант: разработать разметку для устройства с маленьким экраном и разметку для других устройств.
. xref:layoutsAboutSetings.adoc[Настройка разметок].
+
Типовая разметка основного меню может включать следующие элементы:

* xref:Control_foldergroupdashboardwidget.adoc[Виджет / Группа папок];
** xref:Control_folderdashboardwidget.adoc[Виджет / Известная папка];
** другие папки и группы папок;
* xref:Control_recentcardsdashboardwidget.adoc[Виджет / Последние карточки] (содержит список последних карточек).
. xref:conditionsAbout.adoc[Добавление условий выбора разметок].
+
Должно быть добавлено условие, использующее разметку, созданную на шаге 3, для открытия главной страницы.
. xref:conditionsMakeActive.adoc[Назначение действующего набора условий].
+
Решение, в которое были добавлены условия, должно быть назначено действующим, иначе соответствующие разметки выбираться не будут.
