
== Настройка разметки карточек

. xref:SelectLocation.adoc[Выбор локации] карточки, для которой настраиваются разметки.
+
Для выбора локации, нужно:

[loweralpha]
.. Выбрать группу локаций с требуемой локацией карточки:
* «BackOffice Cards» – группа локаций библиотеки карточек «Базовые объекты», включает локации карточек приложения «Управление документами» и др. приложений, основанных на карточках данной библиотеки карточек;
* «TakeOffice Cards» – группа локаций библиотеки карточек «Делопроизводство 4.5»;
* «ApprovalDesigner Cards» – группа локаций библиотеки карточек «Конструктор согласований»;
* «Workflow Cards» – группа локаций библиотеки карточек «Управление процессами».
.. Выбрать локацию, разметки которой настраиваются.
+
Название локации соответствует названию типа/вида карточек. Например: «Документ / ДокументУД / Исходящий».
. xref:ChangeCurrentSolution.adoc[Выбор Решения], в которое включаются разметки и условия выбора, в списке [.ph .uicontrol]*Текущее решение*.
+
Новые разметки автоматически включаются в Решение, выбранное в списке [.ph .uicontrol]*Текущее решение*. Если распространять разметки в виде готового Решения не предполагается, можно выбрать Решение «Мои настройки».
. xref:dl_layouts_create.adoc[Создание разметок карточек].
+
В {wc}е есть два типа разметок: для просмотра и для редактирования карточек. Разметка редактирования также используется для создания карточек.
+
В зависимости от требований, могут быть созданы разметки для просмотра, создания и редактирования карточек, или только для просмотра карточек (если возможность создания и изменения карточки не требуется).
+
Для каждой роли пользователя и/или состояния карточки могут быть разработаны собственные разметки. Также собственные разметки могут быть разработаны для каждого типа клиентского устройства (персональный компьютер, планшет, смартфон).
. xref:dl_customizelayouts.adoc[Настройка разметок].
+
На данном этапе в новые разметки добавляются элементы управления для ввода/просмотра данных карточки. Список элементов управления определяется индивидуально (зависит от типа/вида карточки и бизнес-требований). Параллельно могут быть разработаны xref:dl_cardevents.adoc[скрипты карточек], реализующие/переопределяющие бизнес-логику работы с ней.
+
На что следует обратить внимание:

* некоторые ЭУ жестко связаны с данными карточки, другие должны быть настроены (содержать настройки «Источник данных», «Поле данных»);
* в разметку редактирования необходимо добавить ЭУ xref:Control_saveorcancel.adoc[Кнопки сохранения], иначе возможность сохранения изменений будет недоступна.
. xref:sc_conditions.adoc[Добавление условий выбора разметок].
+
Условия выбора определяют то, какая разметка должна быть использована для открытия/создания карточки. На данном этапе нужно добавить условия, которые будут выбирать созданные на шаге 3 разметки, в зависимости от режима работы с карточкой, роли пользователя, типа устройства и других доступных критериев.
+
Для полноценной работы с карточками (создание/просмотр/редактирование) необходимо добавить условия с режимами «Просмотр», «Редактирование», «Создание», выбирающие соответствующие разметки.
+
Новые условия автоматически включаются в Решение, выбранное текущим.
. xref:ActivateCondition.adoc[Назначение действующего набора условий].
+
Решение, в которое были добавлены условия, должно быть назначено действующим, иначе соответствующие разметки выбираться не будут.

*Parent topic:* xref:PracticeConfigSolution.adoc[Этапы настройки Решения в Конструкторе web-разметок]
