
== Настройка разметки главной страницы

[NOTE]
====
[.note__title]#Note:# Главная страница – страница, которая открывается при запуске Web-клиента и при переходе по ссылке «#/Dashboard».
====

Настройка разметки главной страницы в Конструкторе web-разметок включает несколько последовательно выполняемых действий:

. xref:SelectLocation.html[Выбор локации] главной страницы: [.ph .filepath]`WebFrame → Главная страница`.
. xref:ChangeCurrentSolution.html[Выбор Решения], в которое включаются разметки и условия выбора, в списке [.ph .uicontrol]*Текущее решение*.
. xref:dl_layouts_create.html[Создание разметки главной страницы].
+
Для главной страницы требуется разметка с типом «Просмотр» (режим «Редактирование» не используется). Может быть разработана одна разметка для всех типов пользовательских устройств или отдельные разметки для каждого устройства.
+
Рекомендуемый вариант: разработать разметку для устройства с маленьким экраном и разметку для других устройств.
. xref:dl_customizelayouts.html[Настройка разметок].
+
Типовая разметка основного меню может включать следующие элементы:

* xref:Control_foldergroupdashboardwidget.html[Виджет / Группа папок];
** xref:Control_folderdashboardwidget.html[Виджет / Известная папка];
** другие папки и группы папок;
* xref:Control_recentcardsdashboardwidget.html[Виджет / Последние карточки] (содержит список последних карточек).
. xref:sc_conditions.html[Добавление условий выбора разметок].
+
Должно быть добавлено условие, использующее разметку, созданную на шаге 3, для открытия главной страницы.
. xref:ActivateCondition.html[Назначение действующего набора условий].
+
Решение, в которое были добавлены условия, должно быть назначено действующим, иначе соответствующие разметки выбираться не будут.

*Parent topic:* xref:../topics/PracticeConfigSolution.html[Этапы настройки Решения в Конструкторе web-разметок]
