
== Настройка разметки справочников

{kvr} предоставляет возможность настраивать разметки для справочников и строк справочников.

[NOTE]
====
[.note__title]#Note:# В стандартной реализации {wc}а функциональные возможности работы со справочниками ограничены: только выбор значений; для Справочника контрагентов -- выбор и создание\изменение значений.

Для доступа к строкам справочников {wc} предоставляет специальные методы, которые перечислены в Руководстве программиста, пункт «Список специальных адресов {wc}а». Используя данные методы можно работать со строками справочников, когда это недоступно стандартными средствами.
====

Для создания разметки:

. xref:solutionChangeCurrent.adoc[Выберите настраиваемое Решение], в которое будет включена разметка.
. xref:locationSelect.adoc[Выберите локацию] узла справочника, для строк которого настраиваются разметки.
+
Для выбора локации, нужно:

[loweralpha]
.. Выбрать группу локаций с требуемой локацией справочников:
* «BackOffice Directories» -- содержит локации справочников модуля «Базовые объекты»;
* «TakeOffice Directories» -- содержит локации справочников модуля «Делопроизводство 4.5»;
* «Platform Directories» -- содержит локации справочников модуля «Платформа»;
* «Workflow Directories» -- содержит локации справочников модуля «Управление процессами».
.. Выбрать локацию, разметки которой настраиваются.
+
Название локации соответствует названию справочника\узла\строки. Например: [.ph .filepath]`Справочник контрагентов → Подразделения`.
. xref:layoutsСreate.adoc[Создайте разметки].
+
Для справочника достаточно создать разметку для просмотра.
+
Для строк справочников можно создать разметки для создания, просмотра и редактирования.
. xref:dl_customizelayouts.adoc[Настройте разметки].
+
Для разметок строк добавьте элементы, позволяющие отображать\изменять значения полей данной строки, а также xref:Control_saveorcancel.adoc[кнопки сохранения].
+
Для разметки самого справочника можно добавить элементы для работы с деревом или списком значений: отображение, открытие.
. xref:sc_conditions.adoc[Добавьте условия выбора разметок].
+
В зависимости от типа справочника/строки будут доступны различные критерии для создания условий выбора:

* для всех элементов доступна возможность создания условий на основе режима открытия элемента, роли пользователя и типа пользовательского устройства;
* для Справочника сотрудников и Справочника контрагентов доступен дополнительный критерий: «Тип строки» -- позволяет выбирать разметку в зависимости от типа редактируемой строки;
* для строк «Подразделения» и «Сотрудники» Справочника сотрудников и Справочника контрагентов, а также строк «Узлы справочника» и «Строка справочника» Конструктора справочников доступен дополнительный критерий: «Вид карточки» -- позволяет выбирать разметку в зависимости от «Вида карточки», который выбран для узла данной строки в справочнике в системе {dv}.
