
== Этапы настройки Решения в Конструкторе web-разметок

Настройка Решения в Конструкторе web-разметок – процесс, включающий несколько последовательно выполняемых действий:

. xref:sc_createsolution.html[Создание нового Решения].
+
На данном этапе формируется проект Решения, в который далее будут включены разметки, условия выбора, локации и др.
. xref:Locations.html[Создание новых локаций].
+
Локации – страницы Web-клиента или части страницы, к которым могут применяться разметки. Стандартные локации: карточки, дашборд, основное меню и др. При необходимости могут быть добавлены собственные локации, которые могут быть встроены в разметки других локаций или открываться как отдельные страницы по ссылке.
. xref:dl_layouts_create.html[Создание разметок].
+
Данный этап может включить создание разметок для карточек, дерева папок, дашборда и других локаций.
+
Для каждой локации может быть разработано несколько разметок. Например, можно создать отдельные разметки для каждого типа устройств, роли пользователя, состояния карточки и т.д. Количество разметок, которые потребуется разработать, определяется собственными требованиями. Как минимум, может потребоваться разработать разметки для собственных видов/типов карточек: для создания, изменения и просмотра карточки.
+
На данном шаге важно, чтобы при добавлении разметки текущим было выбрано решение, созданное в п. 1.
. xref:dl_ui_layouteditor.html[Настройка разметок].
+
Настройка разметка – фактическая её реализация. Данный этап включает:

* формирование разметки с помощью предоставляемых и собственных элементов управления,
* настройка элементов управления разметки (связывание их с данными, настройка общих параметров),
* локализация и др.
+
Этап настройки разметок также может включать разработку клиентских скриптов (для реализации дополнительной бизнес-логики), стилей (для изменения графического интерфейса) и др.
. xref:sc_conditions.html[Настройка условий выбора разметок].
+
Условия выбора разметок – правила, по которым Web-клиент выбирает разметку, необходимую для отображения данных в определенной локации, из всех доступных разметок.
+
Условия выбора разметок могут содержать различные критерии, список которых зависит от локаций, для которой настраивается условие.
+
На данном шаге важно, чтобы при добавлении условия текущим было выбрано решение, созданное в п. 1.
. xref:dl_solutions_export.html[Выгрузка Решения].
+
Настройки Решение (разметки, условия выбора и др.) выгружаются в файл XML, который может быть xref:dl_solutions_import.html[загружен] в другие БД.

При настройке разметок Решений ориентируйтесь на правила, по которым Web-клиент выбирает разметки. Правила приведены в ПРИЛОЖЕНИИ xref:SelectLayout.html[Правила выбора разметки для открытия карточки].

[NOTE]
====
[.note__title]#Note:# С целью оптимизации Web-клиент кэширует разметки на сервере. Рекомендуется ознакомится с особенностями настройки и использования кэша, которые указаны в руководстве администратора модуля «Web-клиент».
====

* *xref:../topics/PracticeConfigCardLayout.html[Настройка разметки карточек]* +
* *xref:../topics/PracticeConfigDictionaryLayout.html[Настройка разметки справочников]* +
* *xref:../topics/PracticeConfigFoldersLayout.html[Настройка разметки основного меню]* +
* *xref:../topics/PracticeConfigDashboardLayout.html[Настройка разметки главной страницы]* +
* *xref:../topics/PracticeConfigWebFrameLayout.html[Настройка разметки основного окна Web-клиента]* +
* *xref:../topics/UserProfileConfig.html[Настройка разметки диалога профиля пользователя]* +
* *xref:../topics/WebFrameUserPanelConfig.html[Настройка панели пользователя]* +
* *xref:../topics/SearchCardByBarcodeMode.html[Настройка режима открытия карточки при поиске по штрих-коду]* +
* *xref:../topics/LayoutInLayout.html[Встраивание одной карточки в другую]* +
* *xref:../topics/ApplyDMStyles.html[Использование новых стилей Web-клиент 15 в собственных разметках]* +
* *xref:../topics/ArchiveManagementPreparation.html[Настройка работы с модулем Управление архивом]* +
* *xref:../topics/EmployeesDirPreparation.html[Добавление ссылки на справочник сотрудников]* +

*Parent topic:* xref:../topics/Operations.html[Выполнение операций]
