
== Этапы настройки Решения в программе _{kvr}_

Настройка Решения в программе _{kvr}_ – процесс, включающий несколько последовательно выполняемых действий:

. xref:sc_createsolution.adoc[Создание нового Решения].
+
На данном этапе формируется проект Решения, в который далее будут включены разметки, условия выбора, локации и др.
. xref:Locations.adoc[Создание новых локаций].
+
Локации – страницы {wc}а или части страницы, к которым могут применяться разметки. Стандартные локации: карточки, дашборд, основное меню и др. При необходимости могут быть добавлены собственные локации, которые могут быть встроены в разметки других локаций или открываться как отдельные страницы по ссылке.
. xref:dl_layouts_create.adoc[Создание разметок].
+
Данный этап может включить создание разметок для карточек, дерева папок, дашборда и других локаций.
+
Для каждой локации может быть разработано несколько разметок. Например, можно создать отдельные разметки для каждого типа устройств, роли пользователя, состояния карточки и т.д. Количество разметок, которые потребуется разработать, определяется собственными требованиями. Как минимум, может потребоваться разработать разметки для собственных видов/типов карточек: для создания, изменения и просмотра карточки.
+
На данном шаге важно, чтобы при добавлении разметки текущим было выбрано решение, созданное в п. 1.
. xref:dl_ui_layouteditor.adoc[Настройка разметок].
+
Настройка разметка – фактическая её реализация. Данный этап включает:

* формирование разметки с помощью предоставляемых и собственных элементов управления,
* настройка элементов управления разметки (связывание их с данными, настройка общих параметров),
* локализация и др.
+
Этап настройки разметок также может включать разработку клиентских скриптов (для реализации дополнительной бизнес-логики), стилей (для изменения графического интерфейса) и др.
. xref:sc_conditions.adoc[Настройка условий выбора разметок].
+
Условия выбора разметок – правила, по которым {wc} выбирает разметку, необходимую для отображения данных в определенной локации, из всех доступных разметок.
+
Условия выбора разметок могут содержать различные критерии, список которых зависит от локаций, для которой настраивается условие.
+
На данном шаге важно, чтобы при добавлении условия текущим было выбрано решение, созданное в п. 1.
. xref:dl_solutions_export.adoc[Выгрузка Решения].
+
Настройки Решение (разметки, условия выбора и др.) выгружаются в файл XML, который может быть xref:dl_solutions_import.adoc[загружен] в другие БД.

При настройке разметок Решений ориентируйтесь на правила, по которым {wc} выбирает разметки. Правила приведены в ПРИЛОЖЕНИИ xref:SelectLayout.adoc[Правила выбора разметки для открытия карточки].

[NOTE]
====
[.note__title]#Note:# С целью оптимизации {wc} кэширует разметки на сервере. Рекомендуется ознакомится с особенностями настройки и использования кэша, которые указаны в руководстве администратора модуля {wc}.
====

* *xref:PracticeConfigCardLayout.adoc[Настройка разметки карточек]* +
* *xref:PracticeConfigDictionaryLayout.adoc[Настройка разметки справочников]* +
* *xref:PracticeConfigFoldersLayout.adoc[Настройка разметки основного меню]* +
* *xref:PracticeConfigDashboardLayout.adoc[Настройка разметки главной страницы]* +
* *xref:PracticeConfigWebFrameLayout.adoc[Настройка разметки основного окна {wc}а]* +
* *xref:UserProfileConfig.adoc[Настройка разметки диалога профиля пользователя]* +
* *xref:WebFrameUserPanelConfig.adoc[Настройка панели пользователя]* +
* *xref:SearchCardByBarcodeMode.adoc[Настройка режима открытия карточки при поиске по штрих-коду]* +
* *xref:LayoutInLayout.adoc[Встраивание одной карточки в другую]* +
* *xref:ApplyDMStyles.adoc[Использование новых стилей {wc} 15 в собственных разметках]* +
* *xref:ArchiveManagementPreparation.adoc[Настройка работы с модулем Управление архивом]* +
* *xref:EmployeesDirPreparation.adoc[Добавление ссылки на справочник сотрудников]* +

*Parent topic:* xref:Operations.adoc[Выполнение операций]
