
== Печать договора

В демонстрационном согласовании печать бумажного экземпляра договора осуществляет сотрудник, который включен в группу «Печать Договоров» в Справочнике сотрудников.

На печать договор поступает, если этап «Согласование с контрагентом» был завершен с результатом «Согласован контрагентом».

. Перейдите в папку [.ph .filepath]`Мои задания/Входящие`.
+
Для заместителя: нужно перейти в папку [.ph .filepath]`Замещение/Входящие`.
. Откройте полученное задание с описанием «Подписание документов» в состоянии `Не начато`.
. Распечатайте приложенные к карточке задания файлы.
. Нажмите кнопку [.ph .uicontrol]*Распечатано* на xref:CardOperations.adoc[панели операций].

После проставления отметки о печати, в соответствии с демонстрационным маршрутом согласования будет выполнен переход к следующему этапу «Подписание договора внутри организации». Соответствующее задание поступит пользователю, указанному в поле [.ph .uicontrol]*Подписывает* карточки договора.

*Parent topic:* xref:ContractsReconciliationDemo.adoc[Согласование и подписание договорных документов]
