
== Согласование документов

В данном разделе приведен пример согласования с использованием стандартного маршрута «Согласование с рецензированием и подписанием», который включает этапы:

. Согласование.
. Консолидация.
. Подписание.
. Подведение итогов.

Согласование выполняется с помощью рассылаемых участникам согласования заданий видов: «На согласование», «На консолидацию» и «На подписание».

Состав маршрута согласования определяется при настройке согласования с использованием модуля «Docsvision 5. Конструктор согласований». Пользователи, при наличии разрешения, могут вносить изменения в маршрут при создании и в процессе согласования.

Решения, принимаемые участниками согласования, могут носить положительный, условно-положительный и отрицательный характер, что определяется семантикой решения (трактовкой решения в системе).

По результатам выполнения маршрута, после подведения итогов согласования, документ может быть согласован или возвращен на повторное согласование в новом цикле.

* *xref:../topics/task_dcard_approval_send.html[Отправка документа на согласование]* +
* *xref:../topics/task_dcard_approval_view_process.html[Ознакомление с ходом согласования]* +
* *xref:../topics/dcard_approval_start_and_control.html[Управление активным согласованием]* +
* *xref:../topics/task_tcard_approval_performer_get.html[Принятие решения по согласованию документа]* +
* *xref:../topics/task_tcard_approval_consolidator_get.html[Принятие решения по консолидации документа]* +
* *xref:../topics/task_tcard_approval_significant_get.html[Принятие решения по подписанию документа]* +
* *xref:../topics/task_tcard_approval_delegation.html[Делегирование заданий на согласование/подписание/консолидацию]* +
* *xref:../topics/ApprovDiscussion.html[Обсуждение согласования]* +
* *xref:../topics/AdditionalApprovers.html[Дополнительные согласующие]* +
* *xref:../topics/Ccard_subtasks.html[Подчиненные задания согласования]* +

*На уровень выше:* xref:../topics/WorkWithCards.html[Работа с карточками]
