
== Требования к системе Docsvision

[[concept_uny_yqz_b2b__installcheck]]
* Данная версия Web-клиента предназначена для работы с системой Docsvision версии 5.5. Работа с Docsvision версии 5.4 не поддерживается.
* Для корректной установки Web-клиента БД Docsvision должна быть обновлена до последней версии (см. руководство администратора модуля «Платформа»).
* Web-клиент может работать с Docsvision с БД с расширенными или динамическими метаданными, но динамические метаданные будут недоступны в Модуле. Рекомендуется перевести БД системы Docsvision на работу с расширенными метаданными.
* Если в Web-клиенте планируется работать с функциями модуля «Docsvision 5. Управление архивом», указанный модуль должен быть установлен на сервере Docsvisionxref:#fntarg_1[^1^].
+
[NOTE]
====
[.note__title]#Прим.:# В данном случае также обязательна установка модуля «Docsvision 5. Управление архивом» на сервере Web-клиент (см. xref:Requirements_software.html[Необходимое программное обеспечение]).
====
* {blank}
+
При установке серверного расширения и Web-клиента происходит проверка требуемых модулей и их версий. Результаты проверки определяются цветом:

** Зеленый — проверка прошла успешно. Модуль обнаружен, его [.keyword]*версия соответствует* минимальным требованиям. Установка Web-клиента [.keyword]*может быть продолжена*.
** Красный — проверка не пройдена. Модуль обнаружен, но его [.keyword]*версия не соответствует* минимальным требованиям. Установка Web-клиента [.keyword]*заблокирована*.
** Желтый — модуль обнаружен, его [.keyword]*версия не соответствует* требованиям. Рекомендуется обновить версию модуля. Установка Web-клиента [.keyword]*может быть продолжена*.
** Серый — модуль не обнаружен. Установите модуль, затем возобновите установку Web-клиента. Установка Web-клиента [.keyword]*заблокирована*.

*На уровень выше:* xref:../topics/system_requirements.html[Необходимые ресурсы]

xref:#fnsrc_1[^1^] Поддерживаемая версия модуля «Docsvision 5. Управление архивом» указана в пункте «Необходимое программное обеспечение»
