
== Общие операции с разметками

В данном пункте рассмотрены операции со списком разметок. Настройка разметок рассмотрена в следующем пункте.

При работе со списком разметок обратите внимание на следующие особенности:

* Разметка может быть двух типов: для редактирования/создания и для просмотра. Для большинства видов карточек необходимо чтобы были разработаны разметки обоих типов; для общих локаций – только разметки просмотра.
* Разметка может входить только в одно Решений или в «Мои настройки».
* В зависимости от настроек вида карточек в Справочнике видов карточек у вида могут быть собственные разметки или наследоваться родительские. Если разметки наследуются, но у родительского вида не настроены собственные разметки, для открытия карточек будут использованы разметки типа карточек.
* Карточки, у которых нет собственных или унаследованных разметок, не могут быть открыты.

* *xref:dl_layouts_create.adoc[Создание новой разметки]* +
* *xref:sc_copylayout.adoc[Копирование разметок]* +
* *xref:sc_renamelayout.adoc[Переименование разметки]* +

*На уровень выше:* xref:Operations.adoc[Выполнение операций]
