
== Управление локализованными ресурсами

Конструктор web-разметок предоставляет механизм локализации, основанный на использовании локализованных ресурсов в свойствах элементов управления разметки.

[NOTE]
====
[.note__title]#Прим.:# Пример работы с локализованными ресурсами приведен в пункте xref:dl_config_localizableprop.html[Локализация свойств элемента управления].
====

Управление локализованными ресурсами выполняется с помощью Панели управления ресурсами локализации.

Каждый локализованный ресурс закрепляется за определенным [.dfn .term]_Решением_, в которое включена разметка, использующая данный ресурс. Локализованные ресурсы могут быть использованы только в разметках своего [.dfn .term]_Решения_.

* *xref:../topics/localization_opencontrolpanel.html[Панель управления ресурсами локализации]* +
* *xref:../topics/localization_add.html[Создание локализованного ресурса]* +
* *xref:../topics/localization_change.html[Изменение локализованного ресурса]* +
* *xref:../topics/localization_remove.html[Удаление локализованного ресурса]* +
* *xref:../topics/DefaultLocalizationLang.html[Язык локализации по умолчанию]* +

*На уровень выше:* xref:../topics/Operations.html[Выполнение операций]
