
== Управление локализованными ресурсами

{kvr} предоставляет механизм локализации, основанный на использовании локализованных ресурсов в свойствах элементов управления разметки.

[NOTE]
====
[.note__title]#Прим.:# Пример работы с локализованными ресурсами приведен в пункте xref:dl_config_localizableprop.adoc[Локализация свойств элемента управления].
====

Управление локализованными ресурсами выполняется с помощью Панели управления ресурсами локализации.

Каждый локализованный ресурс закрепляется за определенным [.dfn .term]_Решением_, в которое включена разметка, использующая данный ресурс. Локализованные ресурсы могут быть использованы только в разметках своего [.dfn .term]_Решения_.

* *xref:localization_opencontrolpanel.adoc[Панель управления ресурсами локализации]* +
* *xref:localization_add.adoc[Создание локализованного ресурса]* +
* *xref:localization_change.adoc[Изменение локализованного ресурса]* +
* *xref:localization_remove.adoc[Удаление локализованного ресурса]* +
* *xref:DefaultLocalizationLang.adoc[Язык локализации по умолчанию]* +

