:page-figure-caption: Диаграмма

= Приложение А. Правила выбора разметки для открытия карточки

При открытии карточки в {wc}е используемая разметка выбирается по следующим правилам:

.Правила выбора разметок при открытии карточки
[plantuml,svg]
....
@startuml
skinparam defaultTextAlignment center
#lightgray:Правила выбора разметок;
    split
    #yellow:Вид карточек **не наследует** \nразметки родительского вида;
    split again
    #yellow:Вид карточек **наследует** разметки \nродительского вида;
    #yellow:Используются данные разметки;
    end split
    split
    #orange:**Есть** собственные разметки;
        split
         #lightgreen:Есть разметки, \nсоответствующие \nусловиям выбора;
        #green:**Используются данные разметки**;
        detach
        split again
        #pink:Нет разметок, \nсоответствующих \nусловиям выбора;
        #red:**Открытие карточки невозможно**;
        detach
        end split

        split again
        #orange:**Нет** собственных разметок;
            split
            #pink:Нет разметок типа карточек, \nсоответствующих \nусловиям выбора;
            #red:**Открытие карточки невозможно**;
            detach
            split again
             #lightgreen:Есть разметки типа карточек, \nсоответствующие \nусловиям выбора;
            #green:**Используются данные разметки типа**;
            end split
    end split
detach
@enduml
....
