
== Выбор локации

В xref:interfaceLocationsTree.adoc[дереве локаций] выберите локацию, для которой планируется настройка разметок:

* для настройки разметок карточек:
. Выберите группу локаций, соответствующей библиотеки карточек:
** «BackOffice Cards» (карточки библиотеки «Базовые объекты» и основанных на ней решений);
** «TakeOffice Cards» (карточки библиотеки «Делопроизводство 4.5») и т.д.
+
Будет открыт список локаций выбранной группы. Каждая локация в списке соответствует определенному виду карточек.
. Выберите требуемую локацию.
* для настройки общих разметок:
. Выберите группу локаций «WebFrame».
. Выберите локацию:
** «Главная страница» -- разметки дашборда;
** «Диалог профиля пользователя» -- разметки диалогового окно «Профиль», открываемого из меню пользователя;
** «Компоненты папки»:
*** «Грид» -- разметки области представления. _Используются при включении экспериментальной функции «Новый грид»_;
*** «Групповые операции с карточками» -- разметки панели групповых операций;
*** «Диалог поисковых параметров» -- разметки диалогового окна атрибутивного поиска;
*** «Панель поиска по столбцам представления» -- разметки панели настройки фильтра папки;
*** «Папка» -- разметки области представления;
*** «Последние карточки» -- разметки страницы «Последние карточки». _Используются при включении экспериментальной функции «Новый грид»_;
*** «Результаты поиска» -- разметки страницы «Результаты поиска». _Используются при включении экспериментальной функции «Новый грид»_;
** «Корень WebFrame» -- содержит разметки основного окна {wc}а (заголовок, в котором отображается текущая страница; основное меню с деревом папок; и область, в которой отображается содержимое выбранной папки или карточки).
+
Локация «Корень WebFrame» содержит две разметки: для полной и мобильной версии {wc}а. Создание и удаление разметок в данной локации запрещено. В разметках допускается только изменение элемента управления [.ph .uicontrol]*barcodeSearchButton*;
** «Основное меню» -- разметки дерева папок;
** «Разметки для элементов управления»:
*** Диалоги операций карточек -- разметки боковой панели, отображаемой при выполнении операции с карточкой:
**** Делегировать -- при делегировании задания;
**** Завершить -- при завершении задания;
**** На доработку -- при возврате задания на доработку;
**** Отклонить -- при отклонении задания;
**** Перенос сроков исполнения -- при переносе сроков исполнения задания;
*** «Поиск карточек для ссылок» -- разметки окна добавления ссылок карточки;
*** «Создание дочернего задания согласования» -- разметки панели создания дочернего согласования.

После выбора локации, в рабочей области программы {kvr} будут открыты разметки и условия выбора разметок выбранной локации.
