= Приложение А. Правила выбора разметки для открытия карточки

При открытии карточки в {wc}е разметка, которая будет применена, выбирается по следующим правилам:

.Правила выбора разметок при открытии карточки
[mermaid,svg]
....
graph TD
    subgraph Правила выбора разметок при открытии карточки
        subgraph Вид карточек <br/> не наследует <br> разметки родительского вида
           A{ Нет собственных разметок }
        end
        subgraph Вид карточек наследует разметки родительского вида
            B( используются данные разметки)
        end
end
....

* Вид карточек не наследует разметки родительского вида:
** Нет собственных разметок:
*** Есть разметки типа карточек, соответствующие условиям выбора -- используются данные разметки типа;
*** Нет разметок типа карточек, соответствующих условиям выбора -- открытие карточки невозможно;
** Есть собственные разметки:
*** Есть разметки, соответствующие условиям выбора -- используются данные разметки;
*** Нет разметок, соответствующих условиям выбора -- открытие карточки невозможно.
* Вид карточек наследует разметки родительского вида -- используются данные разметки (правила аналогичны вышеприведенным).
