= Экспортировать Решение

В экспорт решения включаются настройки разметок, используемые в них локализованные ресурсы, условия выбора разметок, локации. Скрипты и стили, используемые в разметках, в выгрузку не включаются.

.Чтобы экспортировать решение:
. Нажмите menu:Файл[Управление Решениями], чтобы открыть xref:solutions-control-panel.adoc[Панель управления Решениями].
. Выберите выгружаемое Решение. Решение должно находиться в режиме xref:solutions-general.adoc#two-modes[Поставщик].
. Выберите формат экспорта: *Файл* *Пакет*.
. Укажите каталог для экспорта и нажмите *Сохранить* (экспорт файлом) или *ОК* (экспорт пакетом).

[#package]
== Экспорт пакетом

Решение может быть экспортировано пакетом. Пакет представляет собой папку с набором файлов и имеет следующий вид:

.Структура папки решения:
[source]
----
Управление документами
|--Layouts <.>
|---Входящий УД (локация)_79EE95AB-80C3-4413-8CBD-61683CA0D0E9.xml <.>
|---Исходящий УД (локация)_9D0C243B-B019-4A95-B4EB-64AE39A0352A.xml
|---...
|-- ConditionGroups.xml <.>
|-- Locales.xml <.>
|-- Solution.xml <.>
----
<.> Папка с файлами разметок.
<.> Файл разметки.
<.> Условия выбора разметок.
<.> Локализации.
<.> Главный файл решения.

WARNING: Не переименовывайте файлы в пакете!

== Экспорт файлом

Решение может быть экспортировано единым XML-файлом с данными.

Как и пакет, файл включает локализации, условия выбора разметок и разметки.
