= Настройка Решений

{kvr} позволяет объединять настройки разметок, условия выбора и данные локализации в _Решение_, которое может быть выгружено для последующего распространения.

Полноценное _Решение_ также может включать собственные элементы управления, скрипты и файлы стилей. Данные компоненты {kvr} не выгружает. Скрипты, файлы стилей и компоненты собственных элементов управления должны быть загружены на сервер {wc}а самостоятельно.

[#two-modes]
== Режим работы с Решением

_Решение_, реализованное с помощью _программы {kvr}_, может работать в одном из двух режимов: _Поставщик_ или _Заказчик_. В зависимости от режима работы, вводятся определенные ограничения на изменение данного _Решения_:

Поставщик:: Разрешено создавать и изменять любые объекты данного _Решения_: разметки, локализованные ресурсы и т.д..
Заказчик:: Запрещено изменять любые объекты данного _Решения_ кроме условий выбора разметок. Разрешено создавать новые разметки, запрещено включать их в _Решение_.

См. также пункт xref:solutionsChangeMode.adoc[Изменение режима работы с Решением].
