= Изменить текущее Решение

В списке xref:interfaceSolutions.adoc[Текущее решение] выберите Решение, которое хотите изменить. Выберите вариант _Мои настройки_, если нет собственного разработанного Решения.

Если вы планируете распространять настройки разметок, рекомендуется xref:sc_createsolution.adoc[создать Решение] перед настройкой разметок и условий выбора. После создания вы сможете выбрать собственное решение из списка.

Возможность изменения настроек Решений _Базовые объекты_, _Управление документами_, _Управление архивом_ и Решений сторонних производителей по умолчанию заблокирована. Заблокированные Решения не отображаются в списке. Как разблокировать изменение Решений, см. в пункте xref:ChangeSolutionMode.adoc[].

[NOTE]
====
Вместо изменения стандартных Разметок можно скопировать данные разметки в собственное Решение или в _Мои настройки_. Копии Разметок могут быть изменены без ограничений.
====

.После того как вы выбрали Решение:
* Новые разметки будут создаваться в выбранном Решении.
* Новые условия выбора будут создаваться в выбранном Решении.
* Возможность изменения условий выбора из других Решений будет заблокирована.
* xref:localization_opencontrolpanel.adoc[Панель управления ресурсами локализации] будет предоставлять доступ к ресурсам выбранного Решения.
