
== Описание стандартных элементов управления

В данном разделе приведено описание стандартных ЭУ, предоставляемых с программой «{kvr}». Описание включает перечень настраиваемых свойств и событий элементов управления.

В зависимости от назначения разметки и типа карточек, для добавления и настройки могут быть недоступны некоторые элементы управления или свойства элементов управления. В описании будут отмечены такие ограничения.

Описание некоторых свойств отмечено тегом:

* [.keyword]*Локализуемый* – если для свойства могут быть установлены несколько значений, зависящих от языка локализации;
* [.keyword]*Адаптивный* – если для свойства могут быть установлены несколько значений, зависящих от типа клиентского устройства.

* *xref:Control_layout.adoc[Разметка]* +
* *xref:WebFrameControls.adoc[WebFrame]* +
* *xref:MainPageControls.adoc[Главная страница]* +
* *xref:MainMenuControls.adoc[Главное меню]* +
* *xref:GroupOperationsControls.adoc[Групповые операции]* +
* *xref:FolderComponentsControls.adoc[Компоненты папки]* +
* *xref:SearchParametersControls.adoc[Параметры поискового запроса]* +
* *xref:UserProfileControls.adoc[Профиль пользователя]* +
* *xref:SystemControls.adoc[Системные]* +
* *xref:ApplovalControls.adoc[Согласование]* +
* *xref:SpecialControls.adoc[Специальные]* +
* *xref:DictionaryControls.adoc[Справочники]* +
* *xref:StandardControls.adoc[Стандартные]* +
* *xref:TableControls.adoc[Таблица]* +
* *xref:FilterControls.adoc[Фильтр папки]* +
* *xref:dl_layoutElements.adoc[Элементы разметки]* +
* *xref:NomenclatureofCases.adoc[Номенклатура дел]* +
