
== Ограничение количества отображаемых в папке карточек

Модуль ограничивает количество карточек, отображаемых на одной странице представления папки. Ограничение устанавливается или для всех папок, или для каждой папки по отдельности. В первом случае используется параметр Модуля, который настраивается в конфигурационном файле. Во втором случае максимальное количество вычисляется из свойств папки, настроенных в Windows-клиенте.

[NOTE]
====
[.note__title]#Note:# Ограничение распространяется только на представление папки – результаты поиска по представлению, результаты полнотекстового поиска и т.п. настройкой не ограничены.
====

По умолчанию в Модуле используется собственное ограничение, которое устанавливает максимальное количество в 15 карточек на страницу представления. Чтобы изменить максимальное количество:

. Откройте конфигурационный файл [.ph]#[.ph .filepath]`[Каталог установки Web-клиента]\5.5\Site\web.config`#.
. Перейдите к элементу [.ph .menucascade]#[.ph .uicontrol]*configuration* > [.ph .uicontrol]*Docsvision* > [.ph .uicontrol]*WebClient* > [.ph .uicontrol]*SettingGroups* > [.ph .uicontrol]*SettingGroup[Name="Views"]* > [.ph .uicontrol]*Setting[Name="DefaultPageSize"]*#.
+
Если данного элемента нет, его нужно создать самостоятельно:

[source,pre,codeblock]
----
<SettingGroup Name="Views">
   <Setting Name="DefaultPageSize" Value="15" />
</SettingGroup>
----
. Укажите в значении `Value` параметра `DefaultPageSize` другое максимальное число карточек.
. Сохраните изменения конфигурационного файла.

Чтобы переключить Модуль на использование ограничений, установленных в свойствах папок (параметр `Ограничение количества выводимых записей`):

. Откройте конфигурационный файл [.ph]#[.ph .filepath]`[Каталог установки Web-клиента]\5.5\Site\web.config`#.
. Перейдите к элементу [.ph .menucascade]#[.ph .uicontrol]*configuration* > [.ph .uicontrol]*Docsvision* > [.ph .uicontrol]*WebClient* > [.ph .uicontrol]*SettingGroups* > [.ph .uicontrol]*SettingGroup[Name="Views"]* > [.ph .uicontrol]*Setting[Name="UseFolderPropertyRestrictionPageSize"]*#.
+
Если данного элемента нет, создайте его самостоятельно следующим образом:

[source,pre,codeblock]
----
<SettingGroup Name="Views">
   <Setting Name="UseFolderPropertyRestrictionPageSize" Value="false" />
</SettingGroup>
----
. Измените значение настройки `UseFolderPropertyRestrictionPageSize`:
* [.keyword]*true* – использовать ограничение, которое установлено в Docsvision;
+
[NOTE]
====
[.note__title]#Note:# Если в настройках папки ограничение не установлено, то в представлении папки будут отображаться все карточки без разбивки на страницы.
====
* [.keyword]*false* (по умолчанию) – использовать собственное ограничение Модуля (настройка `DefaultPageSize`).
. Сохраните изменения конфигурационного файла.

*Parent topic:* xref:../topics/CardsConf.html[Работа с карточками]
