
== Настройка шаблонов для определения типа клиентского устройства

Пользовательский интерфейс Модуля адаптируется под тип клиентского устройства, который определяется по передаваемому веб-браузером клиента https://ru.wikipedia.org/wiki/User_Agent[User Agent]. Если устройство не сопоставляется или некорректно сопоставляется с типом устройства, нужно изменить шаблон, по которому выполняется сопоставление:

. [.ph .cmd]#Откройте конфигурационный файл [.ph]#[.ph .filepath]`[Каталог установки {wc}а]\5.5\Site\web.config`#.#
. [.ph .cmd]#Перейдите к элементу [.ph .menucascade]#[.ph .uicontrol]*configuration* > [.ph .uicontrol]*{dv}* > [.ph .uicontrol]*WebClient* > [.ph .uicontrol]*SettingGroups* > [.ph .uicontrol]*SettingGroup [Name="WebClient"]*#.#
. [.ph .cmd]#Измените значение параметра:#
* `MobileRegExpString` – шаблон определения мобильных устройств нового поколения;
* `MobileRegExpPart2String` – шаблон определения старых мобильных устройств;
* `TabletRegExpString` – шаблон определения планшетов.
+
В значении параметра через символ «|» нужно указать User-Agent соответствующего устройства.
+
Следующая строка демонстрирует пример шаблона, по которому устройство с User-Agent «NEWPAD» будет определяться как планшет.

[source,pre,codeblock]
----
<Setting Name="TabletRegExpString" Value=" … |SM-T355|MediaPad|NEWPAD" />
----
. [.ph .cmd]#Сохраните изменения конфигурационного файла.#

*Parent topic:* xref:CommonConf.adoc[Общие настройки]
