
== Исполнение задания заместителем

Задание поступит заместителю, указанному в [.dfn .term]_Справочнике сотрудников_, если выполнены условия:

* для временного замещения:
** в карточке замещаемого сотрудника пользователь должен быть указан как временный заместитель и являться первым «активным» пользователем в списке временных заместителей;
** состояние замещаемого сотрудника должно быть любым, кроме `Активен`;
** в настройках вида карточки [.dfn .term]_Задание_ должно быть настроено свойство [.keyword]*Автоматически делегировать при неактивности исполнителя* (при этом рядом с полем [.keyword]*Исполнитель* становится доступен признак [.keyword]*Заместителю*);

* для постоянного замещения:
** в карточке замещаемого сотрудника пользователь должен быть указан как постоянный заместитель;
** состояние замещаемого сотрудника должно быть любым, кроме `Активен`.

Чтобы выполнить задание замещаемого сотрудника:

[[task_usp_tvy_f4__steps_zhk_xhj_4j]]
. [.ph .cmd]#Перейдите в папку [.keyword]*Замещение/Входящие*, если являетесь постоянным заместителем; или в папку [.keyword]*Мои задания/Входящие*, если являетесь временным заместителем.#
. [.ph .cmd]#Откройте задание.#
+
Исполнителем задания будет указан замещаемый сотрудник.
. [.ph .cmd]#Выполните задание xref:task_tcard_change_state_finish_performer.html[стандартным образом].#

*На уровень выше:* xref:../topics/WorkWithTask.html[Работа с заданиями]
