
== Отключение возможности создания карточек определенного типа

В случае необходимости, администратор системы может отключить возможность создания из Web-клиента карточек определенного типа. При активации данной функции соответствующий тип (вместе с подвидами) будет скрыт из списка типов карточки, отображаемого при создании новой карточки:

* при нажатии кнопки [.ph .uicontrol]*+ Создать* на панели управления;
* при создании карточки с добавлением ссылки из карточек [.dfn .term]_Документ_ и [.dfn .term]_Задание_.

Чтобы скрыть тип карточки из меню создания:

[[task_dkb_xgz_2x__steps_bjq_r1b_cl]]
. [.ph .cmd]#Откройте конфигурационный файл [.ph]#[.ph .filepath]`[Каталог установки Web-клиента]\5.5\Site\web.config`#.#
. [.ph .cmd]#Перейдите к элементу [.ph .menucascade]#[.ph .uicontrol]*configuration* > [.ph .uicontrol]*Docsvision* > [.ph .uicontrol]*WebClient* > [.ph .uicontrol]*CardTypes* > [.ph .uicontrol]*CardType*#.#
+
В элементе [.dfn .term]_CardTypes_ перечислены типы карточек, с которыми работает [.dfn .term]_Модуль_:

* `[CardTypeId="b9f7bfd7-7429-455e-a3f1-94ffb569c794"]` – Документ;
* `[CardTypeId="c7b36f33-cdd4-4da9-8444-600fe14111e4"]` – Задание;
* `[CardTypeId="2182e2a5-22a9-471f-9d65-e45deeae1c73"]` – Группа заданий.
. [.ph .cmd]#Создайте или измените параметр `DisableCreateFlags` в элементе нужного типа карточек.#
+
Значение параметра `DisableCreateFlags` является суммой цифр, каждая из которых определяет один из вариантов скрытия типа карточки:

* 0 – не скрывать;
* 1 – скрывает тип из списка типов при создании карточки при нажатии кнопки [.ph .uicontrol]*+ Создать* на панели управления;
* 2 – скрывает тип из списка типов при создании карточки с добавлением ссылки из карточек [.dfn .term]_Документ_ и [.dfn .term]_Задание_, а также при создании карточки в качестве отчета к [.dfn .term]_Заданию_;
* 4 – скрывает тип из списка типов при создании связанного задания карточки [.dfn .term]_Документ_;
* 8 – скрывает тип из списка типов при создании подчиненного задания карточки [.dfn .term]_Задание_.

К примеру, чтобы отключить любую возможность создания карточки [.dfn .term]_Документ_ из Web-клиента, нужно в `DisableCreateFlags` строки с `CardType[CardTypeId="b9f7bfd7-7429-455e-a3f1-94ffb569c794"]` указать значение "15" (= 1+2+4+8). Чтобы скрыть тип карточки из списка типов при создании новой карточки по кнопке [.ph .uicontrol]*+ Создать*. укажите "1".
+
[source,pre,codeblock]
----
<configuration>
  <Docsvision>
    <WebClient>
      <CardTypes>
        <CardType CardTypeId="b9f7bfd7-7429-455e-a3f1-94ffb569c794" CssClass="document" SaveInFolder="true"
                  DisableCreateFlags="13" />
        <CardType CardTypeId="c7b36f33-cdd4-4da9-8444-600fe14111e4" />
        <CardType CardTypeId="2182e2a5-22a9-471f-9d65-e45deeae1c73" />
      </CardTypes>
    </WebClient>
  </Docsvision>
</configuration>
----

[NOTE]
====
[.note__title]#Important:# Функциональность флага `DisableCreateFlags` не распространяется на случай, когда меню создания карточки вызывается из настраиваемой разметки.
====
. [.ph .cmd]#Сохраните изменения конфигурационного файла.#

*Parent topic:* xref:../topics/CommonConf.html[Общие настройки]
