
== Синхронизация полей карточки и файла

В Web-клиенте реализована функция автоматической синхронизацииxref:#fntarg_1[^1^] данных карточки и её основного файла, добавленного в xref:Files.html[Список файлов].

Процедура синхронизации зависит от режима синхронизации, установленного для вида документа:

* «Из карточки в файл». При сохранении карточки значения её полей будут записаны в атрибуты файла. До сохранения карточки нужно заполнить синхронизируемые поля и приложить основной файл.
* «Из файла в карточку». При сохранении карточки атрибуты основного файла будут записаны в поля карточки. До сохранения карточки к ней нужно приложить основной файл с заполненными синхронизируемыми атрибутами. Повторно откройте карточку, чтобы посмотреть значения синхронизированных полей.
* «В обе стороны». Синхронизация выполняется при сохранении карточки, если в файле или в карточке есть изменения синхронизируемых полей.

Список синхронизируемых полей выбирается в настройках вида документа.

Синхронизация поддерживается только для основных файлов формата Microsoft Word и Excel. Если основных файлов несколько, синхронизируются данные последнего добавленного/измененного файла.

*На уровень выше:* xref:../topics/WorkWithDocuments.html[Работа с документами]

xref:#fnsrc_1[^1^] Записи значений полей карточки в атрибуты файла и/или наоборот.
