
== Настройка журналирования

События Модуля протоколируются с помощью компонента NLog (http://nlog-project.org). Базовые настройки журналирования представлены в панели управления (xref:ControlPanel_webclient.html[Раздел «WebClient»]). Расширенные настройки осуществляются в конфигурационном файле Модуля.

. [.ph .cmd]#Откройте конфигурационный файл [.ph]#[.ph .filepath]`[Каталог установки Web-клиента]\5.5\Site\web.config`#.#
. [.ph .cmd]#Перейдите к секции [.ph .menucascade]#[.ph .uicontrol]*configuration* > [.ph .uicontrol]*nlog*#.#
. [.ph .cmd]#Измените параметры журналирования.#
+
Измените значение атрибута [.keyword]*fileName* элемента [.ph .menucascade]#[.ph .uicontrol]*targets* > [.ph .uicontrol]*target* > [.ph .uicontrol]*target*#, чтобы настроить путь для сохранения журнала работы. В `fileName` можно использовать допустимые для Nlog переменные (https://github.com/nlog/NLog/wiki/File-target), например: [.ph .filepath]`C:\Logs\$\{level}\WebClient_$\{shortdate}.log`.

Измените значение атрибута [.keyword]*level* элемента [.ph .menucascade]#[.ph .uicontrol]*rules* > [.ph .uicontrol]*logger*#, например, на «trace», чтобы включить протоколирование всех типов событий. Допустимые уровни протоколирования приведены на странице https://github.com/nlog/NLog/wiki/Configuration-file#log-levels.

Для получения дополнительной информации о других настройках NLog обратитесь к документации по данной платформе.
. [.ph .cmd]#Сохраните изменения конфигурационного файла.#
+
[NOTE]
====
[.note__title]#Прим.:#

Уровень журналирования может быть изменён методом /api/Log/SetLogLevel, если пользователь, который вызывает метод, состоит в группе Docsvision Administrators. Методом можно задать следующие уровни: Trace = 0, Debug = 1, Info = 2, Warn = 3, Error = 4 (любое другое значение будет принято как Error).
====

*На уровень выше:* xref:../topics/Logging.html[Настройки протоколирования событий]
