
== Отзыв группы заданий

Права на изменение состояния запущенной на исполнение карточки Группа заданий имеют пользователи с ролями Автор и Ответственный исполнитель.

[NOTE]
====
[.note__title]#Важное замечание:# Отозвать можно только незаблокированные задания. Для выполнения отзыва необходимо, чтобы все задания были закрыты.
====

Чтобы прекратить выполнение группы заданий, выполните следующие действия:

[[task_epf_vtf_wn__steps_zhk_xhj_4j]]
. [.ph .cmd]#Откройте карточку [.dfn .term]_Группа заданий_ её автором.#
. [.ph .cmd]#На xref:CardOperations.adoc[панели операций] нажмите кнопку [.ph .uicontrol]*Отозвать*. Состояние группы заданий и входящих в неё заданий изменится на «Отозвано».#
+
При возврате заданий решения исполнителей сбрасываются, все остальные данные в карточке остаются без изменений (связанные документы остаются в карточке, предыдущие правки карточки остаются доступными в истории, сохраняются комментарии на соответствующей панели).

*На уровень выше:* xref:grtcard_change_state.adoc[Отправка заданий исполнителям и мониторинг исполнения]
