= WebFrame ROOT

_Корень WebFrame_ -- содержит разметки основного окна {wc}а (заголовок, в котором отображается текущая страница; основное меню с деревом папок; и область, в которой отображается содержимое выбранной папки или карточки).


Например, группа локаций _WebFrame_ содержит следующие локации:
** _Главная страница_ -- разметки дашборда;
** _Диалог профиля пользователя_ -- разметки диалогового окно _Профиль_, открываемого из меню пользователя;
** _Компоненты папки_:
*** _Грид_ -- разметки области представления. Используются при включении экспериментальной функции _Новый грид_;
*** _Групповые операции с карточками_ -- разметки панели групповых операций;
*** _Диалог поисковых параметров_ -- разметки диалогового окна атрибутивного поиска;
*** _Панель поиска по столбцам представления_ -- разметки панели настройки фильтра папки;
*** _Папка_ -- разметки области представления;
*** _Последние карточки_ -- разметки страницы _Последние карточки_. _Используются при включении экспериментальной функции _Новый грид__;
*** _Результаты поиска_ -- разметки страницы _Результаты поиска_. _Используются при включении экспериментальной функции _Новый грид__;
** _Корень WebFrame_ -- содержит разметки основного окна {wc}а (заголовок, в котором отображается текущая страница; основное меню с деревом папок; и область, в которой отображается содержимое выбранной папки или карточки).


+
Локация _Корень WebFrame_ содержит две разметки: для полной и мобильной версии {wc}а. Создание и удаление разметок в данной локации запрещено. В разметках допускается только изменение элемента управления [.ph .uicontrol]*barcodeSearchButton*

** _Основное меню_ -- разметки дерева папок;
** _Разметки для элементов управления_:
*** Диалоги операций карточек -- разметки боковой панели, отображаемой при выполнении операции с карточкой:
**** Делегировать -- при делегировании задания;
**** Завершить -- при завершении задания;
**** На доработку -- при возврате задания на доработку;
**** Отклонить -- при отклонении задания;
**** Перенос сроков исполнения -- при переносе сроков исполнения задания;
*** _Поиск карточек для ссылок_ -- разметки окна добавления ссылок карточки;
*** _Создание дочернего задания согласования_ -- разметки панели создания дочернего согласования.