= Переопределение сервиса отрисовки элемента «Ход согласования»

Элемент управления «Ход согласования» представляет собой таблицу, в которой отображаются события заданий согласования (выполнение, делегирование и др.). Описание данного элемента приведено в руководстве пользователя программы «{kvr}».

Программист может переопределить функцию отрисовки всей таблицы и отдельных элементов: заголовков и ячеек определённых столбцов. Для этого нужно передать в поле `stageRenderer` класса элемента управления «Ход согласования» (тип `AgreementHistory`) сервис с интерфейсом `IAgreementHistoryStageRenderer`:

[source,typescript]
----
interface IAgreementHistoryStageRenderer {
    renderStageTable?(props: IApprovalCycleInfoProps): React.ReactNode;
    renderStageHeaderCells?(): React.ReactNode;  
    renderApproverCell?(stageItemProps: IApprovalStageItemRowProps): React.ReactNode; 
    renderDecisionCell?(stageItemProps: IApprovalStageItemRowProps): React.ReactNode;
    renderDateCell?(stageItemProps: IApprovalStageItemRowProps): React.ReactNode;
    renderCommentCell?(stageItemProps: IApprovalStageItemRowProps): React.ReactNode;
    renderCorrectionsCell?(stageItemProps: IApprovalStageItemRowProps): React.ReactNode;
}

----

Интерфейс `IAgreementHistoryStageRenderer` определяет функции, обеспечивающие отрисовку определённых элементов таблицы «Ход согласования»:

* `renderStageTable` – отрисовка всей таблицы;
* `renderStageHeaderCells` – отрисовка заголовков таблицы;
* `renderApproverCell` – отрисовка ячеек столбца «Согласующий»;
* `renderDecisionCell` – отрисовка ячеек столбца «Решение»;
* `renderDateCell` – отрисовка ячеек столбца «Дата»;
* `renderCommentCell` – отрисовка ячеек столбца «Комментарий»;
* `renderCorrectionsCell` – отрисовка ячеек столбца «Правки».

При реализации объекта `IAgreementHistoryStageRenderer` могут быть переопределены все или только требуемые функции интерфейса.

Ниже приведён пример реализации компонента, который переопределяется функцию отрисовки ячеек столбца «Комментарий»: ставит «-», если комментария не было, и текст комментария – если был. Компонент реализуется в виде стандартного link:ClientExtensionsNew.md[клиентского расширения].

Компонент включает две составляющие: сервис, который будет передан в `stageRenderer` и метод, который будет вызываться при открытии вкладки «Ход согласования» карточки ДокументУД/Исходящий, и в котором будет производится передача сервиса в `stageRenderer`.

Ниже приведено содержимое файла `EventHandlers.tsx` (стандартное название основного файла клиентского расширения, создаваемого из шаблона).

[source,typescript]
----
// Импорт зависимостей

import { IAgreementHistoryStageRenderer } from "@{dv}/webclient/Approval/$AgreementHistoryStageRenderer";
import { serviceName } from "@{dv}/webclient/System/ServiceUtils";
import { IApprovalStageItemRowProps } from "@{dv}/webclient/Approval/IApprovalStageItemRowProps";
import { IEventArgs } from "@{dv}/webclient/System/IEventArgs";
import { AgreementHistory } from "@{dv}/webclient/Approval/AgreementHistory";
import { Tab } from "@{dv}/webclient/Platform/Tab";
import { $RequestManager } from "@{dv}/webclient/System/$RequestManager";

import * as React from 'react' 

// Определяется функция, которая будет вызываться при открытии страниц элемента «Вкладки»
export function loadRender(sender: Tab, e: IEventArgs) {
    
    // Следующий код применяется только для страницы с названием «agreementHistoryTabPage»
    if(sender.params.activeTabPage.key == "agreementHistoryTabPage"){
        
        // Получение элемента управления «Ход согласования»
        let agreementHistory = sender.layout.controls.get<AgreementHistory>("agreementHistory");
        
        // Передача сервиса отрисовки (реализация далее) 
        agreementHistory.params.stageRenderer = sender.layout.getService($AgreementHistoryRenderService);
    }
    
} 

// Реализация сервиса отрисовки, наследуемого от IAgreementHistoryStageRenderer
export class AgreementHistoryRenderService implements IAgreementHistoryStageRenderer {
    constructor(private services: $RequestManager) {
    }
    
    // Переопределяется метод отрисовки ячеек столбца «Комментарий» 
    renderCommentCell(stageItemProps: IApprovalStageItemRowProps): React.ReactNode{
   
        	// Если комментарий нет - пишется «-»
            if (!stageItemProps.stageItem.hasComment){
                return (
                <td key="comment"> - </td>
                )
            }

        	// иначе - текст комментария
            return (
            <td key="comment">{stageItemProps.stageItem.comment}</td>
            )
    }
}

// Экспорт сервиса AgreementHistoryRenderService
export type $AgreementHistoryRenderService = { renderService: AgreementHistoryRenderService };
export const $AgreementHistoryRenderService = serviceName((s: $AgreementHistoryRenderService) => s.renderService);

----

____

Инструкция по разработке и регистрации клиентских сервисов приведена в пункте link:ClientExtensionsServices.md[Разработка расширения с клиентским сервисом].

____

В файле `Index.ts` нужно добавить регистрацию сервиса `$AgreementHistoryRenderService`.

[source,typescript]
----
import * as EventHandlers from "./EventHandlers";
import { $AgreementHistoryRenderService, AgreementHistoryRenderService } from "./EventHandlers";
import { Service } from "@{dv}/webclient/System/Service";
import { $RequestManager } from "@{dv}/webclient/System/$RequestManager";
import { extensionManager } from "@{dv}/webclient/System/ExtensionManager";

extensionManager.registerExtension({
    name: "Template web extension",
    version: "5.5.15",
    globalEventHandlers: [ EventHandlers ],
    layoutServices: [
        Service.fromFactory($AgreementHistoryRenderService, (services: $RequestManager) => new AgreementHistoryRenderService(services)) 
    ]
})
----

После загрузки клиентского расширения на сервер {wc}а нужно указать обработчик для переключения страниц элемента «Вкладки» карточки Документ:

. Откройте Конструкторе web-разметок и перейдите к разметке просмотра карточки ДокументУД/Исходящий.
. Перейдите к свойствам элемента «contentTab».
. В событии «После переключения активной вкладки» укажите обработчик «loadRender».
. Сохраните изменения и перезапустите IIS (для загрузки скриптов).

Для проверки примера откройте исходящий документ с согласованием и перейдите на страницу «Ход согласования». В столбце «Комментарий» у событий согласования с комментарием будет указан комментарий, у событий без комментария – знак «-».

____

Для получения других примеров, включая пример получения списка файлов для отображения столбца «Правки», обратитесь к исходным кодам элемента управления «Ход согласования», размещаемым в каталоге установки {wc}а: `C:\Program Files (x86)\{dv}\WebClient\5.5\Site\Content\App\Approval\Controls\AgreementHistory`.

____