= Разработка расширения с локализованными ресурсами

Данный тип расширений предназначен для добавления локализованных строковых ресурсов, которые могут быть использованы в клиентских компонентах элементов управления и скриптах.

Чтобы создать расширение, добавляющее новые обработчики событий, выполните приведенную далее инструкцию.

. Создайте link:ClientExtensionsScript.adoc[проект клиентского расширения] *без публикации*.

. Создайте в папке `src` файл TypeScript (ts, tsx) со следующим содержимым:

[source,typescript]
----
   // Импортируем необходимые сущности из модуля @{dv}/webclient/System/ILocalizationsMap
   import { ILocalizationsMap } from "@{dv}/webclient/System/ILocalizationsMap";
   
   export function getLocalizedResources(): ILocalizationsMap {
       let cultureMap: ILocalizationsMap = {};
       cultureMap["en"] = {
           "Resource_One": "Sample",
           "Resource_Two": "Sample 2"
       };
       cultureMap["ru"] = {
           "Resource_One": "Пример",
           "Resource_Two": "Пример 2"
       };
       return cultureMap;
   }
   ```

   В данном коде выполняется добавление двух ресурсов "Resource_One" и "Resource_Two" для языков русский ("ru") и английский ("en").

   Функция `getLocalizedResources` (можно использовать другое название) возвращает массив добавляемых локализованных ресурсов, в котором каждый элемент соответствует определенной локали. Например, следующий участок кода отвечает за добавление ресурсов для локали "ru" (русский):

   ```tsx
   cultureMap["ru"] = {
    "Resource_One": "Пример",
    "Resource_Two": "Пример 2"
   };
   ```

3. Измените содержимое файла `Index.ts`.

   ```tsx
   // 1. Добавьте строку импорта функции getLocalizedResources из добавленного в 2 файла (в примере -- LocalizedResource)
   import { getLocalizedResources } from "./LocalizedResource";
   import { extensionManager } from "@{dv}/webclient/System/ExtensionManager";
   import { ILocalizationsMap } from "@{dv}/webclient/System/ILocalizationsMap";
   
   // 2. Добавьте в registerExtension функцию getLocalizations, которая должна вызывать импортированную в 1 функцию 
   extensionManager.registerExtension({
       name: "Client extension with localization",
       version: "1.0",
       getLocalizations(): ILocalizationsMap {
           return getLocalizedResources();
       }
   })
   ```

4. Соберите проект клиентского расширения командой `npm run build`.

5. Скопируйте полученный файл `<Каталог сборки>\extension.js` на сервер {wc}а в папку `<Каталог установки {wc}>\5.5\Site\Content\Modules\\<Каталог Решения>`.

   > Обратитесь к разделу [Создание и публикация клиентского расширения](ClientExtensionsNew.md), чтобы получить больше информации, связанной со сборкой проекта.

Получить значение локализованного ресурса в скрипте или клиентской части элемента управления можно из объекта `resources`:

----

resources.Resource_One
```

Проверить работоспособность расширения можно обратившись к `resources.Resource_One` из консоли отладки веб-браузера. Должно быть получено значение "Пример".

После завершения отладки соберите и опубликуйте на сервере {wc}а "релизную версию" клиентского расширения. "Релизная версия" собирается командой `npm run build:prod`.