= Получение сервиса клиентского уровня

Сервисы -- программные объекты с публичными функциями различного назначения и единой точкой доступа. JS API предоставляет сервисы для получения текущего логина пользователя, идентификатора пользователя, состояния полнотекстового поиска, модели со значением элемента управления и др.

Доступ к сервисам предоставляет функция `getService` разметки (тип `Layout`). Функция `getService` принимает тип сервиса, который нужно предоставить. Список сервисов клиентского уровня приведен в справочнике по JS API в разделе "Services".

Следующий код демонстрирует пример получения списка всех операций редактирования, зарегистрированных для карточки, с помощью сервиса `$EditOperationStore`.

[source,tsx]
----
// Метод onMyButtonClick обрабатывает событие нажатия кнопки
export function onMyButtonClick(sender: CustomButton, e: IEventArgs) {
    // Получаем разметку layout из элемента, вызвавшего событие. С помощью метода getService получаем сервис $EditOperationStore
    let editOperationStore = sender.layout.getService($EditOperationStore);

    // Вызываем метод getAll сервиса для получения списка всех операций редактирования
    let editOperations = editOperationStore.getAll();
}
----