= Работа с элементами управления

*Следующая информация относится только к элементам управления, которые работают с моделями объектов.*

Элементы управления являются частью разметки. Ссылка на коллекцию элементов управления разметки содержится в её поле `controls`:

[source,tsx]
----
let layoutControls = someLayout.controls; // someLayout -- разметка

----

Доступ к элементу управления осуществляется по названию, которое ему присвоено в программе {kvr}:

[source,tsx]
----
// Получаем элемент управления Сотрудник (Employee) с названием "registrar" из разметки карточки (layoutManager.cardLayout)
let registrar = layoutManager.cardLayout.controls.get<Employee>("registrar");

----

Доступ к свойствам и значению элемента управления осуществляется через его поле `params`:

[source,tsx]
----
// Получаем значение элемента управления registrar (params.value), из которого получаем отображаемое имя сотрудника (displayName)
let registrarName = registrar.params.value.displayName;

// Изменяем значения свойства Видимость на false (элемент управления будет скрыт)
registrar.params.visibility = false;

----

Изменение значения элемента управления осуществляется через свойство `params.value`. Способ изменения зависит от типа значения:

* для простых типов (string, bool, int и пр.) значение изменяется напрямую:

```tsx
 // Получаем из разметки карточки элемент управления Флажок (CheckBox) с названием "onControl"
 let onControl = layoutManager.cardLayout.controls.get<CheckBox>("onControl");

// Изменяем значения элемента управления на true (флажок будет установлен)
 onControl.params.value = true;
 ```

* для элемента управления Дата/время значение должно быть предварительно сформировано:

```tsx
 // Получаем из разметки карточки элемент управления Дата/время (DateTimePicker) с названием "endDate"
 let endDate = layoutManager.cardLayout.controls.get<DateTimePicker>("endDate");

// Изменяем значения элемента управления на дату 01.03.2019 и время 12:00:00
 endDate.value = new Date("2019-03-01T12:00:00");
 ```

* для элементов управления, работающих с моделями объектов, значение должно быть предварительно сформировано:

```tsx
 // Обратите внимание, функция является асинхронной
 export async function someHandler(sender: CustomButton, e: IEventArgs) {

----
  // Получаем сервис, загружающий модель объекта для элемента управления Подразделение и Подразделение контрагента
  let departmentControllerService = sender.layout.getService($DepartmentController);

  // Получаем модель объекта для подразделения с идентификатором "67E331F0-EF31-4E2C-A1F6-D527606EC8CA" 
  let departmentModel = await departmentControllerService.getStaffDepartment("67E331F0-EF31-4E2C-A1F6-D527606EC8CA");

  // Получаем из разметки карточки элемент управления Подразделение (Department) с названием "department"
  let department = sender.layout.controls.get<Department>("department");

  // Сохраняем в значение элемента управления полученную ранее модель (в элементе управления будет выбрано подразделение
  //  с идентификатором "67E331F0-EF31-4E2C-A1F6-D527606EC8CA"
  department.params.value = await departmentModel;
----

}
 ```

____

Список сервисов генерации моделей объектов приведен в пункте link:ExtraGenModelServices.md[Сервисы генерации моделей объектов].

____

Управление блокировкой элемента управления от изменений осуществляется с помощью параметра _disabled_:

[source,tsx]
----
// получение элемента управления superControl
let control = layoutManager.cardLayout.controls.superControl;

// блокировка элемента управления
control.params.disabled = true
----

Параметр _disabled_ работает совместно с параметром _editOperation_:

* если _disabled_ равен false и _editOperation_ разрешен -- редактирование ЭУ разрешено;
* иначе -- редактирование ЭУ запрещено.

Для отрисовки заблокированного элемента управления вызывается метод `BaseControlImpl.renderDisabledControl`, который может быть переопределён, если требуется собственная реализация отрисовки заблокированного элемента управления.