= Создание и публикация клиентского расширения

Клиентское расширение разрабатывается на языке TypeScript с последующей компиляцией в JavaScript.

.Чтобы создать клиентское расширение:
. Скопируйте к себе в рабочую папку каталог `ProjectTemplates\TemplateWebExtension\` из репозитория WebClient-Samples.
+
. Настройте проект:
+
. Переименуйте папку `TemplateWebExtension` -- укажите название расширения (например, "MyWebExtension").
+
. В файле `MyWebExtension\copy-path.js` измените значения:
+
** `SITE_ROOT` -- укажите относительный путь к папке, в которую будут выгружены файлы, полученные при сборке; для автоматизации процесса публикации файлов на сервере {wc}а можно указать относительный путь к папке {wc}а: `{wcd}/Site`.
** `EXTENSION_NAME` -- укажите название расширения (в данном примере -- "MyWebExtension").
+
. Откройте папку `MyWebExtension` в командной строке и выполните команду: `npm install`.
+
. Создайте в папке `MyWebExtension\src` файл `ts/tsx` с кодом расширения.
+
TIP: Примеры клиентских расширений приведены в следующих пунктах раздела, а также в xref:webClientSamples.adoc[репозитории ДоксВижн].
+
. Измените содержимое файла `src\Index.ts`. В файле должна выполняться регистрация расширения с учетом реализованных в нем функций:

[source,typescript]
----
extensionManager.registerExtension({
    name: "My web Extension",
    version: "1.0",

    getLocalizations: ... , <.>
    controls: ... , <.>
    globalEventHandlers: ... , <.>
    globalServices: ... , <.>
    layoutServices: … <.>

})
----
<.> Расширение добавляет локализованные ресурсы.
<.> Расширение добавляет элементы управления.
<.> Расширение добавляет обработчики событий.
<.> Расширение добавляет публичные сервисы.
<.> Расширение добавляет публичные сервисы, имеющие особое поведение в рамках каждой конкретной разметки.

Описание изменений, которые необходимо выполнить в файле `Index.ts`, приведено в описании примеров расширений, добавляющих обработчики событий, локализованные ресурсы и клиентские компоненты элементов управления.

. Откройте папку `MyWebExtension` в командной строке и выполните команду: `npm run build`.
+
****
Данная команда выполнит компиляцию проекта. В папку, указанную в параметре `SITE_ROOT`, будут выгружены файлы: `extension.js`, `extension.js.map`, `extension.css` и `extension.css.map`. Файлы `.map` используются для отладки кода в браузере.

TIP: Npm может отслеживать изменения в исходных файлах, и при этом самостоятельно выполнять сборку. Выполните команду, чтобы включить режим отслеживания: `npm run watch`.
****
+
. Скопируйте папку `%SITE_ROOT%\Content\Modules\MyWebExtension` в `{wcd}\5.5\Site\Content\Modules`.
+
****
Если в переменной `SITE_ROOT` указан каталог `Site` сервера {wc}а, то копирование будет выполнено автоматически при сборке проекта.

IMPORTANT: После первого копирования файлов нужно перезапустить сервер IIS с приложением {wc}а. При последующих обновлениях содержимого скриптов можно перезапустить IIS или очистить кэш браузера, или вызвать веб-метод `http://&percnt;WebCServer&percnt;/WebClient/Navigator/ResetClientCache` и обновить страницу.
****
+
. После завершения отладки клиентского расширения может быть собрана "релизная версия". Для этого, находясь в командной строке в папке MyWebExtension, выполните команду: `npm run build:prod`.
+
****
Действие данной команды аналогично действию команды `npm run build`, за исключением того, что к полученным файлам будет применена процедура минификации (минимизации). Полученные файлы также необходимо скопировать в папку `{wcd}\5.5\Site\Content\Modules`.

TIP: Информация о загруженных клиентских расширениях отображается в {wc}е в окне "О программе".
****
