= Обработка события сохранения карточки

При сохранении карточки последовательно вызываются события `*Подготовка к сохранению карточки*`, `*Перед сохранением карточки*` и `*При сохранении карточки*` корневого элемента разметки карточки. Данные события могут быть обработаны в пользовательской функции.

Событие `*Перед сохранением карточки*` является прерываемым, т. е. предоставляет возможность отменять сохранение изменений карточки в зависимости от условий:

[source,typescript]
----
function onSaveCard(sender: Layout, e: CancelableEventArgs<ICardSavingEventArgs>) {
    if (CheckPossibility()){ <.>
        e.accept(); <.>
        return;
    }
   
   MessageBox.ShowWarning("Сохранение отклонено");
   e.cancel(); <.>
}
----
<.> Функция CheckPossibility проверяет выполнение неких требований
<.> Подтверждение сохранения. Необязательно.
<.> Отмена сохранения, если условия не выполняются.

TIP: Если при сохранении карточки нужно изменить значение элемента управления разметки (и данное изменение должно быть включено в сохранение), изменение следует применять до сохранения в обработчике события `*Подготовка к сохранению карточки*`.