= Создание и публикация клиентского расширения

Клиентское расширение разрабатывается на языке TypeScript с последующей компиляцией в JavaScript.

Чтобы создать клиентское расширение:

. Скопируйте к себе в рабочую папку каталог `ProjectTemplates\TemplateWebExtension\` из репозитория WebClient-Samples.

. Настройте проект:

. Переименуйте папку `TemplateWebExtension` – укажите название расширения (например, «MyWebExtension»).

. В файле `MyWebExtension\copy-path.js` измените значения:

** «SITE_ROOT» – укажите относительный путь к папке, в которую будут выгружены файлы, полученные при сборке; для автоматизации процесса публикации файлов на сервере Web-клиента можно указать относительный путь к папке Web-клиента: `&lt;Каталог установки Web-клиента&gt;/Site`.
** «EXTENSION_NAME» – укажите название расширения (в данном примере – «MyWebExtension»)
. Откройте папку `MyWebExtension` в командной строке и выполните команду:

`
  npm install
`

. Создайте в папке `MyWebExtension\src` файл ts/tsx с кодом расширения.

Примеры клиентских расширений приведены в следующих пунктах раздела, а также в link:DocsvisionRepOnGitHub.md[репозитории ДоксВижн].

. Измените содержимое файла `src\Index.ts`. В файле должна выполняться регистрация расширения с учетом реализованных в нем функций:

```tsx
 extensionManager.registerExtension({
 name: "My web Extension",
 version: "1.0",

----
   getLocalizations: ... , // расширение добавляет локализованные ресурсы
   controls: ... , // расширение добавляет элементы управления
   globalEventHandlers: ... , // расширение добавляет обработчики событий
   globalServices: ... , // расширение добавляет публичные сервисы
   layoutServices: … // расширение добавляет публичные сервисы, имеющие особое поведение в рамках каждой конкретной разметки
----

})
 ```

Описание изменений, которые необходимо выполнить в файле `Index.ts`, приведено в описании примеров расширений, добавляющих обработчики событий, локализованные ресурсы и клиентские компоненты элементов управления.

. Откройте папку `MyWebExtension` в командной строке и выполните команду:

```bash
 npm run build

```

Данная команда выполнит компиляцию проекта. В папку, указанную в параметре SITE_ROOT, будут выгружены файлы: extension.js, extension.js.map, extension.css и extension.css.map. Файлы .map используются для отладки кода в браузере.

Npm может отслеживать изменения в исходных файлах, и при этом самостоятельно выполнять сборку. Выполните команду, чтобы включить режим отслеживания:

`bash
   npm run watch
`

. Скопируйте папку `{SITE_ROOT}\Content\Modules\MyWebExtension` в `&lt;Каталог установки Web-клиент&gt;\5.5\Site\Content\Modules`.

Если в переменной SITE_ROOT указан каталог Site сервера Web-клиента, то копирование будет выполнено автоматически при сборке проекта.

*После первого копирования файлов нужно перезапустить сервер IIS с приложением Web-клиента. При последующих обновлениях содержимого скриптов можно перезапустить IIS или очистить кэш браузера, или вызвать веб-метод `http://{Адрес Web-клиента}/WebClient/Navigator/ResetClientCache` и обновить страницу.*

. После завершения отладки клиентского расширения может быть собрана «релизная версия». Для этого находясь в командной строке в папке MyWebExtension выполните команду:

`bash
   npm run build:prod
`

Действие данной команды аналогично действию команды npm run build, за исключением того, что к полученным файлам будет применена процедура минификации (минимизации). Полученные файлы также необходимо скопировать в папку `&lt;Каталог установки Web-клиент&gt;\5.5\Site\Content\Modules`.

____

Информация о загруженных клиентских расширениях отображается в Web-клиенте в окне «О программе».

____