= Прерывание выполнения операции

Функция, настроенная для обработки события, возникающего при выполнении операции, позволяет прервать её выполнение, если аргумент события имеет интерфейс `ICancelableEventArgs`. Данный интерфейс определяет два метода: `cancel` -- прерывает выполнение операции; `accept` -- продолжает выполнение операции.

Следующий код демонстрирует пример обработчика события сохранения карточки, прерывающего сохранение, если в названии карточки (cardName) содержится слово «договор».

[source,tsx]
----
// Метод onCardSaving настроен в качестве обработчика события, вызываемого перед сохранением карточки
// Список параметров метода соответствует аргументам события cardSaving класса LayoutParams 
export function onCardSaving(sender: Layout, e: ICancelableEventArgs<ISaveControlData>) {

    let cardName = sender.controls.get<TextBox>("cardName"); // Получение элемента управления с названием карточки

    // Если в названии используется слово «договор», сохранении карточки будет прервано
    if (cardName.params.value.includes("договор")) {
        MessageBox.ShowError("Для оформления договоров используйте вид документа 'Договор'");
        e.cancel(); // Метод cancel прерывает операцию сохранения
    } else {
        e.accept(); // Метод accept продолжает операцию сохранения
    }
}

----

Вызов метода `accept` не является обязательным.

Другой пример демонстрирует использование метода `wait`, который позволяет отложить решение до момента выполнения асинхронной операции (например, запроса к серверу или показа диалога подтверждения).

[source,tsx]
----
export async function onCardSaving(sender: Layout, e: ICancelableEventArgs<ISaveControlData>) {

    // Отменяем автоматический вызов e.accept()
    e.wait();
    try {
        // Показ диалога с ожиданием решения пользователя
        await MessageBox.ShowConfirmation("Вы действительно хотите сохранить карточку?");

        e.accept(); // Разрешаем выполнение операции
    } catch {
        e.cancel(); // Отменяем событие
    }
}
----

Чтобы определить является ли событие прерываемым, обратитесь к его описанию в справочнике по JS API: события возникающие при начале выполнения операции реализуют интерфейс `ICancelableEvent`; после выполнения операции -- `IBasicEvent`.