= Работа с боковой панелью {wc}а

Боковая панель {wc}а -- отображаемая по запросу правая панель, на которую могут быть добавлены требуемые элементы управления. Данный компонент реализован в классе `ModalSidebar` JS-модуля `@{dv}/webclient/Helpers/ModalSidebar/ModalSidebar`.

Следующий код демонстрирует пример использования боковой панели для отображения текущего времени.

[source,typescript]
----
export function showSidebar(sender: CustomButton, e: IEventArgs) { <.>
    let host: ModalHost = new ModalHost("time-dialog", () => {
        return (
            <ModalBackdrop visible={true} onClick={() => host.unmount()} > <.>
            {/* Элемент Боковая панель */}
            <ModalSidebar isOpen={true}>

              {/* button */} <.>
              <ModalSidebarCloseButton onClick={() => host.unmount()} />

             {/* header */} <.>
             <ModalSidebarHeader>Заголовок панели</ModalSidebarHeader>

                {/* contents */} <.>
                <div>Текущее время: {(new Date()).toTimeString()}</div>
                </ModalSidebar>
            </ModalBackdrop>
        );
    });

    host.mount(); <.>

    setInterval(() => host.forceUpdate(), 1000); <.>
}
----
<.> Создаем контейнер для размещения модальных окон, которым является боковая панель.
+
Первый параметр конструктора `ModalHost` -- класс, который будет задан элементу-контейнеру в DOM. Второй параметр -- функция, выполняющая отрисовку модального окна.
+
<.> Элемент `ModalBackdrop` создает темный фон при отображении боковой панели.
+
При клике по элементу `ModalBackdrop` боковая панель будет закрыта.
+
<.> Кнопка для закрытия боковой панели.
<.> Заголовок боковой панели.
<.> Содержимое боковой панели. В данном случае на боковой панели отображается текущее время.
<.> Вызов метода, добавляющего проинициализированный контейнер с боковой панелью в DOM.
<.> Периодически вызываемый метод перерисовки контейнера с боковой панелью. Метод обновляет отображаемое значение текущего времени.
