= Конвертация значения элемента управления

Программист может внедрить в механизм получения значения элемента управления функцию конвертации, которая требуемым образом подготовит данные для использования в клиентском компоненте элемента управления.

Чтобы внедрить функцию конвертации, нужно:

. Указать в описателе свойства Binding название функции конвертации:
* в текстовом описателе -- в атрибуте BindingConverter:

`xml
 &lt;Property Type=&quot;Binding&quot; BindingConverter=&quot;SuperConverter&quot; /&gt;
`

* в бинарном описателе -- в методе GetBindingLoader:

`csharp
 var bindingProperty = PropertyFactory.GetBindingProperty();
 bindingProperty.GetBindingLoader = (() =&gt; new SimpleBindingLoader
 {
     ConverterType = &quot;SuperConverter&quot;
 });
`

. Добавить класс конвертер в link:ServerExtension.md[серверное расширение].

Класс конвертера является производным от `BaseBindingConverter`, в котором переопределяется метод `ConvertForDisplay`. Данный метод должен привести значение элемента управления к требуемому виду.

Следующий код демонстрирует пример класса конвертера, в котором значение элемента управления преобразуется с использованием функции `ConvertForDisplay`.

```csharp
 internal class SuperConverter : BaseBindingConverter
 {
 // В конструктор базового класса должно быть передано название конвертера, которое указано данных свойства
 public SuperConverter(IServiceProvider serviceProvider)
 : base(serviceProvider, "SuperConverter")
 {
 }

----
   // Метод ConvertForDisplay должен возвращать преобразованные данные свойства ЭУ для использования в клиентском расширении ЭУ
   public override BindingResult ConvertForDisplay(ControlContext controlContext, Binding binding, BindingResult bindingResult)
   {
       // Здесь метод SuperMethod требуемым образом преобразует текущее переданное значение ЭУ - bindingResult.Value
       var data = SuperMethod(bindingResult.Value);

       // Метод Clone создает копию bindingResult, в поле Value которой записывается преобразованное значение из data
       return bindingResult.Clone(data);
   }
----

}
 ```

Конвертер вызывается автоматически при загрузке значения элемента управления, при условии совпадения названия конвертера в описателе и в расширении.

При разработке конвертера следует обратить внимание на следующую особенность: в конвертер всегда поступают данные текущей карточки. Если элемент управления связан с данными связанной карточки (не текущей), то получить её данные можно с помощью методов:

* `LayoutContextHelper.TryGetCardDataSource` -- сохраняет в `cardId` идентификатор карточки, с данными которой связан элемент управления;
* `LayoutContextHelper.TryGetDataSource` -- сохраняет идентификаторы метаданных карточки, с которыми связан элемент управления: в `cardId` -- идентификатор карточки, в `sectionId` -- идентификатор секции, в `rowId` -- идентификатор строки.

Пример:

`csharp
   public override BindingResult ConvertForDisplay(ControlContext controlContext, Binding binding, BindingResult bindingResult)
   {
      CardKindModel model = null;
   if (LayoutContextHelper.TryGetCardDataSource(controlContext, binding, out var cardId))
      {
            model = ExSuperMethod(controlContext.LayoutContext.SessionContext, cardId);
      }
      return bindingResult.Clone(model);
   }
`

Конвертер нужно добавить в IoC-контейнер в ядре серверного расширения:

`csharp
   public override void InitializeContainer(ContainerBuilder containerBuilder) {
       containerBuilder.RegisterOrderedType&lt;SuperConverter, IBindingConverter&gt;();
   }
`

Расширение должно быть опубликовано на сервере {wc}а.