= Работа элемента управления с данными карточки

Для того, чтобы элемент управления мог работать с данными карточки, его необходимо определенным образом подготовить:

. Добавьте в описатель элемента управления свойства: «DataSource», «DataField» и «Binding». Первые два свойства предоставляют возможность выбрать в настройках элемента управления секцию (DataSource) и поле карточки (DataField) с данными; свойство «биндинг» (Binding) -- не отображаемое в настройках свойство, с которым значение элемента управления передается в его клиентский компонент.

Элемент управления также может получать данные из карточки, связанной с текущей. Для возможности выбора типа источника (текущая карточки или определенный дополнительный источник) в описатель также нужно добавить свойство «ExtendedDataSource».

Пример:

* Текстовый описатель:
[source,xml]
----
     …
         <Properties>
            …
            <Property Type="DataSource" />
            <Property Type="DataField" />
            <Property Type="Binding" />
            <Property Type="ExtendedDataSource" /> <!-- не обязательно -->
          </Properties>
     ```

   - Бинарный описатель:

     ```csharp
     …
         PropertyDescriptions =
         {
             …
             PropertyFactory.GetDataSourceProperty(),
             PropertyFactory.GetDataFieldProperty(),
             PropertyFactory.GetBindingProperty(),
             PropertyFactory.GetExtendedDataSourceProperty(),
         }
     ```

2. Добавить в клиентский компонент элемента управления в класс параметров поле для хранения значения элемента управления. Тип поля должен соответствовать типу значения элемента управления.

   Пример:

   ```tsx
   export class SomeControlParams extends BaseControlParams {
        @rw value?: string;
   }
   ```

3. Добавить в клиентский компонент элемента управления в интерфейс состояния поле для хранения биндинга. Тип поля должен быть `IBindingResult<string>`. Тип string нужно заменить на тип значения элемента управления.

   Пример:

   ```tsx
   export interface SomeControlState extends SomeControlParams, BaseControlState {
        binding: IBindingResult<string>;
   }
   ```

   Если элемент управления предназначен только для чтения значения (изменять не требуется), свойство `binding` не требуется.

4. Добавить в клиентский компонент элемента управления в интерфейсный класс set-метод, загружающий значение элемента управления. Метод должен быть помечен декоратором @handler("binding").

   Пример:

   ```tsx
   @handler("binding")
   private set binding(binding: IBindingResult<string>) {
       this.state.value =  binding && binding.value;
       this.state.binding = binding; // 
   }
   ```

5. Добавить в клиентский компонент элемента управления в интерфейсный класс метод, возвращающий биндинги.

   Пример:

   ```tsx
   protected getBindings() {
    // "Биндинг" формируется методом getBindingResult, в который нужно передать:
    //  - текущий "биндинг" (из свойства класса, в которое "биндинг" был сохранен при получении с сервера (п. 3))
    //  - текущее значение элемента управления
    //  - поле, в котором содержится ассоциированное с ЭУ название элемента карточки. Переданное значение 
    //     будет записано в историю изменений карточки: "Выполнилась операция "Редактирование". Значение поля 
    //     "{Значение аргумента}" было изменено с "..." на "...".
    return [getBindingResult(this.state.binding, this.params.value, () => at(SomeControlParams).controlTitle)];
   }
   ```

   Метод getBindings должен вернуть IBindingResult, для получения которого вызывается метод getBindingResult, принимающий:

   1. Биндинг, полученный при загрузке элемента управления.
   2. Новое значение элемента управления (в примере, оно хранится в поле this.params.value).
   3. Поле, в котором содержится ассоциированное с элементом управления название элемента карточки. Данное значение используется при формировании истории изменений карточки: "Выполнилась операция "Редактирование". Значение поля "{Значение аргумента}" было изменено с "..." на "...".

6. В класс реализации добавить функцию, сохраняющую значение элемента управления в поле value.

   Пример:

   ```tsx
   changedHandler = (event) => {
    this.state.value = event.target.value;
    this.forceUpdate();
   }
   ```

В составе биндинга может быть передана операция редактирования, настраиваемая в программе {kvr}. Операцию редактирования можно использовать для ограничения возможности изменения значения элемента управления или его скрытия.

Для использования операции редактирования нужно:

1. Добавить в описатель элемента управления свойство EditOperation:

   ```xml
   <Properties>
               <!-- Свойства, перечисленные ранее, также должны быть указаны -->
               <Property Type="DataSource" />
               <Property Type="DataField" />
               <Property Type="Binding" />
   
               <Property Type="EditOperation" /> <!-- Добавляем операцию редактирования -->
           </Properties>
   ```

2. Добавить код проверки операции редактирования в функцию загрузки значения элемента управления (binding):

   ```tsx
   @handler("binding")
   protected set binding(binding: IBindingResult<boolean>) {
       this.state.canEdit = !binding || editOperations.available(binding.editOperation);
   }
   ```

## Проверка прав пользователя на изменение значения

Возможность изменения значения ЭУ (или выполнения других операций) проверяется по доступности пользователю операции редактирования.

Чтобы добавить возможность настраивать для ЭУ операцию редактирования нужно добавить в описатель элемента управления свойство EditOperation.

----

&lt;?xml version="1.0" encoding="utf-8" ?&gt;
<Controls>
 <Control Name="Somecontrol" DisplayName="Somecontrol">
 <Properties>
 <Property Type="Name" />

----
        <!-- Свойства, используемые для связывания ЭУ с данными карточки -->
        <Property Type="DataSource" />
        <Property Type="DataField" />
        <Property Type="Binding" />
        <Property Type="EditOperation" /> <!-- Свойство Операция редактирования -->
    </Properties>
</Control>
----

</Controls>
```

Свойство "Операция редактирования" передается в представительную часть в биндинге, поэтому свойство «Binding» также должно быть в описателе элемента управления.

Чтобы добавить проверку операции редактирования в представительную часть ЭУ, нужно:

. Добавить в «интерфейс состояния» поле, в которое будет сохраняться результат проверки.

. В «интерфейсном классе» в методе, отвечающем за загрузку биндинга, организовать проверку операции редактирования:

`tsx
   @handler(&quot;binding&quot;)
   protected set binding(binding: IBindingResult&lt;boolean&gt;) {
       // Сохраняем результат проверки доступности операции в поле canEdit
       this.state.canEdit = !binding || this.props.services.editOperations.available(binding.editOperation)
   }
`

В приведенном коде проверка доступности операции осуществляется с помощью клиентского сервиса `$EditOperationStore`. Подробности в пункте link:GetServiceOnClient.md[Получение сервисов в клиентском компоненте].