= Формирование текстового описателя элемента управления

. Создайте текстовый файл c расширением xml, кодировкой UTF-8, и содержимым:

```xml
 &lt;?xml version="1.0" encoding="utf-8" ?&gt;
 <Controls>
 <!-- Описатель элемента управления -->
 <Control Name="" DisplayName="" ControlGroupDisplayName="">
 <!-- Свойства элемента управления -->
 <Properties>
 <!-- Здесь перечисляются все свойства элемента управления -->
 <Property Type= ... >
 </Properties>

----
   <!-- События элемента управления -->
   <Events>
      <!-- Здесь перечисляются все события элемента управления --> 
      <Event Name= ... ResourceKey=...>
   </Events>
 </Control>
----

</Controls>
 ```

. Укажите основную информацию об элементе управления в атрибутах элемента Control:
* Name -- название типа элемента управления -- английский, без спецсимволов и пробелов;
* DisplayName -- отображаемое в программе {kvr} название элемента управления. Если нужно использовать локализованное название, замените атрибут DisplayName на ResourceKey, и укажите в значении название локализованного ресурса. Добавить локализованные ресурсы можно с помощью предназначенного для этого xref:LayoutDesignerExtensionWithResources.adoc[расширения программы {kvr}];
* ControlGroupDisplayName -- название группы, в которой будет отображаться элемент управления на панели Библиотека. Можно указать название существующей группы или новой группы. Если нужно использовать локализованное название, замените атрибут ControlGroupDisplayName на ControlGroupResourceKey, и укажите в значении название локализованного ресурса.

Следующие атрибуты являются необязательными:

* AllowedOperations -- название xref:LayoutDesignerExtensionWithAllowedOperations.adoc[функции проверки].
. Перечислите свойства элемента управления в элементе Properties.

Свойства обеспечивают возможность настройки элемента управления в программе {kvr}, и передаются в клиент при загрузке.

. Добавьте дочерний элемент Property.

. Укажите информацию о свойстве в аргументах элемента Property:

** Type -- название типа свойства, зарегистрированного в программе {kvr}. Типы стандартных свойств перечислены в пункте xref:StandartPropertiesOfControls.adoc[Стандартные свойства и события элементов управления].
** DefaultValue -- значение по умолчанию (необязательное).
. Перечислите события элемента управления в элементе Events.

. Добавьте дочерний элемент Event.

. Укажите информацию о событии в аргументах элемента Event:
** Name -- название события. Названия стандартных событий перечислены в пункте xref:StandartPropertiesOfControls.adoc[Стандартные свойства и события элементов управления].
** DisplayName -- отображаемое название события. Если нужно использовать локализованное название, замените атрибут DisplayName на ResourceKey, и укажите в значении название локализованного ресурса.
** DefaultValue -- обработчик по умолчанию (необязательное).
. Сохраните файл XML на сервер {wc}а в папку `{wcd}\Plugins\%Каталог Решения%`.

. Перезапустите {kvr}.