= Формирование и публикация описателя элемента управления

Описатель элемента управления -- программный компонент, содержащий общую информацию об элементе управления, и список его свойств (настроек, которые можно изменять в программе {kvr}).

Описатель элемента управления может быть сформирован двумя способами:

. В виде функции link:LayoutDesignerExtension.adoc[расширения программы {kvr}].
. В виде файла XML.

Для простоты первый вариант описателя будем называть бинарным описателем элемента управления, второй -- текстовым описателем.

Основное отличие: текстовый описатель можно составить с применением уже зарегистрированных редакторов, свойств (пример исключения приведен в пункте link:CreateTextControlDescriptor.adoc[Формирование текстового описателя элемента управления]) и функций проверки, а для бинарного описателя -- недостающие элементы можно включить в расширение программы {kvr}, в котором реализуется описатель. В остальном, выбор способа формирования описателя определяется предпочтениями программиста.