= С чего начать

== Подготовка

. Подготовьте среду разработки.

На компьютере разработчика должны быть установлены:

* Microsoft Visual Studio 2017/2019;
* https://code.visualstudio.com/[Visual Studio Code];
* https://nodejs.org/en/[NodeJS v12.16.1 (LTS) или выше];
* TypeScript 3.8.
. Загрузите на компьютер link:{dv}RepOnGitHub.md[репозиторий WebClient-Samples].

. Установите шаблоны проектов из полученного репозитория:

* «TemplateDesignerExtension» – шаблон проекта для разработки расширения Конструктора web-разметок;
* «TemplateServerExtension» – шаблон проекта для разработки серверного расширения.

Для установки шаблонов:

. Скопируйте из папки `ProjectTemplates\VSTemplates\` репозитория в каталог шаблонов проектов Visual Studio (`C:\Users\\&lt;Имя пользователя&gt;\Documents\Visual Studio &lt;Версия&gt;\Templates\ProjectTemplates\Visual C#\`) файлы `TemplateDesignerExtension.zip` и `TemplateServerExtension.zip`.
. Запустите Visual Studio. Будут добавлены новые типы проектов: «TemplateDesignerExtension» и «TemplateServerExtension».

== Что дальше

. Определите цель разработки.

{wc} имеет несколько точек расширения функциональных возможностей.

Программист может разработать:

* Серверное расширение, добавляющее методы WebAPI, для вызова с клиентского уровня. Серверные методы могут быть использованы для взаимодействия с сервером {dv}: создание карточек, запуск БП и т. д.
* Новый тип элементов управления для создания разметок. Данный тип расширения включает два компонента: расширение Конструктора web-разметок (обеспечивает возможность настройки разметки с использованием ЭУ) и клиентское расширение (обеспечивает функционирование ЭУ на клиентской стороне).
* Клиентский скрипт, содержащий обработчики событий разметки. Данные скрипты могут добавлять в {wc} необходимую бизнес-логику или обеспечивать другие функции клиентского уровня.
* Клиентское расширение – общее название компонентов, обеспечивающих функциональность клиентского уровня. К клиентским расширениями относятся компоненты элементов управления, обеспечивающих их функционирование на стороне клиента, клиентские скрипты, библиотеки JavaScript, добавляющие необходимую клиентскую функциональность.
. Ознакомьтесь с инструкцией по разработке требуемого типа компонента {wc}а в данном документе.

. Ознакомьтесь с предоставляемыми примерами.