= Руководство по разработке

Данная глава посвящена разработке программных компонентов для решений на базе {wc}а.

Глава содержит инструкцию по разработке серверных и клиентских расширений {wc}а, клиентских скриптов, расширений программы {kvr}, рассмотрены этапы разработки элементов управления.

В заключении главы приведены справочные сведения, касающиеся разработки на базе {wc}а.

Данный документ является руководством программиста модуля "{dv} 5. {wc}" (далее -- {wc}, Модуль).
Руководство содержит инструкции по разработке дополнительных компонентов {wc}а, комментарии к исходным кодам предоставляемых примеров дополнительных компонентов, описания членов объектной модели Модуля, задействованных при разработке компонентов, а также другую информацию, связанную с разработкой Решений.

Руководство предназначено для специалистов, обладающих знаниями в области веб-разработки, знакомым с разработкой компонентов на ReactJS, обладающих опытом разработки на платформе {dv} 5.

____

Обратите внимание. При обращении к API, методы следует вызывать последовательно, один за другим. Параллельный вызов методов API не гарантирует их работу.

____