= Сервисы получения моделей объектов

Следующие сервисы предназначены для получения на клиенте моделей объектов для программного изменения значений элементов управления.

* `$DirectoryDesignerRowController` -- предоставляет методы для получения объектов Конструктора справочников:
* `getDirectoryDesignerRow(rowId: string)` -- получает объект Строка справочника для строки с идентификатором rowId;
* `getDirectoryDesignerRows(rows: GenModels.CollectionRequestModelOf&lt;string&gt;)` -- получает объекты Строка справочника для строк с идентификаторами rows;
* `$CardKindController` -- предоставляет методы для получения объектов Справочника видов карточек:
* `getCardKind(cardKindId: string)` -- получает объект Вид карточки для вида с идентификатором cardKindId;
* `getCardKinds(cardKinds: GenModels.CollectionRequestModelOf&lt;string&gt;)` -- получает объекты Вид карточки для видов с идентификаторами cardKinds;
* `$DepartmentController` -- предоставляет методы для получения объектов Справочника сотрудников и Справочника контрагентов:
* `getStaffDepartment(departmentId: string)` -- получает объект Подразделение для подразделения с идентификатором departmentId;
* `getPartnerDepartment(departmentId: string)` -- получает объект Подразделение контрагента для подразделения с идентификатором departmentId;
* `getStaffDepartments(departments: GenModels.CollectionRequestModelOf&lt;string&gt;)` -- получает объекты Подразделение для подразделений с идентификаторами departments;
* `getPartnerDepartments(departments: GenModels.CollectionRequestModelOf&lt;string&gt;)` -- получает объекты Подразделение контрагента для подразделений с идентификаторами departments;
* `$EmployeeController` -- предоставляет методы для получения объектов Справочника сотрудников:
* `getEmployee(employeeId: string, options?: RequestOptions)` -- получает объект Сотрудник для сотрудника с идентификатором employeeId;
* `getEmployees(employees: GenModels.CollectionRequestModelOf&lt;string&gt;, options?: RequestOptions)` -- получает объекты Сотрудник для сотрудников с идентификаторами employees;
* `$PartnerEmployeeController` -- предоставляет методы для получения объектов Справочника контрагентов:
* `getPartnerEmployee(employeeId: string, options?: RequestOptions)` -- получает объект Сотрудник контрагента для сотрудника с идентификатором employeeId;
* `getPartnerEmployees(employees: GenModels.CollectionRequestModel, options?: RequestOptions)` -- получает объекты Сотрудник контрагента для сотрудников с идентификаторами employees.

Следующий код демонстрирует пример получения объекта Подразделение с идентификатором «6832216B-FED9-4D20-B1D4-0097C73D446E» с помощью сервиса ​`$DepartmentController`.

[source,tsx]
----
export function superHandler(sender: CustomButton, e: IEventArgs) {
    let departmentControllerService = sender.layout.getService($DepartmentController);
    let departmentModel = departmentControllerService.getStaffDepartment("6832216B-FED9-4D20-B1D4-0097C73D446E");
}
----

____

Подробное описание сервисов приведено в link:HowUseDocJsApi.md[справочнике по JS API].

____