= Особенности реализации скриптов на JavaScript

Клиентские компоненты {wc}а, предоставляющие общедоступные сущности, являются модулями JavaScript, которые реализованы в формате CommonJS. Также поддерживаются другие ES5-совместимые форматы: AMD, System или UMD. Описание форматов модулей приведено здесь.

Пользовательские модули, а также некоторые системные модули, загружаются из папки `{wcd}\Site\Content\Modules`.

Модули обрабатываются библиотекой SystemJS следующим образом:

. Перед загрузкой модуля просматривается его код при помощи регулярных выражений, и обнаруживаются все вызовы метода require.
. Все запрашиваемые модули динамически загружаются, после чего выполняется код самого модуля. При этом, поскольку все необходимые модули уже были загружены, функция `require` сразу возвращает запрашиваемый модуль.

SystemJS автоматически пытается определить, какой формат модуля используется в скрипте (AMD, CommonJS, System) при помощи регулярных выражений. В случае, если формат определяется неверно (например, из-за наличия соответствующих комментариев в коде), он может быть указан вручную. Для этого создайте в папке `{wcd}\Site\Content\ModulesMeta` файл JavaScript с произвольным названием и следующим содержимым:

[source,javascript]
----
System.config({
  meta: {
   "Content/Modules/MyWebExtension/*":{ <.>
       format: 'cjs' <.>
    }
  }
});
----
<.> Точный путь к папке с файлами своих скриптов.
<.> Формат модуля: `cjs` -- CommonJS, `amd` -- AMD, `register` -- System.

NOTE: Описание формата конфигурационного файла приведено в https://github.com/systemjs/systemjs/blob/0.19/docs/config-api.adoc[документации к SystemJS].
