= Создание и публикация расширения Конструктора web-разметок

Серверное расширение представляет собой библиотеку DLL, разработанную на платформе .NET.

Чтобы создать расширение Конструктора web-разметок:

. Создайте в Visual Studio новый проект с типом TemplateDesignerExtension.

. Обновите в проекте ссылки на зависимости.

Версии подключаемых компонентов должны соответствовать версиям компонентов, используемых сервером Web-клиента, для которого разрабатывается расширение.

. Реализуйте в проекте функции расширения Конструктора web-разметок.

Примеры кода расширений Конструктора web-разметок приведены в следующих пунктах раздела, а также в link:HowUseDocJsApi.md[репозитории ДоксВижн].

. Настройте ядро расширения.

Ядром расширения является класс, производный от `WebLayoutsDesignerExtension`, который содержится в файле `Extension/TemplateDesignerExtension.cs`.

```csharp
 class TemplateDesignerExtension : WebLayoutsDesignerExtension
 {
 public TemplateDesignerExtension(IServiceProvider provider)
 : base(provider)
 {
 }

----
   // Метод регистрации новых типов элементов управления
   protected override List<ControlTypeDescription> GetControlTypeDescriptions()
   {
       return new List<ControlTypeDescription>
       {
       };
   }

   // Метод регистрации новых свойств элементов управления
   protected override Dictionary<string, PropertyDescription> GetPropertyDescriptions()
   {
       return new Dictionary<string, PropertyDescription>
       {
       };
   }

   // Метод регистрации локализованных ресурсов
   protected override List<ResourceManager> GetResourceManagers()
   {
       return new List<ResourceManager>
       {
         Resources.ResourceManager
       };
   }
----

}
 ```

. Скомпилируйте проект.

В результате будет получен файл DLL с ядром расширения Конструктора web-разметок и реализуемыми функциями, а также файлы DLL с локализованными ресурсами.

. Скопируйте файл расширения на сервер Web-клиента в папку `&lt;Каталог установки Web-клиента&gt;\Plugins\\&lt;Каталог Решения&gt;`. Каталог Решения необходимо создать самостоятельно. Ресурсные сборки нужно скопировать в папки `&lt;Каталог установки Web-клиента&gt;\ru\` (для русской локализации), `&lt;Каталог установки Web-клиента&gt;\uk\` (для английской локализации) и т.д.

. Перезапустите Конструктор web-разметок.