= Ограничение прав на использование элементом управления в программе {kvr}

Программист может установить запрет на выполнение определенных действий с элементом управления в программе {kvr}.

Ограничение устанавливается "функцией проверки", которая возвращает набор флагов, разрешающих только определенные действия с элементом управления. Например, _функция проверки_ может ограничить использование элемента управления определенным типом карточек.

Чтобы создать расширение, добавляющее функцию проверки, выполните приведенную далее инструкцию.

. xref:layoutDesignerExtensionsCreatePublish.adoc[Создайте проект расширения программы {kvr}].

. Добавьте в ядро расширения (файл TemplateDesignerExtension.cs) функцию проверки следующего вида:

[source,csharp]
----
 public static AllowedOperationsFlag GetPossibleOperation(IServiceProvider serviceProvider)
 {
 // По умолчанию доступны все операции
 var flags = AllowedOperationsFlag.All;

----
   return flags;
----

}
 ```

Функция проверки должна вернуть набор флагов xref:Platform_Tools_LayoutEditor_ObjectModel_Descriptions_AllowedOperationsFlag.adoc[AllowedOperationsFlag].

. Добавьте в код функции проверки алгоритм, добавляющий нужные ограничения.

Следующий код демонстрирует пример функции проверки, запрещающей добавление элемента управления в разметку карточки, если тип карточки не Документ.

[source,csharp]
----
 public static AllowedOperationsFlag GetPossibleOperation(IServiceProvider serviceProvider)
 {
 // По умолчанию доступны все операции
 var flags = AllowedOperationsFlag.All;

----
   // Получение сервиса для работы с разметкой
   var selectedLayoutService = ServiceUtil.GetService<ISelectedLayoutService>(serviceProvider);

   // Из сервиса получаем идентификатор типа карточек, для которых настраивается разметка.
   // Если тип карточки не документ (CardDocument.ID) из возможных операций удаляется флаг Create
   //  что фактически приводит к невозможности добавить элемент управления в разметку
   if (selectedLayoutService.SelectedCardTypeId != {dv}.BackOffice.CardLib.CardDefs.CardDocument.ID)
       flags &= ~AllowedOperationsFlag.Create;

   return flags;
----

}
 ```

В примере информация о контексте использования элемента управления предоставляется сервисом xref:Platform_Tools_LayoutEditor_Infrostructure_ISelectedLayoutService.adoc[ISelectedLayoutService].

. Переопределите метод GetAllowedOperations базового класса расширения, чтобы он возвращал коллекцию с парой: ключ -- имя, по которому можно получить данную функцию проверки; значение -- функция проверки:

[source,charp]
----
   protected override Dictionary<string, Func<AllowedOperationsFlag>> GetAllowedOperations()
   {
       return new Dictionary<string, Func<AllowedOperationsFlag>>
       {
           // Обратите внимание, что в функцию передается сервис-провайдер расширения
           {"GetPossibleOperation", () => GetPossibleOperation(this.serviceProvider) }
       };
   }
`

. Скомпилируйте проект и скопируйте полученную сборку на сервер {wc}а в папку `{wcd}\Plugins\%Каталог Решения%`. Ресурсные сборки скопируйте в папки `{wcd}\ru\` (для русской локализации), `{wcd}\uk\` (для английской локализации) и т.д.

. Перезапустите {kvr}.

== Проверка примера

. xref:layoutDesignerExtensionsAddNewControl.adoc[Создайте проект нового элемента управления].

. В поле GetAllowedOperations (функция проверки) описателя элемента управления укажите функцию GetPossibleOperation.

[source,csharp]
----
 ControlTypeDescription GetSuperControlTypeDescription()
 {
 var controlTypeDescription = new ControlTypeDescription("SuperControl")
 {
 DisplayName = "Супер элемент управления",
 ControlGroupDisplayName = "Примеры",
 PropertyDescriptions = {
 PropertyFactory.GetNameProperty (),
 PropertyFactory.GetVisibilityProperty (),
 PropertyFactory.GetClickEvent ()
 },
 GetAllowedOperations = () => GetPossibleOperation(serviceProvider) // Передаем функцию проверки
 };

----
   return controlTypeDescription;
----

}

```

Функция проверки также может быть получена по имени из хранилища функций проверки:

[source,csharp]
----
 GetAllowedOperations = AllowedOperationsStorage.GetAllowedOperations("GetPossibleOperation")

```

Код получения хранилища функций проверки:

[source,charp]
----
   IAllowedOperationsStorage allowedOperationsStorage;
   protected IAllowedOperationsStorage AllowedOperationsStorage
   {
       get
       {
           return this.allowedOperationsStorage ?? (this.allowedOperationsStorage = ServiceUtil.GetService<IAllowedOperationsStorage>(serviceProvider));
       }
   }
`

. Опубликуйте расширение с элементом управления на сервере {wc}а.

. Откройте для настройки разметку карточки Документ -- элемент управления "Супер элемент управления" представлен в библиотеке элементов управления; откройте любую другую разметку -- элемент управления "Супер элемент управления" отсутствует в библиотеке элементов управления.