= Расширение возможностей Конструктора web-разметок

Конструктор web-разметок предоставляет возможность дополнять собственные функциональные возможности с помощью расширений.

Расширение Конструктора web-разметок может добавлять:

* типы элементов управления,
* свойства (настройки) элементов управления,
* редакторы для свойств элементов управления,
* функции проверки доступности операций,
* критерии для условий выбора разметок,
* локализованные ресурсы.

== Разработка расширения Конструктора web-разметок

Процесс разработки расширения Конструктора web-разметок может включать следующие шаги:

. Создание в Visual Studio проекта типа TemplateDesignerExtension.

. При необходимости, обновление ссылок на подключаемые компоненты.

Версии подключаемых компонентов в проекте должны соответствовать версиям компонентов, используемых Конструктором web-разметок, для которого разрабатывается расширение. При обновлении версии Web-клиента все разработанные компоненты должны быть скомпилированы повторно с использованием новых версий библиотек Web-клиента.

. Разработка ядра расширения Конструктора web-разметок.

Ядро расширения Конструктора web-разметок представляет собой производный от `WebLayoutsDesignerExtension` класс. В нём переопределяются методы получения описателей типов элементов управления, описателей типов свойств элементов управления, редакторов значений свойств и пр., в зависимости от назначения расширения Конструктора web-разметок.

При создании проекта из шаблона TemplateDesignerExtension ядро расширения Конструктора web-разметок будет содержаться в файле `Extension\TemplateDesignerExtension.cs`.

Примеры реализации отдельных элементов ядра расширения Конструктора web-разметок рассмотрены в следующих разделах.

. Компиляция проекта.

В результате будет получен файл DLL – расширение Конструктора web-разметок, а также файлы DLL с локализованными ресурсами.

== Публикация расширения Конструктора web-разметок

Последовательность публикации расширения Конструктора web-разметок на сервере Web-клиента включает следующие шаги: 

. Создание каталога для Решения на сервере Web-клиента: `[Каталог установки Web-клиента]\Plugins\[Каталог Решения]`.
. Копирование сборки расширения Конструктора web-разметок в `[Каталог Решения]`. Файлы DLL с локализованными ресурсами копируются в существующие в каталоге `[Каталог установки Web-клиента]\ru\` (для русской локализации), `[Каталог установки Web-клиента]\uk\` (для английской локализации) и т.д.

Реализованная в расширении Конструктора web-разметок функциональность будет доступна после запуска Конструктора web-разметок.