= Добавление локализованных ресурсов

В строковых переменных расширения программы {kvr} (отображаемые названия свойств, диалоги) можно использовать локализованные ресурсы, добавляемые расширением.

Чтобы создать расширение, добавляющее новые локализованные ресурсы, выполните приведенную далее инструкцию.

. link:LayoutDesignerExtensionNew.adoc[Создайте проект расширения программы {kvr}].

. Добавьте в проект расширения ресурсные файлы (для английского, русского и др. языков), содержащие требуемые локализованные ресурсы. 

Проект расширения, формируемый из шаблона "TemplateDesignerExtension", содержит ресурсные файлы, которые можно использовать для формирования локализованных ресурсов.

. Переопределите метод GetResourceManagers базового класса расширения, чтобы он предоставлял менеджер ресурсов для добавленных ресурсных файлов:

`csharp
   protected override List&lt;ResourceManager&gt; GetResourceManagers()
   {
       return new List&lt;ResourceManager&gt;
       {
           Resources.ResourceManager
       };
   }
`

. Скомпилируйте проект и скопируйте полученную сборку на сервер {wc}а в папку `&lt;Каталог установки {wc}а&gt;\Plugins\\&lt;Каталог Решения&gt;`. Ресурсные сборки скопируйте в папки `&lt;Каталог установки {wc}а&gt;\ru\` (для русской локализации), `&lt;Каталог установки {wc}а&gt;\uk\` (для английской локализации) и т.д.