= Ограничение прав на использование элементом управления в Конструкторе web-разметок

Программист может установить запрет на выполнение определенных действий с элементом управления в Конструкторе web-разметок.

Ограничение устанавливается «функцией проверки», которая возвращает набор флагов, разрешающих только определенные действия с элементом управления. Например, _функция проверки_ может ограничить использование элемента управления определенным типом карточек.

Чтобы создать расширение, добавляющее функцию проверки, выполните приведенную далее инструкцию.

. link:LayoutDesignerExtensionNew.md[Создайте проект расширения Конструктора web-разметок].

. Добавьте в ядро расширения (файл TemplateDesignerExtension.cs) функцию проверки следующего вида:

```csharp
 public static AllowedOperationsFlag GetPossibleOperation(IServiceProvider serviceProvider)
 {
 // По умолчанию доступны все операции
 var flags = AllowedOperationsFlag.All;

----
   return flags;
----

}
 ```

Функция проверки должна вернуть набор флагов link:Platform_Tools_LayoutEditor_ObjectModel_Descriptions_AllowedOperationsFlag.md[AllowedOperationsFlag].

. Добавьте в код функции проверки алгоритм, добавляющий нужные ограничения.

Следующий код демонстрирует пример функции проверки, запрещающей добавление элемента управления в разметку карточки, если тип карточки не Документ.

```csharp
 public static AllowedOperationsFlag GetPossibleOperation(IServiceProvider serviceProvider)
 {
 // По умолчанию доступны все операции
 var flags = AllowedOperationsFlag.All;

----
   // Получение сервиса для работы с разметкой
   var selectedLayoutService = ServiceUtil.GetService<ISelectedLayoutService>(serviceProvider);

   // Из сервиса получаем идентификатор типа карточек, для которых настраивается разметка.
   // Если тип карточки не документ (CardDocument.ID) из возможных операций удаляется флаг Create
   //  что фактически приводит к невозможности добавить элемент управления в разметку
   if (selectedLayoutService.SelectedCardTypeId != DocsVision.BackOffice.CardLib.CardDefs.CardDocument.ID)
       flags &= ~AllowedOperationsFlag.Create;

   return flags;
----

}
 ```

В примере информация о контексте использования элемента управления предоставляется сервисом link:Platform_Tools_LayoutEditor_Infrostructure_ISelectedLayoutService.md[ISelectedLayoutService].

. Переопределите метод GetAllowedOperations базового класса расширения, чтобы он возвращал коллекцию с парой: ключ – имя, по которому можно получить данную функцию проверки; значение – функция проверки:

`csharp
   protected override Dictionary&lt;string, Func&lt;AllowedOperationsFlag&gt;&gt; GetAllowedOperations()
   {
       return new Dictionary&lt;string, Func&lt;AllowedOperationsFlag&gt;&gt;
       {
           // Обратите внимание, что в функцию передается сервис-провайдер расширения
           {&quot;GetPossibleOperation&quot;, () =&gt; GetPossibleOperation(this.serviceProvider) }
       };
   }
`

. Скомпилируйте проект и скопируйте полученную сборку на сервер Web-клиента в папку `&lt;Каталог установки Web-клиента&gt;\Plugins\\&lt;Каталог Решения&gt;`. Ресурсные сборки скопируйте в папки `&lt;Каталог установки Web-клиента&gt;\ru\` (для русской локализации), `&lt;Каталог установки Web-клиента&gt;\uk\` (для английской локализации) и т.д.

. Перезапустите Конструктор web-разметок.

== Проверка примера

. link:LayoutDesignerExtensionWithControlType.md[Создайте проект нового элемента управления].

. В поле GetAllowedOperations (функция проверки) описателя элемента управления укажите функцию GetPossibleOperation.

```csharp
 ControlTypeDescription GetSuperControlTypeDescription()
 {
 var controlTypeDescription = new ControlTypeDescription("SuperControl")
 {
 DisplayName = "Супер элемент управления",
 ControlGroupDisplayName = "Примеры",
 PropertyDescriptions = {
 PropertyFactory.GetNameProperty (),
 PropertyFactory.GetVisibilityProperty (),
 PropertyFactory.GetClickEvent ()
 },
 GetAllowedOperations = () =&gt; GetPossibleOperation(serviceProvider) // Передаем функцию проверки
 };

----
   return controlTypeDescription;
----

}

```

Функция проверки также может быть получена по имени из хранилища функций проверки:

```csharp
 GetAllowedOperations = AllowedOperationsStorage.GetAllowedOperations("GetPossibleOperation")

```

Код получения хранилища функций проверки:

`csharp
   IAllowedOperationsStorage allowedOperationsStorage;
   protected IAllowedOperationsStorage AllowedOperationsStorage
   {
       get
       {
           return this.allowedOperationsStorage ?? (this.allowedOperationsStorage = ServiceUtil.GetService&lt;IAllowedOperationsStorage&gt;(serviceProvider));
       }
   }
`

. Опубликуйте расширение с элементом управления на сервере Web-клиента.

. Откройте для настройки разметку карточки Документ – элемент управления «Супер элемент управления» представлен в библиотеке элементов управления; откройте любую другую разметку – элемент управления «Супер элемент управления» отсутствует в библиотеке элементов управления.