= Пример. Элемент управления для выбора из справочника "Делопроизводство 5"

В данном пункте рассмотрено создание элемента управления для выбора дела из Справочника номенклатуры дел 5 (приложение _{dv} 5. Делопроизводство 5_).

.В примере рассмотрены следующие вопросы разработки элементов управления:
* Создание расширения программы {kvr}, решающего следующие задачи:
** Ограничение выбора поля карточки со значением элемента управления -- поле должно содержать ссылку на строку _Справочника номенклатуры дел 5_.
** Возможность ограничить для пользователя область выбора дел -- настройки элемента управления должны содержать параметр для выбора _Раздела_, из которого можно выбирать дела.
* Создание серверного расширения {wc}, который должен предоставлять:
** Сервис для работы с данными Справочника номенклатуры дел 5 (с использованием базового API {dv}).
** Конвертер значений, возвращающий отображаемое значение элемента управления.
* Создание клиентского расширения с несколькими функциями:
** Реализация пользовательского интерфейса, одним из элементов которого должно быть дерево разделов Справочника номенклатуры дел 5.
** Реализация функции ограничения выбора дел из раздела Справочника номенклатуры дел 5, указанного в программе {kvr}.
** Предоставление возможности быстрого поиска дел.

NOTE: Полный исходный код примера приведён в репозитории {dv} Samples на GitHub, проект `Controls/RefCases`.
