= Формирование текстового описателя элемента управления

. Создайте текстовый файл c расширением `.xml`, кодировкой `UTF-8`, и содержимым:
+
[source,xml]
----
<?xml version="1.0" encoding="utf-8" ?>
<Controls>
  <Control Name="" DisplayName="" ControlGroupDisplayName=""> <.>
    <Properties> <.>
       <Property Type="" > <.>
    </Properties>

    <Events> <.>
       <Event Name="" ResourceKey=""> <.>
    </Events>
  </Control>
</Controls>
----
<.> Описатель элемента управления.
<.> Свойства элемента управления.
<.> Здесь перечисляются все свойства элемента управления.
<.> События элемента управления.
<.> Здесь перечисляются все события элемента управления.
+
. Укажите основную информацию об элементе управления в атрибутах элемента `Control`.
+
****
Name::
Название типа элемента управления -- английский, без спецсимволов и пробелов.
DisplayName::
Отображаемое в программе {kvr} название элемента управления. Если нужно использовать локализованное название, замените атрибут `DisplayName` на `ResourceKey`, и укажите в значении название локализованного ресурса.
+
Добавить локализованные ресурсы можно с помощью предназначенного для этого xref:layoutDesignerExtensionsAddLocalizedResources.adoc[расширения программы {kvr}].
+
ControlGroupDisplayName::
Название группы, в которой будет отображаться элемент управления на панели _Библиотека_. Можно указать название существующей группы или новой группы.
+
Если нужно использовать локализованное название, замените атрибут `ControlGroupDisplayName` на `ControlGroupResourceKey`, и укажите в значении название локализованного ресурса.
AllowedOperations::
Название xref:layoutDesignerExtensionsLimitControlUse.adoc[функции проверки]. Необязательный атрибут.
****
+
. Перечислите свойства элемента управления в элементе `Properties`.
+
Свойства обеспечивают возможность настройки элемента управления в программе {kvr}, и передаются в клиент при загрузке.
+
. Добавьте дочерний элемент `Property`.
+
. Укажите информацию о свойстве в аргументах элемента `Property`.
+
****
Type::
Название типа свойства, зарегистрированного в программе {kvr}.
+
Типы стандартных свойств перечислены в пункте xref:StandartPropertiesOfControls.adoc[Стандартные свойства и события элементов управления].
+
DefaultValue::
Значение по умолчанию (необязательное).
****
+
. Перечислите события элемента управления в элементе `Events`.
+
. Добавьте дочерний элемент `Event`.
+
. Укажите информацию о событии в аргументах элемента `Event`.
+
****
Name::
Название события. Названия стандартных событий перечислены в пункте xref:StandartPropertiesOfControls.adoc[Стандартные свойства и события элементов управления].
DisplayName::
Отображаемое название события. Если нужно использовать локализованное название, замените атрибут `DisplayName` на `ResourceKey`, и укажите в значении название локализованного ресурса.
DefaultValue::
Обработчик по умолчанию (необязательное).
. Сохраните файл `.xml` на сервер {wc}а в папку `{wcd}\Plugins\%Каталог Решения%`.
****
+
. Перезапустите {kvr}.
