= Сервисы получения моделей объектов

Следующие сервисы предназначены для получения на клиенте моделей объектов для программного изменения значений элементов управления.

* `$DirectoryDesignerRowController` -- предоставляет методы для получения объектов _Конструктора справочников_:
** `getDirectoryDesignerRow(rowId: string)` -- получает объект _Строка справочника_ для строки с идентификатором `rowId`.
** `getDirectoryDesignerRows(rows: GenModels.CollectionRequestModelOf<string>)` -- получает объекты _Строка справочника_ для строк с идентификаторами rows.
* `$CardKindController` -- предоставляет методы для получения объектов _Справочника видов карточек_:
** `getCardKind(cardKindId: string)` -- получает объект _Вид карточки_ для вида с идентификатором `cardKindId`.
** `getCardKinds(cardKinds: GenModels.CollectionRequestModelOf<string>)` -- получает объекты _Вид карточки_ для видов с идентификаторами `cardKinds`.
* `$DepartmentController` -- предоставляет методы для получения объектов _Справочника сотрудников_ и _Справочника контрагентов_:
** `getStaffDepartment(departmentId: string)` -- получает объект _Подразделение_ для подразделения с идентификатором `departmentId`.
** `getPartnerDepartment(departmentId: string)` -- получает объект _Подразделение контрагента_ для подразделения с идентификатором `departmentId`.
** `getStaffDepartments(departments: GenModels.CollectionRequestModelOf<string>)` -- получает объекты _Подразделение_ для подразделений с идентификаторами `departments`.
** `getPartnerDepartments(departments: GenModels.CollectionRequestModelOf<string>)` -- получает объекты _Подразделение контрагента_ для подразделений с идентификаторами `departments`.
* `$EmployeeController` -- предоставляет методы для получения объектов _Справочника сотрудников_:
** `getEmployee(employeeId: string, options?: RequestOptions)` -- получает объект _Сотрудник_ для сотрудника с идентификатором `employeeId`.
** `getEmployees(employees: GenModels.CollectionRequestModelOf<string>, options?: RequestOptions)` -- получает объекты _Сотрудник_ для сотрудников с идентификаторами `employees`.
* `$PartnerEmployeeController` -- предоставляет методы для получения объектов _Справочника контрагентов_:
** `getPartnerEmployee(employeeId: string, options?: RequestOptions)` -- получает объект Сотрудник контрагента для сотрудника с идентификатором `employeeId`.
** `getPartnerEmployees(employees: GenModels.CollectionRequestModel, options?: RequestOptions)` -- получает объекты _Сотрудник контрагента_ для сотрудников с идентификаторами `employees`.

Следующий код демонстрирует пример получения объекта _Подразделение_ с идентификатором `6832216B-FED9-4D20-B1D4-0097C73D446E` при помощи сервиса `$DepartmentController`.

[source,typescript]
----
export function superHandler(sender: CustomButton, e: IEventArgs) {
    let departmentControllerService = sender.layout.getService($DepartmentController);
    let departmentModel = departmentControllerService.getStaffDepartment("6832216B-FED9-4D20-B1D4-0097C73D446E");
}
----

TIP: Подробное описание сервисов приведено в xref:how-to-use-js-api.adoc[справочнике по JS API].
