= Пример. Элемент управления для выбора из справочника «Делопроизводство 5»

В данном пункте рассмотрено создание элемента управления для выбора дела из Справочника номенклатуры дел 5 (приложение «{dv} 5. Делопроизводство 5»).

В примере рассмотрены следующие вопросы разработки элементов управления:

* Создание расширения программы {kvr}, решающего следующие задачи:
* ограничение выбора поля карточки со значением элемента управления -- поле должно содержать ссылку на строку _Справочника номенклатуры дел 5_;
* возможность ограничить для пользователя область выбора дел -- настройки элемента управления должны содержать параметр для выбора Раздела, из которого можно выбирать дела.
* Создание серверного расширения {wc}, который должен предоставлять:
* сервис для работы с данными Справочника номенклатуры дел 5 (с использованием базового API {dv});
* конвертер значений, возвращающий отображаемое значение элемента управления.
* Создание клиентского расширения с несколькими функциями:
* реализация пользовательского интерфейса, одним из элементов которого должно быть дерево разделов Справочника номенклатуры дел 5;
* реализация функции ограничения выбора дел из раздела Справочника номенклатуры дел 5, указанного в программе {kvr};
* предоставление возможности быстрого поиска дел.

____

Полный исходный код примера приведён в репозитории {dv} Samples на GitHub, проект `Controls/RefCases`.

____