= Разработка расширения с методами WebApi

Данный тип расширений предназначен для добавления новых веб-методов, реализующих функции взаимодействия с сервером {dv} (создание и изменение карточек, изменение данных, запуск бизнес-процессов), а также выполнения других задач, для которых необходимы возможности сервера {wc}а.

Чтобы создать расширение, добавляющее новые методы WebApi, выполните приведенную далее инструкцию.

. Создайте проект link:ServerExtensionNew.md[серверного расширения].

. Добавьте в проект класс WebApi контроллера (производный от `System.Web.Http.ApiController`).

. Реализуйте в классе контроллера веб-методы.

Следующий код демонстрирует пример реализации контроллера с методом, проверяющим существование карточки в {dv}.

```csharp
 using {dv}.BackOffice.ObjectModel;
 using {dv}.Platform.WebClient.Helpers;
 using System;
 using System.Web.Http;

namespace WebApiServerExtension
 {
 public class CardServiceController : ApiController
 {
 private readonly ICurrentObjectContextProvider currentObjectContextProvider;

----
       // В конструкторе контроллера получаем ссылку на сервис-провайдер, 
       //  из которого можно получать различные сервисы объектной модели,
       // а также сервис для получения контекста объектов
       public CardServiceController(ICurrentObjectContextProvider currentObjectContextProvider)
       {
           this.currentObjectContextProvider = currentObjectContextProvider;
       }

       // Метод, проверяющий существует ли карточка с идентификатором cardId
       // Если карточка существует, метод возвращает true, иначе - false
       [HttpGet]
       public bool Exists(Guid cardId)
       {
           // Получаем пользовательский контекст объектов
           // ВСЕГДА нужно получать контекст объектов заново. Дополнительная информация
           //  в пункте Получение контекста объектов в серверном расширении 
           var objectContext = currentObjectContextProvider.GetOrCreateCurrentSessionContext().ObjectContext;

           try
           {
               // Получаем карточку с указанным идентификатором
               var card = objectContext.GetObject<BaseCard>(cardId);

               // Возвращаем true, если при получении карточки из контекста объектов не было ошибки и полученный объект не null
               return (card != null);
           }
           catch
           {
               return false;
           }
       }
   }
----

}
 ```

. Скомпилируйте проект и скопируйте полученную сборку на сервер {wc}а в папку `&lt;Каталог установки {wc}а&gt;\Site\Extensions\\&lt;Каталог Решения&gt;`. Перезапустите IIS.

Для проверки работоспособности примера, откройте в веб-браузере страницу `http://&lt;Адрес сервера {wc}а&gt;/{dv}WebClient/api/CardService/Exists?cardId=&lt;Идентификатор карточки&gt;`. Вместо _Идентификатор карточки_ укажите идентификатор любой существующей карточки. Метод вернет значение «true» (если карточки не существует – «false»).

Пример клиентского расширения, использующего метод `Exists`, приведен в пункте link:ClientExtensionsServices.md[Разработка расширения с клиентским сервисом].