= Разработка расширения с методами WebApi

Данный тип расширений предназначен для добавления новых веб-методов, реализующих функции взаимодействия с сервером {dv} (создание и изменение карточек, изменение данных, запуск бизнес-процессов), а также выполнения других задач, для которых необходимы возможности сервера {wc}а.

Чтобы создать расширение, добавляющее новые методы WebApi, выполните приведенную далее инструкцию.

. Создайте проект xref:serverExtensionsCreatePublish.adoc[серверного расширения].
+
. Добавьте в проект класс WebApi контроллера (производный от `System.Web.Http.ApiController`).
+
. Реализуйте в классе контроллера веб-методы.
+
****
Следующий код демонстрирует пример реализации контроллера с методом, проверяющим существование карточки в {dv}.

[source,csharp]
----
using DocsVision.BackOffice.ObjectModel;
using DocsVision.Platform.WebClient.Helpers;
using System;
using System.Web.Http;

namespace WebApiServerExtension
{
    public class CardServiceController : ApiController
    {
        private readonly ICurrentObjectContextProvider currentObjectContextProvider; <.>

        public CardServiceController(ICurrentObjectContextProvider currentObjectContextProvider) <.>
        {
            this.currentObjectContextProvider = currentObjectContextProvider;
        }

        [HttpGet]
        public bool Exists(Guid cardId) <.>
        {
            var objectContext = currentObjectContextProvider.GetOrCreateCurrentSessionContext().ObjectContext; <.>

            try
            {
                var card = objectContext.GetObject<BaseCard>(cardId); <.>

                return (card != null); <.>
            }
            catch
            {
                return false;
            }
        }
    }
}
----
<.> В конструкторе контроллера получаем ссылку на сервис-провайдер,
<.> Из сервис-провайдера можно получать различные сервисы объектной модели, а также сервис для получения контекста объектов.
<.> Метод, проверяющий существует ли карточка с идентификатором cardId. Если карточка существует, метод возвращает true, иначе -- false.
<.> Получаем пользовательский контекст объектов.
+
IMPORTANT: Всегда нужно получать контекст объектов заново. Дополнительная информация в пункте xref:serverExtensionsGetObjectContext.adoc[Получение контекста объектов] в серверном расширении.
+
<.> Получаем карточку с указанным идентификатором.
<.> Возвращаем true, если при получении карточки из контекста объектов не было ошибки и полученный объект не null.
****
+
. Скомпилируйте проект и скопируйте полученную сборку на сервер {wc}а в папку `{wcd}\Site\Extensions\%Каталог Решения%`. Перезапустите IIS.
+
****
Для проверки работоспособности примера, откройте в веб-браузере страницу `\http://%WebCinstallDir%/{dv}WebClient/api/CardService/Exists?cardId=*<CardID>*`. Вместо _CardID_ укажите идентификатор любой существующей карточки. Метод вернет значение *true* (если карточки не существует -- *false*).

Пример клиентского расширения, использующего метод `Exists`, приведен в пункте xref:clientExtensionsWithClientService.adoc[Разработка расширения с клиентским сервисом].
****
