= Создание и публикация серверного расширения

Серверное расширение представляет собой библиотеку DLL, разработанную на платформе .NET.

.Чтобы создать серверное расширение:
. Создайте в Visual Studio новый проект с типом TemplateServerExtension.
+
. Обновите в проекте ссылки на зависимости.
+
****
Версии подключаемых компонентов должны соответствовать версиям компонентов, используемых сервером {wc}а, для которого разрабатывается расширение. При обновлении {wc}а необходимо перекомпилировать расширение с новыми версиями компонентов.
****
+
. Реализуйте в проекте функции серверного расширения.
+
****
Примеры кода серверных расширений приведены в следующих пунктах раздела, а также в xref:webClientSamples.adoc[репозитории ДоксВижн].
****
+
. Настройте ядро серверного расширения.
+
****
Ядром серверного расширения называется файл `TemplateServerExtension.cs` в проекте расширения. Ядро является производным от `WebClientExtension` классом, содержащим ссылки на реализуемые функции расширения.

[source,csharp]
----
public class TemplateServerExtension : WebClientExtension
{
    public TemplateServerExtension(IServiceProvider serviceProvider)
        : base(serviceProvider)
    {
    }

    public override string ExtensionName <.>
    {
        get {
            return Assembly.GetAssembly(typeof(TemplateServerExtension)).GetName().Name;
        }
    }

    public override Version ExtensionVersion <.>
    {
        get {
            return new Version(FileVersionInfo.GetVersionInfo(Assembly.GetExecutingAssembly().Location).FileVersion);
        }
    }

    public override void InitializeContainer(ContainerBuilder containerBuilder) { <.>

<.>
    // containerBuilder.RegisterType<YourService>().As<IYourService>().SingleInstance();
    // containerBuilder.RegisterOrderedType<YourBindingConverterType, IBindingConverter>();
    // containerBuilder.RegisterOrderedType<YourBindingResolverType, IBindingResolver>();
    // containerBuilder.RegisterOrderedType<YourControlResolverType, IControlResolver>();
    // containerBuilder.RegisterOrderedType<YourPropertyResolverType, IPropertyResolver>();
    // containerBuilder.RegisterType<YourCardLifeCycle>().Keyed<ICardLifeCycle>(CardTypeID).SingleInstance();
    // containerBuilder.RegisterType<YourRowLifeCycle>().Keyed<IRowLifeCycle>(SectionID).SingleInstance();
    }

<.>

}
----
<.> Название расширения.
<.> Версия расширения.
<.> Метод регистрации добавляемых расширением сервисов, преобразователей, конвертеров и т.п. в IoC контейнере.
<.> Примеры регистрации.
<.> Далее идут функции, возвращающие реализованные функции серверного расширения.

Описание изменений, которые необходимо выполнить в ядре расширения, приведено в описании примеров расширений, добавляющих обработчики событий и локализованные ресурсы.

В серверном расширении {wc}а используется IoC контейнер, реализованный с использованием библиотеки Autofac. Описание данной библиотеки и её возможностей см. на сайте [](https://autofac.org/).
****
+
. Скомпилируйте проект.
+
****
В результате будет получен файл DLL с ядром серверного расширения и реализуемыми функциями, а также файлы DLL с локализованными ресурсами.
****
+
. Скопируйте файл расширения на сервер {wc}а в папку `{wcd}\Site\Extensions\%Каталог Решения%`. Каталог Решения необходимо создать самостоятельно.
+
Ресурсные сборки нужно скопировать в папки `{wcd}\Site\Extensions\ru\` (для русской локализации), `{wcd}\Site\Extensions\uk\` (для английской локализации) и т. д.
+
. Перезапустите сервер IIS.
