= Пример. Элемент управления "SuperControl"

В данном примере будут разработаны компоненты элемента управления "SuperControl": текстовый описатель элемента управления и клиентский компонент.

Элемент управления SuperControl является ссылкой, адрес которой указывается в программе {kvr}. Для элемента управления доступна настройка Видимость и событие При щелчке.

. Формируем текстовый описатель элемента управления.

. Создаем новый файл `SuperControl.xml` со следующим содержимым:

[source,typescript]
----
 &lt;?xml version="1.0" encoding="utf-8" ?&gt;
 <Controls>
 <Control Name="SuperControl" DisplayName="Супер элемент управления">
 <Properties>
 <Property Type="Name" /><!-- Название -->
 <Property Type="Visibility" /><!-- Видимость -->

. Файл `SuperControl.xml` копируем в папку `C:\Program Files (x86)Docsvision\WebClient\5.5\Plugins\`.

. Формируем клиентское расширение с клиентским компонентом элемента управления.

. xref:ClientExtensionsNew.adoc[Создаем новое клиентское расширение].

. Добавляем в папку расширения файл `src/Controls/SuperControl.tsx` со следующим содержимым:

[source,typescript]
----
 // Импорт используемых модулей
 import { BaseControlParams, BaseControlState, BaseControl } from "@{dv}/webclient/System/BaseControl";
 import { r } from "@{dv}/webclient/System/Readonly";
 import { apiEvent } from "@{dv}/webclient/System/Event";
 import { BasicApiEvent } from "@{dv}/webclient/System/ApiEvent";
 import { IEventArgs } from "@{dv}/webclient/System/IEventArgs";
 import { BaseControlImpl } from "@{dv}/webclient/System/BaseControlImpl";
 import { SimpleEvent } from "@{dv}/webclient/System/SimpleEvent";
 import React from "react";

. Настраиваем клиентское расширение в файле `src/Index.tsx`.

[source,typescript]
----
 import { extensionManager } from "@{dv}/webclient/System/ExtensionManager";
 import { SuperControl } from "./Controls/SuperControl";

. Собираем клиентское расширение с помощью команды `npm run build`.

. Полученный файл `Site\Content\Modules\...\extension.js` копируем в папку `C:\Program Files (x86)Docsvision\WebClient\5.5\Site\Content\Modules\SuperControlExtension\` на сервере {wc}а.

После выполнения всех действий нужно:

. Перезапустить сервер {wc}а (IIS), чтобы загрузились скрипты с элементом управления.
. Открыть {kvr} и настроить разметку с использованием "Супер элемента управления".

При настройке элемента управления должны быть доступны свойства Url и Видимость, а также событие При щелчке, для которого можно настроить обработчик.

В веб-браузере "Супер элемент управления" представляет собой ссылку (тег "a"), при нажатии на которую будет выполнен переход по адресу, указанному в Url, а также вызван обработчик, указанный в событии При щелчке.