= Список специальных адресов {wc}а

Адреса, перечисленные в данном разделе, позволяют вызвать специальные функции {wc}а из адресной строки браузера.

* *Работа со строками справочников*.

* Открыть окно просмотра строки справочника: `#/RowView/<cardId>/<sectionId>/<rowId>`.

* Открыть окно создания строки справочника: `#/NewRow/<cardId>/<sectionId>/<parentRowId>/<parentTreeRowID>`.
* Открыть окно редактирования строки справочника: `#/RowEdit/<cardId>/<sectionId>/<rowId>`.

Здесь:

* `cardId` -- идентификатор карточки;
* `sectionId` -- идентификатор секции карточки cardId;
* `rowId` -- идентификатор редактируемой/открываемой строки;
* `parentRowId` -- идентификатор родительской строки родительской секции (если секция находится внутри другой секции);
* `parentTreeRowID` -- идентификатор родительской строки текущей секции (в случае, если секция древовидная).
* *Работа со Справочником контрагентов*.

* Добавление:

** Открыть окно добавления корневой организации: `#/NewOrganizationRow/65ff9382-17dc-4e9f-8e93-84d6d3d8fe8c/c78abded-db1c-4217-ae0d-51a400546923/00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000`.
** Открыть окно добавления дочерней организации: `#/NewOrganizationRow/65ff9382-17dc-4e9f-8e93-84d6d3d8fe8c/c78abded-db1c-4217-ae0d-51a400546923/00000000-0000-0000-0000-000000000000/<parent-id>`. Здесь parent-id -- идентификатор родительской организации.
** Открыть окно добавления подразделения: `#/NewDepartmentRow/65ff9382-17dc-4e9f-8e93-84d6d3d8fe8c/c78abded-db1c-4217-ae0d-51a400546923/00000000-0000-0000-0000-000000000000/<parent-id>`. Здесь parent-id -- идентификатор организации.
** Открывает окно добавления сотрудника: `#/NewRow/65ff9382-17dc-4e9f-8e93-84d6d3d8fe8c/1a46bf0f-2d02-4ac9-8866-5adf245921e8/<parent-id>/00000000-0000-0000-0000-000000000000`. Здесь parent-id -- идентификатор организации/подразделения.
* Просмотр:
** Открывает окно просмотра сотрудника: `#/RowView/65ff9382-17dc-4e9f-8e93-84d6d3d8fe8c/1a46bf0f-2d02-4ac9-8866-5adf245921e8/<id>`. Здесь id -- идентификатор сотрудника.
** Открывает окно просмотра организации: `#/OrganizationRowView/65ff9382-17dc-4e9f-8e93-84d6d3d8fe8c/c78abded-db1c-4217-ae0d-51a400546923/<id>`. Здесь id -- идентификатор организации.
** Открывает окно просмотра подразделения: `#/DepartmentRowView/65ff9382-17dc-4e9f-8e93-84d6d3d8fe8c/c78abded-db1c-4217-ae0d-51a400546923/<id>`. Здесь id -- идентификатор подразделения.
* Редактирование:
** Открывает окно редактирования сотрудника: `#/RowEdit/65ff9382-17dc-4e9f-8e93-84d6d3d8fe8c/1a46bf0f-2d02-4ac9-8866-5adf245921e8/<id>`. Здесь id -- идентификатор сотрудника.
** Открывает окно редактирования организации: `#/OrganizationRowEdit/65ff9382-17dc-4e9f-8e93-84d6d3d8fe8c/c78abded-db1c-4217-ae0d-51a400546923/<id>`. Здесь id -- идентификатор организации.
** Открывает окно редактирования подразделения: `#/DepartmentRowEdit/65ff9382-17dc-4e9f-8e93-84d6d3d8fe8c/c78abded-db1c-4217-ae0d-51a400546923/<id>`. Здесь id -- идентификатор подразделения.