= Стандартные свойства и события элементов управления

Далее приведено описание стандартных свойств и событий элементов управления, которое включает: тип значения свойства, метод получения описателя свойства, а также ключ ресурса с локализованным названием -- для событий.

== Свойства

* *Name* (Название)

Тип: String

Метод получения описателя: PropertyFactory.GetNameProperty

* *Width* (Ширина в процентах)

Тип: Double

Метод получения описателя: PropertyFactory.GetWidthProperty

* *Header* (Заголовок)

Тип: String

Метод получения описателя: PropertyFactory.GetHeaderProperty

* *Binding* (Свойство, содержащее механизм получения данных)

Тип: String

Метод получения описателя свойства: PropertyFactory.GetBindingProperty

* *DataSource* (Источник данных)

Тип: Guid

Метод получения описателя: PropertyFactory.GetDataSourceProperty

* *EditOperation* (Операция редактирования)

Тип: Guid

Метод получения описателя: PropertyFactory.GetEditOperationProperty

* *ExtendedDataSource* (Расширенный источник данных)

Тип: Guid

Метод получения описателя: PropertyFactory.GetExtendedDataSourceProperty

* *StandardCssClass* (Стандартный css класс)

Тип: String

Метод получения описателя: PropertyFactory.GetStandardCssClassProperty

* *CustomCssClasses* (Дополнительные css классы)

Тип: String

Метод получения описателя: PropertyFactory.GetCustomCssClassesProperty

* *TabStop* (Переходить по TAB)

Тип: Boolean

Метод получения описателя: PropertyFactory.GetTabStopProperty

* *Visibility* (Видимость)

Тип: Boolean

Метод получения описателя: PropertyFactory.GetVisibilityProperty

* *Default* (Значение по умолчанию)

Тип: String

Метод получения описателя: PropertyFactory.GetDefaultProperty

* *Required* (Обязательное)

Тип: Boolean

Метод получения описателя: PropertyFactory.GetRequiredProperty

* *EditMode* (Режим редактирования)

Тип: Int32

Метод получения описателя: PropertyFactory.GetEditModeProperty

* *PlaceHolder* (Заполнитель)

Тип: String

Метод получения описателя: PropertyFactory.GetPlaceHolderProperty

* *Tip* (Подсказка)

Тип: String

Метод получения описателя: PropertyFactory.GetTipProperty

* *LabelText* (Текст метки)

Тип: String

Метод получения описателя: PropertyFactory.GetLabelTextProperty

* *ShowEmptyLabel* (Отображать метку без значения)

Тип значения: Boolean

Метод получения описателя: PropertyFactory.GetShowEmptyLabelProperty

* *MinWidth* (Минимальная ширина)

Тип: Double

Метод получения описателя: PropertyFactory.GetMinWidthProperty

* *ButtonText* (Текст кнопки)

Тип: String

Метод получения описателя: PropertyFactory.GetButtonTextProperty

== События

Все события имеют тип String.

* *Click* (При щелчке)

Метод получения описателя: PropertyFactory.GetClickEvent

Ключ ресурса: ControlTypes_ClickEventProperty

* *MouseOver* (При наведении курсора)

Метод получения описателя: PropertyFactory.GetMouseOverEvent

Ключ ресурса: ControlTypes_MouseOverEventProperty

* *MouseOut* (При отведении курсора)

Метод получения описателя: PropertyFactory.GetMouseOutEvent

Ключ ресурса: ControlTypes_MouseOutEventProperty

* *Focus* (При получении фокуса)

Метод получения описателя: PropertyFactory.GetFocusEvent

Ключ ресурса: ControlTypes_FocusEventProperty

* *Blur* (При потере фокуса)

Метод получения описателя: PropertyFactory.GetBlurEvent

Ключ ресурса: ControlTypes_BlurEventProperty

* *Collapsed* (При сворачивании)

Метод получения описателя: PropertyFactory.GetCollapsedEvent

Ключ ресурса: ControlTypes_CollapsedEventProperty

* *Collapsing* (Перед сворачиванием)

Метод получения описателя свойства: PropertyFactory.GetCollapsingEvent

Ключ ресурса: ControlTypes_CollapsingEventProperty

* *Expanded* (При разворачивании)

Метод получения описателя: PropertyFactory.GetExpandedEvent

Ключ ресурса: ControlTypes_ExpandedEventProperty

* *Expanding* (Перед разворачиванием)

Метод получения описателя: PropertyFactory.GetExpandingEvent

Ключ ресурса: ControlTypes_ExpandingEventProperty

* *DataChanged* (При смене данных)

Метод получения описателя: PropertyFactory.GetDataChangedEvent

Ключ ресурса: ControlTypes_DataChangedEventProperty