= Остановка выполнения операции с помощью прерываемого события элемента управления

События, генерируемые элементом управления, могут быть стандартными (непрерываемые) и прерываемыми, с помощью которых обработчик может остановить выполнение операции (например, сохранение карточки).

Чтобы создать прерываемое событие:

. Добавьте событие в описатель элемента управления:

`xml
   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
   &lt;Controls&gt;
     &lt;Control Name=&quot;SomeControl&quot; DisplayName=&quot;Пример элемента управления&quot;&gt;
       &lt;Properties&gt;
         &lt;Property Type=&quot;Name&quot; /&gt;
       &lt;/Properties&gt;
       &lt;Events&gt;
         &lt;Event Name=&quot;someEventing&quot; DisplayName=&quot;Перед выполнение операции&quot;/&gt; &lt;!--- Прерываемое событие --&gt;
       &lt;/Events&gt;
     &lt;/Control&gt;
   &lt;/Controls&gt;
`

. В клиентском компоненте элемента управления в классе параметров для события укажите тип CancelableApiEvent:

`
   export class SomeControlParams extends BaseControlParams {
       @apiEvent someEventing?: CancelableApiEvent&lt;IEventArgs&gt;;
   }
`

. В клиентском компоненте элемента управления в классе реализации:

. Проинициализируйте прерываемое событие с помощью метода CancelableEvent.Create:

```tsx
 construct() {
 super.construct();

. Во внутреннем обработчике события, вызываемого перед выполнением операции, добавьте код, который будет выполняться при прерывании события внешними обработчиками, и код для продолжения обработки события:

```tsx
 protected internalEventHandler = async () =&gt; {
 try {
 await CancelableEvent.cast(this.state.someEventing).trigger().deferred;