= Остановка выполнения операции с помощью прерываемого события элемента управления

События, генерируемые элементом управления, могут быть стандартными (непрерываемые) и прерываемыми, с помощью которых обработчик может остановить выполнение операции (например, сохранение карточки).

Чтобы создать прерываемое событие:

. Добавьте событие в описатель элемента управления:

`xml
   <?xml version="1.0" encoding="utf-8" ?>
   <Controls>
     <Control Name="SomeControl" DisplayName="Пример элемента управления">
       <Properties>
         <Property Type="Name" />
       </Properties>
       <Events>
         <Event Name="someEventing" DisplayName="Перед выполнение операции"/> <!--- Прерываемое событие -->
       </Events>
     </Control>
   </Controls>
`

. В клиентском компоненте элемента управления в классе параметров для события укажите тип CancelableApiEvent:

`
   export class SomeControlParams extends BaseControlParams {
       @apiEvent someEventing?: CancelableApiEvent<IEventArgs>;
   }
`

. В клиентском компоненте элемента управления в классе реализации:

. Проинициализируйте прерываемое событие с помощью метода CancelableEvent.Create:

[source,typescript]
----
 construct() {
 super.construct();

. Во внутреннем обработчике события, вызываемого перед выполнением операции, добавьте код, который будет выполняться при прерывании события внешними обработчиками, и код для продолжения обработки события:

[source,typescript]
----
 protected internalEventHandler = async () => {
 try {
 await CancelableEvent.cast(this.state.someEventing).trigger().deferred;