= С чего начать

== Подготовка

. Подготовьте среду разработки.
+
На компьютере разработчика должны быть установлены:
+
* Microsoft Visual Studio 2017/2019;
* https://code.visualstudio.com/[Visual Studio Code];
* https://nodejs.org/en/[NodeJS v12.16.1 (LTS) или выше];
* TypeScript 3.8.
. Загрузите на компьютер xref:webClientSamples.adoc[репозиторий WebClient-Samples].
+
. Установите шаблоны проектов из полученного репозитория:
+
* _TemplateDesignerExtension_ -- шаблон проекта для разработки расширения программы {kvr}.
* _TemplateServerExtension_ -- шаблон проекта для разработки серверного расширения.

.Чтобы установить шаблоны:
. Скопируйте файлы `TemplateDesignerExtension.zip` и `TemplateServerExtension.zip` из каталога репозитория `ProjectTemplates\VSTemplates\` в каталог шаблонов проектов Visual Studio (`C:\Users\\%username%\Documents\Visual Studio %version%\Templates\ProjectTemplates\Visual C#\`) .
. Запустите Visual Studio. Будут добавлены новые типы проектов: _TemplateDesignerExtension_ и _TemplateServerExtension_.

== Что дальше

. Определите цель разработки.
+
{wc} имеет несколько точек расширения функциональных возможностей.
+
.Программист может разработать:
* Серверное расширение, добавляющее методы WebAPI, для вызова с клиентского уровня.
+
Серверные методы могут быть использованы для взаимодействия с сервером {dv}: создание карточек, запуск БП и т. д.
+
* Новый тип элементов управления для создания разметок.
+
Данный тип расширения включает два компонента: _расширение программы {kvr}_ (обеспечивает возможность настройки разметки с использованием ЭУ) и _клиентское расширение_ (обеспечивает функционирование ЭУ на клиентской стороне).
+
* Клиентский скрипт, содержащий обработчики событий разметки.
+
Данные скрипты могут добавлять в {wc} необходимую бизнес-логику или обеспечивать другие функции клиентского уровня.
+
* Клиентское расширение -- общее название компонентов, обеспечивающих функциональность клиентского уровня.
+
К клиентским расширениями относятся компоненты элементов управления, обеспечивающих их функционирование на стороне клиента, клиентские скрипты, библиотеки JavaScript, добавляющие необходимую клиентскую функциональность.
+
. Ознакомьтесь с инструкцией по разработке требуемого типа компонента {wc}а в данном руководстве.
+
. Ознакомьтесь с предоставляемыми примерами.
