= Работа с сервисом жизненного цикла объектов {wc}а

Рассмотренные в пунктах link:ServerExtensionCardFactory.adoc[Реализация методов для работы с карточками из разметок] и link:ServerExtensionRowFactory.adoc[Реализация методов для работы со строками секций из разметок] компоненты, которые позволяют внести изменения в механизмы создания, изменения и удаления карточек и строк секций из разметок, доступны программисту через специальный сервис `ILifeCycleService`. Данный сервис определяет методы:

* `GetCardLifeCycle` -- возвращает реализацию интерфейса `ICardLifeCycle` для указанного типа карточек;
* `GetRowLifeCycle` -- возвращает реализацию интерфейса `IRowLifeCycle` для указанной секции.

Следующий код демонстрирует способ получения сервиса `ICardLifeCycle` и его использования в веб-методе для создания карточки по шаблону:

[source,csharp]
----
public class CardServiceController : ApiController
{
    private readonly ILifeCycleService lifeCycleService;
    
    // Принимаем требуемый сервис в конструкторе
    public CardServiceController(ILifeCycleService lifeCycleService)
    {
        this.lifeCycleService = lifeCycleService;
    }

    [HttpGet]
    public Guid CreateByTemplate(Guid cardTypeId)
    {
        // Получаем интерфейс для работы с карточкой типа CardDocument
        var documentCardLifeCycle = lifeCycleService.GetCardLifeCycle(CardDocument.ID);
        if (templateId != Guid.Empty)
        {
            // Используем метод создания карточки по шаблону
            var newDocumentId = documentCardLifeCycle.CreateFromTemplate(sessionContext, templateId, null);
        }
        return newDocumentId;
    }
}
----