= Информация о пользователе

Элемент управления `_Информация о пользователе_` предназначен для отображения информации о пользователе в разметке локации menu:WebFrame[Диалог профиля пользователя].

== Свойства

Общие::
Название ЭУ:::
Название типа элемента управления.
Название:::
Уникальное название элемента управления.
Поведение::
Видимость:::
Настройка видимости. Элемент управления отображается в карточке, когда флаг установлен и не отображается вместе с содержимым, когда флаг снят.
+
`*Адаптивный*`
Дополнительные css классы:::
Названия дополнительных классов CSS для изменения стиля элемента управления. Перечисляются через пробел.
Стандартный css класс:::
Название CSS класса, в котором определен стандартный стиль элемента управления.
События::
При наведении курсора:::
Вызывается при входе курсора мыши в область элемента управления.
При отведении курсора:::
Вызывается, когда курсор мыши покидает область элемента управления.
При щелчке:::
Вызывается при щелчке мыши по любой области элемента управления.
