= Кнопка отправки письмом

Элемент управления позволяет отправлять карточку и файлы по почте. Для отправки файлов элемент управления может быть помещён только в ЭУ `_Список файлов_`. Элемент управления может быть добавлен только в карточки вида _{dm}_ в режиме просмотр.

== Свойства

include::partial$properties.adoc[tags=general]

=== Внешний вид

==== Текст кнопки

Текст, отображаемый в кнопке. Если значение не установлено, отображается только значок.

`*Локализуемый*`

=== Поведение

[#template]
==== Использовать шаблон

Свойство активирует настройку шаблонов письма. Если свойство неактивно, тело письма останется пустым.

Окно _Доступные шаблоны письма_ аналогично xref:ctrl/special/printButton.adoc#printTemplates[выбору] шаблона печати. Однако, в шаблонах письма можно выбрать только один шаблон или не использовать шаблоны.

==== Прикладываемые файлы

Свойство позволяет выбрать, какие файлы по умолчанию будут включены в приложение к письму:

* *_Основные_* -- к письму автоматически прикладываются только все основные файлы карточки.
* *_Дополнительные_* -- к письму прикладываются только все дополнительные файлы.
* *_Все_* -- к письму прикладываются все файлы карточки.
* *_Никакие_* -- к письму не прикладываются файлы.

[#allow-selection]
==== По выбору пользователя

Свойство определяет, может ли пользователь выбирать файлы, которые будут приложены к письму. Если свойство активно, при нажатии на кнопку пользователь увидит окно со списком файлов и возможностью их выбирать. Список файлов в окне зависит от значения свойства `_Прикладываемые файлы_`.

==== Ссылка на карточку

Свойство определяет, будет ли в тело письма добавлена ссылка на карточку в {wc}е в формате `Ссылка на карточку в Веб Клиенте: ссылка`. Ссылка добавляется в конце тела письма.

include::partial$properties.adoc[tags=addCss]

include::partial$properties.adoc[tags=editOperationForVisibility]

include::partial$properties.adoc[tags=stdCss]

include::partial$properties.adoc[tags=visibility]

=== События

include::partial$properties.adoc[tags=mouseOver]

include::partial$properties.adoc[tags=mouseAway]

include::partial$properties.adoc[tags=onClick]
