= Кнопка электронной подписи

Элемент управления даёт позволяет подписывать карточки без файлов (выполнять подписание атрибутов).

WARNING: ЭУ можно разместить только в разметке карточки типа "Документ". Для разметок других типов ЭУ в библиотеке не отображается.

== Свойства

include::partial$properties.adoc[tags=general]

=== Внешний вид

include::partial$properties.adoc[tags=hint]

=== Данные

==== Операция редактирования Настроек подписи

Свойство регулирует доступность кнопки для вызова окна "Настройки подписи", в котором осуществляется настройка списка сертификатов.

=== Поведение

include::partial$properties.adoc[tags=visibility]

include::partial$properties.adoc[tags=addCss]

include::partial$properties.adoc[tags=byTab]

==== Подписывать без метки

Флаг определяет, будет ли отображаться выпадающий список способов подписания. Если флаг установлен, будет выполняться подписание без метки и выпадающий список не будет отображаться.

include::partial$properties.adoc[tags=stdCss]

=== События

Перед открытием диалога подписи

Перед открытием журнала подписей

Перед сохранением подписи

Перед формированием подписи

После открытия диалога подписи

После открытия журнала подписей

После подписания

include::partial$properties.adoc[tags=mouseOver]

include::partial$properties.adoc[tags=mouseAway]

include::partial$properties.adoc[tags=onClick]
