== Изменения в библиотеке элементов управления

* В локацию "Компоненты папки" добавлен элемент управления нового грида — _folderGrid/Карточки папки_.

Для ЭУ _folderGrid/Карточки папки_ доступно свойство _Непрозрачность_. Свойство регулирует прозрачность грида. Прозрачность может быть настроена в диапазоне от 0 - 100 (в процентах), где 0 означает максимальную прозрачность, а 100 — максимальную непрозрачность. Значение по умолчанию — 100.

[#contextMenu]
Свойство _Контекстное меню включено_ регулирует доступность контекстного меню.

[#filter]
Свойство _Фильтрация_ регулирует доступность фильтрации данных.

ЭУ _folderGrid/Карточки папки_ содержит два элемента управления: _folderGrid_FolderGridToolbar/Тулбар папки_ и _folderGrid_FolderGridBatchOperationsNode/Узел для групповых операций_:

* _folderGrid_FolderGridToolbar/Тулбар папки_ — панель управления нового грида. Свойства панели управления регулируют операции, доступные для представления папки:
** Обновить - обновляет данные в представлении.
** Настройки - регулирует доступность настроек грида.
** Прочитать все - прочитать все карточки в папке.
[#folderSize]
** Размер папки - отображает количество карточек в папке.
** Cбросить настройки - сбрасывает пользовательские настройки папки.
** Экспорт - экспортирует представление в Excel.
[#notAvailableMessage]
* _folderGrid_FolderGridBatchOperationsNode/Узел для групповых операций_ — элемент управления групповых операций в представлении папки. Свойство _Текст, если нет групповых операций_ показывает сообщение о недоступности групповых операций.
* Добавлена новая локация Фильтр папки, включающая два новых элемента управления:

* _gridFilterItems/Элементы фильтра папки_— ЭУ делает доступной функцию фильтрации данных в представлении.

* _gridFilterResetButton/Кнопка сброса фильтра папки_ — кнопка для сброса настроек фильтров данных.

В КР для Folder Grid добавить свойство (чекбокс) "Использовать ленту по умолчанию" (Show list by default) с зависимостью от устройства.

В КР для тулбара добавить свойство "Изменить отображение" (Change mode) <- данное свойство добавляет в UI тулбара кнопку переключалку, позволяющую менять значение по умолчание на другое