= Редактор для выбора поля карточки

Для выбора поля карточки, с которым связаны данные элемента управления, может использоваться стандартный редактор -- `{dv}.BackOffice.WebLayoutsDesigner.Editors.FieldMetadataEditor`. Данный редактор предоставляет возможность установки фильтра для ограничения доступных для выбора полей.

Следующий пример демонстрирует редактор, предоставляющий возможность выбирать только поля булева типа.

[source,csharp]
----
class BooleanMetadataEditor : ITypeEditor
{
    public FrameworkElement ResolveEditor(PropertyItem propertyItem)
    {
        var editor = new FieldMetadataEditor();
        
        //
        editor.FieldFilter = (field) => { return field.FieldType == FieldType.Bool; }; <.>
        return editor.ResolveEditor(propertyItem);
    }
}
----
<.> Устанавливаем ограничением для отображаемых типов. Текущее обрабатываемое поле передаётся в `field`.

Использование возможностей фильтра `FieldFilter` позволяет установить более точные критерии для отображения списка полей в редакторе.

Например, в следующем коде поля ограничиваются по типу и связанной карточки и секции, с которой должно быть связано поле (для полей ссылающихся на справочники).

[source,csharp]
----
public FrameworkElement ResolveEditor(PropertyItem propertyItem)
{
    var editor = new FieldMetadataEditor();

    editor.FieldFilter = (field) => { <.>
        return (field.FieldType == FieldType.RefId || field.FieldType == FieldType.UniqueId) && 
            field.LinkedCardTypeId == RefBaseUniversal.ID && <.>
            field.LinkedSectionId == RefBaseUniversal.Items.ID; }; <.>

    return editor.ResolveEditor(propertyItem);
}
----
<.> Устанавливаем фильтр.
<.> Поле должно быть связано с карточкой Конструктор справочников
<.> Поле должно быть связано с секцией _Строка справочника_
