= Расширение возможностей программы {kvr}

{kvr} предоставляет возможность дополнять собственные функциональные возможности с помощью расширений.

Расширение программы {kvr} может добавлять:

* Типы элементов управления.
* Свойства (настройки) элементов управления.
* Редакторы для свойств элементов управления.
* Функции проверки доступности операций.
* Критерии для условий выбора разметок.
* Локализованные ресурсы.

== Разработка расширения программы {kvr}

.Процесс разработки расширения программы {kvr} может включать следующие шаги:

. Создание в Visual Studio проекта типа TemplateDesignerExtension.
+
. Обновление ссылок на подключаемые компоненты (при необходимости).
+
CAUTION: Версии подключаемых компонентов в проекте должны соответствовать версиям компонентов, используемых Конструктором web-разметок, для которого разрабатывается расширение. При обновлении версии {wc}а все разработанные компоненты должны быть скомпилированы повторно с использованием новых версий библиотек {wc}а.
+
. Разработка ядра расширения программы {kvr}.
+
Ядро расширения программы {kvr} представляет собой производный от `WebLayoutsDesignerExtension` класс. В нём переопределяются методы получения описателей типов элементов управления, описателей типов свойств элементов управления, редакторов значений свойств и пр., в зависимости от назначения расширения программы {kvr}.
+
При создании проекта из шаблона `TemplateDesignerExtension` ядро расширения программы {kvr} будет содержаться в файле `Extension\TemplateDesignerExtension.cs`.
+
Примеры реализации отдельных элементов ядра расширения программы {kvr} рассмотрены в следующих разделах.
+
. Компиляция проекта.
+
****
В результате будет получен файл DLL -- расширение программы {kvr}, а также файлы DLL с локализованными ресурсами.
****

== Публикация расширения программы {kvr}

Последовательность публикации расширения программы {kvr} на сервере {wc}а включает следующие шаги:

. Создание каталога для Решения на сервере {wc}а: `{wcd}\Plugins\%Каталог Решения%`.
. Копирование сборки расширения программы {kvr} в `%Каталог Решения%`. Файлы DLL с локализованными ресурсами копируются в существующие в каталоге `{wcd}\ru\` (для русской локализации), `{wcd}\uk\` (для английской локализации) и т.д.
+
****
Реализованная в расширении программы {kvr} функциональность будет доступна после запуска программы {kvr}.
****
