
== Изменение списка типов файлов, разрешенных для добавления в карточки

По умолчанию пользователь может добавлять в карточки файлы со следующими расширениямиxref:#fntarg_1[^1^]: rtf, dot, doc, dotx, dotm, ods, docx, docm, odt, csv, xlt, xltm, xls, xlsm, xltx, xlsx, pdf, jpg, jpeg, gif, png, bmp, tiff, tif, emf, wmf, xslt, xsl, xml, htm, html, txt, log, cs, asmx, ascx, aspx, js, cpp, h, css, idl, ini, java, rc, rc2, shtm, shtml, sql, zip, rar, 7z, vsd, vsdx, msg, one, pptx, ppt. Администратор может добавить в список новые расширения файлов или удалить существующие.

. Откройте конфигурационный файл [.ph]#[.ph .filepath]`[Каталог установки Web-клиента]\5.5\Site\web.config`#.
. Перейдите к секции [.ph .menucascade]#[.ph .uicontrol]*configuration* > [.ph .uicontrol]*Docsvision* > [.ph .uicontrol]*WebClient* > [.ph .uicontrol]*SettingGroups* > [.ph .uicontrol]*SettingGroup[Name="WebClient"]*#.
. Измените значение параметра `AcceptableFileExtensions`. Значение содержит строку регулярного выражения. Новые расширения файлов нужно добавлять во вторые скобки, через символ «|».
+
Пример добавления в расширения DWG:
+
[source,pre,codeblock]
----
<Setting Name="AcceptableFileExtensions" Value="(.|/)(rtf|dot|doc|dotm|dotx|docm|ods|docx|odt|csv|xlt|xls|xlsm|xltm|xltx|xlsx|pdf|jpg|jpeg|gif|png|bmp|tiff|tif|emf|wmf|xslt|xsl|xml|htm|html|txt|log|cs|asmx|ascx|aspx|js|cpp|h|css|idl|ini|java|rc|rc2|shtm|shtml|sql|zip|rar|7z|vsd|vsdx|msg|one|pptx|ppt|avi|wav|dwg)$"/>
----
. Сохраните изменения конфигурационного файла.

*Parent topic:* xref:../topics/CardsConf.html[Работа с карточками]

xref:#fnsrc_1[^1^] Для возможности загрузки файлов .ascx, .cs и .java требуется дополнительная настройка. См. пункт «Действия после установки Web-клиента».
