
== Дополнительные согласующие

Дополнительные согласующие – участники, добавленные другими согласующими в процессе согласования. Дополнительные согласующие автоматически добавляются в следующий цикл согласования (становятся полноправными участниками).

Добавление согласующих является вариантом завершения задания согласования, возможность принятия которого определяется настройками согласования.

Дополнительные согласующие добавляются в согласование сразу или после их утверждения инициатором согласования (необходимость утверждения определяется настройками согласования).

В последовательном согласовании дополнительные участники согласуют сразу после сотрудника, который их добавил; в параллельном – (после добавления) вместе с остальными участниками.

Согласование может вернуться к участнику, который добавил согласующих, если это предусмотрено настройками согласования: после принятия решения доп. согласующими и при отрицательном решении инициатора согласования по их добавлению.

* *xref:ApprovalAddApprovers.adoc[Добавление новых согласующих в согласование]* +
* *xref:ApprovalAcceptApprovers.adoc[Утверждение дополнительных согласующих]* +

*Parent topic:* xref:reconcilement_approvaldesigner.adoc[Согласование документов]
