
== Согласование договора

. Перейдите в папку [.ph .filepath]`Мои задания/Входящие`.
+
Для заместителя: нужно перейти в папку [.ph .filepath]`Замещение/Входящие`.
. Откройте полученное задание с описанием «Согласование документов» в состоянии `Не начато`.
. Выполните действия с согласуемыми документами:
* xref:tcardApprovalFileViewMain.adoc[ознакомьтесь с составом согласуемых файлов];
* ознакомьтесь с договором: нажмите на ссылку в разделе [.ph .uicontrol]*Ссылка на карточку* для перехода к договору;
* если требуется, xref:tcardApprovalFileVersionAdd.adoc[добавьте собственную версию договора].
. Для принятия решения по согласованию на xref:CardOperations.adoc[панели операций] нажмите кнопку:
* [.ph .uicontrol]*Согласовать*, [.ph .uicontrol]*Согласовать с замечаниями* – после завершения заданий всеми согласующими документ будет передан на xref:ConsolidationOfContract.adoc[консолидацию];
* [.ph .uicontrol]*Не согласовано* – документ будет отправлен на новый цикл согласования;
* [.ph .uicontrol]*Делегировать*, [.ph .uicontrol]*В работу*.

Общая информация по принятию решения по согласованию приведена в пункте xref:tcardApprovalPerformerGet.adoc[Принятие решения по согласованию документа].

*Parent topic:* xref:ContractsReconciliationDemo.adoc[Согласование и подписание договорных документов]
