= Отключить создание карточек определенного типа

В случае необходимости, администратор системы может отключить возможность создания из {wc}а карточек определенного типа. Когда функция отключена, соответствующий тип карточек будет скрыт из списка доступных для создания типов карточки вместе с подвидами:

* При нажатии кнопки *+ Создать* на панели управления.
* При создании карточки с добавлением ссылки из карточек _Документ_ и _Задание_.

.Чтобы скрыть тип карточки из меню создания:
. Откройте конфигурационный файл `{webconfig}`.
. Перейдите к элементу menu:configuration[{dv} > WebClient > CardTypes > CardType].
+
В элементе _CardTypes_ перечислены типы карточек, с которыми работает {wc}:
+
* `[CardTypeId="b9f7bfd7-7429-455e-a3f1-94ffb569c794"]` -- Документ.
* `[CardTypeId="c7b36f33-cdd4-4da9-8444-600fe14111e4"]` -- Задание.
* `[CardTypeId="2182e2a5-22a9-471f-9d65-e45deeae1c73"]` -- Группа заданий.
+
. Создайте или измените параметр *_DisableCreateFlags_* в элементе нужного типа карточек.
+
****
Значение параметра *_DisableCreateFlags_* является суммой цифр, каждая из которых определяет один из вариантов скрытия типа карточки:

* *_0_* -- не скрывать.
* *_1_* -- скрывать тип из списка типов при создании карточки при нажатии кнопки *+ Создать* на панели управления.
* *_2_* -- скрывать тип из списка типов при создании карточки с добавлением ссылки из карточек _Документ_ и _Задание_, а также при создании карточки в качестве отчета к _Заданию_.
* *_4_* -- скрывать тип из списка типов при создании связанного задания карточки _Документ_.
* *_8_* -- скрывать тип из списка типов при создании подчиненного задания карточки _Задание_.

.Изменение параметра "DisableCreateFlags"
====
[source]
----
<configuration>
  <{dv}>
    <WebClient>
      <CardTypes>
        <CardType CardTypeId="b9f7bfd7-7429-455e-a3f1-94ffb569c794" CssClass="document" SaveInFolder="true"
                  DisableCreateFlags="13" /> <.>
        <CardType CardTypeId="c7b36f33-cdd4-4da9-8444-600fe14111e4" />
        <CardType CardTypeId="2182e2a5-22a9-471f-9d65-e45deeae1c73" />
      </CardTypes>
    </WebClient>
  </{dv}>
</configuration>
----
<.> Чтобы отключить любую возможность создания карточки _Документ_ из {wc}а, укажите значение *_15_* (= 1+2+4+8). Чтобы скрыть тип карточки _Документ_ из списка типов при создании новой карточки, укажите значение *_1_*.

IMPORTANT: Параметр *_DisableCreateFlags_* не действует, когда меню создания карточки вызывается из настраиваемой разметки.
====
****
+
. Сохраните изменения конфигурационного файла.
