= Автоматически закрывать неактивные сессии пользователей

{wc} автоматически переводит в офлайн-режим сессии (подключение к серверу {dv}) неактивных пользователей. При этом у пользователей появится предупреждение о переводе сессии в офлайн. Впоследствии неактивные сессии будут закрыты. Таймер закрытия сессии запускается одновременно с переходом в офлайн-режим.

[NOTE]
====
После перевода пользовательской сессии в офлайн-режим или её закрытия будет остановлено автоматическое обновление счетчиков непрочитанных карточек и содержимого папок.
====

// tag::webconfig[]
.Чтобы изменить стандартные настройки сессии пользователей:
. Откройте конфигурационный файл `{webconfig}`.
. Перейдите к секции {setgroups-wc}.
. Измените значение параметра:
+
include::partial$table.adoc[]
|*_SessionSuspendTimeout_*
|Время неактивности пользователя в минутах, через которое сессия будет переведена в офлайн-режим. Значение по умолчанию -- 10 минут.

|*_SessionCloseTimeout_*
|Время неактивности пользователя в минутах, через которое сессия будет закрыта. Значение по умолчанию -- 300 минут.

|*_SessionInactiveMessageHide_*
|Отключает показ сообщения _"Подключение остановлено в связи с отсутствием активности"_.

Значение *_true_* Сообщение не отображается, сессия восстанавливается при нажатии курсором мыши в любой области окна {wc};

Значение *_false_* Сообщение отображается, сессия восстанавливается при нажатии курсором мыши на сообщение или в любой области окна {wc} (значение по умолчанию).
|===
+
Чтобы отключить перевод неактивной сессии в офлайн-режим, установите *_SessionSuspendTimeout_* в значение *_0_*.
+
Чтобы отключить закрытие неактивных сессий, установите *_SessionCloseTimeout_* в значение *_0_*.
// end::webconfig[]
+
. Сохраните изменения конфигурационного файла.

TIP: Сервер {wc}а проверяет неактивность пользователей через промежуток времени *_SessionSuspendTimeout * 0.5_*, поэтому перевод пользовательской сессии в офлайн-режим может быть выполнен в промежутке времени до *_SessionSuspendTimeout * 1.5_*.

IMPORTANT: Неактивные сессии не закрываются, если в конфигурационном файле {wc}а параметр xref:clear-cache-config.adoc[*_DisableClearSession_*] установлен в значении *_true_*.
