= Изменить логотип для штампа ЭП

По умолчанию в печатной версии подписанного файла, в штампе ЭП размещается логотип "Щит". Администратор может изменить изображение.

. Откройте конфигурационный файл `{webconfig}`.
. Перейдите к секции {setgroups} > SettingGroup[Name="DefaultESImageGenerator"\]].
+
TIP: По умолчанию данной секции нет -- её нужно создать самостоятельно.
+
. Измените значение параметра *_LogoImagePath_*, указав путь к PNG файлу нового логотипа (относительно каталога `{wcd}\5.5\Site\` или абсолютный).
+
[source,,l]
----
<SettingGroup Name="DefaultESImageGenerator">
   <Setting Name="LogoImagePath" Value="Content/logo.png" />
</SettingGroup>
----
+
Файл логотипа должен быть доступен процессу сервера {wc}а. Размер стандартного изображения: 127x131 пискелей. Изображение будет сжато в соответствии с фактическим размером штампа.
+
. Сохраните изменения конфигурационного файла.

[NOTE]
====
Предусмотрена возможность реализации собственной функции формирования штампа. Пример реализации см. в https://github.com/Docsvision/WebClient-Samples[репозитории ДоксВижн на GitHub].
====
