= Настроить работу {wc}а по HTTPS

По умолчанию {wc} работает по протоколу HTTP. Если требуется подключаться по защищённому соединению, потребуются дополнительные настройки.

[#create-cert]
.Создайте сертификат:
. Откройте _{dispatch}_.
. На начальной странице выберите _Сертификаты сервера_.
+
Будет открыто окно выбора доступных сертификатов. Вам необходимо создать новый сертификат.
. В области _Действия_ выберите *Создать самозаверенный сертификат*.
+
[NOTE]
====
Если у вас уже есть сертификат, выданный центром сертификации или компанией, вы можете его *Импортировать*. Вы также можете *Создать запрос сертификата* согласно https://www.ssl.com/ru/%D0%BA%D0%B0%D0%BA/%D1%81%D0%B3%D0%B5%D0%BD%D0%B5%D1%80%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%BF%D1%80%D0%BE%D1%81-%D0%BF%D0%BE%D0%B4%D0%BF%D0%B8%D1%81%D0%B8-%D1%81%D0%B5%D1%80%D1%82%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%B0-csr-%D0%B2-iis-10/[инструкции онлайн]. В последнем случае обратите внимание на следующее <<mind-this,примечание>>.
====
+
. В открывшемся окне введите понятное имя сертификата и нажмите *ОК*.
+
Сертификат будет создан и автоматически помещён в хранилище.

[start=5]
.Настройте привязки:
. Перейдите на сайт DocsVision в IIS. Например, Default Web Site.
. Справа в области _Действия_ выберите *Привязки*.
. В появившемся окне нажмите *Добавить*.
. Выберите _Тип_: *_https_*. Поставьте _IP-адрес_ в значение *_"Все неназначенные"_*, укажите `Порт` 443.
. В поле `Имя узла` введите адрес подключения к {wc}у.
. Выберите SSL-сертификат, созданный ранее из списка или, нажав на кнопку *Выбрать*. Нажмите *ОК*.
. Повторите шаги 1 -- 6, если требуется задать привязки для нескольких адресов.

[#mind-this]
[CAUTION]
Данная настройка не исключает возможности подключения по HTTP. Если вы хотите, чтобы клиенты могли работать в {wc}е только по HTTPS, выполните шаги из пункта <<limit-http>>.

[#limit-http]
[start=12]
.Ограничьте использование HTTP:
. Перейдите на сайт {wc}а в IIS. По умолчанию DocsVisionWebClient.
. В окне выберите "Параметры SSL".
. Поставьте флаг `*Требовать SSL*`. В списке `*Сертификаты клиента*` выберите *Принимать*.
. В области _Действия_ справа нажмите *Применить*.
+
Будут сохранены настройки. Убедитесь, что клиенты уведомлены о необходимости вводить адрес через *http__s__*. В противном случае при вводе адреса {wc}а через *http* клиенты получат ошибку.
+
. Откройте {pu}.
. На панели управления {wc} выберите раздел _"xref:control-panel-webc.adoc[{wc}]"_ и нажмите *Обновить* напротив адреса {wc}а.
+
[WARNING]
====
При настройке Параметров SSL в диспетчере IIS не устанавливайте флаг `*Требовать SSL*` для Default Web Site или сайта DocsVision. Если установить флаг для этих сайтов, Windows клиент и другие модули будут требовать защищённое подключение. Понадобится настроить адрес сервера в Консоли настройки DocsVision см. Руководство Администратора модуля {pl}, раздел Настройки сервера. Адрес подключения понадобится также сменить на всех клиентских машинах.
====
