= Управление временем жизни пользовательских cookie

Управлять временем действия пользовательской сессии можно с помощью настроек в конфигурационном файле {wc}а:

[source]
----
<Setting Name="AuthCookieAutoRenewalInterval" Value="0" /> <.>
<Setting Name="AuthCookieLifetime" Value="120" /> <.>
<Setting Name="MobileAuthCookieLifetime" Value="120" /> <.>
----
<.> Интервал автоматического обновления сессии.
<.> Период действия пользовательской сессии.
<.> Период действия пользовательской сессии на мобильных устройствах.

.Принцип действия настроек:
. Настройка позволяет продлевать срок уже выданных cookie, если пользователь зашёл до того, как они истекли.
+
По умолчанию настройка отключена, то есть установлена в значение `0`. Можно задать количество часов.
+
Когда пользователь авторизуется в {wc}е, ему по умолчанию выдаются cookie на 5 дней. Если в настройке указано значение `24` часа, действие cookie будет продлено, когда пользователь откроет {wc}. Действие cookie будет продлено только, если пользователь откроет {wc} до истечения сессии в течение 5 дней.
+
. Вторая настройка устанавливает период действия пользовательской сессии. Значение по умолчанию: 120 часов (5 дней).
. Третья настройка отдельно задаёт период действия пользовательской сессии на мобильных устройствах. Значение по умолчанию: 120 часов (5 дней).

Настройки можно комбинировать. Например, задать для `AuthCookieLifetime` значение `240` часов, чтобы все пользователи получали cookie на 10 дней. Для настройки `MobileAuthCookieLifetime` можно указать период в `720` часов (30 дней). А также установить значение `AuthCookieAutoRenewalInterval` на `72` часа, чтобы при открытии {wc}а в течение двух дней с предыдущей авторизации cookie автоматически продлевались.
