= Настройка меню создания карточек

Администратор {wc}а может изменить настройки меню создания карточек: добавить или удалить типы карточек, изменить последовательность отображения типов.

// tag::webconfig[]
.Чтобы изменить настройки меню создания карточек:
. Откройте конфигурационный файл `{webconfig}`.
. Перейдите к элементу menu:{dv}[WebClient > CardTypes].
. Измените конфигурацию:
* Чтобы изменить порядок кнопок создания типов карточек, измените порядок строк в *_CardTypes_*.
* Чтобы добавить новый тип карточек, добавьте в секцию *_CardTypes_* строку следующего формата:
+
[source]
----
<CardType CardTypeId="<>" /> <.>
----
<.> CardTypeId -- GUID идентификатор типа карточки.
// end::webconfig[]
+
IMPORTANT: {wc} поддерживает работу только с карточками, созданными на основе _Базовых объектов_.
+
* Чтобы новые карточки выбранного типа сохранялись в текущей открытой папке, добавьте в элемент *_CardType_* параметр *_SaveInFolder_* со значением *_true_*.
+
.Сохранять карточки с данным GUID в текущей папке:
[source]
----
<CardType CardTypeId="b9f7bfd7-7429-455e-a3f1-94ffb569c794" SaveInFolder="true" />
----
+
Если *_SaveInFolder_* имеет значение `false` (или отсутствует), ярлыки карточек не будут добавляться в текущую папку.
+
* Чтобы изменить цвет строки типа карточки в меню создания карточек, добавьте в элемент *_CardType_* параметр *_CssClass_* с названием класса CSS в значении:
+
[source]
----
<CardType CardTypeId="b9f7bfd7-7429-455e-a3f1-94ffb569c794" CssClass="document" />
----
+
Чтобы данная функциональность работала, к {wc}у должен быть подключен файл стилей с CSS-классом `%Значение атрибута CssClass%-color`:
+
[source,css]
----
.document-color {
    background-color: #639;
}
----
+
. Сохраните изменения конфигурационного файла.
