= Обновление {wc}а без импорта решений

При обновлении {wc}а происходит проверка параметра *_LoadLayouts_* конфигурационного файла панели управления {wc}а, расположенного по адресу `/%LocalAppData%\Docsvision\WebClientAdminConsole.config`.

Если файл отсутствует или значение *_LoadLayouts_* *_true_*, {wc} будет обновлён в стандартном режиме с импортом решений в базу данных.

Если значение *_LoadLayouts_* *_false_*, при обновлении {wc}а решения не будут автоматически загружены в базу данных, и администратор должен будет сделать это самостоятельно позднее.

.Чтобы включить режим обновления без импорта решений:
. На сервере с модулем _{wc}_ перейдите по адресу `/%LocalAppData%/Docsvision`.
. Создайте в папке документ `WebClientAdminConsole.config` при помощи любого текстового редактора.
. Добавьте в файл следующие строки, при необходимости заменив `true` на `false`:
+
====
[source,,l,language-xml]
----
<?xml version="1.0" encoding="utf-8"?>
<WebAdminConsoleSettings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <LoadLayouts>false</LoadLayouts>
</WebAdminConsoleSettings>
----
====
. Закройте файл с сохранением изменений.
+
****
Обновление {wc}а будет происходить без автоматической загрузки решений в базу данных.
****

