= Порядок кнопок "ОК/Отмена" по умолчанию

Порядок кнопок *ОК*/*Сохранить* и *Отмена*, отображаемых в диалоговых окнах и разметках {wc}а, может быть настроен. Пользователь может настроить схему расположения в меню _Профиль_. Администратор может установить порядок расположения по умолчанию, который будет действовать до выбора нового значения пользователем.

. Откройте конфигурационный файл `{webconfig}`.
. Перейдите к секции {setgroupsWC}.
. Измените значение параметра *_DefaultButtonPosition_*:
+
.Значение параметра "DefaultButtonPosition"
[cols="33,66",frame="none",grid="none"]
|===
|*_Auto_*
|Значение по умолчанию -- порядок отображения кнопок определяется типом ОС пользователя:

для ОС MacOS: *Отмена*/*OK*;

для ОС Windows, Android и др. – *ОК*/*Отмена*.

|*_OkCancel_*
|*ОК*/*Отмена*

|*_CancelOk_*
| *Отмена*/*ОК*;
|===
+
====
Пример включения режима *Отмена*/*ОК*:
[source,,l]
----
<Setting Name="DefaultButtonPosition" Value="CancelOk" />
----
====
. Сохраните изменения конфигурационного файла.
