= Изменить способ обновления справочников в режиме "только чтение"

[NOTE]
====
Настройка, рассмотренная в данном пункте, применяется, если включена экспериментальная функция xref:experimentSharedDictionaties.adoc[Общие справочники].
====

{wc} использует справочники, данные которых только читаются и не изменяются, в режиме "только чтение". В данном режиме один справочник используется всеми сессиями и обновляется в соответствии со стратегией обновления, установленной в настройках {wc}.

Администратор может изменить режим обновления таких справочников в зависимости от требований к актуальности их данных. Увеличение частоты обновления ведёт к увеличению числа обращений с северу {dv}, а уменьшение -- к возможности получения устаревших данных.

.Чтобы изменить способ обновления справочников:
. Откройте конфигурационный файл `{webconfig}`.
. Перейдите к секции {setgroupsWC}.
. Измените значение параметра *_SharedDictionaryRefreshMode_*. Параметр определяет способ обновления справочников.
+
.Возможные значения:
include::partial$table.adoc[]
|*_0_*
|Обновление выполняется с интервалом, указанным в параметре *_SharedDictionaryRefreshPeriod_*. Значение указывается в секундах, по умолчанию -- 60 секунд.
|*_1_*
|Если в одной из сессий данные справочника в режиме только чтение были изменены, обновление будет выполнено при следующем обращении.
|*_2_*
|Если в одной из сессий данные справочника в режиме только чтение были изменены, обновление будет выполнено сразу после изменения (значение по умолчанию).
|===
+
====
Далее приведён пример конфигурации, включающей периодическое обновление справочника с периодом 2 минуты.
[source,]
----
<Setting Name="SharedDictionaryRefreshMode" Value="0" />
<Setting Name="SharedDictionaryRefreshPeriod" Value="120" />
----
====
+
TIP: Если указанных параметров нет в конфигурационном файле, создайте их самостоятельно.
+
. Сохраните изменения конфигурационного файла.
