
== Изменение способа обновления справочников в режиме «только чтение»

[NOTE]
====
[.note__title]#Note:# Настройка, рассмотренная в данном пункте, применяется, если включена экспериментальная функция xref:NewFunction_SharedDictionaties.adoc[«Общие справочники»].
====

В {wc}е справочники, данные которых только читаются и не изменяются, используются в режиме «только чтение». В данном режиме один справочник используется всеми сессиями и обновляется в соответствии со стратегией обновления, установленной в настройках Модуля.

Администратор может изменить режим обновления таких справочников в зависимости от требований к актуальности их данных. Увеличение частоты обновление ведёт к увеличению числа обращений с северу {dv}, а уменьшение – к возможности получения устаревших данных.

Для изменения способа обновления справочников:

. Откройте конфигурационный файл [.ph]#[.ph .filepath]`{wcd}\5.5\Site\web.config`#.
. Перейдите к секции [.ph .menucascade]#[.ph .uicontrol]*configuration* > [.ph .uicontrol]*{dv}* > [.ph .uicontrol]*WebClient* > [.ph .uicontrol]*SettingGroups* > [.ph .uicontrol]*SettingGroup[Name="WebClient"]*#.
. Измените значение параметра `SharedDictionaryRefreshMode` – определяет способ обновления справочников. Возможные значения:
* 0 – периодическое обновление с периодом, указанным в параметре `SharedDictionaryRefreshPeriod`;
* 1 – обновление справочника, предоставляемого в режиме чтения, выполняется при следующем обращении, если в одной из сессий были изменены данные справочника;
* 2 (по умолчанию) – данные справочника, предоставляемого в режиме чтения, обновляются сразу после изменения данные справочника в одной из сессий.
. Если `SharedDictionaryRefreshMode` установлен в режиме периодического обновления (0), установите период обновления в параметре `SharedDictionaryRefreshPeriod` в секундах. Период обновления по умолчанию – 60 секунд.
+
Далее приведён пример конфигурации, включающей периодическое обновление справочника с периодом 2 минуты.
+
[source,pre,codeblock]
----
<Setting Name="SharedDictionaryRefreshMode" Value="0"/>
<Setting Name="SharedDictionaryRefreshMode" Value="120"/>
----
+
Если указанных параметров нет в конфигурационном файле, создайте их самостоятельно.
. Сохраните изменения конфигурационного файла.

*Parent topic:* xref:CacheConf.adoc[Настройки кэширования]
