= Функция "Общие справочники"

Данная функция включает особый режим работы со справочниками, данные которых используются только в режиме чтения.

Функция по умолчанию активна в {wc}е, начиная с версии 17.

Использование функции _Общие справочники_ призвано сократить потребления памяти процессом сервера {dv}.

== Изменить способ обновления справочников в режиме "только чтение"

{wc} использует справочники, данные которых только читаются и не изменяются, в режиме "только чтение". В данном режиме один справочник используется всеми сессиями и обновляется в соответствии со стратегией обновления, установленной в настройках {wc}.

Администратор может изменить режим обновления таких справочников в зависимости от требований к актуальности их данных. Увеличение частоты обновления ведёт к увеличению числа обращений с северу {dv}, а уменьшение -- к возможности получения устаревших данных.

.Чтобы изменить способ обновления справочников:
. Откройте конфигурационный файл `{webconfig}`.
. Перейдите к секции {setgroups-wc}.
. Измените значение параметра *_SharedDictionaryRefreshMode_*. Параметр определяет способ обновления справочников.
+
.Возможные значения:
include::partial$table.adoc[]
|*_0_*
|Обновление выполняется с интервалом, указанным в параметре *_SharedDictionaryRefreshPeriod_*. Значение указывается в секундах, по умолчанию -- 600 секунд.
|*_1_*
|Если в одной из сессий данные справочника в режиме только чтение были изменены, обновление будет выполнено при следующем обращении.
|*_2_*
|Если в одной из сессий данные справочника в режиме только чтение были изменены, обновление будет выполнено сразу после изменения (значение по умолчанию).
|===
+
.Задать период обновления справочника равный 2 минутам
====
Если указанных параметров нет в конфигурационном файле, создайте их самостоятельно.

[source]
----
<Setting Name="SharedDictionaryRefreshMode" Value="0" />
<Setting Name="SharedDictionaryRefreshPeriod" Value="120" />
----
====
+
. Сохраните изменения конфигурационного файла.
