
== Включение протоколирования событий навигации

Администратор может включить ведение протокола для записи информации о событиях клиентской навигации, для анализа ошибок, связанных с переходами между страницами и отображением некорректной информации. В лог (браузера) записывается информация о специальных навигационных обработчиках, передаваемым им параметрах и результатах их работы.

. [.ph .cmd]#Откройте конфигурационный файл [.ph]#[.ph .filepath]`{wcd}\5.5\Site\web.config`#.#
. [.ph .cmd]#Перейдите к секции [.ph .menucascade]#[.ph .uicontrol]*configuration* > [.ph .uicontrol]*{dv}* > [.ph .uicontrol]*WebClient* > [.ph .uicontrol]*SettingGroups* > [.ph .uicontrol]*SettingGroup[Name="WebClient"]*#.#
. [.ph .cmd]#Измените в [.keyword]*True* значение параметра `EnableRouterLogging`:#
+
[source,pre,codeblock]
----
<SettingGroup Name="WebClient">
 <Setting Name="EnableRouterLogging" Value="True" />
</SettingGroup>
----
+
Если указанного параметра нет в конфигурационном файле, создайте его самостоятельно.
. [.ph .cmd]#Сохраните изменения конфигурационного файла.#

*Parent topic:* xref:logging.adoc[Настройки протоколирования событий]
