= Включить счетчики производительности

{wc} предоставляет администратору возможность анализировать параметры работы с помощью счетчиков производительности -- встроенного механизма ОС Windows.

Модуль предоставляет следующие группы счетчиков:

{dv} WebClient AdvancedLayouts opening::
Позволяют оценить время формирования разметки карточек.
{dv} WebClient Grid first opening::
Позволяют оценить время формирования представления папки.
{dv} WebClient Grid paging::
Позволяют оценить время формирования страницы представления папки.
{dv} WebClient ExtendedLayouts first opening::
Позволяют оценить время формирования разметки дерева папок и дашборда.
{dv} WebClient summary::
Позволяют учитывать количество открытых пользовательских сессий.

По умолчанию счетчики производительности выключены.

.Чтобы включить счетчики:
. Откройте конфигурационный файл `{webconfig}`.
. Перейдите к секции {setgroupsWC}.
. Измените на *_True_* значение параметра `EnablePerformanceCounters`:
+
====
[source,,l]
----
<SettingGroup Name="WebClient">
 <Setting Name="EnablePerformanceCounters" Value="True" />
</SettingGroup>
----
====
+
TIP: Если указанного параметра нет в конфигурационном файле, создайте его самостоятельно.
+
. [.ph .cmd]#Сохраните изменения конфигурационного файла.#

Чтобы сбросить счетчики производительности:

. xref:controlPanel.adoc[Откройте Панель управления].
. Нажмите на кнопку [.ph .uicontrol]*Reset perf. counters* на начальной странице.
