
== Функция «Контрол комментарии с html редактором»

Данная функция делает доступным новое свойство элемента управления комментарии. Свойство «Использовать HTML редактор», при активации, открывает возможность форматирования текста комментария с поддержкой HTML-синтаксиса и упоминания сотрудников.

Включение данной функции на Панели управления {wc}ом добавляет новое по умолчанию неактивное свойство «Использовать HTML редактор» в элемент управления [.ph .uicontrol]*Комментарии* в программе _{kvr}_. После включения экспериментальной функции необходимо перейти в {kvr} и активировать свойство (поставить флаг). Новое свойство позволяет упоминать сотрудников в комментариях через символ @, а также форматировать текст комментария в процессе ввода с использованием HTML-редактора.

Возможность отправки уведомления об упоминании на электронную почту сотрудника отсутствует. При желании такая возможность может быть настроена самостоятельно с помощью бизнес-процессов или иных средств.

*На уровень выше:* xref:enableExperimentalFunction.adoc[Экспериментальные функции]
