= Отключить кэширование разметок фильтров данных

По умолчанию {wc} использует серверный кэш для хранения разметок фильтров данных в представлении. Кэш обновляется при перезапуске сервера {wc}, а также автоматически при изменении настроек представления.

Администратору нужно отключить кэширование разметок фильтров, если в {wc}е планируется использовать две или более разметки представлений. Если кэширование не отключено, пользователи могут получать разметки фильтра, не соответствующие условиям выбора разметок, указанным в программе {kvr}.

.Чтобы отключить кэширование разметок:
. Откройте конфигурационный файл `{webconfig}`.
. Перейдите к секции {setgroupsWC}.
. Установите значение параметра `MinCheckDirectoryTimestampsInterval` в `false`:
+
[source]
----
<SettingGroup Name="WebClient">
    <Setting Name="GridFilterCache" Value="false" />
</SettingGroup>
----
+
TIP: Если указанного параметра нет в конфигурационном файле, создайте его самостоятельно.
+
. Сохраните изменения конфигурационного файла.
