= Настройки агрегации

include::user:page$grid-aggregate.adoc[tags=whatis]

== Доступность агрегации

Для работы с агрегацией требуется иметь опцию _Docsvision Модуль Интеллектуальный поиск_ лицензии {dv}. Если опция отключена, {es} работает как полнотекстовый поиск без функции агрегации.

Агрегация доступна только для пользователей, включённых в группу безопасности Windows *DocsVision Aggregation Users* и в группу _Использование агрегатов_ в справочнике сотрудников.

Сотрудники, включенные в эти группы, получают доступ к использованию агрегации с {es}. Для пользователей, которым не разрешена работа с агрегацией, не отображается дополнительная  область в интерфейсе {wc}а. При использовании {es} для таких пользователей будут выводиться только результаты поиска.

Настройки включения в группы применятся только в новой сессии пользователя. Чтобы настройки применились, необходимо повторно выполнить вход в {wc}.

== Задержка обновления агрегации

Администратор может настроить задержку обновления списка карточек и доступных агрегатов при использовании {es}.

.Чтобы настроить автоматическое применение по таймеру:
. Откройте файл {webconfig}.
. Измените значение параметра, заданное по умолчанию:
+
--
[source]
----
<SettingGroup Name="Grid">
        <Setting Name="ApplyAggregatesTimeout" Value="1000" /> <.>
        <Setting Name="ApplyAggregatesButton " Value="True" /> <.>
</SettingGroup>
----
<.> По истечении указанного количества миллисекунд будут автоматически обновлены список карточек и доступные агрегаты.
<.> Флаг определяет, будет ли список карточек обновляться автоматически или перестраиваться по нажатию кнопки *Применить*.
+
Доступные агрегаты обновляются согласно настройке `ApplyAggregatesTimeout`.
--
