
== Групповые операции

Групповая операция – операция, которая применяется сразу к нескольким карточкам.

В Web-клиенте есть следующие особенности работы с групповыми операциями:

* Групповая операция является синхронной – во время её выполнения блокируется возможность выполнения других операций.
* Операции групповой операции выполняются последовательно.
* Групповая операция является прерываемой – пользователь может прервать её выполнение, при этом невыполненные операции не будут выполнены.
* Групповая операция выполняется в веб-браузере – страница Web-клиента, в которой выполняется групповая операция, должна оставаться открытой до завершения, иначе выполнение будет прервано.
* Проверка возможности выполнения операции осуществляется при её выполнении.

* *xref:../topics/EnterToGroupOperationsMode.html[Переключение в режим групповых операций]* +
* *xref:../topics/GroupOperationsDelegate.html[Групповое делегирование заданий]* +
* *xref:../topics/BatchOperationMoveShortcuts.html[Перемещение ярлыков карточек]* +
* *xref:../topics/GroupOpsCopyTags.html[Копирование ярлыков карточек]* +
* *xref:../topics/GroupOpsDeleteTags.html[Удаление ярлыков карточек]* +
