= Режим скрытия правой боковой панели

На правой боковой панели отображаются параметры отправки документа на согласование, на ознакомление и пр. По умолчанию панель скрывается при нажатии на ней кнопок выполнения: *ОК*, *Отмена* и пр. Администратор может включить режим, при котором панель также будет скрываться по щелчку в любой области страницы {wc}а вне боковой панели.

// tag::webconfig[]
.Чтобы изменить режим скрытия панели:
. Откройте конфигурационный файл `{webconfig}`.
. Перейдите к секции {setgroups-wc}.
. Измените значение параметра *_HideSidebarOnPageClick_*:
* *_false_* (значение по умолчанию) -- панель должна скрываться только при нажатии кнопки *ОК*/*Отмена* и пр.
* *_true_* -- панель также должна скрываться при щелчке вне боковой панели.
+
====
Пример включения режима, при котором панель будет скрываться нажатием кнопки *ОК*/*Отмена* и пр., а также при щелчке вне боковой панели:

[source]
----
<Setting Name="HideSidebarOnPageClick" Value="true" />
----
====
// end::webconfig[]
. Сохраните изменения конфигурационного файла.
