= Настройка журналирования

События {wc}а протоколируются с помощью компонента NLog (http://nlog-project.org).

include::partial$nlog.adoc[]

Базовые настройки журналирования представлены в панели управления (xref:control-panel-webc.adoc[Раздел "WebClient"]). Расширенные настройки осуществляются в конфигурационном файле {wc}а.

. Откройте конфигурационный файл `{webconfig}`.
. Перейдите к секции menu:configuration[nlog].
. Измените параметры журналирования.
+
Измените значение атрибута *_fileName_* элемента menu:targets[target > target], чтобы настроить путь для сохранения журнала работы.
+
TIP: В *_fileName_* можно использовать допустимые для Nlog переменные (https://github.com/nlog/NLog/wiki/File-target), например: `C:\Logs\$\{level}\WebClient_$\{shortdate}.log`.
+
Измените значение атрибута *_level_* элемента menu:rules[logger], например, на *_trace_*, чтобы включить протоколирование всех типов событий.
+
TIP: Допустимые уровни протоколирования приведены на странице https://github.com/nlog/NLog/wiki/Configuration-file#log-levels.
+
Для получения дополнительной информации о других настройках NLog обратитесь к документации по данной платформе.
+
. Сохраните изменения конфигурационного файла.
+
[NOTE]
====
Уровень журналирования может быть изменён методом `/api/Log/SetLogLevel`, если пользователь, который вызывает метод, состоит в группе _{dv} Administrators_. Методом можно задать следующие уровни: *_Trace = 0_*, *_Debug = 1_*, *_Info = 2_*, *_Warn = 3_*, *_Error = 4_* (любое другое значение будет распознано как *_Error_*).

Данный способ применим для случая, когда есть потребность не перезагружать пул {wc}а. После рестарта IIS уровень журналирования будет возвращён в исходное состояние в соответствии с конфигурационным файлом.
====
