= Ограничить размер прикладываемых файлов

В {wc}е по умолчанию действует несколько ограничений, влияющих на возможность прикладывания "тяжелых" файлов:

* Максимальный размер файла, прикладываемого при создании карточки. Значение по умолчанию: 50 Мб.
* Максимальный размер всех прикладываемых файлов одной карточки. Значение по умолчанию: 128 Мб.

Администратор системы может изменить действующее ограничение.

// tag::webconfig[]
.Чтобы изменить ограничение для максимального размера единичного файла:
. Откройте конфигурационный файл `{webconfig}`.
. Перейдите к элементу {setgroups} > Setting [Name="MaxUploadFileItemSize"\]].
. Укажите новое ограничение в параметре `Value`. Тип `int`, значение в байтах, но не более `2147483647`.
. Сохраните изменения конфигурационного файла.

.Чтобы изменить ограничение для максимального общего размера всех добавляемых файлов карточки:
. Перейдите к элементу menu:configuration[system.webServer > security > requestFiltering > requestLimits].
. Укажите новое ограничение в параметре `_maxAllowedContentLength_`. Тип `uint` и значение в байтах, но не более `4294967295`.
. Установите аналогичное значение в параметре `_maxRequestLength_`, тип int, значение в байтах не более `2147483647` в элементах:
+
* menu:configuration[location[path="api/DocumentCardApi"\] > system.web > httpRuntime].
* menu:configuration[location[path="api/LayoutFileApi"\] > system.web > httpRuntime].
+
[NOTE]
====
Указанные параметры ограничивают общий размер файлов только для элемента управления _Список файлов_. Для элемента управления _Файл_ данные ограничения действуют на единичный файл.

Значения указанных параметров должны быть не меньше, чем значение параметра `_MaxUploadFileItemSize_` (см. выше).
====
// end::webconfig[]
+
. Сохраните изменения конфигурационного файла.
