= Ограничить количество отображаемых карточек в папке

{wc} ограничивает количество карточек, отображаемых на одной странице представления папки. Ограничение устанавливается или для всех папок, или для каждой папки по отдельности. В первом случае используется параметр, который настраивается в конфигурационном файле {wc}. Во втором случае максимальное количество вычисляется из свойств папки, настроенных в {wincl}е.

[NOTE]
====
Ограничение распространяется только на представление папки -- результаты поиска по представлению, результаты полнотекстового поиска и т.п. настройкой не ограничены.
====

По умолчанию {wc} использует собственное ограничение максимального количества в 15 карточек на страницу представления.

Чтобы изменить максимальное количество карточек на страницу представления:

. Откройте конфигурационный файл `{webconfig}`.
. Перейдите к элементу {setgroups} > SettingGroup[Name="Views"\] > Setting[Name="DefaultPageSize"\]].
+
.Изменение максимального количества карточек на страницу
====
Если данного элемента нет, создайте его:

[source]
----
<SettingGroup Name="Views">
   <Setting Name="DefaultPageSize" Value="15" />
</SettingGroup>
----
====
+
. Укажите в значении *_Value_* параметра *_DefaultPageSize_* другое максимальное число карточек.
. Сохраните изменения конфигурационного файла.

Чтобы переключить {wc} на использование ограничений, установленных в свойствах папок, измените параметр "Ограничение количества выводимых записей":

. Откройте конфигурационный файл `{webconfig}`.
. Перейдите к элементу {setgroups} > SettingGroup[Name="Views"\] > Setting[Name="UseFolderPropertyRestrictionPageSize"\]].
+
.Использование ограничения из свойств папки
====
Если данного элемента нет, создайте его:

[source]
----
<SettingGroup Name="Views">
   <Setting Name="UseFolderPropertyRestrictionPageSize" Value="true" />
</SettingGroup>
----
====
+
. Измените значение настройки *_UseFolderPropertyRestrictionPageSize_*:
+
[horizontal]
true::
Использовать ограничение, установленное в {dv}.
+
TIP: Если в настройках папки ограничение не установлено, то в представлении папки будут отображаться все карточки без разбивки на страницы.
+
false::
Использовать собственное ограничение {wc}, настройка *_DefaultPageSize_* (значение по умолчанию).
+
. Сохраните изменения конфигурационного файла.
