= Ограничить размер прикладываемых файлов

В {wc}е по умолчанию действует несколько ограничений, влияющих на возможность прикладывания «тяжелых» файлов:

. Максимальный размер файла, прикладываемого при создании карточки. Значение по умолчанию: 50 МБ.
. Максимальный размер всех прикладываемых файлов одной карточки. Значение по умолчанию: 128 МБ.

Администратор системы может изменить действующее ограничение. Для этого:

. [.ph .cmd]#Откройте конфигурационный файл `{webconfig}`.
. [.ph .cmd]#Чтобы изменить ограничение для максимального размера единичного файл:#
[loweralpha]
.. [.ph .cmd]#Перейдите к элементу {setgroups} > *Setting [Name="MaxUploadFileItemSize"]*#.#
.. [.ph .cmd]#Укажите новое ограничение в параметре `Value`. Значение в байтах.#
. [.ph .cmd]#Чтобы изменить ограничение для максимального общего размера всех добавляемых файл карточки:#
[loweralpha]
.. [.ph .cmd]#Перейдите к элементу [.ph .menucascade]#*configuration* > *system.webServer* > *security* > *requestFiltering* > *requestLimits*#.#
.. [.ph .cmd]#Укажите новое ограничение в параметре `maxAllowedContentLength`. Значение в байтах.#
.. [.ph .cmd]#Установите аналогичное значение в параметре `maxRequestLength` в элементах:#
+
* [.ph .menucascade]#*configuration* > *location[path="api/DocumentCardApi"]* > *system.web* > *httpRuntime*#;
* [.ph .menucascade]#*configuration* > *location[path="api/LayoutFileApi"]* > *system.web* > *httpRuntime*#.
+
Обратите внимание:

* Указанные параметры ограничивают общий размер файлов только для элемента управления *Список файлов*. Для элемента управления *Файл* данные ограничения действуют на единичный файл.
* Значения указанных параметров должны быть не меньше, чем значение параметра «MaxUploadFileItemSize» (см. выше).
. [#task_z3l_lzr_3k__step_fhk_dyz_zy]#[.ph .cmd]#Сохраните изменения конфигурационного файла.##
