
== Мобильная и полная версия Web-клиента

Интерфейс Web-клиента соответствует типу устройства, на котором выполняется работа: на персональном компьютере – полная версия; на мобильных устройствах – мобильная. Пользователь может переключить вид интерфейса из xref:dvweb_folder_tree.html[Основного меню].

Мобильная версия предоставляет все функции полной версии с некоторыми ограничениями, которые обусловлены возможностями мобильного устройства: специальное форматирование страниц Web-клиента для размещения элементов на небольшом экране, отсутствие функции сканирования документов и некоторые другие.

Функции Web-клиента, рассматриваемые в данном документе, соответствуют полной версии. Если реализация или способ использования функции в мобильной версии отличается, или данная функция не предоставляется, это будет отмечено отдельно.

Если для полной версии написано «щелкнуть» или «нажать», в мобильной версии нужно «коснуться» указанного элемента.

*Parent topic:* xref:../topics/Introduction.html[Введение]
