= Работа в мультитенантном режиме

{wc} поддерживает работу в мультитенантном режиме без дополнительных настроек. В мультитенантном режиме имеет значение адрес открытия {wc}а. Для правильной работы мультитенантного режима необходимо выполнить следующие условия:

[#requirements]
- [*] Во всех БД, версии модулей должны соответствовать xref:ROOT:requirements-dv.adoc#modules[требованиям], если планируется работать в мультитенантном режиме.
- [*] Вводимый адрес с указанием псевдонима БД должен настроен на соответствие адресу подключения к серверу {dv}.
- [*] Адрес должен быть введён правильно.
+
До первой точки указывается псевдоним БД, в которой планируется работа, например, `\http://**oldDB.**company.com/Docsvision/WebClient/#/Dashboard`.
+
Если все условия выполнены, {wc} сможет подключиться к любой указанной БД. При загрузке страницы будет предложено авторизоваться в новой БД. Такая схема позволяет работать одновременно в нескольких БД от имени разных пользователей.

[#multitenant-auth]
== Авторизация в мультитенантном режиме

.Чтобы авторизоваться под именем другого пользователя:
. Откройте {wc} в новой вкладке, указав в адресе точку подключения к БД, например, `\http://newDB.company.com/{dv}/WebClient/#/Dashboard`.

Текущая активная БД в мультитенантном режиме указывается рядом с фотографией, под именем текущего пользователя только, если пользователь является Администратором. Текущую БД всегда можно проверить из меню xref:user:interface-user-menu.adoc#aboutModule["О программе"].

Если указать адрес по умолчанию без псевдонима БД, {wc} подключится к БД, заданной по умолчанию в _{cns}_.

Если адрес с псевдонимом БД указан корректно, но {wc} всё равно не подключается к нужной БД, убедитесь ещё раз, что выполнены все <<requirements,требования>>.

====
Если адрес подключения к серверу {dv} выглядит следующим образом: `\http://company.com/{dv}/WebClient/#/Dashboard`

Адрес подключения {wc}а к БД с псевдонимом *newDB* будет следующий: `http://**newDB.**company.com/{dv}/WebClient/#/Dashboard`.

Псевдоним БД указывается до первой точки в адресе.

Администратор может настроить адрес подключения с помощью файла _hosts_ или других инструментов.
====
