= Включить счетчики производительности

{wc} предоставляет администратору возможность анализировать параметры работы с помощью счетчиков производительности -- встроенного механизма ОС Windows.

{wc} предоставляет следующие группы счетчиков:

{dv} WebClient AdvancedLayouts opening::
Позволяют оценить время формирования разметки карточек.
{dv} WebClient Grid first opening::
Позволяют оценить время формирования представления папки.
{dv} WebClient Grid paging::
Позволяют оценить время формирования страницы представления папки.
{dv} WebClient ExtendedLayouts first opening::
Позволяют оценить время формирования разметки дерева папок и дашборда.
{dv} WebClient summary::
Позволяют учитывать количество открытых пользовательских сессий.

По умолчанию счетчики производительности выключены.

.Чтобы включить счетчики:
. Откройте конфигурационный файл `{webconfig}`.
. Перейдите к секции {setgroups-wc}.
. Измените значение параметра `EnablePerformanceCounters` на *_True_* :
+
.Включение счетчиков производительности
====
Если указанного параметра нет в конфигурационном файле, создайте его самостоятельно.

[source]
----
<SettingGroup Name="WebClient">
 <Setting Name="EnablePerformanceCounters" Value="True" />
</SettingGroup>
----
====
+
. Сохраните изменения конфигурационного файла.

== Сбросить счётчики производительности

.Чтобы сбросить счетчики производительности:
. xref:control-panel.adoc[Откройте Панель управления].
. Нажмите на кнопку xref:control-panel.adoc#reset-counters["Сбросить счетчики произв."] на начальной странице.
