
== Назначение и функции Модуля

«Docsvision 5. Web-клиент» является [.dfn .term]_дополнительным модулем_ системы «Docsvision 5.5», который предоставляет возможность работать с карточками системы Docsvision и осуществлять основные операции с электронными документами в веб-браузере на персональном компьютере и на мобильном устройстве.

Модуль обеспечивает выполнение следующих функциональных задач:

. Работа с документами:
* создание и просмотр документов;
* просмотр приложенных к документам файлов офисных и графических форматов в веб-браузере;
* согласование документов с использованием расширенных маршрутов согласования приложения «Docsvision 5. Конструктор согласований».
. Работа с заданиями:
* создание, просмотр и отправка на исполнение заданий;
* исполнение или делегирование поступивших на исполнение заданий;
* просмотр приложенных к заданиям файлов офисных и графических форматов в веб-браузере;
* создание подчинённых заданий и групп заданий.
. Поиск карточек:
* в выбранной папке;
* по всей базе данных с помощью полнотекстового поиска.

Модуль предоставляет «Конструктор Web-разметок» для настройки разметок карточек:

* создание разметок для зарегистрированных типов карточек;
* использование сценариев (язык JavaScript) для обработки событий разметки;
* создание правил для выбора разметки карточки в зависимости от роли сотрудника и состояния карточки;
* локализация разметок.

Модуль предоставляет возможность разрабатывать новые компоненты:

* типы элементов управления для настройки разметок;
* серверные расширения для получения дополнительной серверной бизнес-логики.

*На уровень выше:* xref:../topics/General_information.html[Общие сведения]
