
== Регистрация документа

Зарегистрированы могут быть документы видов: [.dfn .term]_Входящий_, [.dfn .term]_Исходящий_, [.dfn .term]_Служебная записка_ и [.dfn .term]_Заявка_. Возможность регистрации собственных видов документов определяется настройками.

Регистрируемый документ должен быть в xref:StateOfCard.adoc[состоянии]:

* `Подготовка` – для вида документа [.dfn .term]_Входящий_;
* `Подготовка`, `Согласован` или `Подписан` – для видов документа [.dfn .term]_Исходящий_, [.dfn .term]_Служебная записка_ и [.dfn .term]_Заявка_. После регистрации согласование данных видов документа станет невозможным.

В регистрируемом документе должны быть заполнены поля с регистрационным номером и датой регистрации.

Для регистрации документа:

. xref:OpenCard.adoc[Откройте карточку] документа.
. На xref:CardOperations.adoc[панели операций] нажмите кнопку [.ph .uicontrol]*Зарегистрировать*. Состояние документа изменится на `Зарегистрирован`.

[.dfn .term]_Регистратору_ данный документ будет доступен в папке [.ph .filepath]`Мои документы - Я - автор`.

*Parent topic:* xref:WorkWithDocuments.adoc[Работа с документами]
