
== Программное обеспечение для формирования усиленной подписи

Web-клиент поддерживает два типа подписи: простая и усиленная. Формирование простой подписи доступно без дополнительной настройки (но должно быть предусмотрено сценарием подписания). Для формирования усиленной подписи (с использованием сертификатов ЭП) должны быть установлены компоненты КриптоПро , перечисленные далее по тексту.

=== Общие требования

В справочнике «Системные настройки», в разделе «Базовые объекты – Подписи и шифрование» должен быть выбран криптопровайдер и алгоритм подписи, соответствующие используемому сертификату ЭП. В частности, для работы с сертификатами КриптоПро должен быть выбран провайдер КриптоПро («Crypto-Pro GOST R 34.10-2012 Cryptographic Service Provider»).

[NOTE]
====
[.note__title]#Прим.:# Дополнительная информация по настройке подписания и шифрования приведена в руководстве администратора модуля «Базовые объекты».
====

=== Использование неквалифицированных сертификатов

* Требования к клиентским рабочим местам:
. Операционная система: Windows или Mac OS.
. Веб-браузер: Google Chrome, Яндекс.Браузер или Microsoft Edge на Chromium (поддерживаемые версии см. в пункте xref:Requirements_software.html[Необходимое программное обеспечение]).
. Компоненты криптопровайдера «КриптоПро»:
** КриптоПро ЭЦП Browser plug-in версии 2.0 (https://www.cryptopro.ru/products/cades/plugin[ссылка для загрузки]).
. Сертификаты:
** неквалифицированный сертификат пользователя – должен быть установлен в хранилище «Личное» на уровне «Текущий пользователь».

=== Использование квалифицированных сертификатов КриптоПро

* Требования к серверу:
. Компоненты криптопровайдера «КриптоПро»:
** КриптоПро CSP версии 4.0;
** КриптоПро CADESCOM версия 2.0 (https://www.cryptopro.ru/downloads[ссылка для загрузки]).
. Сертификаты:
** корневой сертификат КриптоПро – должен быть установлен в хранилище «Доверенные корневые центры сертификации» на уровне «Локальный компьютер».
* Требования к клиентским рабочим местам:
. Операционная система: Windows или Mac OS (версии см. в требованиях КриптоПро CSP на странице https://www.cryptopro.ru/products/csp/compare).
. Веб-браузер: Google Chrome, Яндекс.Браузер или Microsoft Edge на Chromium (поддерживаемые версии см. в пункте xref:Requirements_software.html[Необходимое программное обеспечение]).
. Компоненты криптопровайдера «КриптоПро»:
** КриптоПро CSP версии 4.0;
** КриптоПро ЭЦП Browser plug-in версии 2.0 (https://www.cryptopro.ru/products/cades/plugin[ссылка для загрузки]);
** CryptoPro Extension for CAdES Browser Plug-in версии 1.2.4 или выше (https://chrome.google.com/webstore/detail/cryptopro-extension-for-c/iifchhfnnmpdbibifmljnfjhpififfog[ссылка для загрузки]).
. Сертификаты:
** корневой сертификат КриптоПро – должен быть установлен в хранилище «Доверенные корневые центры сертификации» на уровне «Локальный компьютер»;
** квалифицированный сертификат пользователя – должен быть установлен в хранилище «Личное» на уровне «Текущий пользователь».
+
Здесь указано название хранилищ в ОС Windows. Для получения инструкции по настройке КриптоПро в ОС Mac OS обратитесь к документации КриптоПро. Вариант инструкции приведен на странице https://support.cryptopro.ru/index.php?/Knowledgebase/Article/View/232/0/rbot-s-kriptopro-csp-v-macos.

[.keyword]*Обратите внимание.* В случае, если лицензия на компоненты КриптоПро CSP истекла, блокируется возможность добавления новых подписей. Если подпись была добавлена ранее и срок действия сертификата ЭП не истёк, возможность проверки такой подписи не будет заблокирована. Проверка старых подписей выполняется успешно в любом случае.

По вопросам получения компонентов криптопровайдера «КриптоПро» следует обращаться в компанию ООО "КРИПТО-ПРО".

*На уровень выше:* xref:../topics/Requirements_software.html[Необходимое программное обеспечение]
