
== Необходимое техническое обеспечение

=== Требования Web-клиента

Ниже приведены минимальные аппаратные требования сервера Docsvision для 50 одновременно работающих пользователейxref:#fntarg_1[^1^].

* Процессор: 2,5 ГГц и выше, 4 ядра;
* Оперативная память: от 6 ГБ;
* Система хранения данных: от 12 ГБ свободного места на диске; рекомендуется использовать высокоскоростной HDD, массив или твердотельный накопитель.

Если количество одновременно работающих пользователей превышает 50, требования увеличиваются по следующим правилам:

* Процессор: каждые 50 дополнительных активных пользователей – дополнительное ядро процессора;
* Оперативная память: каждый дополнительный активный пользователь – дополнительные 100 МБ ОП;
* Система хранения данных: каждый дополнительный активный пользователь – дополнительные 200 МБ.

Требования приведены исходя из «нормальной» нагрузки от работы пользователей. При повышении нагрузки (повышении активности пользователей, усложнении бизнес-сценариев, использовании расширений и дополнений Web-клиента и т. п.) требования должны быть пересмотрены в сторону увеличения.

При использовании на компьютере дополнительного ПО к приведенным в требованиям необходимо прибавить требования установленных программных продуктов.

=== Требования к клиентским рабочим местам

Следующие требования предъявляются к рабочему месту пользователя при работе на персональном компьютере.

* Процессор: 2 ГГц и выше, Intel Core i3 или аналоги (двухъядерные);
* Оперативная память: от 2 ГБ; для запуска веб-браузера и открытия одной страницы Web-клиент должно быть свободно 512 МБ ОП;
* Дополнительное оборудование:
** Для осуществления сканирования необходим WIA или TWAIN-сканер.

*На уровень выше:* xref:../topics/system_requirements.html[Необходимые ресурсы]

xref:#fnsrc_1[^1^] Подразумеваются пользователи с «активной сессией». Время активности может быть настроено администратором.
