= Простая настройка

В простом варианте настройки все необходимые параметры будут получены из конфигурации установленной на компьютере системы {dv}. Для подключения к серверу {dv} будет использоваться HTTP REST или SOAP-транспорт.

include::partial$rest-soap.adoc[]

Нажмите на кнопку *Простая* в приветственном окне мастера настройки, чтобы начать процесс автоматической настройки.

Простая настройка включает следующие шаги:

. Создание собственного сайта для размещения сервера приложений Модуля.
. Создание в IIS пула приложений для сервера приложений.
+
include::admin:partial$pool.adoc[]
+
include::partial$new-pool.adoc[]
+
. Дождитесь завершения обновления базы данных.#
+
Формат Решений, загруженных в БД по умолчанию, будет обновлен до новой версии. Стандартные Решения в БД по умолчанию будут перезагружены.
. На последней странице мастера настройки будет показан URL-адрес Модуля для пользователей.
. Выполните xref:Post_install.adoc[действия после установки].

Изменить настройки {wc}а можно в панели управления, функции которой рассмотрены в разделе xref:Administrator_functions.adoc[Функции администратора].
