
== Особенности работы с файлами через протокол WebDAV

Пользователи Модуля могут редактировать приложенные к карточкам файлы Microsoft Office непосредственно в веб-браузере с помощью компонента "WebDAV" - набора расширений и дополнений к протоколу  HTTP, поддерживающих совместную работу пользователей над редактированием файлов и управление файлами.

Для параллельной работы с файлами существует ряд особенностей:

* если веб-браузер запущен от имени текущего пользователя Windows, файл также будет открыт под именем данного пользователя;
* если веб-браузер запущен не от имени текущего пользователя Windows и браузер не Internet Explorer (Chrome, Safari), файл будет открыт от имени текущего пользователя Windows или того пользователя, от имени которого открыт браузер Internet Explorer. Чтобы избежать подобной ситуации, рекомендуется при работе под несколькими учетными записями использовать только браузер Internet Explorer, запуская его от имени другого пользователя с нажатой клавишей [.ph .uicontrol]*Shift*.

*На уровень выше:* xref:../topics/Administrator_functions.html[Функции администратора]
