
== Сведения о составных частях программы

Модуль «Web-клиент» состоит из двух частей:

. Сервер приложений «Web-клиент» включает следующие элементы:
[loweralpha]
.. Компоненты сервера приложений, обеспечивающие работу веб-приложения в IIS.
.. Программа «Панель управления Web-клиентом» – приложение для рабочего стола, которое предназначено для настройки Web-клиента администратором.
.. Программа «Конструктор web-разметок» – приложение для рабочего стола, которое предназначено для настройки разметок (интерфейса пользователя) Web-клиента.
.. Программа «DVWebTool» – приложение для рабочего стола, которое обеспечивает возможность взаимодействия Web-клиента с программным и аппаратным обеспечением компьютера пользователя.
. Серверное расширение «Web-клиент» (для установки на компьютеры с [.dfn .term]_сервером Docsvision_) включает следующие элементы:
[loweralpha]
.. Схема метаданных справочника [.dfn .term]_Расширенный конструктор разметок_ (для хранения данных программы «Конструктор web-разметок).
.. Хранимые процедуры для БД.

*Parent topic:* xref:../topics/Structureof_program.html[Структура Модуля]
