
== Изменение таймаута пользовательской сессии

Администратор может изменить максимальное время ожидания ответа от сервера Docsvision. Время ожидания устанавливается в миллисекундах.

. [.ph .cmd]#Откройте конфигурационный файл [.ph]#[.ph .filepath]`[Каталог установки Web-клиента]\5.5\Site\web.config`#.#
. [.ph .cmd]#Перейдите к секции [.ph .menucascade]#[.ph .uicontrol]*configuration* > [.ph .uicontrol]*Docsvision* > [.ph .uicontrol]*WebClient* > [.ph .uicontrol]*SettingGroups* > [.ph .uicontrol]*SettingGroup[Name="System"]*#.#
. [.ph .cmd]#Измените значение параметра `ConnectionTimeout`. Время ожидания задается в миллисекундах.#
+
[source,pre,codeblock]
----
<SettingGroup Name="System">
    <Setting Name="ConnectionTimeout" Value="3600000" /> 
</SettingGroup>
----
+
Если указанного параметра нет в конфигурационном файле, создайте его самостоятельно.
. [.ph .cmd]#Сохраните изменения конфигурационного файла.#

*Parent topic:* xref:../topics/Administrator_functions.html[Функции администратора]
