
== Включение счетчиков производительности

Web-клиент предоставляет администратору возможность анализировать параметры работы Модуля с помощью счетчиков производительности – встроенного механизма ОС Windows.

Модуль предоставляет следующие группы счетчиков:

* «Docsvision WebClient AdvancedLayouts opening» – счетчики, позволяющие оценить время формирования разметки карточек;
* «Docsvision WebClient Grid first opening» – счетчики, позволяющие оценить время формирования представления папки;
* «Docsvision WebClient Grid paging» – счетчики, позволяющие оценить время формирования страницы представления папки;
* «Docsvision WebClient ExtendedLayouts first opening» – счетчики, позволяющие оценить время формирования разметки дерева папок и дашборда;
* «Docsvision WebClient summary» – счетчик учета количества открытых пользовательских сессий.

По умолчанию счетчики производительности выключены. Чтобы включить счетчики выполните следующие действия:

. [.ph .cmd]#Откройте конфигурационный файл [.ph]#[.ph .filepath]`[Каталог установки Web-клиента]\5.5\Site\web.config`#.#
. [.ph .cmd]#Перейдите к секции [.ph .menucascade]#[.ph .uicontrol]*configuration* > [.ph .uicontrol]*Docsvision* > [.ph .uicontrol]*WebClient* > [.ph .uicontrol]*SettingGroups* > [.ph .uicontrol]*SettingGroup[Name="WebClient"]*#.#
. [.ph .cmd]#Измените в [.keyword]*True* значение параметра `EnablePerformanceCounters`:#
+
[source,pre,codeblock]
----
<SettingGroup Name="WebClient">
 <Setting Name="EnablePerformanceCounters" Value="True" />
</SettingGroup>
----
+
Если указанного параметра нет в конфигурационном файле, создайте его самостоятельно.
. [.ph .cmd]#Сохраните изменения конфигурационного файла.#

Чтобы сбросить счетчики производительности:

. xref:task_ControlPanel_open.html[Откройте Панель управления].
. Нажмите на кнопку [.ph .uicontrol]*Reset perf. counters* на начальной странице.

*Parent topic:* xref:../topics/Administrator_functions.html[Функции администратора]
