
== Настройка автоматического закрытия неактивных пользовательских сессий

Модуль автоматически переводит в офлайн-режим сессию пользователя (подключение к серверу Docsvision), который определённое время не выполнял действий в Web-клиенте. При этом у пользователя появится предупреждение о переводе сессии в офлайн. В последствии сессии, по которым не было активности, будут закрыты. Отсчет времени неактивности пользователя до перевода сессии в офлайн-режим и до её закрытия запускается одновременно.

[NOTE]
====
[.note__title]#Note:# После перевода пользовательской сессии в «офлайн» режим или её закрытия будет остановлено автоматическое обновление счетчиков непрочитанных карточек и содержимого папок.
====

Для изменения стандартных настроек:

. [.ph .cmd]#Откройте конфигурационный файл [.ph]#[.ph .filepath]`[Каталог установки Web-клиента]\5.5\Site\web.config`#.#
. [.ph .cmd]#Перейдите к секции [.ph .menucascade]#[.ph .uicontrol]*configuration* > [.ph .uicontrol]*Docsvision* > [.ph .uicontrol]*WebClient* > [.ph .uicontrol]*SettingGroups* > [.ph .uicontrol]*SettingGroup[Name="WebClient"]*#.#
. [.ph .cmd]#Измените значение параметра:#
* `SessionSuspendTimeout` – время неактивности пользователя в минутах, через которое сессия будет переведена в «офлайн» режим (по умолчанию – 10 минут);
* `SessionCloseTimeout` – время неактивности пользователя в минутах, через которое сессия будет закрыта (по умолчанию – 300 минут);
* `SessionInactiveMessageHide` – отключает показ сообщения «Подключение остановлено в связи с отсутствием активности»:
** значение [.keyword]*true* – сообщение не отображается, сессия восстанавливается при нажатии курсором мыши в любой области окна Модуля;
** значение [.keyword]*false* (по умолчанию) – сообщение отображается, сессия восстанавливается при нажатии курсором мыши на сообщение или в любой области окна Модуля.
+
Для отключения функции перевода неактивной сессии в «офлайн» режим установите `SessionSuspendTimeout` в значение «0», для отключения функции закрытия неактивных сессий – `SessionCloseTimeout` в значение «0».
. [.ph .cmd]#Сохраните изменения конфигурационного файла.#

Сервер Модуля проверяет неактивность пользователей через промежуток времени `SessionSuspendTimeout * 0.5`, поэтому перевод пользовательской сессии в «офлайн» режим может быть выполнен в промежутке времени от `SessionSuspendTimeout` до `SessionSuspendTimeout *         1.5`.

Обратите внимание: неактивные сессии не закрываются, если в конфигурационном файле Модуля параметр `DisableClearSession` (xref:task_ClearCache_configuration.html[Настройка очистки данных пользовательских сессий]) установлен в значении [.keyword]*true*.

*Parent topic:* xref:../topics/Administrator_functions.html[Функции администратора]
