= Включить аутентификацию Kerberos

. Настройте _Service Principal Names_ для учетной записи пула приложений {wc}а. Для этого от имени администратора домена выполните команды:
+
[source,,l]
----
Setspn /s HTTP/webc company\webuser <.>
Setspn /s HTTP/webc.company.com company\webuser <.>
----
+
<.> webc -- имя и полное сетевое имя сервера {wc}а.
<.> company\webuser -- имя учётной записи, под которой работает пул приложений {wc}а.
+
IMPORTANT: Учетная запись пула должна быть доменной учётной записью, входить в группу локальных администраторов на сервере {wc}а и в группу _Администраторы {dv}_.
+
. Включите аутентификацию Kerberos в конфигурационном файле {wc}а:
.. Откройте конфигурационный файл `{webconfig}` в режиме редактирования.
.. Перейдите к секции menu:configuration[location[path="Account/LoginWindows"\]].
.. Измените секцию следующим образом:
+
====
[source,,l,language-xml]
----
<location path="Account/LoginWindows">
    <system.web>
      <authorization>
        <deny users="?" />
        <allow users="*" />
      </authorization>
    </system.web>
    <system.webServer>
      <security>
        <authentication>
          <anonymousAuthentication enabled="false" />
          <windowsAuthentication enabled="true" useKernelMode="false" useAppPoolCredentials="true">
            <providers>
              <clear />
              <add value="Negotiate:Kerberos" />
            </providers>            
          </windowsAuthentication>
          <basicAuthentication enabled="false" />
        </authentication>
      </security>
    </system.webServer>
</location>
----
====
.. Сохраните изменения.
. Очистите кэш браузера пользователей.
