
== Настройка аутентификации Kerberos

. Настройте Service Principal Names для учетной записи пула приложений {wc}а. Для этого от имени администратора домена выполните команды:
+
[source,,l]
----
Setspn /s HTTP/webc company\webuser
Setspn /s HTTP/webc.company.com company\webuser
----
+
Здесь: «webc» и «webc.company.com» нужно заменить на имя и полное сетевое имя сервера {wc}а, «company\webuser» – заменить на имя учётной записи, под которой работает пул приложений {wc}а. Учетная запись пула должна быть доменной учётной записью, входить в группу локальных администраторов на сервере {wc}а, и в группу администраторов {dv}.
. Включите аутентификацию Kerberos в конфигурационном файле {wc}а:
[loweralpha]
.. Откройте конфигурационный файл [.ph]#[.ph .filepath]`{webconfig}`# в режиме редактирования.
.. Перейдите к секции [.ph .menucascade]#[.ph .uicontrol]*configuration* > [.ph .uicontrol]*location[path="Account/LoginWindows"]*#.
.. Измените секцию на:
+
[source,,l,language-xml]
----
<location path="Account/LoginWindows">
    <system.web>
      <authorization>
        <deny users="?" />
        <allow users="*" />
      </authorization>
    </system.web>
    <system.webServer>
      <security>
        <authentication>
          <anonymousAuthentication enabled="false" />
          <windowsAuthentication enabled="true" useKernelMode="false" useAppPoolCredentials="true">
            <providers>
              <clear />
              <add value="Negotiate:Kerberos" />
            </providers>            
          </windowsAuthentication>
          <basicAuthentication enabled="false" />
        </authentication>
      </security>
    </system.webServer>
</location>
----
.. Сохраните изменения.
. Очистите кэш браузеров пользователей.

