= Шаблоны для определения типа клиентского устройства

Пользовательский интерфейс {wc}а адаптируется под тип клиентского устройства, который определяется по https://ru.wikipedia.org/wiki/User_Agent[User Agent], передаваемому веб-браузером клиента. Если User Agent не сопоставляется или некорректно сопоставляется с типом устройства, нужно изменить шаблон, по которому выполняется сопоставление:

. Откройте конфигурационный файл `{webconfig}`.
. Перейдите к элементу menu:configuration[{dv} > WebClient > SettingGroups > SettingGroup [Name="WebClient"\]].
. Измените значение параметра:
+
include::partial$table.adoc[]
|*_MobileRegExpString_*
|Шаблон определения мобильных устройств нового поколения.

|*_MobileRegExpPart2String_*
|Шаблон определения старых мобильных устройств.

|*_TabletRegExpString_*
|Шаблон определения планшетов.
|===
+
В значении параметра через символ `|` нужно указать User Agent соответствующего устройства.
+
.Определять устройство с User Agent _NEWPAD_ как планшет
+
====
[source]
----
<Setting Name="TabletRegExpString" Value=" … |SM-T355|MediaPad|NEWPAD" />
----
====
+
. Сохраните изменения конфигурационного файла.

NOTE: Адаптивные свойства разметок могут быть xref:layouts:layouts-adaptive.adoc[настроены] в программе {kvr}.
