= Особенности работы с файлами через протокол WebDAV

Пользователи {wc}а могут редактировать приложенные к карточкам файлы Microsoft Office непосредственно в веб-браузере с помощью компонента "WebDAV" -- набора расширений и дополнений к протоколу HTTP, поддерживающих совместную работу пользователей над редактированием файлов и управление файлами.

[CAUTION]
====
В сетях со сложной конфигурацией, при наличии прокси и VPN могут возникать проблемы с работой через протокол WebDav.
====

.Особенности параллельной работы с файлами:
****
Если веб-браузер запущен от имени текущего пользователя Windows, файл также будет открыт под именем данного пользователя.

Если веб-браузер запущен не от имени текущего пользователя Windows и браузер не Internet Explorer (Chrome, Safari), файл будет открыт от имени текущего пользователя Windows или того пользователя, от имени которого открыт браузер Internet Explorer.

Чтобы избежать подобной ситуации, рекомендуется при работе под несколькими учетными записями использовать только браузер Internet Explorer, запуская его от имени другого пользователя с нажатой клавишей kbd:[Shift].
****
