= Настройки запуска программы DVWebTool

Поведение программы по умолчанию: программа запускается при загрузке системы и не закрывается после выполнения действия. Данное поведение можно изменить в конфигурационном файле {wc}а, расположенном по пути: `{webconfig}`. Настройки располагаются в группе:  menu:Docsvision[WebClient > SettingGroups > SettingGroup Name="WebClient"].

// tag::webconfig[]
.Поведение DVWebTool при запуске настраивается в конфигурационном файле {wc}а:
* `DvWebToolAppShutDown` -- закрывать DVWebTool после выполнения действия. Значение по умолчанию: `false` -- не закрывать.
* `DvWebToolStartUpLaunch` -- отвечает за автоматический запуск DVWebTool. Значение по умолчанию: `true` -- утилита запускается автоматически при загрузке системы.
// end::webconfig[]

Чтобы настройки вступили в действие после изменения, необходимо повторно собрать инсталлятор DVWebTool -- запустить консоль настройки Web-клиента и нажать на кнопку "Пересобрать DVWebTool", либо запустить настройку (xref:admin:settings-simple.adoc[простую] или xref:admin:setings-extended.adoc[расширенную]) и пройти её до второго шага.
