= Добавление локализованных ресурсов

В строковых переменных расширения программы {kvr} (отображаемые названия свойств, диалоги) можно использовать локализованные ресурсы, добавляемые расширением.

Чтобы создать расширение, добавляющее новые локализованные ресурсы, выполните приведенную далее инструкцию.

. xref:layout-designer/create-publish.adoc[Создайте проект расширения программы {kvr}].
+
. Добавьте в проект расширения ресурсные файлы (для английского, русского и др. языков), содержащие требуемые локализованные ресурсы. 
+
NOTE: Проект расширения, формируемый из шаблона `TemplateDesignerExtension`, содержит ресурсные файлы, которые можно использовать для формирования локализованных ресурсов.
+
. Переопределите метод `GetResourceManagers` базового класса расширения, чтобы он предоставлял менеджер ресурсов для добавленных ресурсных файлов:
+
[source,csharp]
----
   protected override List<ResourceManager> GetResourceManagers()
   {
       return new List<ResourceManager>
       {
           Resources.ResourceManager
       };
   }
----
+
. Скомпилируйте проект и скопируйте полученную сборку на сервер {wc}а в папку `{wcd}\Plugins\%Каталог Решения%`. Ресурсные сборки скопируйте в папки `{wcd}\ru\` (для русской локализации), `{wcd}\uk\` (для английской локализации) и т.д.
