
== Консолидация подписанного договора

В демонстрационном согласовании в роли консолидатора подписанного документа выступает инициатор согласования -- сотрудник, указанный в поле *Подготовил* согласуемой карточки договора (дополнительного соглашения).

Целью данного этапа является принятие решения о завершении согласования.

Консолидация подписанного документа отличается от консолидации согласованного документа только набором решений, которые может принять консолидатор.

. Перейдите в папку `Мои задания/Входящие`.
+
Для заместителя: нужно перейти в папку `Замещение/Входящие`.
. Откройте полученное задание с описанием "Консолидация договора" в состоянии "Не начато".
. Для принятия решения по подписанию на xref:cardsOperations.adoc[панели операций] нажмите кнопку:
* *Завершить маршрут* -- подписанный договор будет переведен в состояние "Подписано", процесс согласования и подписания договора будет завершен;
* *На согласование с контрагентом* -- договор будет передан на согласование с контрагентом;
* *Повторить согласование* -- будет запущен новый цикл согласования договора;
* *Отмена* -- переведет карточку договора в состояние "Подготовка" для начала нового согласования или его аннулирования.
