= Работа с актами

Карточка _Акт_ предназначена для хранения сведений об акте по договору. _Акт_ не предполагает согласования и подписания в системе {dv}, работа с ним заключается в проставлении отметок о движении бумажного документа, приводящих к изменению состояния карточки:

* Передаче на подписание внутри организации.
* Подписание внутри организации.
* Передаче на подписание контрагенту.
* Перевод в состояние _Действителен_.
* Аннулирование (при возникновении такой необходимости).

При помощи команд ленты можно либо перевести карточку в другое состояние относительно текущего, либо вернуть в предыдущее состояние.

Для карточек актов предусмотрен следующий набор доступных состояний:

.Подготовка акта
Подготовка::
Создание новой карточки акта и заполнение первичных регистрационных данных. Сохранение карточки с присвоением регистрационного номера и заполнением даты регистрации. См. xref:actsCreate.adoc[Подготовка и регистрация акта].

.Проставление отметок о движении документа
На подписании::
В карточке договорного документа выполнена команда *На подписание контрагентом*. См. xref:actsStampToSigning.adoc[Проставление отметки о передаче на подписание].
Подписан::
В карточке договорного документа выполнена команда *Подписан*. В карточке в поле *Дата подписания контрагентом* проставлена дата. См. xref:actStampSigned.adoc[Проставление отметки о подписании].
На подписание контрагенту::
В карточке договорного документа выполнена команда *На подписание контрагенту*. В карточке в поле *Дата подписания контрагентом* проставлена дата. См. xref:actsStampToPartnerSigning.adoc[Проставление отметки о передаче на подписание контрагентом].
Действителен::
В карточке договорного документа выполнена команда *Назначить действительным*. См. xref:actsStampValid.adoc[Проставление отметки о действительности акта]
Аннулирован::
В карточке договорного документа выполнена команда *Аннулировать*. См. xref:actsCancel.adoc[Аннулирование акта].
