= Управление активным согласованием

== Изменить параметров активного согласования

_Автор_ может изменить параметры активного согласования из карточки согласуемого документа.

.Чтобы изменить параметры активного согласования:
. Откройте карточку согласуемого документа.
// tag::approvalControlPanel[]
. Откройте панель управления активным согласованием нажатием кнопки *Управление* на xref:cards-terms.adoc#cards-operations[панели операций].
+
NOTE: Кнопка *Управление* может быть недоступна, если у пользователя отсутствуют права на управление согласованием.
+
// end::approvalControlPanel[]
. Выберите этап согласования, настройки которого требуется изменить.
. xref:approval-send-modify.adoc#modifyRoute[Измените] настройки этапа или этапов.
. Нажмите кнопку *Сохранить*.
+
****
Если измененный этап ещё не выполнялся, то изменения будут применены в текущем цикле согласования, иначе -- в следующем цикле.
****

== Принудительно прекратить текущий этап

_Автор_ может принудительно завершить текущий этап согласования из карточки согласуемого документа.

.Чтобы принудительно завершить текущий этап согласования:
include::approval-manage.adoc[tags=approvalControlPanel]
. Нажмите кнопку *Завершить этап* в строке текущего этапа согласования (выделяется голубым цветом).
+
****
Для завершенного этапа будет установлена отрицательная семантика, все незавершенные задания участников согласования будут отозваны. Будет запущен следующий этап согласования в соответствии с маршрутом.
****

== Приостановить согласование

_Автор_ может на время приостановить активное согласование из карточки согласуемого документа.

include::approval-manage.adoc[tags=approvalControlPanel]
. Нажмите кнопку *Пауза*.
+
****
Процесс согласования будет приостановлен, рассылка новых заданий будет прекращена. Карточка будет доступна в режиме чтения для согласующих.

Чтобы вновь запустить приостановленное согласование, нажмите кнопку *Запустить*, которая появится на панели управления согласованием после приостановки.
****

== Отменить согласование

_Автор_ может отменить активное согласование из карточки согласуемого документа.

.Чтобы отменить согласование:
include::approval-manage.adoc[tags=approvalControlPanel]
. Нажмите кнопку *Отменить*.
+
****
Карточка перейдет в состояние _Подготовка_. Все незавершенные задания текущего согласования будут отозваны.
****

== Принудительно завершить согласование

_Автор_ может принудительно завершить процесс активного согласования из карточки согласуемого документа.

.Чтобы принудительно завершить согласование:
include::approval-manage.adoc[tags=approvalControlPanel]
. Нажмите кнопку *Завершить*.
+
****
Карточка перейдет в финальное состояние, указанное администратором в маршруте. Все незавершенные задания согласования будут отозваны.
****
