
== Краткое описание возможностей

«Docsvision 5. Web-клиент» является [.dfn .term]_дополнительным модулем_ системы «Docsvision 5.5», который предоставляет возможность работать с карточками системы Docsvision и осуществлять основные операции с электронными документами в веб-браузере.

Модуль обеспечивает выполнение следующих функциональных задач:

. Работа с документами:
* создание и просмотр документов;
* просмотр приложенных к документам файлов офисных и графических форматов в веб-браузере;
* согласование документов с использованием расширенных маршрутов согласования приложения «Docsvision 5. Конструктор согласований».
. Работа с заданиями:
* создание, просмотр и отправка на исполнение заданий;
* исполнение или делегирование поступивших на исполнение заданий;
* просмотр приложенных к заданиям файлов офисных и графических форматов в веб-браузере;
* создание подчинённых заданий и групп заданий.
. Поиск карточек:
* в выбранной папке;
* по всей базе данных с помощью полнотекстового поиска.
. Настраиваемый интерфейс.
+
Пользовательский интерфейс Web-клиента может быть настроен с помощью программы «Конструктор web-разметок». Данная программа предоставляет возможность настраивать общие элементы интерфейса, а также разметки карточек.

*На уровень выше:* xref:../topics/Introduction.html[Введение]
