
== Подчиненные задания согласования

Подчиненное задание согласования – особый класс заданий, которые могут быть созданы из задания согласования с целью сбора информации, связанной с согласованием, с сотрудников, которые в согласовании непосредственно не участвуют. Результаты подчинённых согласований не влияют на ход согласования и используются только участником согласования для принятия решения. В подчиненные задания прикладываются согласуемые версии файлов.

Участник согласования может:

* создать подчиненное задание согласования к своему заданию. Возможна отправка одновременно нескольких заданий разным исполнителям. Эти задания никак не связаны между собой и всегда рассылаются параллельно;
* скопировать комментарии из подчиненных заданий в согласование;
* отзывать подчинённые задания;
* завершить своё задание согласования без учёта состояния заданий подчинённых.

Поведение подчиненных заданий при отзыве задания согласования определяется настройками вида задания согласования.

* *xref:task_Ccard_createsubtask.adoc[Создание подчиненного задания согласования]* +
* *xref:task_Ccard_executsubtask.adoc[Исполнение подчиненного задания согласования]* +
* *xref:task_Ccard_copysubtaskresult.adoc[Копирование комментариев из подчиненного согласования]* +

*На уровень выше:* xref:reconcilement_approvaldesigner.adoc[Согласование документов]
