
== Проставление отметки о заключении договора/дополнительного соглашения

После того, как контрагентом будет возвращен подписанный договор и в карточке будет указана соответствующая дата, выполняется заключение договора, о чем в карточке должна быть проставлена соответствующая отметка.

Для проставления отметки о заключении договора выполните следующие действия:

. [.ph .cmd]#Откройте карточку договора (дополнительного соглашения) в состоянии «Подписан» или «На подписании контрагентом».#
+
В карточке должны быть заполнены поля [.ph .uicontrol]*Дата подписания* и [.ph .uicontrol]*Дата согласования*.
. [.ph .cmd]#Если договор необходимо заключить на определенную дату, отличную от текущей, установите нужную дату в поле [.ph .uicontrol]*Договор заключен* раздела [.ph .uicontrol]*Общие даты*.#
+
Если дата не указана, при сохранении карточки будет установлена текущая дата.
. [.ph .cmd]#Если в поле [.ph .uicontrol]*Получен оригинал* не указана дата, укажите дату получения оригинала договора.#
. [.ph .cmd]#Нажмите кнопку [.ph .uicontrol]*Заключен* на xref:CardOperations.adoc[панели операций].#
+
Договор переводится в состояние «Заключен».

*На уровень выше:* xref:WorkWithContractsAndSupplementaryAgreemens.adoc[Работа по договору и дополнительному соглашению]
