
== Проставление отметки о заключении договора/дополнительного соглашения

После того, как контрагентом будет возвращен подписанный договор и в карточке будет указана соответствующая дата, выполняется заключение договора, о чем в карточке должна быть проставлена соответствующая отметка.

Для проставления отметки о заключении договора выполните следующие действия:

. Откройте карточку договора (дополнительного соглашения) в состоянии "Подписан" или "На подписании контрагентом".
+
В карточке должны быть заполнены поля *Дата подписания* и *Дата согласования*.
. Если договор необходимо заключить на определенную дату, отличную от текущей, установите нужную дату в поле *Договор заключен* раздела *Общие даты*.
+
Если дата не указана, при сохранении карточки будет установлена текущая дата.
. Если в поле *Получен оригинал* не указана дата, укажите дату получения оригинала договора.
. Нажмите кнопку *Заключен* на xref:cardsOperations.adoc[панели операций].
+
Договор переводится в состояние "Заключен".
