
== Консолидация договора

Консолидация договора (принятие решения по результатам согласования) выполняется после завершения согласования договора. В демонстрационном согласовании консолидацию выполняет сотрудник, подготовивший договор.

Согласование может быть завершено со статусом согласовано или не согласовано. В зависимости от результата будет начат один из двух демонстрационных вариантов консолидации: «Согласовано с нашей стороны» или «Не согласовано с нашей стороны».

. Перейдите в папку [.ph .filepath]`Мои задания/Входящие`.
+
Для заместителя: нужно перейти в папку [.ph .filepath]`Замещение/Входящие`.
. Откройте полученное задание с описанием «Консолидация договора»
. Ознакомитесь с результатными согласования и версиями согласующих.
. Для принятия решения по согласованию на xref:CardOperations.adoc[панели операций] нажмите кнопку:
* для согласованного договора:
** [.ph .uicontrol]*На подписание* -- передать договор на подписание в организации;
** [.ph .uicontrol]*На согласование с контрагентом* -- передать договор на согласование с контрагентом;
** [.ph .uicontrol]*Отменить* -- отменить согласование договора;
* для несогласованного договора:
** [.ph .uicontrol]*Отмена* -- отменить согласование договора;
** [.ph .uicontrol]*Повторить согласование* -- запустить новый цикл согласования.
