= Согласование и подписание договорных документов

{wc} включает демонстрационный процесс согласования, по которому могут согласовываться и подписываться карточки _Договор_ и _Дополнительное соглашение_.

Демонстрационный процесс согласования представляет собой выполнение описанного далее сценария работы с договором.

== Согласование документа внутри организации

При запуске согласования карточка договорного документа переводится в состояние `На согласовании`.

Всем пользователям, состоящим в группе _Согласование Договоров_, рассылаются задания вида _На согласование_, к которым приложены согласуемые файлы.

Режим исполнения заданий -- _Параллельно_, то есть задания рассылаются одновременно всем исполнителям и выполняются ими независимо друг от друга.

В процессе согласования документа исполнитель может ознакомиться с документами и высказать положительное или отрицательное решение посредством соответствующих кнопок бокового меню карточки задания _На согласование_.

Решение по согласованию принимается сразу для всех файлов, приложенных к карточке задания.

== Консолидация согласованного договора

Консолидация -- создание итогового документа по итогам согласования внутри организации.

Когда все согласующие лица высказали своё мнение по документу, консолидатор (инициатор согласования) должен принять решение о дальнейшей судьбе договора.

****
. Если принято решение о том, что договор в текущей редакции _не согласован_, консолидатор может:
* Cоставить новую редакцию договора и отправить её на согласование.
* Отменить согласование.

. Если договор _согласован_ или _согласован с замечаниями_, карточка договорного документа переводится в состояние `Согласован`. Консолидатор (после выбора итоговой на данном этапе версии документа) может:
* Отправить договор на согласование с контрагентом.
* Отправить договор на печать (если согласование с контрагентом было произведено ранее).
* Отменить согласование.
****

== Согласование и подписание документа с контрагентом

При переходе к этому этапу карточка договорного документа переводится в состояние `На согласовании Контрагентом`. Ответственному за договорной документ приходит задание вида _Согласование с контрагентом_, к которому приложена согласованная внутри организации версия договора.

Получив такое задание, сотрудник должен передать полученную версию договора на согласование в организацию контрагента, получить ответ контрагента и принять решение о дальнейшей судьбе договора.

****
. Если принято решение о том, что договор в текущей редакции _не согласован_, ответственный может:
* Загрузить в карточку версию, полученную от контрагента и отправить её на согласование внутри организации.
* Отменить согласование.

. Если договор _согласован_ или _согласован с замечаниями_, ответственный может:
* Отправить договор на печать.
* Отправить договор на подписание внутри организации (если от контрагента вернулся подписанный оригинал).
* Отменить согласование.
****

[NOTE]
====
Этапы согласования договора внутри организации, консолидации и согласования с контрагентом могут циклически повторяться до выработки одобренного всеми согласующими варианта договора.
====

== Печать бумажного экземпляра документа

Этап является техническим, предваряющим подписание бумажного оригинала договорного документа. При передаче на печать карточка договорного документа переводится в состояние "На подписании".

Печать договора осуществляет сотрудник из "Группы печати", получивший задание вида _Подписание_. После печати бумажный оригинал договорного документа передается на подписание сотрудникам, указанным в поле _Подписал_ карточки договорного документа.

== Подписание документа внутри организации

При передаче на подписание карточка договорного документа переводится (или остается) в состояние `На подписании`.

Всем пользователям, состоящим в группе `Подписано`, рассылаются задания вида _Подписание_, к которым приложены файлы для подписания.

Режим исполнения заданий -- _Параллельно_, то есть задания рассылаются одновременно всем исполнителям и выполняются ими независимо друг от друга.

В процессе подписания исполнитель может ознакомиться с документами и высказать положительное или отрицательное решение посредством соответствующих кнопок бокового меню карточки задания _Подписание_.

Решение по подписанию принимается сразу для всех основных файлов, приложенных к карточке.

[IMPORTANT]
====
При согласовании договора или дополнительного соглашения с использованием демонстрационного процесса, заполнение полей _Подписано_ и _Ответственный_ в карточке _Договор_ или _Дополнительное соглашение_ является обязательным.
====

== Консолидация подписанного договора

Консолидация -- создание итогового документа по итогам подписания внутри организации и завершение маршрута.

Когда все подписанты высказали своё мнение по документу, консолидатор (инициатор согласования) должен принять решение о дальнейшей судьбе договора.

****
. Если в подписании отказано, консолидатор может:
* Составить новую редакцию договора и начать новый цикл согласования.
* Отменить согласование.

. Если договор _подписан_, консолидатору следует:
* Завершить согласование, если ранее договор был согласован/подписан контрагентом.
* Передать договор на согласование/подписание контрагенту, если ранее этого сделано не было.
****
