
== Проставление отметки о передаче на подписание контрагентом

После того, как договор будет согласован с контрагентом и подписан внутри организации, бумажный экземпляр договорного документа отправляется для подписания контрагенту в соответствии с регламентом, принятым в организации. Для сохранения этой информации, после выполнения отправки в карточке может быть проставлена соответствующая отметка.

Для передачи карточки [.dfn .term]_Договор_ ([.dfn .term]_Дополнительное соглашение)_ на подписание контрагентом выполните следующие действия:

[[task_dqt_bdz__steps_lsy_ckd_mk]]
. [.ph .cmd]#Откройте карточку [.dfn .term]_Договор_ ([.dfn .term]_Дополнительное соглашение)_ в состоянии «На подписании» или «Подписан».#
. [.ph .cmd]#Нажмите кнопку [.ph .uicontrol]*На подписание контрагентом* на xref:CardOperations.html[панели операций].#
+
Карточка [.dfn .term]_Договор_ ([.dfn .term]_Дополнительное соглашение)_ будет переведена в состояние «На подписании контрагентом».
. [.ph .cmd]#После возврата подписанного экземпляра договора следует проставить в карточке дату в поле [.ph .uicontrol]*Дата подписания*.#
. [.ph .cmd]#Если получен оригинал договора, укажите дату получения в поле [.ph .uicontrol]*Получен оригинал*.#

*На уровень выше:* xref:../topics/WorkWithContractsAndSupplementaryAgreemens.html[Работа по договору и дополнительному соглашению]
