
== Согласование и подписание договорных документов

Модуль включает демонстрационный процесс согласования, по которому могут согласовываться и подписываться карточки Договор и Дополнительное соглашение.

Демонстрационный процесс согласования представляет собой выполнение следующего сценария работы с договором:

1. Согласование документа внутри организации.::
  При запуске согласования карточка договорного документа переводится в состояние «На согласовании».
  +
  Всем пользователям, состоящим в группе «Согласование Договоров», рассылаются задания вида _На согласование_, к которым приложены согласуемые файлы. Режим исполнения заданий - [.keyword .parmname]_Параллельно_, то есть задания рассылаются одновременно всем исполнителям и выполняются ими независимо друг от друга.
  +
  В процессе согласования документа исполнитель может ознакомиться с документами и высказать положительное или отрицательное решение посредством соответствующих кнопок бокового меню карточки задания _На согласование_. Решение по согласованию выполняется сразу для всех файлов, приложенных к карточке задания.
2. Консолидация -- создание итогового документа по итогам согласования внутри организации.::
  После того, как все согласующие лица высказали свое мнение по документу, консолидатор (в роли которого выступает инициатор согласования) должен принять решение о дальнейшей судьбе договора.
  +
  . Если принято решение о том, что договор в текущей редакции «не согласован», то консолидатор может:
  * составить новую редакцию договора и отправить ее на согласование;
  * отменить согласование.
  . Если договор [.keyword .parmname]_согласован_ или [.keyword .parmname]_согласован с замечаниями_, карточка договорного документа переводится в состояние «Согласован». Консолидатор (после выбора итоговой на данном этапе версии документа) может:
  * отправить договор на согласование с контрагентом;
  * отправить договор на печать (если согласование с контрагентом было произведено ранее);
  * отменить согласование.
3. Согласование/подписание документа с контрагентом.::
  При переходе к этому этапу карточка договорного документа переводится в состояние «На согласовании Контрагентом». Ответственному за договорной документ приходит задание вида _Согласование с контрагентом_, к которому приложена согласованная внутри организации версия договора.
  +
  Получив такое задание, сотрудник должен передать полученную версию договора на согласование в организацию контрагента, получить ответ контрагента и принять решение о дальнейшей судьбе договора.
  +
  . Если принято решение о том, что договор в текущей редакции «не согласован», то ответственный может:
  * погрузить в карточку версию, полученную от контрагента и отправить ее на согласование внутри организации;
  * отменить согласование.
  . Если договор согласован или согласован с замечаниями, ответственный может:
  * отправить договор на печать;
  * отправить договор на подписание внутри организации (если от контрагента вернулся [.keyword]*подписанный оригинал*);
  * отменить согласование.

[NOTE]
====
[.note__title]#Note:# Этапы согласования договора внутри организации, консолидации и согласования с контрагентом могут циклически повторяться до выработки одобренного всеми согласующими варианта договора.
====

4. Печать бумажного экземпляра документа.::
  Этап является техническим, предваряющим подписание бумажного оригинала договорного документа. При передаче на печать карточка договорного документа переводится в состояние «На подписании».
  +
  Печать договора осуществляет сотрудник из «Группы печати», получивший задание вида _Подписание_. После печати бумажный оригинал договорного документа передается на подписание сотрудникам, указанным в поле *Подписал* карточки договорного документа.
5. Подписание документа внутри организации.::
  При передаче на подписание карточка договорного документа переводится (или остается) в состояние «На подписании».
  +
  Всем пользователям, указанным в поле *Подписано*, рассылаются задания вида _Подписание_, к которым приложены согласованные договорные документы, требующие подписания. Режим исполнения заданий - [.keyword .parmname]_Параллельно_, то есть задания рассылаются одновременно всем исполнителям и выполняются ими независимо друг от друга.
  +
  В процессе подписания документа исполнитель может ознакомиться с документами и высказать положительное или отрицательное решение посредством соответствующих кнопок бокового меню карточки задания вида _Подписание_. Решение по подписанию выполняется сразу для всех основных файлов, приложенных к карточке.
  +
  [NOTE]
  ====
  [.note__title]#Attention:# При согласовании договора (дополнительного соглашения) с использованием демонстрационного процесса, заполнение полей [.keyword .parmname]_Подписано_ и [.keyword .parmname]_Ответственный_ в карточке _Договор_ (_Дополнительное соглашение_) является обязательным.
  ====
6. Консолидация -- создание итогового документа по итогам подписания внутри организации и завершение маршрута.::
  После того, как все подписанты высказали свое мнение по документу, консолидатор (в роли которого выступает инициатор согласования) должен принять решение о дальнейшей судьбе договора.
  +
  . Если в подписании отказано, то консолидатор может:
  * составить новую редакцию договора и начать новый цикл согласования;
  * отменить согласование.
  . Если договор [.keyword .parmname]_подписан_, то консолидатору следует:
  * завершить согласование, если ранее договор был согласован/подписан контрагентом;
  * передать договор на согласование/подписание контрагенту, если ранее этого сделано не было.

* *xref:SendContractToAgreement.adoc[Отправка договора на согласование]* +
* *xref:AgreementOfContract.adoc[Согласование договора]* +
* *xref:ConsolidationOfContract.adoc[Консолидация договора]* +
* *xref:PartnerAgreementOfContract.adoc[Согласование договора с контрагентом]* +
* *xref:PrintOfContract.adoc[Печать договора]* +
* *xref:SignOfContract.adoc[Подписание договора]* +
* *xref:AcceptOfContract.adoc[Консолидация подписанного договора]* +
