= Консолидация согласованного договора

Консолидация договора (принятие решения по результатам согласования) выполняется после завершения согласования договора.

В xref:contracts-approval-demo-process.adoc[демонстрационном согласовании] консолидацию выполняет сотрудник, подготовивший договор.

Согласование может быть завершено со статусом _согласовано_ или _не согласовано_. В зависимости от результата будет начат один из двух демонстрационных вариантов консолидации: _Согласовано с нашей стороны_ или _Не согласовано с нашей стороны_.

include::partial$excerpts.adoc[tags=incomingFolder]
+
. Откройте полученное задание с описанием _Консолидация договора_
. Ознакомитесь с результатными согласования и версиями согласующих.
. Для принятия решения по согласованию на xref:cards-terms.adoc#cardsOperations[панели операций] нажмите кнопку:
+
--
.Для согласованного договора:
** *На подписание*. Передать договор на подписание в организации.
** *На согласование с контрагентом*. Передать договор на согласование с контрагентом.
** *Отменить*. Отменить согласование договора.
--
+
.Для несогласованного договора:
** *Отмена* -- отменить согласование договора.
** *Повторить согласование* -- запустить новый цикл согласования.
