
== Проставление отметки о передаче на подписание контрагентом

После того, как договор будет согласован с контрагентом и подписан внутри организации, бумажный экземпляр договорного документа отправляется для подписания контрагенту в соответствии с регламентом, принятым в организации. Для сохранения этой информации, после выполнения отправки в карточке может быть проставлена соответствующая отметка.

Для передачи карточки _Договор_ (_Дополнительное соглашение)_ на подписание контрагентом выполните следующие действия:

[[task_dqt_bdz__steps_lsy_ckd_mk]]
. [.ph .cmd]#Откройте карточку _Договор_ (_Дополнительное соглашение)_ в состоянии «На подписании» или «Подписан».#
. [.ph .cmd]#Нажмите кнопку *На подписание контрагентом* на xref:CardOperations.adoc[панели операций].#
+
Карточка _Договор_ (_Дополнительное соглашение)_ будет переведена в состояние «На подписании контрагентом».
. [.ph .cmd]#После возврата подписанного экземпляра договора следует проставить в карточке дату в поле *Дата подписания*.#
. [.ph .cmd]#Если получен оригинал договора, укажите дату получения в поле *Получен оригинал*.#
