= Согласование договора с контрагентом

Этап согласования договора с контрагентом выполняется, если при консолидации было принято решение *На согласование с контрагентом*.

Согласование документов с контрагентами выполняется вне системы {dv}. Целью данного этапа является фиксация факта поступления в организацию согласованного экземпляра документа (например, документ может поступить по электронной почте или это может быть обычное письмо с документом, в котором проставлены подписи руководителей контрагента).

include::partial$excerpts.adoc[tags=incomingFolder]
+
. Откройте полученное задание с описанием _Согласование с контрагентом_ в состоянии `Не начато`.
+
Задание содержит версию договора, которая должна быть согласована с контрагентом.
+
. Если документ не был отправлен контрагенту письмом на предыдущем этапе, отправьте документ на согласование или подписание контрагенту способом, предусмотренным регламентом организации.
+
. Получите согласованный документ от контрагента способом, предусмотренным регламентом организации.
. Примите решение по дальнейшей работе с документом:
* xref:approval-files.adoc[Ознакомьтесь с составом согласуемых файлов].
* Ознакомьтесь с договором: нажмите на ссылку в разделе *Ссылка на карточку* для перехода к договору
* Если требуется, xref:approval-files.adoc#add-version[добавьте собственную версию договора].
. Для принятия решения по согласованию на xref:cards-terms.adoc#cards-operations[панели операций] нажмите кнопку:
* *Согласован и подписан контрагентом*. Если контрагент прислал подписанный бумажный оригинал договора.
* *Согласован контрагентом*. Если контрагент прислал согласованный файл договора.
* *Повторить*. Начать новый цикл, если контрагент отказал в согласовании.
* *Отмена*. Отменить согласование.
+
****
Если документ был успешно согласован контрагентом, то согласно xref:contracts-approval-demo-process.adoc[демонстрационному маршруту] согласования будет выполнен переход к этапу _Печать договора_. Соответствующее задание поступит сотрудникам из группы _Печать договоров_ Справочника сотрудников.
****
