= Консолидация подписанного договора

В xref:contracts-approval-demo-process.adoc[демонстрационном согласовании] в роли консолидатора подписанного документа выступает инициатор согласования -- сотрудник, указанный в поле `Подготовил` согласуемой карточки договора или дополнительного соглашения.

Целью данного этапа является принятие решения о завершении согласования.

Консолидация подписанного документа отличается от xref:contracts-consolidate.adoc[консолидации согласованного] документа только набором решений, которые может принять консолидатор.

include::partial$excerpts.adoc[tags=incomingFolder]
+
. Откройте полученное задание с описанием _Консолидация договора_ в состоянии `Не начато`.
. Для принятия решения по подписанию на xref:cards-terms.adoc#cards-operations[панели операций] нажмите кнопку:
* *Завершить маршрут*. Подписанный договор будет переведен в состояние `Подписано`, процесс согласования и подписания договора будет завершен.
* *На согласование с контрагентом*. Договор будет передан на согласование с контрагентом.
* *Повторить согласование*. Будет запущен новый цикл согласования договора.
* *Отмена*. Карточка договора будет переведена в состояние `Подготовка`, чтобы начать новое или аннулировать согласование.
