= Передача договора или дополнительного соглашения на подписание контрагентом

Когда договор согласован с контрагентом и подписан внутри организации, бумажный экземпляр договорного документа отправляется для подписания контрагенту в соответствии с регламентом, принятым в организации. Чтобы сохранить эту информацию, после того, как договор отправлен, проставьте соответствующую отметку в карточке.

.Чтобы передать карточку _Договор_ или _Дополнительное соглашение_ на подписание контрагентом:
. Откройте карточку _Договор_ или _Дополнительное соглашение_ в состоянии `На подписании` или `Подписан`.
. Нажмите кнопку *На подписание контрагентом* на xref:cards-terms.adoc#cards-operations[панели операций].
+
****
Карточка _Договор_ или _Дополнительное соглашение_ будет переведена в состояние `На подписании контрагентом`.
****
+
. Когда подписанный экземпляр договора вернётся, проставьте в карточке дату в поле _Дата подписания_.
. Если получен оригинал договора, укажите дату получения в поле _Получен оригинал_.
