= Подписание договора

См. также "xref:docs-sign.adoc[]".

В демонстрационном согласовании договор подписывают сотрудники, указанные в поле _Подписывает_ карточки Договор.

При получении задания на подписание подписант может ознакомиться с уже согласованными документами и высказать положительное или отрицательное решение.

include::partial$excerpts.adoc[tags=incomingFolder]
+
. Откройте полученное задание с описанием _Подписание документов_ в состоянии _Не начато_.
. Чтобы принять решение по подписанию на xref:cards-terms.adoc#cards-operations[панели операций] нажмите кнопку:
* *Подписано*. Договорной документ будет переведен в состояние _Подписан_.
+
include::partial$excerpts.adoc[tags=35mb]
+
[NOTE]
====
include::user:partial$excerpts.adoc[tags=signature]
====
+
* *Отказано в подписании* -- договорной документ будет переведен в состояние Подготовка.
+
****
После проставления отметки о подписании, в соответствии с демонстрационным маршрутом согласования будет выполнен переход к этапу _Завершен этап подписания_.

Соответствующее задание поступит пользователю, указанному в поле `Подготовил` карточки договора.
****
