
== Копирование узлов справочника сотрудников

В справочнике реализована возможность _Копировать_ и _Вырезать_ узлы и сотрудников. Операции копирования или вырезания могут быть вызваны из контекстного меню выбранного узла. Вокруг скопированных или вырезанных узлов и сотрудников появляется пунктирная рамка. Вырезанный узел дополнительно обозначается серым цветом. Цвет скопированных узлов и сотрудников не меняется.

* Операция _Копировать_ копирует только иерархию узла, но не копирует сотрудников. Для копирования узлов вместе с сотрудниками воспользуйтесь операцией "Вырезать".
* {blank}
+
Операция _Вырезать_ перемещает узел со всеми дочерними узлами, включая сотрудников. При выполнении операции исходный узел удаляется в старом месте и перемещается в новое. Вырезать можно также отдельных сотрудников.

[NOTE]
====
[.note__title]#Прим.:# Для копирования или перемещения узла выберите _Копировать_ или _Вырезать_ из контекстного меню текущего узла, затем вызовите контекстное меню на другом узле, в который необходимо добавить или переместить текущий, и выберите _Вставить_.
====

Скопированный/вырезанный узел или сотрудник помещаются в буфер обмена. После этого справа от узла или сотрудника появляется кнопка *Отменить*, а вместо пунктов _Копировать_ или _Вырезать_ контекстного меню появляется пункт _Отменить_. [#CopyEmplDirNode__clear .ph]#Нажатие на эту кнопку или пункт в контекстном меню очищает буфер обмена.#

* Операция _Вставить_ завершает копирование или вырезание. Операция недоступна, пока раздел не был скопирован или вырезан. Для выполнения операции нужно сначала выбрать _Копировать_ или _Вырезать_ из контекстного меню текущего узла. После этого необходимо выбрать операцию _Вставить_ из контекстного меню другого узла. Операция *Вставить* отправляет запрос на сервер. Это значит, что узел будет скопирован или вырезан только после выбора _Вставить_.
+
[NOTE]
====
[.note__title]#Прим.:# Перемещать и копировать организации и подразделения можно только в организации или подразделения, группы - только в группы, ограничений на перемещение сотрудников нет.
====

Операции могут быть отменены в следующих случаях:

* [#CopyEmplDirNode__repeatopen]#при повторном открытия справочника (или обновлении страницы);#
* [#CopyEmplDirNode__leavepage]#при переходе на новую вкладку или при закрытии текущей;#
* [#CopyEmplDirNode__ESC]#при нажатии кнопки Esc на клавиатуре;#
* [#CopyEmplDirNode__cancelmenu]#при выборе пункта _Отменить_ из контекстного меню;#
* [#CopyEmplDirNode__cancelbutton .ph]#при нажатии кнопки *Отменить* справа от# узла;
* [#CopyEmplDirNode__selectother .ph]#при копировании или вырезании другого# узла.

При выполнении операций проверяются права доступа на редактирование узлов справочника. Чтобы вырезать узлы и сотрудников, пользователь должен иметь права на редактирование исходного узла. Чтобы вставить узлы и сотрудников, пользователь должен иметь права на редактирование целевого узла.

После выполнения операций, xref:EmployeesDirSecurity.adoc[настройки прав доступа] исходного узла будут заменены настройками, унаследованными от нового родительского узла.
