
== Копирование элементов справочника номенклатуры дел

В справочнике реализована возможность [.keyword .parmname]_Копировать_ и [.keyword .parmname]_Вырезать_ разделы справочника. Операции копирования или вырезания могут быть вызваны из контекстного меню выбранного раздела. Вокруг скопированного или вырезанного раздела появляется пунктирная рамка. Вырезанный раздел дополнительно обозначается серым цветом. Цвет скопированного раздела не меняется.

* Операция [.keyword .parmname]_Копировать_ копирует только иерархию разделов, но не копирует дела. Для копирования разделов вместе с делами воспользуйтесь операцией «Вырезать».
* Операция [.keyword .parmname]_Вырезать_ перемещает раздел со всеми дочерними элементами, включая дела. При выполнении операции исходный раздел удаляется в старом месте и перемещается в новое.

Скопированный или вырезанный раздел помещается в буфер обмена. Справа от раздела появляется кнопка [.ph .uicontrol]*Отменить*, вместо пункта [.keyword .parmname]_Копировать_ или [.keyword .parmname]_Вырезать_ контекстного меню появляется пункт [.keyword .parmname]_Отменить_. [.ph]#Нажатие на эту кнопку или пункт в контекстном меню очищает буфер обмена.#

* Операция [.keyword .parmname]_Вставить_ завершает копирование или вырезание. Операция недоступна, пока раздел не был скопирован или вырезан. Для выполнения операции нужно сначала выбрать [.keyword .parmname]_Копировать_ или [.keyword .parmname]_Вырезать_ из контекстного меню текущего раздела. После этого необходимо выбрать операцию [.keyword .parmname]_Вставить_ из контекстного меню другого раздела. Операция *Вставить* отправляет запрос на сервер. Это значит, что раздел будет скопирован или вырезан только после выбора [.keyword .parmname]_Вставить_.
+
Любой раздел одного года можно скопировать или вырезать и вставить в другой год. Включая корневой раздел.

Операции могут быть отменены в следующих случаях:

* при повторном открытия справочника (или обновлении страницы);
* при переходе на новую вкладку или при закрытии текущей;
* при нажатии кнопки Esc на клавиатуре;
* при выборе пункта [.keyword .parmname]_Отменить_ из контекстного меню;
* [.ph]#при нажатии кнопки [.ph .uicontrol]*Отменить* справа от# раздела,
* [.ph]#при копировании или вырезании другого# разделе.

При выполнении операций проверяются права доступа на редактирование разделов справочника. Чтобы вырезать раздел, пользователь должен иметь права на редактирование исходного раздела. Чтобы вставить раздел, пользователь должен иметь права на редактирование целевого раздела.

После выполнения операций, xref:NomenclatureSecurityParent.adoc[настройки прав доступа] исходного раздела перестанут действовать и будут заменены настройками, унаследованными от нового родительского раздела.
