= Перечень полей исходящего документа

xref:appendix/ctrlSimpleFields.adoc[Тема]::
Название документа.
+
include::partial$excerpts.adoc[tags=mandatory]

xref:appendix/ctrlStaffDirectoryItems.adoc[Подготовил]::
Сотрудник, подготовивший проект документа. По умолчанию выбирается текущий сотрудник.
+
include::partial$excerpts.adoc[tags=mandatory]

xref:appendix/ctrlDateTime.adoc[Дата регистрации]::
Дата регистрации документа в организации. По умолчанию устанавливаются текущие дата и время.

xref:appendix/ctrlStaffDirectoryItems.adoc[Согласуют]::
Сотрудники, участвующие в согласовании документа.
+
Могут быть выбраны только сотрудники.

xref:appendix/ctrlStaffDirectoryItems.adoc[Подписывает]::
Сотрудники, участвующие в подписании документа при согласовании.
+
Могут быть выбраны только сотрудники.

xref:appendix/ctrlText.adoc[Примечание]::
Дополнительная информация по документу.

xref:appendix/ctrlFiles.adoc[Файлы]::
Файлы документа.
include::partial$excerpts.adoc[tags=scanOrFileSystem]

xref:appendix/ctrlPartnerOrg.adoc[Организация]::
Контрагенты из _Справочника контрагентов_, которым должен быть отправлен документ после подготовки, согласования и регистрации.

xref:appendix/ctrlPartner.adoc[Сотрудник]::
Сотрудник контрагента.
