= Перечень полей входящего документа

xref:ctrlSimpleFields.adoc[Тема]::
Название документа.
+
include::partial$excerpts.adoc[tags=mandatory]

xref:Numerator.adoc[Регистрационный номер]::
Регистрационный номер документа. Может быть получен из списка свободных номеров. Ручной ввод номера не предусмотрен.

xref:ctrlDateTime.adoc[Дата регистрации]::
Дата регистрации документа в организации. По умолчанию устанавливаются текущие дата и время.

xref:ctrlStaffDirectoryItems.adoc[Регистратор]::
Сотрудник, который будет регистрировать документ. По умолчанию выбирается текущий сотрудник.
+
include::partial$excerpts.adoc[tags=mandatory]

xref:ctrlText.adoc[Описание]::
Дополнительная информация по документу.

xref:Files.adoc[Файлы]::
Файлы документа.
include::partial$excerpts.adoc[tags=scanOrFileSystem]
+
xref:ctrlStaffDirectoryItems.adoc[Получатели]::
Сотрудники организации, которые должны быть ознакомлены с документом.

Отправитель-контрагент::
Информация об организации-отправителе документа.

xref:ctrlPartnerOrg.adoc[Организация-отправитель]:::
Контрагент, отправивший документ.

xref:ctrlPartner.adoc[Сотрудник-отправитель]:::
Ответственный сотрудник контрагента.

xref:ctrlSimpleFields.adoc[Номер отправителя]:::
Номер документа, который был присвоен в организации-отправителе.
+
Вводится вручную.

xref:ctrlDateTime.adoc[Дата отправки]:::
Дата регистрации документа в организации-отправителе.
+
По умолчанию устанавливаются текущие дата и время.
