= Перечень полей исходящего документа

xref:SimpleFields.adoc[Тема]::
Название документа.
+
include::partial$excerpts.adoc[tags=mandatory]

xref:StaffDirectoryItems.adoc[Подготовил]::
Сотрудник, подготовивший проект документа. По умолчанию выбирается текущий сотрудник.
+
include::partial$excerpts.adoc[tags=mandatory]

xref:DateTime.adoc[Дата регистрации]::
Дата регистрации документа в организации. По умолчанию устанавливаются текущие дата и время.

xref:StaffDirectoryItems.adoc[Согласуют]::
Сотрудники, участвующие в согласовании документа.
+
Могут быть выбраны только сотрудники.

xref:StaffDirectoryItems.adoc[Подписывает]::
Сотрудники, участвующие в подписании документа при согласовании.
+
Могут быть выбраны только сотрудники.

xref:Text.adoc[Примечание]::
Дополнительная информация по документу.

xref:Files.adoc[Файлы]::
Файлы документа.
include::partial$excerpts.adoc[tags=scanOrFileSystem]

xref:PartnerOrg.adoc[Организация]::
Контрагенты из _Справочника контрагентов_, которым должен быть отправлен документ после подготовки, согласования и регистрации.

xref:partner.adoc[Сотрудник]::
Сотрудник контрагента.
