= Перечень полей входящего документа

xref:SimpleFields.adoc[Тема]::
Название документа.
+
include::partial$excerpts.adoc[tags=mandatory]

xref:Numerator.adoc[Регистрационный номер]::
Регистрационный номер документа. Может быть получен из списка свободных номеров. Ручной ввод номера не предусмотрен.

xref:DateTime.adoc[Дата регистрации]::
Дата регистрации документа в организации. По умолчанию устанавливаются текущие дата и время.

xref:StaffDirectoryItems.adoc[Регистратор]::
Сотрудник, который будет регистрировать документ. По умолчанию выбирается текущий сотрудник.
+
include::partial$excerpts.adoc[tags=mandatory]

xref:Text.adoc[Описание]::
Дополнительная информация по документу.

xref:Files.adoc[Файлы]::
Файлы документа.
include::partial$excerpts.adoc[tags=scanOrFileSystem]
+
xref:StaffDirectoryItems.adoc[Получатели]::
Сотрудники организации, которые должны быть ознакомлены с документом.

Отправитель-контрагент::
Информация об организации-отправителе документа.

xref:PartnerOrg.adoc[Организация-отправитель]:::
Контрагент, отправивший документ.

xref:partner.adoc[Сотрудник-отправитель]:::
Ответственный сотрудник контрагента.

xref:SimpleFields.adoc[Номер отправителя]:::
Номер документа, который был присвоен в организации-отправителе.
+
Вводится вручную.

xref:DateTime.adoc[Дата отправки]:::
Дата регистрации документа в организации-отправителе.
+
По умолчанию устанавливаются текущие дата и время.
