= Агрегация

Новый грид позволяет настроить агрегацию строк. Агрегация -- сбор суммарных данных -- позволяет получать
численные результаты по данным, содержащимся в строках таблицы. Например,
в представлении может отображаться, количество документов определённого вида или количество документов, отправленных определённому пользователю.

Агрегаты отображаются в виде флагов в дополнительной области.

Агрегаты работают только, когда подключен и настроен xref:5.5.5@platform:admin:search-elastic.adoc[полнотекстовый поиск Elasticsearch].

.Агрегаты не отображаются (не отображается дополнительная область) если:
* Elasticsearch включен, но не настроены агрегаты.
* Elasticsearch включен, агрегаты не найдены.
* Elasticsearch выключен.

Настройка агрегации при использовании Elasticsearch xref:5.5.5@platform:admin:search-elastic-aggregates.adoc[описана] в документации модуля {pl}.

== Как работает агрегация

По умолчанию после выполнения поиска выводятся все результаты поиска и найденные агрегаты, но ни один флаг не установлен. После того, как хотя бы в одном агрегате выставляется флаг, результаты поиска фильтруются с учетом выбранных агрегатов.

Для выбранных агрегатов могут быть доступны другие агрегаты или категория агрегатов. Если другие агрегаты или категория агрегатов неприменимы, их строки становятся неактивными.

При выборе агрегата, помимо основного фильтра по значению агрегата, автоматически добавляется фильтр по типу карточек, для которых в настройках агрегата установлены поля. При применении нескольких агрегатов будут отображены только те типы карточек, которые присутствуют в настройках всех выбранных агрегатов.

Агрегаты считаются только для типов карточек, для которых задан этот агрегат. То есть счетчики могут быть не совсем достоверны: в поиске может отображаться 2 элемента с встречающимся названием, но реальное количество будет равно 1. Такое поведение обусловлено xref:5.5.5@platform:admin:search-elastic-aggregates.adoc[настройкой файла конфигурации].

== Отображение агрегатов в представлении

В представлении выводятся все агрегаты для найденного типа карточки, за исключением агрегатов, в котором не нашлось ни одного значения.
Агрегаты отображаются в дополнительной области грида слева.

Агрегат с пометкой _главный_ выводится первым в списке,
//и отображается в верхней части представления,
все остальные агрегаты выводятся в порядке указанном в ref:5.5.5@platform:admin:search-elastic-aggregates.adoc[файле конфигурации]. Если количество различных вариантов в агрегате превышает 7 шт, появляется ссылка-кнопка *Ещё*. Нажмите на *Ещё*, чтобы отобразить следующие 7 агрегатов. Когда все результаты подгружены вместо кнопки *Ещё*, отображается кнопка *Скрыть*, которая скрывает результаты до исходных 7 вариантов.

Результаты агрегатов отсортированы по количеству найденных совпадений от большего к меньшему.

Каждый агрегат имеет кнопку свернуть/развернуть.

NOTE: Новые настройки агрегации могут быть применены только в случае полной перенастройки полнотекстового поиска. Для настройки агрегации сперва нужно отключить БД от полнотекстового поиска, удалить индексы, изменить настройки агрегатов, затем настроить всё заново.
