= Агрегация

Работа с функцией агрегации может быть ограничена администратором, см. пункт xref:admin:grid-aggregate.adoc["Настройки агрегации"].

//tag::whatis[]
Новый грид позволяет настроить агрегацию строк. Агрегация -- сбор суммарных данных -- позволяет получать численные результаты по данным, содержащимся в строках таблицы. Например, в представлении может отображаться количество документов определённого вида или количество документов, отправленных определённому пользователю.
//end::whatis[]

Агрегаты отображаются в виде флагов в дополнительной области.

Агрегаты работают, только когда подключен и настроен xref:platform:admin:search-elastic.adoc[полнотекстовый поиск {es}].

.Агрегаты не отображаются в дополнительной области, если:
* {es} включен, но не xref:platform:admin:search-elastic-change.adoc#facets[настроены] агрегаты в программе {cns}.
* {es} включен, агрегаты не найдены.
* {es} выключен.
* Использование агрегатов ограничено администратором, см. пункт xref:admin:grid-aggregate.adoc["Настройки агрегации"].
* В xref::license.adoc[лицензии] отсутствует опция _Умный поиск_.

Настройка агрегации при использовании {es} xref:platform:admin:search-elastic-change.adoc[описана] в документации модуля {pl}.

== Как работает агрегация

Агрегаты отображаются в виде флагов в дополнительной области представления. Чтобы применить один или несколько агрегатов, установите напротив них флаги, а затем нажмите кнопку *Применить*. Кнопка может не отображаться в зависимости от настроек xref:admin:grid-aggregate.adoc[администратора].

По умолчанию после выполнения поиска выводятся все результаты поиска и найденные агрегаты, но ни один флаг не установлен. После того как хотя бы в одном агрегате выставляется флаг, результаты поиска фильтруются с учетом выбранных агрегатов.

Для выбранных агрегатов могут быть доступны другие агрегаты или категория агрегатов. Если другие агрегаты или категория агрегатов неприменимы, их строки становятся неактивными.

При выборе агрегата, помимо основного фильтра по значению агрегата, автоматически добавляется фильтр по типу карточек, для которых в настройках агрегата установлены поля. При применении нескольких агрегатов будут отображены только те типы карточек, которые присутствуют в настройках всех выбранных агрегатов.

Агрегаты считаются только для типов карточек, для которых задан этот агрегат. То есть счетчики могут быть не совсем достоверны: в поиске может отображаться 2 элемента с встречающимся названием, но реальное количество будет равно 1. Такое поведение обусловлено xref:platform:admin:search-elastic-change.adoc[настройкой фасетов {es}].

== Отображение агрегатов в представлении

В представлении выводятся все агрегаты для найденного типа карточки, за исключением агрегатов, в котором не нашлось ни одного значения.
Агрегаты отображаются в дополнительной области грида слева.

Агрегат с пометкой _главный_ выводится первым в списке,
//и отображается в верхней части представления,
все остальные агрегаты выводятся в порядке, указанном в xref:platform:admin:search-elastic-change.adoc[Консоли настроек {dv}]. Если количество различных вариантов в агрегате превышает 7 шт., появляется ссылка-кнопка *Ещё*. Нажмите на *Ещё*, чтобы отобразить следующие 7 агрегатов. Когда все результаты загружены, вместо кнопки *Ещё* отображается кнопка *Скрыть*, которая скрывает результаты до исходных 7 вариантов.

Результаты агрегатов отсортированы по количеству найденных совпадений от большего к меньшему.

Каждый агрегат имеет кнопку *Свернуть/Развернуть*.

NOTE: Новые настройки агрегации могут быть применены только в случае полной перенастройки полнотекстового поиска. Для настройки агрегации сперва нужно отключить БД от полнотекстового поиска, удалить индексы, изменить настройки агрегатов, затем настроить всё заново.
