
== Групповые операции

Групповая операция -- операция, которая применяется сразу к нескольким карточкам.

В {wc}е есть следующие особенности работы с групповыми операциями:

* Групповая операция является синхронной -- во время её выполнения блокируется возможность выполнения других операций.
* Операции групповой операции выполняются последовательно.
* Групповая операция является прерываемой -- пользователь может прервать её выполнение, при этом невыполненные операции не будут выполнены.
* Групповая операция выполняется в веб-браузере -- страница {wc}а, в которой выполняется групповая операция, должна оставаться открытой до завершения, иначе выполнение будет прервано.
* Проверка возможности выполнения операции осуществляется при её выполнении.

* *xref:EnterToGroupOperationsMode.adoc[Переключение в режим групповых операций]* +
* *xref:GroupOperationsDelegate.adoc[Групповое делегирование заданий]* +
* *xref:BatchOperationMoveShortcuts.adoc[Перемещение ярлыков карточек]* +
* *xref:GroupOpsCopyTags.adoc[Копирование ярлыков карточек]* +
* *xref:GroupOpsDeleteTags.adoc[Удаление ярлыков карточек]* +
