= Стандартные папки

Дерево папок включает следующие ссылки:

Главная:: Открывает xref:interfaceDashboard.adoc[главную страницу] {wc}а.
Поиск:: Открывает папку с результатами полнотекстового поиска; если полнотекстовый поиск выключен, папка будет скрыта.
Последние карточки:: Открывает список последних открытых карточек.
Мои задания:: Задания пользователя:
Входящие::: Задания в состояниях _Не начато_, _Делегировано_, _Возвращено с делегирования_ и _На доработке_, в которых исполнителем является текущий пользователь.
В работе:::: задания текущего пользователя в состояниях _В работе_ и _Отложено_.
Завершено:::: Задания текущего пользователя во всех состояниях, кроме _Подготовка_, _Отозвано_ и _Отклонено_.
На контроле:::: задания во всех состояниях кроме _Подготовка_ (включая завершенные за последние 30 дней), в которых текущий пользователь является контролёром.
Ответственное исполнение:::: Задания во всех состояниях кроме _Подготовка_, _Отозвано_ и _Завершено_, в которых текущий пользователь является ответственным исполнителем и не является текущим исполнителем.
Исходящие::: Незавершенные задания, в которых текущий пользователь является Автором.
Делегировано:::: Задания в состояниях _Делегировано_ и _В работе_, которые были делегированы текущим сотрудником.
Завершено:::: Завершенные и отменённые за последние 30 дней задания, в которых текущий пользователь является Автором.
Поиск заданий::: Запускает диалог поиска заданий по атрибутам.
Мои документы:: Документы, в которых текущий сотрудник является автором.
Поиск документов::: Запускает диалог поиска документов по атрибутам.
Я автор::: Открывает список документов, в которых пользователь является автором.
Замещение:: Задания постоянного и временного заместителя:
Входящие::: Задания во всех состояниях кроме _Завершено_ и _Отозвано_, в которых текущий пользователь является постоянным или временным заместителем исполнителя.
В работе:::: Задания заместителя в состояниях _В работе_ и _Отложено_.
На контроле:::: Задания во всех состояниях кроме _Подготовка_ (включая завершенные за последние 30 дней), в которых текущий пользователь является заместителем контролёра.
Исходящие::: Незавершенные задания, в которых текущий пользователь является заместителем Автора.
Делегировано:::: Задания в состояниях _Делегировано_ и _В работе_, которые были делегированы замещаемым сотрудником.
Завершено:::: Завершенные и отменённые за последние 30 дней задания, в которых текущий пользователь является заместителем Автора.
Договоры:: Содержит папки поиска договорных документов и отчёты:
Действующие договоры::: Система виртуальных папок с договорами, отбираемыми по различным параметрам:
По контрагенту:::: Действующие договоры, сгруппированные по контрагенту.
По сроку действия:::: Действующие договоры, сгруппированные по сроку действия (по кварталам).
Заключенные договоры::: Система виртуальных папок с договорами по годам заключения:
2018 -- договоры и дополнительные соглашения:::: Договоры и дополнительные соглашения, заключенные в 2018 году и сгруппированные по контрагенту.
2019 -- договоры и дополнительные соглашения:::: Договоры и дополнительные соглашения, заключенные в 2019 году и сгруппированные по контрагенту.
Договоры с доп. соглашением:::: Запускает диалог поиска дополнительных соглашений и актов к договорам, заключенным за определённый период.
+
[NOTE]
====
Папки для выбора договоров за другие года могут быть созданы при настройке {wc}а.
====
+
Исполнение договоров:::: Запускает диалог поиска актов, зарегистрированных за определённый период.
Поиск:::: запускает диалог поиска договорных документов по атрибутам.
Договоры к ознакомлению::: Договоры для сотрудников группы ознакомления. Она представляет собой структуру папок с настроенными поисковыми запросами, предназначенную для поиска карточек договоров, с которыми может ознакомиться текущий пользователь:
Заключенные:::: Заключенные договоры и дополнительные соглашения, в которых текущий пользователь входит в _Группу ознакомления_ с договором.
Согласование:::: Договоры и дополнительные соглашения в состоянии _Подготовка_, _На согласовании_, _На согласовании с контрагентом_, в которых текущий пользователь входит в _Группу ознакомления_ с договором.
Мои договоры::: Договоры в состоянии _Подготовка_, в которых текущий или временно замещаемый им сотрудник является _Ответственным_ или _Подготовившим_. Включает подпапки с дополнительным условием по состоянию договора:
Завершенные:::: Договоры и дополнительные соглашения в состоянии _Завершено_.
Заключенные:::: Договоры и дополнительные соглашения в состоянии _Заключено_.
Подготовка и согласование:::: Договоры в состоянии _Подготовка_, _На согласовании_, _На согласовании с контрагентом_, _Согласован_, _На подписании_, _Подписан_, _На подписании контрагентом_.
Отчёты: :::
Договоры и ДС без подписанного оригинала:::: Запускает диалог поиска договоров и дополнительных соглашений в состояниях _Подписан_ и _Заключен_, для которых отсутствует подписанный оригинал (в карточке не заполнено поле `Получен оригинал`).
Договоры с истекающим сроком окончания:::: Запускает диалог поиска договоров и дополнительных соглашений в состояниях _Подписан_ и _Заключен_, у которых заканчивается срок действия.
Мои группы:: Содержит папки _рабочей группы_ пользователя. Доступна, если пользователь включен в рабочую группу.
Мои папки:: Содержит папки, подключенные пользователем.

[NOTE]
====
Состав элементов в дереве папок может быть изменён при настройке {wc}а.
====
