:current: раздела

= Копировать элементы справочника номенклатуры дел

В справочнике реализована возможность _Копировать_ и _Вырезать_ разделы справочника. Операции копирования или вырезания могут быть вызваны из контекстного меню выбранного раздела. Вокруг скопированного или вырезанного раздела появляется пунктирная рамка. Вырезанный раздел дополнительно обозначается серым цветом. Цвет скопированного раздела не меняется.

Операция Копировать::
Копирует только иерархию разделов, но не копирует дела. Для копирования разделов вместе с делами воспользуйтесь операцией _Вырезать_.

Операция Вырезать::
Перемещает раздел со всеми дочерними элементами, включая дела. При выполнении операции исходный раздел удаляется в старом месте и перемещается в новое.
+
Скопированный или вырезанный раздел помещается в буфер обмена. Справа от раздела появляется кнопка *Отменить*, вместо пункта _Копировать_ или _Вырезать_ контекстного меню появляется пункт _Отменить_. Нажатие на эту кнопку или пункт в контекстном меню очищает буфер обмена.

Операция Вставить::
Завершает копирование или вырезание. Для выполнения операции нужно сначала выбрать _Копировать_ или _Вырезать_ из контекстного меню исходного раздела. После этого необходимо выбрать операцию _Вставить_ из контекстного меню целевого раздела.
+
Операция _Вставить_ отправляет запрос на сервер. Это значит, что раздел будет скопирован или вырезан только после нажатия на _Вставить_.
+
TIP: Любой раздел одного года можно скопировать или вырезать и вставить в другой год. Включая корневой раздел.

include::partial$excerpts.adoc[tags=operationsAborted]

При выполнении операций проверяются xref:nomenclatureSecurity.adoc[права доступа] на редактирование разделов справочника. Чтобы вырезать раздел, пользователь должен иметь права на редактирование исходного раздела. Чтобы вставить раздел, пользователь должен иметь права на редактирование целевого раздела.

После выполнения операций, xref:nomenclatureSecurity.adoc[настройки прав доступа] исходного раздела перестанут действовать и будут заменены настройками, унаследованными от нового родительского раздела.
