
== Согласование договора с контрагентом

Этап согласования договора с контрагентом выполняется, если при консолидации было принято решение [.ph .uicontrol]*На согласование с контрагентом*.

Согласование документов с контрагентами выполняется вне системы {dv}. Целью данного этапа является фиксация факта поступления в организацию согласованного экземпляра документа (например, документ может поступить по электронной почте или это может быть обычное письмо с документом, в котором проставлены подписи руководителей контрагента).

. Перейдите в папку [.ph .filepath]`Мои задания/Входящие`.
+
Для заместителя: нужно перейти в папку [.ph .filepath]`Замещение/Входящие`.
. Откройте полученное задание с описанием «Согласование с контрагентом» в состоянии `Не начато`.
+
Задание содержит версию договора, которая должна быть согласована с контрагентом.
. Если документ не был отправлен контрагенту письмом на предыдущем этапе, отправьте документ на согласование/подписание контрагенту способом, предусмотренным регламентом организации.
. Получите согласованный документ от контрагента способом, предусмотренным регламентом организации.
. Примите решение по дальнейшей работе с документом:
* xref:task_tcard_approval_file_view_main.adoc[ознакомьтесь с составом согласуемых файлов];
* ознакомьтесь с договором: нажмите на ссылку в разделе [.ph .uicontrol]*Ссылка на карточку* для перехода к договору
* если требуется, xref:task_tcard_approval_file_version_add.adoc[добавьте собственную версию договора].
. Для принятия решения по согласованию на xref:CardOperations.adoc[панели операций] нажмите кнопку:
* [.ph .uicontrol]*Согласован и подписан контрагентом* -- если контрагент прислал подписанный бумажный оригинал договора;
* [.ph .uicontrol]*Согласован контрагентом* -- если контрагент прислал согласованный файл договора.
* [.ph .uicontrol]*Повторить* -- если контрагент отказал в согласовании; чтобы начать новый цикл согласования;
* [.ph .uicontrol]*Отмена* -- для отмены согласования.

Если документ был успешно согласован контрагентом, в соответствии с демонстрационным маршрутом согласования будет выполнен переход к следующему этапу «Печать договора». Соответствующее задание поступит сотрудникам из группы «Печать договоров» Справочника сотрудников.
