
== Согласование документов

В данном разделе приведен пример согласования с использованием стандартного маршрута «Согласование с рецензированием и подписанием», который включает этапы:

. Согласование.
. Консолидация.
. Подписание.
. Подведение итогов.

Согласование выполняется с помощью рассылаемых участникам согласования заданий видов: «На согласование», «На консолидацию» и «На подписание».

Состав маршрута согласования определяется при настройке согласования с использованием модуля «{dv} 5. Конструктор согласований». Пользователи, при наличии разрешения, могут вносить изменения в маршрут при создании и в процессе согласования.

Решения, принимаемые участниками согласования, могут носить положительный, условно-положительный и отрицательный характер, что определяется семантикой решения (трактовкой решения в системе).

По результатам выполнения маршрута, после подведения итогов согласования, документ может быть согласован или возвращен на повторное согласование в новом цикле.

* *xref:task_dcard_approval_send.adoc[Отправка документа на согласование]* +
* *xref:task_dcard_approval_view_process.adoc[Ознакомление с ходом согласования]* +
* *xref:dcard_approval_start_and_control.adoc[Управление активным согласованием]* +
* *xref:task_tcard_approval_performer_get.adoc[Принятие решения по согласованию документа]* +
* *xref:task_tcard_approval_consolidator_get.adoc[Принятие решения по консолидации документа]* +
* *xref:task_tcard_approval_significant_get.adoc[Принятие решения по подписанию документа]* +
* *xref:task_tcard_approval_delegation.adoc[Делегирование заданий на согласование/подписание/консолидацию]* +
* *xref:ApprovDiscussion.adoc[Обсуждение согласования]* +
* *xref:AdditionalApprovers.adoc[Дополнительные согласующие]* +
* *xref:Ccard_subtasks.adoc[Подчиненные задания согласования]* +
