= Лента

При переключении между гридом и лентой позиционирование происходит по верхней карточке страницы.

Лента формируется по аналогии с Мобильной версией со следующими уточнениями:

Карточка:

Перед первой строкой карточки добавляется чекбокс для групповых операций;
Количество строк в карточке зависит от выставленных настроек (см. ниже);
Первая строка карточки всегда жирная (по аналогии с мобильным представлением);
На тулбаре, слева выводить чекбокс "Выбрать все" без надписи, пояснение только тултипом (работает по аналогии с таковым в шапке грида)

После чекбокса выводить фразы "Всего карточек"/ "Показано x из N" + показать все/ "Выбрано: x" по аналогии с гридом

На тулбаре в центре отображается переключалка Лента -- Грид;

Работа сортировки для ленты описана в GBL-1969 Сортировка в Ленте и Результатах поиска;

Дополнительная область (GBL-2016 Грид. Реализация дополнительной области) должна работать в представлении "Лента";

Окно настройки ленты в целом повторяет окно настройка таблицы:

Шапка меняется на "Настройка ленты";
Поле "Представление" остается, и логика работы сохраняется (Какое представление -- такие колонки можем добавить в ленту);
Поле "Колонки" работает следующим образом:
По умолчанию представление выбирается как настроено в папке;
По умолчанию для отображения выбираются три первых колонки (например Вид д-та, Номер, Дата создания);
Все колонки добавляются в карточку в ленте друг под другом;
Сохраняется возможность выбирать порядок полей перетаскиванием;
Настройка "Строки" убирается; то что не помещается -- должно переносится;
Настройка колонок для ленты и для грида сохраняются отдельно для каждого представления. Т.е. если в ленте что-то поменяли, в том же представлении грида должно быть как в гриде настраивали.

При вызове из Ленты эксель файл должен формироваться в виде таблицы, но на основании полей, выбранных в "Настройках ленты" в том порядке, в котором они представлены в ленте.