
== Подписание договора

В демонстрационном согласовании договор подписывают сотрудники, указанные в поле *Подписывает* карточки Договор.

При получении задания на подписание подписант может ознакомиться с уже согласованными документами и высказать положительное или отрицательное решение.

. Перейдите в папку [.ph .filepath]`Мои задания/Входящие`.
+
Для заместителя: нужно перейти в папку [.ph .filepath]`Замещение/Входящие`.
. Откройте полученное задание с описанием «Подписание документов» в состоянии `Не начато`.
. Для принятия решения по подписанию на xref:CardOperations.adoc[панели операций] нажмите кнопку:
* *Подписано* -- договорной документ будет переведен в состояние «Подписан»;
+
[NOTE]
====
[.note__title]#Important:# Со стандартными настройками в {dv} не поддерживается подписание усиленной/квалифицированной ЭП файлов с размером больше 35 МБ.
====
+
[NOTE]
====
[.note__title]#Note:# Для подписания усиленной подписью должны быть установлены компоненты, указанные в пункте xref:Install_cryptopro.adoc[Установка компонентов КриптоПро].
====
* *Отказано в подписании* -- договорной документ будет переведен в состояние Подготовка.

После проставления отметки о подписании, в соответствии с демонстрационным маршрутом согласования будет выполнен переход к следующему этапу «Завершен этап подписания».

Соответствующее задание поступит пользователю, указанному в поле *Подготовил* карточки договора.
