
== Состояния сотрудника

Активен::
  Сотрудник активен и может выполнять свои рабочие обязанности. [.ph]#Состояние можно изменить из [.dfn .term]_Справочника сотрудников_ и [#reference_r4d_jmg_2n__d8e104 .ph]#из xref:UserProfile.adoc[профиля сотрудника] в {wc}е.##

Болен::
  Сотрудник отсутствует по состоянию здоровья. [.ph]#Состояние можно изменить из [.dfn .term]_Справочника сотрудников_ и [#reference_r4d_jmg_2n__d8e104 .ph]#из xref:UserProfile.adoc[профиля сотрудника] в {wc}е.##

В отпуске::
  Сотрудник находится в отпуске. [.ph]#Состояние можно изменить из [.dfn .term]_Справочника сотрудников_ и [#reference_r4d_jmg_2n__d8e104 .ph]#из xref:UserProfile.adoc[профиля сотрудника] в {wc}е.##

В командировке::
  Сотрудник находится в командировке. [.ph]#Состояние можно изменить из [.dfn .term]_Справочника сотрудников_ и [#reference_r4d_jmg_2n__d8e104 .ph]#из xref:UserProfile.adoc[профиля сотрудника] в {wc}е.##

Отсутствует::
  Сотрудник отсутствует по каким-либо другим причинам. [.ph]#Состояние можно изменить из [.dfn .term]_Справочника сотрудников_ и [#reference_r4d_jmg_2n__d8e104 .ph]#из xref:UserProfile.adoc[профиля сотрудника] в {wc}е.##

Уволен::
  Сотрудник уволен. [.ph]#Состояние доступно для смены только из _Справочника сотрудников_. #

Переведен::
  Сотрудник переведен в другое подразделение. [.ph]#Состояние доступно для смены только из _Справочника сотрудников_. #

Уволен без возможности восстановления::
  Запрет любых изменений сведений о сотруднике, включая повторное изменение состояния. Работа с системой для сотрудников в данном состоянии запрещена. [.ph]#Состояние доступно для смены только из _Справочника сотрудников_. #

*На уровень выше:* xref:EmployeeDirFieldEmployee.adoc[Описание полей карточки сотрудника]
