
== Типы маршрутизации

Маршрутизация для сотрудника может быть задана во вкладке *Дополнительно* xref:staff_Employee_main_additional.adoc#routing[карточки сотрудника]. Для работы маршрутизации необходимо xref:staff_Employee_main_common.adoc#email[указать E-mail] сотрудника.

Онлайн задание::
  Задание приходит в настроенную виртуальную папку _{dv}_.
Задача Почтового клиента::
  На настроенный электронный почтовый ящик приходит письмо со ссылкой для доступа к карточке вида Задание в системе {dv}. Также пользователю предоставляется возможность выполнять задания непосредственно в почтовом клиенте с помощью ответных писем.
Зашифрованное офлайн задание::
  Данный способ маршрутизации и внешний вид карточки задания полностью аналогичны способу маршрутизации онлайн-задание, однако при отправке пользователю все данные задания автоматически шифруются и доступ к нему имеет только тот пользователь, которому оно предназначено.
  +
  Для отправки зашифрованных офлайн-заданий необходимо настроить параметры шифрования в справочнике Windows-клиента _Системные настройки_, а также выбрать сертификат в _Серверной консоли {dv}_ (выполняется администратором системы).
  +
  Получателю зашифрованного офлайн-задания помимо самого задания отправляются сессионный ключ шифрования и настройки крипто-провайдера и алгоритма шифрования. Для того, чтобы получатель смог открыть свое задание, администратор должен предоставить ему личный сертификат.
  +
  Данный тип маршрутизации совместим только с карточками {dv} 4.5. Задания {dv} 5 не работают с данным типом маршрутизации, в _Справочнике видов карточек_ данный тип не отображается.
Не маршрутизировать::
  При отправке задания в системной папке _Карточки_ (в ветке Задание бизнес-процесса библиотеки Делопроизводство) появляется карточка задания. Вся работа пользователя с заданием осуществляется в рамках работы с приложением {wc}.
Офлайн задание::
  Пользователь получает по электронной почте специальное сообщение (форму Outlook), внешне похожее на карточку задания, однако обмен данными происходит по электронной почте. В личную папку пользователя помещается ярлык на онлайн-задание.
  +
  Данный тип маршрутизации совместим только с карточками {dv} 4.5. Задания {dv} 5 не работают с данным типом маршрутизации, в _Справочнике видов карточек_ данный тип не отображается.
Письмо с вложениями::
  На настроенный электронный почтовый ящик приходит письмо со ссылкой для доступа к карточке вида _Задание_ в системе {dv} и текстом, который указан в XSLT-преобразовании.
Ссылка на задание::
  На настроенный электронный почтовый ящик приходит письмо со ссылкой для доступа к карточке вида _Задание_ в системе {dv}.
