= Статусы сотрудника

Активен::
Сотрудник активен и может выполнять свои рабочие обязанности. 

Статус можно изменить из _Справочника сотрудников_ и из xref:interfaceUserProfile.adoc[профиля сотрудника] в {wc}е.

Болен::
Сотрудник отсутствует по состоянию здоровья. 

Статус можно изменить из _Справочника сотрудников_ и из xref:interfaceUserProfile.adoc[профиля сотрудника] в {wc}е.

В отпуске::
Сотрудник находится в отпуске. 

Статус можно изменить из _Справочника сотрудников_ и из xref:interfaceUserProfile.adoc[профиля сотрудника] в {wc}е.

В командировке::
Сотрудник находится в командировке. 

Статус можно изменить из _Справочника сотрудников_ и из xref:interfaceUserProfile.adoc[профиля сотрудника] в {wc}е.

Отсутствует::
Сотрудник отсутствует по каким-либо другим причинам. 

Статус можно изменить из _Справочника сотрудников_ и из xref:interfaceUserProfile.adoc[профиля сотрудника] в {wc}е.

Уволен::
Сотрудник уволен. 

Статус доступен для смены только из _Справочника сотрудников_.

Переведен::
Сотрудник переведен в другое подразделение.

Статус доступен для смены только из _Справочника сотрудников_.

Уволен без возможности восстановления::
Запрет любых изменений сведений о сотруднике, включая повторное изменение состояния. Работа с системой для сотрудников в данном состоянии запрещена.

Статус доступен для смены только из _Справочника сотрудников_.

*Зелёный* -- Активен.

*Красный* -- Болен.

*Серый* -- В отпуске.

*Синий* -- В командировке.

*Жёлтый* -- Отсутствует.