
== Стандартные папки

Дерево папок включает ссылки:

* «Главная» – открывает xref:Dashboard.adoc[главную страницу] {wc}а;
* «Поиск» – открывает папку с результатами полнотекстового поиска; если полнотекстовый поиск выключен, папка будет скрыта;
* «Последние карточки» – открывает список последних открытых карточек;
* «Мои задания» – задания пользователя:
** «Входящие» – задания в состояниях «Не начато», «Делегировано», «Возвращено с делегирования» и «На доработке», в которых исполнителем является текущий пользователь;
*** «В работе» – задания текущего пользователя в состояниях «В работе» и «Отложено»;
*** «Завершено» – задания текущего пользователя во всех состояниях, кроме «Подготовка», «Отозвано» и «Отклонено»;
*** «На контроле» – задания во всех состояниях кроме «Подготовка» (включая завершенные за последние 30 дней), в которых текущий пользователь является контролёром;
*** «Ответственное исполнение» – задания во всех состояниях кроме «Подготовка», «Отозвано» и «Завершено», в которых текущий пользователь является ответственным исполнителем и не является текущим исполнителем;
** Исходящие – незавершенные задания, в которых текущий пользователь является Автором;
*** Делегировано – задания в состояниях «Делегировано» и «В работе», которые были делегированы текущим сотрудником;
*** Завершено – завершенные и отменённые за последние 30 дней задания, в которых текущий пользователь является Автором;
** Поиск заданий – запускает диалог поиска заданий по атрибутам;
* «Мои документы» – документы, в которых текущий сотрудник является автором;
** Поиск документов – запускает диалог поиска документов по атрибутам;
** Я автор – открывает список документов, в которых пользователь является автором;
* «Замещение» – задания постоянного и временного заместителя:
** «Входящие» – задания во всех состояниях кроме «Завершено» и «Отозвано», в которых текущий пользователь является постоянным или временным заместителем исполнителя;
*** «В работе» – задания заместителя в состояниях «В работе» и «Отложено»;
*** «На контроле» – задания во всех состояниях кроме «Подготовка» (включая завершенные за последние 30 дней), в которых текущий пользователь является заместителем контролёра;
** «Исходящие» – незавершенные задания, в которых текущий пользователь является заместителем Автора;
*** Делегировано – задания в состояниях «Делегировано» и «В работе», которые были делегированы замещаемым сотрудником;
*** Завершено – завершенные и отменённые за последние 30 дней задания, в которых текущий пользователь является заместителем Автора;
* «Договоры» с папками поиска договорных документов и отчетами:
** «Действующие договоры» – система виртуальных папок с договорами, отбираемыми по различным параметрам:
*** «По контрагенту» – действующие договоры, сгруппированные по контрагенту;
*** «По сроку действия» – действующие договоры, сгруппированные по сроку действия (по кварталам);
** «Договоры с доп. соглашением» – запускает диалог поиска дополнительных соглашений и актов к договорам, заключенным за определённый период;
** «Заключенные договоры» – система виртуальных папок с договорами по годам заключения:
*** «2018 – договоры и дополнительные соглашения» – договоры и дополнительные соглашения, заключенные в 2018 году и сгруппированные по контрагенту;
*** «2019 – договоры и дополнительные соглашения» – договоры и дополнительные соглашения, заключенные в 2019 году и сгруппированные по контрагенту;
+
[NOTE]
====
[.note__title]#Note:# Папки для выбора договоров за другие года могут быть созданы при настройке {wc}а.
====
** «Исполнение договоров» – запускает диалог поиск актов, зарегистрированных за определённый период;
** «Поиск» – запускает диалог поиска договорных документов по атрибутам;
** «Договоры к ознакомлению» – договоры для сотрудников группы ознакомления. Она представляет собой структуру папок с настроенными поисковыми запросами, предназначенную для поиска карточек договоров, с которыми может ознакомиться текущий пользователь:
*** «Заключенные» – заключенные договоры и дополнительные соглашения, в которых текущий пользователь входит в [.dfn .term]_Группу ознакомления_ с договором;
*** «Согласование» – договоры и дополнительные соглашения в состоянии «Подготовка», «На согласовании», «На согласовании с контрагентом», в которых текущий пользователь входит в [.dfn .term]_Группу ознакомления_ с договором;
** «Мои договоры» – договора в состоянии «Подготовка», в которых текущий или временно замещаемый им сотрудник является Ответственным или Подготовившим. Включает подпапки с дополнительным условием по состоянию договора:
*** «Завершенные» – договора и дополнительные соглашения в состоянии «Завершено»;
*** «Заключенные» – договора и дополнительные соглашения в состоянии «Заключено»;
*** «Подготовка и согласование» – договора в состоянии «Подготовка», «На согласовании», «На согласовании с контрагентом», «Согласован», «На подписании», «Подписан», «На подписании контрагентом»;
** «Отчёты»:
*** «Договоры и ДС без подписанного оригинала» – запускает диалог поиска договоров и дополнительных соглашений в состояниях «Подписан» и «Заключен», для которых отсутствует подписанный оригинал (в карточке не заполнено поле Получен оригинал);
*** «Договоры с истекающим сроком окончания» – запускает диалог поиска договоров и дополнительных соглашений в состояниях «Подписан» и «Заключен», у которых заканчивается срок действия;
* «Мои группы» – содержит папки [.dfn .term]_рабочей группы_ пользователя; доступна, если пользователь включен в рабочую группу;
* «Мои папки» – содержит папки, подключенные пользователем.

[NOTE]
====
[.note__title]#Note:# Состав элементов в дереве папок может быть изменён при настройке {wc}а.
====

