= Исполнение задания заместителем

Задание поступит заместителю, указанному в _Справочнике сотрудников_, если выполнены условия:

.Для временного заместителя:
* В карточке замещаемого сотрудника пользователь указан как временный заместитель и являться первым _активным_ пользователем в списке временных заместителей.
* Состояние замещаемого сотрудника любое, кроме _Активен_.
* В настройках вида карточки _Задание_ должно быть настроено свойство "Автоматически делегировать при неактивности исполнителя". При этом рядом с полем `Исполнитель` становится доступен признак `Заместителю`).

.Для постоянного заместителя:
* В карточке замещаемого сотрудника пользователь указан как постоянный заместитель.
* Состояние замещаемого сотрудника любое, кроме _Активен_.

.Чтобы выполнить задание замещаемого сотрудника:
. Перейдите в папку `Замещение/Входящие`, если являетесь постоянным заместителем.
+
Если вы являетесь временным заместителем, Перейдите в папку menu:Мои задания[Входящие]
+
. Откройте задание.
+
****
Исполнителем задания будет указан замещаемый сотрудник.
****
+
. Выполните задание xref:tasksFinalize.adoc[стандартным образом].
