
== Исполнение задания заместителем

Задание поступит заместителю, указанному в _Справочнике сотрудников_, если выполнены условия:

* для временного замещения:
** в карточке замещаемого сотрудника пользователь должен быть указан как временный заместитель и являться первым "активным" пользователем в списке временных заместителей;
** состояние замещаемого сотрудника должно быть любым, кроме `Активен`;
** в настройках вида карточки _Задание_ должно быть настроено свойство *Автоматически делегировать при неактивности исполнителя* (при этом рядом с полем *Исполнитель* становится доступен признак *Заместителю*);

* для постоянного замещения:
** в карточке замещаемого сотрудника пользователь должен быть указан как постоянный заместитель;
** состояние замещаемого сотрудника должно быть любым, кроме `Активен`.

Чтобы выполнить задание замещаемого сотрудника:

[[task_usp_tvy_f4__steps_zhk_xhj_4j]]
. Перейдите в папку *Замещение/Входящие*, если являетесь постоянным заместителем; или в папку *Мои задания/Входящие*, если являетесь временным заместителем.
. Откройте задание.
+
Исполнителем задания будет указан замещаемый сотрудник.
. Выполните задание xref:task_tcard_change_state_finish_performer.adoc[стандартным образом].
