= Особенности контроля заданий и передачи на приёмку

* При последовательном исполнении, пока предыдущее задание находится в состоянии `На приёмке`, следующее задание не будет выслано очередному исполнителю. Отправка произойдет только после перехода предыдущего задания в состояние `Завершено`.
* В экземплярах заданий, которые по завершении должны перейти в состояние `На приёмке`, также автоматически устанавливается флаг `*Требуется приёмка*`, а в поле `Контролёр` переносится значение либо из поля `Контролёр` (если он указан), либо из поля `Ответственный исполнитель` (если не указан контролёр, но указан ответственный исполнитель).
* Если одновременно указаны контролёр и ответственный исполнитель, контролёр будет проверять выполнение задания только ответственного исполнителя. Задания остальных исполнителей на приёмку после завершения не переходят.
* Если указан только Контролёр, а Ответственный исполнитель -- нет, Контролёру на приёмку переходят задания всех исполнителей.
* Если указан только Ответственный исполнитель, задания всех исполнителей (кроме своего собственного) переходят ему на приёмку.
