= Перечень полей задания на исполнение

xref:ctrlSimpleFields.adoc[Тема]::
Тема задания.
+
include::partial$excerpts.adoc[tags=mandatory]

xref:ctrlStaffDirectoryItems.adoc[Исполнители]::
Исполнители задания.
+
include::partial$excerpts.adoc[tags=mandatory]
+
Задание будет отправлено всем выбранным сотрудникам и сотрудникам выбранных организаций, подразделений, групп и ролей. Фактическим исполнителем станет первый сотрудник, взявший задание в работу.
+
[NOTE]
====
Если нужно отправить каждому сотруднику собственное задание, используйте xref:taskGroups.adoc[Группу заданий].
====

xref:ctrlDateTime.adoc[Срок исполнения]::
Плановый срок исполнения задания выбранными исполнителями. По умолчанию устанавливаются текущие дата и время.

xref:ctrlText.adoc[Примечание]::
Дополнительная информация по заданию.

Поставить на контроль::
Включает функции xref:tasksUserController.adoc[контроля исполнения] задания ответственным сотрудником. При включенном контроле станут доступны параметры контроля:

xref:ctrlStaffDirectoryItems.adoc[Контролёр]:::
Сотрудник, который контролирует выполнение задания.

xref:ctrlDateTime.adoc[Дата контроля]:::
Дата, когда должен быть выполнен контроль выполнения задания.

xref:tasksControllerAcceptance.adoc[Требуется приёмка]:::
Включает функцию приёмки задания контролёром. После выполнения задания исполнителем, контролёр может принять результат выполнения или отказать. При включении приёмки будет автоматически включается контроль.

xref:TaskCardFilePanel.adoc[Добавить файл]::
Файлы задания.
