= Работа с представлением папки

Данный раздел описывает действия при работе с представлением папки.

Представление папки определяет настройки отображения данных карточек папки. Чтобы изменит текущее представление, выполните шаги, описанные в разделе xref:views-change.adoc[].

Данные в представлении могут быть отсортированы по заданным параметрам. Описание сортировки приведено в разделе xref:views-sort.adoc[].

Чтобы отфильтровать данные в представлении по определённым полям карточки, используйте фильтры. Работа с фильтрами рассматривается в разделе xref:views-filtering.adoc[].

Для удобства чтения при работе с представлениями в {wc}е реализована функция xref:views-line-wrap.adoc[переноса строк в представлении папки].

При необходимости данные представления могут быть экспортированы в таблицу в формате Microsoft Excel. Подробнее см. в разделе xref:views-export-to-excel.adoc[].

{wc} позволяет xref:views-change-column-width.adoc[настроить ширину колонок] представления или xref:views-paged-display.adoc[постраничное отображение данных], если такая необходимость возникает.
