= Работа с представлением папки

Данный раздел описывает действия при работе с представлением папки.

Представление папки определяет настройки отображения данных карточек папки. Чтобы изменит текущее представление, выполните шаги, описанные в разделе xref:viewsChange.adoc[].

Данные в представлении могут быть отсортированы по заданным параметрам. Описание сортировки приведено в разделе xref:viewsSorting.adoc[].

Чтобы отфильтровать данные в представлении по определённым полям карточки, используйте фильтры. Работа с фильтрами рассматривается в разделе xref:viewsFiltering.adoc[].

Для удобства чтения при работе с представлениями в {wc}е реализована функция xref:viewsLineWrapping.adoc[переноса строк в представлении папки].

При необходимости данные представления могут быть экспортированы в таблицу в формате Microsoft Excel. Подробнее см. в разделе xref:viewsExportToExcel.adoc[].

{wc} позволяет xref:viewsChangeColumnWidth.adoc[настроить ширину колонок] представления или xref:viewsPagedDisplay.adoc[постраничное отображение данных], если такая необходимость возникает.
