
== Работа с актом

Карточка [.dfn .term]_Акт_ предназначена для хранения сведений об акте по договору. [.dfn .term]_Акт_ не предполагает согласования и подписания в системе Docsvision, работа с ним заключается в проставлении отметок о движении бумажного документа, приводящих к изменению состояния карточки:

* передаче на подписание внутри организации;
* подписание внутри организации;
* передаче на подписание контрагенту;
* перевод в состояние «Действителен»;
* аннулирование (при возникновении такой необходимости).

При помощи команд ленты можно либо перевести карточку в другое состояние относительно текущего, либо вернуться в предыдущее состояние.

Для карточек актов предусмотрен следующий набор доступных состояний:

[[ActWork__section_q1b_243_h3b]]
=== Подготовка акта

Подготовка::
  Создание новой карточки акта и заполнение первичных регистрационных данных. Сохранение карточки с присвоением регистрационного номера и заполнением даты регистрации. См. xref:CreateAct.html[Подготовка и регистрация акта].

[[ActWork__section_r1b_243_h3b]]
=== Проставление отметок о движении документа

На подписании::
  В карточке договорного документа выполнена команда [.keyword]*На подписание контрагентом*. См. xref:ActTransferToSign.html[Проставление отметки о передаче на подписание].
Подписан::
  В карточке договорного документа выполнена команда [.keyword]*Подписан*. В карточке в поле [.keyword]*Дата подписания контрагентом* проставлена дата. См. xref:ActMarkSigning.html[Проставление отметки о подписании].
На подписание контрагенту::
  В карточке договорного документа выполнена команда [.keyword]*На подписание контрагенту*. В карточке в поле [.keyword]*Дата подписания контрагентом* проставлена дата. См. xref:ActTransferToSignCounterparty.html[Проставление отметки о передаче на подписание контрагентом].
Действителен::
  В карточке договорного документа выполнена команда [.keyword]*Назначить действительным*. См. xref:ActMarkOnValidity.html[Проставление отметки о действительности акта]
Аннулирован::
  В карточке договорного документа выполнена команда [.keyword]*Аннулировать*. См. xref:ActCancel.html[Аннулирование акта].

* *xref:../topics/CreateAct.html[Подготовка и регистрация акта]* +
* *xref:../topics/ActTransferToSign.html[Проставление отметки о передаче на подписание]* +
* *xref:../topics/ActMarkSigning.html[Проставление отметки о подписании]* +
* *xref:../topics/ActTransferToSignCounterparty.html[Проставление отметки о передаче на подписание контрагентом]* +
* *xref:../topics/ActMarkOnValidity.html[Проставление отметки о действительности акта]* +
* *xref:../topics/ActReturnToPreparation.html[Возврат акта на подготовку]* +
* *xref:../topics/ActCancel.html[Аннулирование акта]* +

*Parent topic:* xref:../topics/WorkWithContracts.html[Работа с договорными документами]
