
== Работа с актом

Карточка [.dfn .term]_Акт_ предназначена для хранения сведений об акте по договору. [.dfn .term]_Акт_ не предполагает согласования и подписания в системе {dv}, работа с ним заключается в проставлении отметок о движении бумажного документа, приводящих к изменению состояния карточки:

* передаче на подписание внутри организации;
* подписание внутри организации;
* передаче на подписание контрагенту;
* перевод в состояние «Действителен»;
* аннулирование (при возникновении такой необходимости).

При помощи команд ленты можно либо перевести карточку в другое состояние относительно текущего, либо вернуться в предыдущее состояние.

Для карточек актов предусмотрен следующий набор доступных состояний:

[[ActWork__section_q1b_243_h3b]]
=== Подготовка акта

Подготовка::
  Создание новой карточки акта и заполнение первичных регистрационных данных. Сохранение карточки с присвоением регистрационного номера и заполнением даты регистрации. См. xref:CreateAct.adoc[Подготовка и регистрация акта].

[[ActWork__section_r1b_243_h3b]]
=== Проставление отметок о движении документа

На подписании::
  В карточке договорного документа выполнена команда [.keyword]*На подписание контрагентом*. См. xref:ActTransferToSign.adoc[Проставление отметки о передаче на подписание].
Подписан::
  В карточке договорного документа выполнена команда [.keyword]*Подписан*. В карточке в поле [.keyword]*Дата подписания контрагентом* проставлена дата. См. xref:ActMarkSigning.adoc[Проставление отметки о подписании].
На подписание контрагенту::
  В карточке договорного документа выполнена команда [.keyword]*На подписание контрагенту*. В карточке в поле [.keyword]*Дата подписания контрагентом* проставлена дата. См. xref:ActTransferToSignCounterparty.adoc[Проставление отметки о передаче на подписание контрагентом].
Действителен::
  В карточке договорного документа выполнена команда [.keyword]*Назначить действительным*. См. xref:ActMarkOnValidity.adoc[Проставление отметки о действительности акта]
Аннулирован::
  В карточке договорного документа выполнена команда [.keyword]*Аннулировать*. См. xref:ActCancel.adoc[Аннулирование акта].

* *xref:CreateAct.adoc[Подготовка и регистрация акта]* +
* *xref:ActTransferToSign.adoc[Проставление отметки о передаче на подписание]* +
* *xref:ActMarkSigning.adoc[Проставление отметки о подписании]* +
* *xref:ActTransferToSignCounterparty.adoc[Проставление отметки о передаче на подписание контрагентом]* +
* *xref:ActMarkOnValidity.adoc[Проставление отметки о действительности акта]* +
* *xref:ActReturnToPreparation.adoc[Возврат акта на подготовку]* +
* *xref:ActCancel.adoc[Аннулирование акта]* +

