
== Работа по договору и дополнительному соглашению

Работа с договорами и дополнительными соглашениями предполагает выполнение пользователями действий, приводящих к изменению состояния карточки. При помощи команд бокового меню можно либо перевести карточку в другое состояние относительно текущего, либо вернуться в предыдущее состояние.

Для карточек договоров и дополнительных соглашений предусмотрен следующий набор доступных состояний:

. Подготовка договорного документа.
[loweralpha]
.. Подготовка.
+
Создание новой карточки договорного документа и заполнение первичных регистрационных данных. Сохранение карточки с присвоением регистрационного номера и заполнением даты регистрации. См. xref:CreateContract.html[Подготовка и регистрация договора].
. Согласование и подписание договорного документа.
[loweralpha]
.. На согласовании.
+
В карточке выполнена команда [.keyword]*Создать согласование*. Создано и запущено согласование по договорному документу. Согласующим отправлены задания на согласование. Всеми согласующими принято решение по согласованию документа внутри собственной организации. Инициатором согласования выполнена консолидация полученных от согласующих версий документа, создана итоговая версия документа.
.. На согласовании контрагентом.
+
В карточке согласования консолидатором, подготовившим итоговую версию документа, выполнена команда [.keyword]*Отправить контрагенту*. Сформировано письмо контрагенту с приложенной версией итогового договорного документа.
.. Согласован.
+
От контрагента получен согласованный вариант документа.
.. На подписании.
+
Полученный от контрагента согласованный вариант документа передан на подписание сотруднику, указанному в поле [.ph .uicontrol]*Подписывает* собственной организации.
.. На подписании контрагентом.
+
Контрагенту отправлен оригинал договорного документа с подписью представителя собственной организации.
.. Подписан.
+
Оригиналы договора подписаны со стороны собственной организации и организации контрагента. В заданиях на подписание принято решение [.keyword]*Подписан*.
. Проставление отметок о движении договорного документа.
[loweralpha]
.. Заключен.
+
В карточке договорного документа выполнена команда [.keyword]*Заключить*. В карточке в поле [.keyword]*Договор заключен* проставлена дата заключения договора. См. xref:ConclusionofContracts.html[Проставление отметки о заключении договора/дополнительного соглашения].
.. Завершен.
+
В карточке договорного документа выполнена команда [.keyword]*Завершить* или истек срок действия договора. В карточке в поле [.keyword]*Дата завершения* проставлена дата завершения действия договора. См. xref:ContractForcedFinish.html[Проставление отметки о завершении договора/дополнительного соглашения].
.. Расторгнут.
+
В карточке договорного документа выполнена команда [.keyword]*Расторгнуть*. В карточке в поле [.keyword]*Дата завершения* проставлена дата завершения действия договора. См. xref:TerminationOfContract.html[Расторжение договора/дополнительного соглашения].
.. Аннулирован.
+
В карточке договорного документа выполнена команда [.keyword]*Аннулировать*. См. xref:CancelOfContract.html[Аннулирование договора/дополнительного соглашения].
. Перевод карточки договорного документа в архив.
[loweralpha]
.. В архиве.
+
В свойствах карточки установлен атрибут [.keyword]*Архивирована*.

* *xref:../topics/CreateContract.html[Подготовка и регистрация договора]* +
* *xref:../topics/CreateAdditionalAgreement.html[Подготовка и регистрация дополнительного соглашения]* +
* *xref:../topics/ContractsReconciliationDemo.html[Согласование и подписание договорных документов]* +
* *xref:../topics/ContractTransfertoSignCounterparty.html[Проставление отметки о передаче на подписание контрагентом]* +
* *xref:../topics/ConclusionofContracts.html[Проставление отметки о заключении договора/дополнительного соглашения]* +
* *xref:../topics/ContractForcedFinish.html[Проставление отметки о завершении договора/дополнительного соглашения]* +
* *xref:../topics/TerminationOfContract.html[Расторжение договора/дополнительного соглашения]* +
* *xref:../topics/CancelOfContract.html[Аннулирование договора/дополнительного соглашения]* +
* *xref:../topics/ContractExtension.html[Продление срока договора]* +

*Parent topic:* xref:../topics/WorkWithContracts.html[Работа с договорными документами]
