:current: узла

= Копирование узлов справочника сотрудников

В справочнике реализована возможность _Копировать_ и _Вырезать_ узлы и сотрудников. Операции копирования или вырезания могут быть вызваны из контекстного меню выбранного узла.

Вокруг скопированных или вырезанных узлов и сотрудников появляется пунктирная рамка. Вырезанный узел дополнительно обозначается серым цветом. Цвет скопированных узлов и сотрудников не меняется.

Копировать::
Операция копирует только иерархию узла, но не копирует сотрудников. Для перемещения узлов вместе с сотрудниками воспользуйтесь операцией _Вырезать_.

Вырезать::
Операция перемещает узел со всеми дочерними узлами, включая сотрудников. При выполнении операции исходный узел удаляется в старом месте и перемещается в новое. Вырезать можно также отдельных сотрудников.

Вставить::
Операция завершает копирование или вырезание. Операция недоступна, пока раздел не был скопирован или вырезан.
+
Операция *Вставить* отправляет запрос на сервер. Это значит, что узел будет скопирован или вырезан только после выбора _Вставить_.

.Чтобы скопировать или переместить узел:
. Выберите узел-источник, который желаете скопировать или вырезать.
. Вызовите контекстное меню узла-источника.
. Из контекстного меню узла выберите _Копировать_ или _Вырезать_.
+
NOTE: Скопированный или вырезанный узел или сотрудник помещаются в буфер обмена. После этого справа от узла или сотрудника появляется кнопка *Отменить*. Вместо пунктов _Копировать_ или _Вырезать_ контекстного меню появляется пункт _Отменить_. Нажатие на эту кнопку или пункт в контекстном меню очищает буфер обмена.
+
. Вызовите контекстное меню на целевом узле, в который необходимо добавить или переместить текущий.
. В контекстном меню выберите пункт _Вставить_.

[NOTE]
====
Перемещать и копировать организации и подразделения можно только в организации или подразделения, группы -- только в группы, ограничений на перемещение сотрудников нет.
====

include::partial$excerpts.adoc[tags=operationsAborted]

При выполнении операций проверяются права доступа на редактирование узлов справочника.

Чтобы вырезать узлы и сотрудников, пользователь должен иметь права на редактирование исходного узла. Чтобы вставить узлы и сотрудников, пользователь должен иметь права на редактирование целевого узла.

После выполнения операций, xref:directories/staff/security.adoc[настройки прав доступа] исходного узла будут заменены настройками, унаследованными от нового родительского узла.
