= Поиск по номенклатуре дел

include::user:page$directories/staff/search.adoc[tags=activateSearch]

Поиск осуществляется по всем разделам и делам справочника в выбранном году. Если был выбран другой год, то поиск запустится снова, но уже для другого года. В выпадающем списке слева от поисковой строки можно выбрать поиск только по делам или только по разделам. Поиск по делу осуществляется по полям `Заголовок дела`, `Индекс дела`. Поиск по разделу осуществляется по полям `Наименование раздела`, `Индекс раздела`.

В результатах поиска отображаются все найденные результаты, а также указывается общее количество найденных результатов. Цветом выделяются совпадения с поисковым запросом.

Нажатие на результат поиска переводит в иерархическую структуру справочника. Если поиск осуществлялся по разделам, структура справочника сворачивается до выбранного раздела и фокус смещается на найденный раздел. Если поиск осуществлялся по делам, то структура раскрывается до родительского раздела, и фокус смещается на найденное дело.
