= Формирование и публикация описателя элемента управления

Описатель элемента управления -- программный компонент, содержащий общую информацию об элементе управления, и список его свойств (настроек, которые можно изменять в программе {kvr}).

.Описатель элемента управления может быть сформирован двумя способами:
. В виде функции xref:layout-designer-extensions/layout-designer-extensions.adoc[расширения программы {kvr}].
. В виде файла XML.

Для простоты первый вариант описателя будем называть _бинарным описателем_ элемента управления, второй -- _текстовым описателем_.

Основное отличие: _текстовый описатель_ можно составить с применением уже зарегистрированных редакторов, свойств (пример исключения приведен в пункте xref:new-controls/create-text-descriptor.adoc[Формирование текстового описателя элемента управления]) и функций проверки. Для _бинарного описателя_ недостающие элементы можно включить в расширение программы {kvr}, в котором реализуется описатель. В остальном выбор способа формирования описателя определяется предпочтениями программиста.
