= Получение сервисов в клиентском компоненте

В клиентском компоненте элемента управления можно получить доступ к стандартным (список в справочнике JS API, раздел Services) и xref:client/with-client-service.adoc[разработанным клиентским сервисам].

Ссылка на сервисы автоматически передается при загрузке клиентского компонента. Чтобы получить ссылку, нужно добавить в класс параметров поле services с указанием типов требуемых сервисов:

[source,typescript]
----
@rw services?: $EditOperationStore & $UrlStore & $RequestManager;
----

В данном примере в services сохраняются сервисы: `$EditOperationStore`, `$UrlStore`, `$RequestManager`.

.Обратиться к сервису можно следующим образом:
[source,typescript]
----
let editOperations = this.state.services.editOperations.getAll(); <.>
----
<.> Получаем список всех операций редактирования с помощью метода `getAll` сервиса `editOperations`.

[CAUTION]
====
Сервисы `$CardId`, `$CardTimestamp`, `$CardInfo`, `$RowInfo` и `$RowId` возвращают информацию о карточке, с данными которой связан текущий элемент управления.

Если элемент управления связан с данными связанной карточки, а не карточки, в разметке которой он используется, указанные сервисы будут возвращать информацию именно о связанной карточке.

Получить данные о текущей карточке можно с помощью сервиса `$Layout`. Например, следующий код демонстрирует способ получения идентификатора карточки:

[source,typescript]
----
let cardId = this.state.services.layout.cardInfo.id;
----
====
