= Переопределение реализации стандартного элемента управления собственной

Стандартная реализация элементов управления {wc}а может не всегда отвечать требованиям пользователя. В качестве решения, программист может реализовать собственные типы элементов управления и использовать их в разметках, или переопределить стандартную реализацию существующих элементов управления. В последнем случае разметки остаются без изменений, а изменяется клиентская часть элементов управления.

Переопределение реализации стандартных элементов управления упрощает внедрение требуемой клиентской функциональности, но усложняет процесса обновления версии {wc}а.

WARNING: Данные способ разработки не позволяет переопределить серверную часть элемента управления и его описатель.

.Чтобы переопределить стандартную реализацию элемента управления собственной:
. Скопируйте файлы `.tsx` с реализацией клиентской части стандартного элемента управления и файлы зависимостей в отдельный каталог.
+
. Внесите требуемые изменения в файлы.
+
Изменять тип элемента управления не нужно.
+
. Сохраните изменения и опубликуйте компоненты в каталоге собственного решения на сервере {wc}а стандартным образом.
+
. При обновлении версии {wc}а выполните следующие действия:
+
.. Проанализируйте исходный код стандартной реализации на наличие измененийfootnote:[Перечень изменений в реализации исходного кода стандартных компонентов не предоставляется.] относительной версии, для которой создавалось переопределение.
+
.. Если изменения затронули настройки или формат данных элемента управления, внесите соответствующие изменения в собственный компонент, переопределяющий стандартный.
