= Получение контекста объектов в серверном расширении

Программист может использовать в серверном расширении контекст объектов {dv} для доступа к данным системы.

.Разработчику доступны два контекста объектов:
. Пользовательский -- создается для каждого пользователя при его входе в {wc}. Права на работу с объектами соответствуют правам данного пользователя в системе {dv}.
. Серверный -- создается для сервера {dv}. Права на работу с объектами соответствуют правам учетной записи пула приложений с {wc}ом в системе {dv}.

Получить контекст объектов можно используя функции сервиса `ICurrentObjectContextProvider`:

* `GetOrCreateCurrentSessionContext` -- возвращает контекст объектов текущего пользователя.
* `GetOrCreateApplicationPoolSessionContext` -- возвращает серверный контекст объектов.

Сервис `ICurrentObjectContextProvider` может быть получен двумя способами:

[source,csharp]
----
public class LayoutController : ApiController <.>
{
    public LayoutController(ICurrentObjectContextProvider currentObjectContextProvider) {
        var context = currentObjectContextProvider.GetOrCreateCurrentSessionContext().ObjectContext <.>

    public LayoutController(IServiceProvider serviceProvider) { <.>
            var serviceHelper = new ServiceHelper(serviceProvider);
            var context = serviceHelper.CurrentObjectContextProvider.GetOrCreateCurrentSessionContext().ObjectContext; <.>
----
<.> Указать сервис в качестве аргумента конструктора класса контроллера.
<.> Получение контекста пользователя.
<.> Получить сервис из передаваемого в конструктор поставщика сервисов serviceProvider.
<.> Получение контекста пользователя.

{wc} периодически закрывает неиспользуемые пользовательские сессии, из-за чего контекст объектов, сохранённый в статический объект класса (серверного расширения или контроллера), спустя время станет недействительным. *Всегда получайте контекст объектов заново* (с помощью функции `GetOrCreateCurrentSessionContext`).

Примеры работы с контекстом объектов рассмотрены в документе _{dv} 5. Руководство программиста_. Следующий код демонстрирует пример получения объектной модели карточки _Документ_.

[source,csharp]
----
Document document = objectContext.GetObject<Document>(Guid.Parse("9E11083F-D0EC-4F9F-8981-285498280BD9")); <.>
----
<.> В метод GetObject передаются тип объекта (Document) и идентификатор объекта (ID карточки).
