= Создание и публикация серверного расширения

Серверное расширение представляет собой библиотеку DLL, разработанную на платформе .NET.

== Перечень необходимых инструментов

* https://www.visualstudio.com/[Visual Studio].
* Docsvision WebClient SDK (запрашивается через портал ТП).

== Описание файлов проекта

* `ServerExtension.cs` -- входная точка расширение, в которой регистрируются сервисы и прочие сущности.
* `Sign.snk` -- файл подписи сборки. Для установки сборки должны быть подписаны. Рекомендуется сгенерировать новый файл подписи в настройках проекта.
* `Resource.resx`, `Resource.ru.resx` -- локализации, используемые в расширении.
* `Feature1` -- папка, содержащая реализацию некоторой функциональности.
* `Feature1/Feature1Controller.cs` -- класс, регистрирующий конечные точки Web API.
* `Feature1/IFeature1Service.cs` и `Feature1/Feature1Service.cs` -- интерфейс и реализация сервиса, реализующего логику обработки запроса.
* `Feature1/Models` -- классы моделей, используемых в сервисе и контроллере.

== Сборка и установка

.Чтобы создать серверное расширение:
. Убедитесь, что установлен Docsvision WebClient SDK.
+
В этом случае в переменной окружения `DocsvisionWebClientSDK` содержится путь к его папке, например, `C:\Program Files (x86)\Docsvision\WebClient\5.5\SDK`.
+
. Создайте в Visual Studio новый проект с типом `TemplateServerExtension`.
+
. Обновите в проекте ссылки на зависимости.
+
****
include::ROOT:partial$excerpts.adoc[tags=versions]
****
+
. Реализуйте в проекте функции серверного расширения.
+
****
Примеры кода серверных расширений приведены в следующих пунктах раздела, а также в xref:web-client-samples.adoc[репозитории "ДоксВижн"].
****
+
. Настройте ядро серверного расширения.
+
****
Ядром серверного расширения называется файл `TemplateServerExtension.cs` в проекте расширения. Ядро является производным от `WebClientExtension` классом, содержащим ссылки на реализуемые функции расширения.

[source,csharp]
----
public class TemplateServerExtension : WebClientExtension
{
    public TemplateServerExtension(IServiceProvider serviceProvider)
        : base(serviceProvider)
    {
    }

    public override string ExtensionName <.>
    {
        get {
            return Assembly.GetAssembly(typeof(TemplateServerExtension)).GetName().Name;
        }
    }

    public override Version ExtensionVersion <.>
    {
        get {
            return new Version(FileVersionInfo.GetVersionInfo(Assembly.GetExecutingAssembly().Location).FileVersion);
        }
    }

    public override void InitializeContainer(ContainerBuilder containerBuilder) { <.>

<.>
    // containerBuilder.RegisterType<YourService>().As<IYourService>().SingleInstance();
    // containerBuilder.RegisterOrderedType<YourBindingConverterType, IBindingConverter>();
    // containerBuilder.RegisterOrderedType<YourBindingResolverType, IBindingResolver>();
    // containerBuilder.RegisterOrderedType<YourControlResolverType, IControlResolver>();
    // containerBuilder.RegisterOrderedType<YourPropertyResolverType, IPropertyResolver>();
    // containerBuilder.RegisterType<YourCardLifeCycle>().Keyed<ICardLifeCycle>(CardTypeID).SingleInstance();
    // containerBuilder.RegisterType<YourRowLifeCycle>().Keyed<IRowLifeCycle>(SectionID).SingleInstance();
    }

<.>

}
----
<.> Название расширения.
<.> Версия расширения.
<.> Метод регистрации добавляемых расширением сервисов, преобразователей, конвертеров и т.п. в IoC контейнере.
<.> Примеры регистрации.
<.> Далее идут функции, возвращающие реализованные функции серверного расширения.

Описание изменений, которые необходимо выполнить в ядре расширения, приведено в описании примеров расширений, добавляющих обработчики событий и локализованные ресурсы.

В серверном расширении {wc}а используется IoC контейнер, реализованный с использованием библиотеки Autofac. Описание данной библиотеки и её возможностей см. на сайте [](https://autofac.org/).
****
+
. Скомпилируйте проект.
+
****
В результате будет получен файл DLL с ядром серверного расширения и реализуемыми функциями, а также файлы DLL с локализованными ресурсами.
****
+
. Скопируйте `safeprojectnamesafeprojectname.dll` и `safeprojectnamesafeprojectname.dll.pdb` из папки `bin\WebClientBin` в `Каталог-установки-Web-клиента\Site\bin`.
+
Ресурсные сборки нужно скопировать в папки `{wcd}\Site\Extensions\ru\` (для русской локализации), `{wcd}\Site\Extensions\uk\` (для английской локализации) и т. д.
+
. Перезапустите сервер IIS.

== Проверка работы

. Откройте Web-клиент.
. Откройте диалог "О программе" и убедитесь, что расширение присутствует в списке подключенных расширений.
. Откройте произвольный документ и в консоли браузера выполните:
+
 $ await layoutManager.cardLayout.getService("requestManager").post("api/Feature1/Action1", JSON.stringify({ documentId: layoutManager.cardLayout.getService("cardId") }));
+
. Обновите документ, убедиться, что в названии добавился знак.
