= Свойства

# tag::mandatory[]
==== Обязательное

Определяет требование к заполнению значения ЭУ до сохранения карточки:

* Когда флаг установлен, значение ЭУ должно быть присвоено, иначе карточка не будет сохранена. При этом ЭУ помечается предупреждающим сообщением.
* Когда флаг не установлен, присваивать значение необязательно.
# end::mandatory[]

# tag::editOperationForVisibility[]
==== Операция редактирования для видимости

Определяет операцию, которая должна быть доступна, чтобы ЭУ отображался для пользователя. Работа свойства зависит от значения свойства `*Видимость*`:

* Когда флаг `*Видимость*` установлен и выбрана _операция редактирования для видимости_, видимость элемента определяется исходя из доступности пользователю выбранной операции редактирования.
* Когда флаг `*Видимость*` установлен, и _операция редактирования для видимости_ НЕ выбрана, ЭУ отображается всегда.
* Когда флаг `*Видимость*` НЕ установлен, ЭУ всегда скрыт.
# end::editOperationForVisibility[]

# tag::disabled[]
==== Отключен

Когда флаг установлен, отключается возможность изменить значения элемента управления. Работает совместно со свойством `*Операция редактирования*. Редактирование будет запрещено, если одно из свойств запрещает редактирование.

`*Адаптивный*`
# end::disabled[]

# tag::byTab[]
==== Переходить по TAB

Флаг определяет последовательность перехода по ЭУ карточки при нажатии кнопки kbd:[TAB]. Если флаг установлен, переход по kbd:[TAB] разрешён.
# end::byTab[]

# tag::editMode[]
==== Режим редактирования

Определяет вариант отображения элемента управления и возможность изменения его значения:

* *_По месту_*. Значение изменяется в отдельном окне, которое открывается нажатием на элемент управления.
+
Данный вариант подходит как для разметки режима редактирования, так и для разметки режима просмотра карточки.
+
* *_Редактирование_*. Значение изменяется непосредственно в элементе управления.
+
Данный вариант может быть выбран в разметке режима редактирования и просмотра.
+
Если элемент с режимом *_Редактирование_* добавлен в разметку просмотра, необходимо самостоятельно обеспечить сохранение его значения. Например, с использованием скриптов карточек.
+
* *_Без редактирования_*. Значение изменить нельзя.
# end::editMode[]

# tag::stdCss[]
==== Стандартный css класс

Название CSS класса, в котором определен стандартный стиль элемента управления.
# end::stdCss[]

# tag::mouseOver[]
==== При наведении курсора

Вызывается при входе курсора мыши в область элемента управления.
# end::mouseOver[]

# tag::mouseAway[]
==== При отведении курсора

Вызывается, когда курсор мыши покидает область элемента управления.
# end::mouseAway[]

# tag::dataChanged[]
==== После смены данных

Вызывается после изменения содержимого элемента управления.
# end::dataChanged[]

# tag::onClick[]
==== При щелчке

Вызывается при щелчке мыши по любой области элемента управления.
# end::onClick[]

# tag::searchDelay[]
==== Задержка поиска (мс)

Определяет время задержки (в мс) от ввода последнего символа в строку поиска до выполнения быстрого поиска по справочнику.
# end::searchDelay[]

# tag::addCss[]
==== Дополнительные css классы

Названия дополнительных классов CSS для изменения стиля элемента управления. Перечисляются через пробел.
# end::addCss[]

# tag::visibility[]
==== Видимость

Настройка видимости. Элемент управления отображается в карточке, когда флаг установлен. Элемент управления и любое его содержимое не отображаются, когда флаг снят.

`*Адаптивный*`
# end::visibility[]

# tag::selectCompanyOrDepartment[]
==== Выбор организаций

Определяет возможность выбора организации из _Справочника сотрудников_. Когда флаг установлен выбирать организации разрешено. Когда флаг не установлен -- не разрешено.

==== Выбор подразделений

Определяет возможность выбора подразделения из _Справочника сотрудников_. Когда флаг установлен выбирать подразделения разрешено. Когда флаг не установлен -- не разрешено.
# end::selectCompanyOrDepartment[]

# tag::editOperation[]
==== Операция редактирования

Выбор операции редактирования значения элемента управления. Если операция недоступна пользователю, то изменение значения элемента управления также недоступно. Если операция не выбрана, то возможность редактирования значения элемента управления не проверяется.

Если значение `*Операции редактирования*` наследуется от родительского Блока, название свойства меняется на `*Операция редактирования (наследовано)*`.
# end::editOperation[]

# tag::dataField[]
==== Поле данных

Поле карточки, содержащее ссылку на организацию _Справочника сотрудников_.
# end::dataField[]

# tag::dataSource[]
==== Источник данных

Секция карточки, содержащая данные элемента управления.
# end::dataSource[]

# tag::extendedDataSource[]
==== Расширенный источник данных

Выбор типа источника данных элемента управления: текущая карточка или один из типов, настроенных в корневом элементе разметки.
# end::extendedDataSource[]

# tag::labelText[]
==== Текст метки

Содержимое метки, отображаемой слева от элемента управления.

`*Локализуемый*`
# end::labelText[]

# tag::hint[]
==== Подсказка

Содержимое всплывающей подсказки.

`*Локализуемый*`
# end::hint[]

# tag::displayLabelWithoutDefinition[]
==== Отображать метку без значения

Определяет вариант отображения метки.

* Когда флаг установлен, текст метки отображается всегда.
* Когда флаг не установлен, текст метки отображается только, если задано значение ЭУ.
# end::displayLabelWithoutDefinition[]

# tag::filler[]
==== Заполнитель

Текст, отображаемый в элементе управления, если подразделение не выбрано.

`*Локализуемый*`
# end::filler[]

# tag::general[]
=== Общие

==== Название ЭУ

Название типа элемента управления.

==== Название

Уникальное название элемента управления.
# end::general[]

# tag::editDirectory[]
==== Редактирование справочника

Активирует функцию редактирования данных Справочника контрагентов с помощью данного элемента управления. Когда флаг установлен, редактирование разрешено при наличии у пользователя прав. Когда флаг снят, функции редактирования справочника не предоставляются.
# end::editDirectory[]

# tag::iii[]

# end::iii[]

# tag::iii[]

# end::iii[]

# tag::iii[]

# end::iii[]

# tag::iii[]

# end::iii[]

# tag::iii[]

# end::iii[]

# tag::iii[]

# end::iii[]

# tag::iii[]

# end::iii[]

# tag::iii[]

# end::iii[]

# tag::iii[]

# end::iii[]

# tag::iii[]

# end::iii[]

# tag::iii[]

# end::iii[]