= Обработка события изменения состояния карточки

При изменения состояния карточки из пользовательского интерфейса {wc}а вызывается событие `*Перед изменением состояния карточки*` разметки карточки (корневой элемент разметки), которое может быть обработано в клиентском скрипте.

Данное событие является прерываемым -- может быть использовано для отмены изменения состояния карточки.

Ниже приведён код обработчика события изменения состояния карточки (Документ, Задание):

[source,typescript]
----
function changeState(sender: Layout, e: CancelableEventArgs<ICardStateChangingEventArgs>) { <.>

    if (CheckPossibility()){
        e.accept(); <.>
        return;
    }

    MessageBox.ShowWarning("Операция " + e.data.operationId  + " запрещена"); <.>
    e.cancel(); <.>
}
----
<.> Функция CheckPossibility проверяет выполнение неких требований.
<.> Подтверждаем выполнение операции. Необязательно.
<.> Показываем сообщение о запрете операции с указанием идентификатора операции.
<.> Необходимо вызвать e.cancel для отмены операции.

Для карточки _Задание_ после изменения состояния карточки будет вызвано событие `*После изменения состояния карточки*` элемента управления `_Кнопки операций задания_`.
