= Сохранение изменений карточки

.Код сохраняет все изменения карточки:
[source,typescript]
----
export async function saveCard(sender: CustomButton, e: IEventArgs) {
    await MessageBox.ShowConfirmation("Сохранить карточку?");

    layoutManager.cardLayout.saveCard(); <.>
}
----
<.> Получаем разметку карточки (cardLayout) и вызываем её метод saveCard для сохранения.

.Чтобы сохранить изменения определённого элемента управления, используйте его метод save:
[source,typescript]
----
export function saveDescription(sender: CustomButton, e: IEventArgs) {
    let cardDescription = sender.layout.controls.get<TextArea>("Description"); <.>

    cardDescription.save(); <.>
}
----
<.> Получаем элемент управления Description, данные которого сохраняются.
<.> Вызываем метод save для сохранения изменений.

[WARNING]
====
Если за сохранением следует другая операция, изменяющая карточку, сохранение карточки может привести к ошибке `Содержимое карточки было изменено другим пользователем. Пожалуйста, обновите карточку и выполните операцию снова`.

Например, данная ошибка возникнет при сохранении карточки, если сохранение вызывается в обработчике изменения состояния карточки.
====

****
Чтобы обойти данную ошибку, приостановите обработку основного события до сохранения карточки, а сохранение сделайте асинхронным. Следующий код демонстрируется данный способ:

[source,typescript]
----
export async function onChangeState(sender: Layout, e: CancelableEventArgs<ICardStateChangingEventArgs>) {
        let description = sender.controls.get<TextArea>("Description");
    
        description.value = description.value + "\nЗарегистрировано"; <.>
    
        e.wait(); <.>
        await sender.saveCard(); <.>
        e.accept(); <.>
}
----
<.> Изменяем значение поля карточки.
<.> Приостанавливаем обработку основного события.
<.> Асинхронное сохранение.
<.> Продолжаем обработку.
****
