= Разработка расширения с клиентским сервисом

Данный тип расширений предназначен для добавления новых сервисов клиентского уровня. Сервисы предоставляют публичные методы, которые могут быть вызваны (с помощью функции получения сервиса) из клиентских расширений (скриптов, компонентов элементов управления). Программист может реализовать сервисы различного назначения.

WARNING: Разрабатываемый сервис и его "потребители" должны находиться в одном клиентском расширении.

== Создание расширения

Чтобы создать расширение, добавляющее новые сервисы, выполните приведенную далее инструкцию.

. Создайте xref:client/create-publish.adoc[проект клиентского расширения] *без публикации*.
+
. Создайте в папке `src` файл TypeScript (`.ts`, `.tsx`) со следующим содержимым:
+
[source,typescript]
----
import { $RequestManager } from "@Docsvision/webclient/System/$RequestManager";
import { urlStore } from "@Docsvision/webclient/System/UrlStore";
import { serviceName } from "@Docsvision/webclient/System/ServiceUtils";

export class CardService {
    constructor(private services: $RequestManager) {
    }
    exists(cardId: string): Promise<boolean> { <.>
        let url = urlStore.urlResolver.resolveApiUrl("Exists", "CardService"); <.>
        url = url + "?cardId=" + cardId;
        return this.services.requestManager.get<boolean>(url);
    }
}

export type $CardService = { cardService: CardService };
export const $CardService = serviceName((s: $CardService) => s.cardService); <.>
----
<.> Функция exists проверяет существование карточки.
<.> Проверка выполняется с помощью серверной функции Exists контроллера CardService.
<.> Объявление сервиса $CardService.
+
****
В данном коде реализован сервис `CardService`, содержащий единственную функцию exists, возвращающую признак существования карточки в системе {dv}.

При реализации собственного сервиса, используйте его объявление, по аналогии с приведенным примером, заменив `CardService` на название собственного сервиса.
****
+
. Измените содержимое файла `Index.ts`.
+
[source,typescript]
----
import { $CardService, CardService } from "./WebService"; <.>
import { extensionManager } from "@Docsvision/webclient/System/ExtensionManager";
import { Service } from "@Docsvision/webclient/System/Service";
import { $RequestManager } from "@Docsvision/webclient/System/$RequestManager";

extensionManager.registerExtension({
    name: "Client extension with service",
    version: "1.0",
    layoutServices: [ <.>
        Service.fromFactory($CardService, (services: $RequestManager) => new CardService(services)) <.>
        ]
})
----
<.> Добавьте строку импорта тип/константы $CardService и класса CardService из добавленного в 2 файла (в примере -- WebService).
<.> Добавьте в registerExtension поле layoutServices, в значении которого должна быть специальная конструкция.
<.> Service.fromFactory(*<Тип сервиса>*, (services: $RequestManager) => new *<Класс реализации сервиса>*(services)).
+
. Соберите проект клиентского расширения командой `npm run build`.
+
. Скопируйте полученный файл `%BuildDir%\extension.js` на сервер {wc}а в папку `{wcd}\5.5\Site\Content\Modules\%Каталог Решения%`.
+
****
[NOTE]
====
Обратитесь к разделу xref:client/create-publish.adoc[Создание и публикация клиентского расширения], чтобы получить больше информации, связанной со сборкой проекта.
====

Получить разработанный сервис в клиентском расширении можно с помощью метода `getService`. Дополнительная информация по использованию функции getService приведена в пункте xref:client/script-get-service.adoc[Получение сервиса клиентского уровня].

[source,typescript]
----
let cardService = layout.getService($CardService); <.>
----
<.> Получение сервиса $CardService.
****

== Проверка работы расширения

.Чтобы проверить работу сервиса CardService:

. Добавьте в данное расширение xref:client/with-event-handlers.adoc[обработчик событий], вызывающий функцию `$CardService.exists`.
+
****
В следующем коде в метод exists сервиса `$CardService` передается идентификатор карточки, введённый в строку `cardId`. Результат проверки отображается на экране. Реализованный метод `onMyButtonClick` должен быть назначен обработчиком события нажатия *Кнопки*.

[source,typescript]
----
export async function onMyButtonClick(sender: CustomButton, e: IEventArgs) {

let cardId = sender.layout.controls.get<TextBox>("cardId").value;
let result = await sender.layout.getService($CardService).exists(cardId);

if (result)
MessageBox.ShowInfo('Карточка существует');
else
MessageBox.ShowInfo('Карточка не существует');
}
----
****
+
. Разработайте серверное расширение, предоставляющее функцию `Exists`. Инструкция по разработке такого расширения приведена в разделе xref:server/using-web-api.adoc[Разработка расширения с методами WebApi].
+
. Опубликуйте клиентское и серверное расширения на сервере {wc}а.
+
. Перезапустите сервер {wc}а.
+
. Настройте разметку карточки, указав для любой *Кнопки* обработчик `onMyButtonClick`. Добавьте в разметку _Строку_ с названием _cardId_.
+
. Откройте карточку с настроенной разметкой. Введите идентификатор существующей карточки в _Строку_ и нажмите *Кнопку*. На экране отобразится сообщение: `Карточка существует`.
