= Разработка расширения с локализованными ресурсами

Данный тип расширений предназначен для добавления локализованных строковых ресурсов, которые могут быть использованы в клиентских компонентах элементов управления и скриптах.

Чтобы создать расширение, добавляющее новые обработчики событий, выполните приведенную далее инструкцию.

. Создайте xref:client-extensions/with-event-handlers.adoc[проект клиентского расширения] *без публикации*.
+
. Создайте в папке `src` файл TypeScript (`.ts`, `.tsx`) со следующим содержимым:
+
[source,typescript]
----
import { ILocalizationsMap } from "@{dv}/webclient/System/ILocalizationsMap"; <.>
   
export function getLocalizedResources(): ILocalizationsMap {
    let cultureMap: ILocalizationsMap = {};
    cultureMap["en"] = {
        "Resource_One": "Sample",
        "Resource_Two": "Sample 2"
    };
       cultureMap["ru"] = {
        "Resource_One": "Пример",
        "Resource_Two": "Пример 2"
    };
    return cultureMap;
}
----
<.> Импортируем необходимые сущности из модуля.
+
****
В данном коде выполняется добавление двух ресурсов `Resource_One` и `Resource_Two` для языков русский (`ru`) и английский (`en`).

Функция `getLocalizedResources` (можно использовать другое название) возвращает массив добавляемых локализованных ресурсов, в котором каждый элемент соответствует определённой локали. Например, следующий участок кода отвечает за добавление ресурсов для локали `ru` (русский):

[source,typescript]
----
cultureMap["ru"] = {
    "Resource_One": "Пример",
    "Resource_Two": "Пример 2"
};
----
****
+
. Измените содержимое файла `Index.ts`.
+
[source,typescript]
----
import { getLocalizedResources } from "./LocalizedResource"; <.>
import { extensionManager } from "@{dv}/webclient/System/ExtensionManager";
import { ILocalizationsMap } from "@{dv}/webclient/System/ILocalizationsMap";

extensionManager.registerExtension({ <.>
    name: "Client extension with localization",
    version: "1.0",
    getLocalizations(): ILocalizationsMap {
        return getLocalizedResources();
        }
})
----
<.> Добавьте строку импорта функции getLocalizedResources из добавленного в 2 файла (в примере -- LocalizedResource).
<.> Добавьте в registerExtension функцию getLocalizations, которая должна вызывать импортированную в 1 функцию.
+
. Соберите проект клиентского расширения командой `npm run build`.
+
. Скопируйте полученный файл `%BuildDir%\extension.js` на сервер {wc}а в папку `{wcd}\5.5\Site\Content\Modules\%Каталог Решения%`.
+
****
TIP: Обратитесь к разделу xref:client-extensions/create-publish.adoc[Создание и публикация клиентского расширения], чтобы получить больше информации, связанной со сборкой проекта.

Получить значение локализованного ресурса в скрипте или клиентской части элемента управления можно из объекта `resources`:

----
resources.Resource_One
----
****
+
TIP: Проверить работоспособность расширения можно обратившись к `resources.Resource_One` из консоли отладки веб-браузера. Должно быть получено значение _Пример_.
+
. После завершения отладки соберите и опубликуйте на сервере {wc}а "релизную версию" клиентского расширения. "Релизная версия" собирается командой `npm run build:prod`.

[source,typescript]
----
import { $RequestManager } from "@{dv}/webclient/System/$RequestManager";
import { urlStore } from "@{dv}/webclient/System/UrlStore";
import { serviceName } from "@{dv}/webclient/System/ServiceUtils";

export class CardService {
constructor(private services: $RequestManager) {
 }

 exists(cardId: string): Promise<boolean> { <.>
 let url = urlStore.urlResolver.resolveApiUrl("Exists", "CardService"); <.>
 url = url + "?cardId=" + cardId;
 return this.services.requestManager.get<boolean>(url);
 }
}

export type $CardService = { cardService: CardService };
export const $CardService = serviceName((s: $CardService) => s.cardService); <.>
----
